string DLG_TEXT[50] = {
"As-tu quelque chose à vendre ou viens-tu m'acheter quelque chose, capitaine?",
"Je souhaite vendre la cargaison que je ramène.",
"Je viens faire des achats.",
"Je n'ai pas l'intention de faire affaire avec toi. Bonne journée.",
"Bonjour, ",
". Mon humble boutique est à ta disposition.",
"Merci. Je me nomme ",
".",
"Bien le bonjour! C'est un plaisir, vraiment! Si nous faisions affaire?",
"Alors, qu'est-ce que tu nous apportes, cette fois, capitaine?",
"Ah, capitaine! Que puis-je pour toi?",
"Voyons ce que tu as à me proposer.",
"Je préférerais discuter.",
"Au revoir.",
"C'est un plaisir de faire ta connaissance. Je m'appelle ",
". J'espère que c'est le début de bonnes relations d'affaires.",
"Eh bien, ",
", voyons ce que tu as à me proposer.",
"J'aimerais te parler, ",
".",
"Au revoir.",
"C'est toujours un plaisir de discuter avec toi, capitaine.",
"Je t'écoute.",
"On m'a demandé de te livrer une cargaison.",
"Serais-tu à la recherche d'un capitaine? Je dispose d'un excellent bateau et je peux acheminer n'importe quelle cargaison là où tu le souhaites.",
"Je n'ai pas le temps de parler pour le moment.",
"Je n'ai pas besoin de tes services. Du moins, tant que tu continueras à couler les bateaux français.",
"Dans ce cas, au revoir.",
"Je regrette, mais je n'ai rien pour toi actuellement.",
"Dans ce cas, je reviendrai plus tard.",
"Je regrette, mais le tonnage de ton bateau est trop faible pour ce que j'ai en tête.",
"Dans ce cas, je reviendrai plus tard.",
"Oh! J'allais justement te demander si tu ne pouvais pas me rendre un service. J'ai une cargaison à livrer à ",
", le plus vite possible. Si tu y parviens avant un mois, tu recevras ",
" pièces d'or à la livraison. Qu'en dis-tu?",
"Ça me va.",
"Je ne peux pas accepter.",
"Je t'ai déjà dit que je n'avais rien à te proposer.",
"Oh, pardon.",
"La mémoire t'est revenue un peu tard, non? J'ai déjà reçu tout ce dont j'avais besoin. Au revoir.",
"Au revoir.",
"Oh! Cela faisait tellement longtemps que j'attendais cette cargaison! Tiens, voilà pour toi.",
"Ç'a été un plaisir.",
"Comme tu veux, ",
".",
"Voyons ce que tu as là...",
"Merci de ton aide. A bientôt.",
"Hélas, ",
", les Français ont confisqué la plupart de mes vivres et de mes munitions et m'ont interdit de vendre le reste avant la fin de la guerre.",
"Quelle déveine!",

};