string DLG_TEXT[61] = {
"Hors d'ici, ou j'appelle mes hommes!",
"...",
"Qui es-tu et que fais-tu là? Tu as trois secondes pour me répondre avant que mes hommes ne te jettent à la rue!",
"Je suis ici pour affaires. Je me suis laissé dire que tu avais récemment capturé un navire transportant des figurines indiennes.",
"Quoi? C'est toi qui a tué mes hommes! Qui es-tu?",
"C'est moi qui pose les questions. Et si tu es malin, tu vas me répondre. Où est la cargaison du bateau que tu as arraisonné?",
"Que veux-tu, au juste?",
"Je m'intéresse à un navire et je crois qu'il appartient à la confrérie dont tu fais partie.",
"Entre donc, capitaine. N'aie crainte, je ne te causerai pas d'ennuis. Je suis bien plus avisé que mon prédécesseur, comme tu vas pouvoir t'en apercevoir. Qu'est-ce qui t'amène?",
"Je m'intéresse à un navire et je crois qu'il appartient à la confrérie dont tu fais partie.",
"De quel navire s'agit-il? Son capitaine t'a-t-il causé des soucis? S'il s'agit de l'un des nôtres, je jure de le pendre de mes mains ; nous ne voulons pas d'ennuis, par ici.",
"Voilà qui est sage. Nul doute que tu vivras vieux. Malheureusement, je ne sais toujours pas qui commandait ce navire. Il s'agit d'une frégate noire qui a quitté la colonie de nuit.",
"Une frégate noire? Ce navire n'a rien à voir avec moi ou les miens. Nous aussi, nous avons déjà été victimes de ces monstres.",
"Victimes? Comment ça?",
"Cette frégate a coulé une de mes barques et trois de mes hommes ont disparu dans la jungle.",
"Les marins de cette frégate noire... sais-tu qui ils sont?",
"Je n'en ai pas la moindre idée, mais je te conseille de les éviter\nCe navire n'est pas catholique. Plusieurs de mes hommes jurent avoir entendu des enfants pleurer à son bord.",
"C'est très étrange, en effet. Merci du renseignement.",
"Je possède de nombreux bateaux, mon ami. Il va falloir te montrer plus précis.",
"C'était une frégate noire. Que sais-tu à son sujet?",
"Toi aussi, tu as croisé sa route? Dans ce cas, j'imagine que cela signifie que nous sommes dans le même camp.",
"Mais de quoi parles-tu?",
"Cette frégate n'est pas à moi. En fait, elle a coulé une de mes barques et trois de mes hommes ont disparu dans la jungle.",
"Tu ne sais donc rien de son équipage?",
"Non. Je ne suis même pas sûr qu'ils soient humains, mon ami. Mes hommes ont vu cette frégate partir, et jurent avoir entendu des enfants pleurer à son bord.",
"Voilà qui est troublant, en effet. Merci du renseignement.",
"Ce navire n'apporte que des ennuis.",
"En quoi t'intéresse-t-il, si je puis me permettre?",
"Seule sa cargaison m'intéresse. Est-elle toujours intacte?",
"J'ai perdu mon propre bateau et tout mon équipage lors de la tempête, et je ne serais pas là aujourd'hui si je ne m'étais pas trouvé à bord de la barque capturée\nJ'ai échappé de justesse à une corvette française et je ne dois mon salut qu'à des hauts-fonds\nEnsuite, j'ai vu arriver la folle qui a tué mon maître d'équipage, à la recherche de l'une de ces maudites idoles...",
"J'ai l'air d'un tavernier? Non? Alors, ne me raconte pas ta vie. La seule chose qui m'intéresse, c'est la cargaison.",
"Ecoute-moi bien : quand je dis que ces idoles sont maudites, ce n'est pas une façon de parler! Il y a quelques heures à peine, le vaisseau qui les transportait a sombré.",
"Vraiment? Dans ce cas, je perds mon temps, ici. Au revoir.",
"Tu veux acheter ces idoles? Dans ce cas, discutons. Franchement, je serais heureux de m'en débarrasser. Elles n'apportent que des ennuis!",
"Dans ce cas, j'imagine que tu es prêt à négocier. Combien en veux-tu?",
"Je n'ai jamais parlé de les acheter, bien au contraire. Disons plutôt que tu vas me les offrir.",
"Comprends bien que je dois me refaire après la perte de ce navire. En d'autres termes, j'ai besoin de 10 000 pièces d'or.",
"Je n'aurais jamais cru dépenser un jour autant d'argent pour quelques babioles sans valeur, mais tiens, voilà ton argent.",
"Pour une poignée d'idoles impies? Soyons sérieux. Propose-m'en un prix plus raisonnable.",
"J'ai une meilleure idée : donne-moi ce que je veux et je disparais.",
"D'accord, disons 8 000 pièces d'or, mais c'est mon dernier mot. Fais voir ton argent si tu ne veux pas que je te montre la porte.",
"Marché conclu.",
"Ne rêve pas. C'est 10 000 pièces d'or ou tu ne les verras même pas, ces idoles.",
"Tu es dur en affaires, mais je n'ai pas le temps de marchander. Voilà ton argent.",
"J'ai une solution toute simple à t'offrir : tu me donnes les idoles sans attendre et tu gardes la tête sur les épaules.",
"C'est un peu arrogant de la part d'un homme venu me voir seul. Je peux appeler mes hommes à tout moment.",
"Tu marques un point. Combien en veux-tu, déjà?",
"Appelle-les et ce seront tes dernières paroles!",
"D'accord! Ces idoles n'ont fait que me causer des ennuis. Prends-les et disparais!",
"Voilà une sage décision. La meilleure pour chacun de nous.",
"Me tuer ne t'apportera rien. Les idoles sont sous bonne garde, à mon bord. Même toi, tu n'arriverais pas à t'en emparer.",
"Merci de m'avoir dit où elles se trouvaient. Et maintenant, j'ai bien peur que ta dernière heure soit venue...",
"Il faut que j'y aille.",
"Tu bluffes!",
"Crois-tu vraiment? Laisse-moi te prouver le contraire...",
"Tu as raison, c'était du bluff. Bon, je m'en vais.",
"Laisse-moi tranquille, je t'en prie! Je ne sais rien!",
"Mauvaise réponse. Je t'accorde une seconde chance. Cette fois, demande-toi si tu aimes respirer...",
"Ces maudites idoles ne m'ont apporté que des ennuis! D'abord la tempête, puis la corvette, cette fille qui a tué mon maître d'équipage pour en récupérer une, et maintenant toi. Prends-les et disparais!",
"Voilà une sage décision. La meilleure pour chacun de nous.",
"Une très sage décision. Maintenant, il ne me reste plus qu'à m'assurer que tu ne parleras à personne de notre petite transaction.",

};
