string DLG_TEXT[46] = {
"Qu'est-ce que tu veux?",
"Rien. Désolé de t'avoir dérangé.",
"Tu te présentes devant moi alors que ",
"Mateus Santos",
" est toujours en vie? Tu me déçois, capitaine.",
"Plus pour longtemps. Je vais me charger de lui, crois-moi.",
"Que fais-tu ici, capitaine? Que je sache, ",
"Mateus Santos",
" est toujours en vie.",
"Oui, mais la situation a changé, mon ami. ",
"Mateus Santos",
" m'a fait une offre plus... alléchante. Je t'accorde une dernière prière, mais courte. J'ai à faire.",
"Oui, et tu m'as trompé. Ce travail était tout sauf simple. ",
"Mateus Santos",
" n'est pas une proie facile. En fait, il m'a offert une belle somme pour te faire la peau, judas!",
"Peux-tu m'accorder quelques instants? J'aurais un travail à confier à un homme ayant tes capacités et surtout ta... réputation.",
"Je t'écoute.",
"Oublie ça. Ce travail ne m'intéresse pas.",
"Comme tu voudras. Mais je ne pensais pas qu'on puisse refuser une belle somme pour une tâche aussi aisée...",
"De l'argent facile? Je suis tout ouïe.",
"Ça ne m'intéresse pas, je te dis! Ça suffit, maintenant!",
"Oh, c'est très facile, pour peu qu'on ait suffisamment de cran. Et je pense que c'est ton cas.",
"Je déteste qu'on me parle en code. Si tu veux la tête de quelqu'un, dis-moi qui et combien tu paies.",
"Oh, je vois. C'est un travail facile si on n'a pas peur de se salir les mains. Désolé, je ne mange pas de ce pain-là. Salut.",
"La tête en question vaut 1 500 pièces d'or à mes yeux. Elle est perchée sur les épaules de ",
"Mateus Santos",
"Mateus Santos",
" d'Isla Muelle. Sa maison se trouve juste à droite du chantier naval.",
"C'est comme si c'était fait. Où dois-je ramener le trophée?",
"C'est une plaisanterie? Je ne dégaine même pas pour si peu. Fais-moi une meilleure offre ou laisse tomber.",
"Je t'attendrai sur le rivage, près du campement des contrebandiers.",
"D'accord. Ce ne sera pas long.",
"Je t'en supplie, ne me tue pas, capitaine! Je n'ai que les 1 500 pièces d'or que je t'ai promises! Prends-les, mais ne me tue pas!",
"Je regrette, l'ami, mais les affaires sont les affaires, et ",
"Mateus Santos",
" paie mieux que toi.",
"Je n'ai jamais su résister au tintement des pièces d'or. Donne ton argent et file!",
"Je ne veux pas de ton or, idiot! Cesse tes jérémiades et déguerpis avant que je ne change d'avis!",
"Ce n'est rien comparé à ma vie. Prends tout et je m'en vais.",
"D'accord, mais vite!",
"Je n'arrive pas à croire que tu te sois laissé berner par une ruse aussi éculée, sombre crétin! Tu ne mérites pas de vivre!",
"Tu me laisserais partir comme ça? Je... je n'arrive pas à le croire...",
"Oh, tu peux. Mais va le faire ailleurs... et vite, avant que je ne change d'avis.",
"Oui, c'est trop beau pour être vrai, n'est-ce pas? Peut-être parce que j'ai menti. Fais tes prières, et vite!",
"Alors, tel est ton vrai visage? Je ne suis peut-être pas le meilleur bretteur, mais tu vas voir qu'il n'est pas facile de vaincre un homme luttant pour sa vie. En garde!",
"...",

};
