string DLG_TEXT[25] = {
"Quelqu'un à découper en morceaux, capitaine?",
"Certainement. En tout petits morceaux...",
"Voyons. Tu es une fine lame et tu as le regard froid. Je dirais que c'est ",
"Mateus Santos",
" qui t'envoie.",
"Exact. Je suppose que tu sais aussi pourquoi.",
"Oui, je le sais. Mais toi, tu n'as pas l'air d'en savoir long. Tu vois, j'ai travaillé pour ",
"Mateus Santos",
", moi aussi, il n'y a pas si longtemps. J'étais assez bon. Peut-être trop. ",
"Mateus Santos",
" a fini par me craindre. Et un homme comme lui ne connaît qu'un moyen de faire face à la peur : en détruire l'origine.",
"C'est une histoire fascinante, mais je ne vois pas en quoi elle me concerne.",
"Oh, elle te concerne de près, l'ami. Il t'a envoyé pour me tuer parce qu'il a peur de moi. Si tu réussis cette mission, il te craindra aussi. Et tes jours seront comptés. Un assassin ne vit jamais très vieux, surtout avec un employeur comme lui.",
"Je vois. Et quel conseil as-tu à offrir à un autre assassin?",
"Un seul : pars pendant que tu le peux ou cette mission pourrait être ta dernière.",
"Tu as peut-être raison, mais ta tête vaut très cher. Quelqu'un la rapportera, alors autant que ce soit moi!",
"Tu as peut-être raison. Je ne suis pas fait pour le meurtre et je ne vois pas l'intérêt de te tuer.",
"Je suis heureux que tu te sois rangé du côté de la raison. Évidemment, si tu ne me tues pas, quelqu'un d'autre le fera. Où que j'aille, les hommes de ",
"Mateus Santos",
"' me trouveront toujours. Un de ces jours, la chance me quittera.",
"Tu as sûrement raison, mais je ne peux pas t'aider. Tout ce que je peux faire, c'est te souhaiter bonne chance.",
"Tu sais, tu as raison. Quelqu'un aura ta peau un jour ou l'autre, et je ne veux pas laisser passer l'occasion de croiser le fer avec la meilleure lame de l'archipel! En garde!",
"Je peux peut-être t'aider, si tu acceptes un petit travail honnête. Il y a de la place sur mon navire pour la meilleure lame de l'archipel.",
"J'aime ta façon de penser, capitaine. Mon épée est à ton service.",
"Je suis heureux de l'entendre. Bienvenue parmi mon équipage.",

};