string DLG_TEXT[73] = {
"Bonjour, ",
". Puis-je te demander qui tu es et ce que tu fais ici?",
".",
". Pas mal pour un début. Alors, qu'est-ce que tu veux, ",
"?",
"Je sais qu'on t'a engagé pour escorter l'Oiseau.",
"Sans doute. Pourquoi pas? Je suis à court d'argent. C'est pour cette raison que j'ai accepté de faire l'aller-retour jusqu'à Oxbay pour la somme ridicule que m'ont offerte ces radins de Français.",
"Et si je te demandais de me faire l'honneur de me laisser remplir cette mission?",
"Si tu veux ce travail, c'est que ta situation doit être encore pire que la mienne. Mais pourquoi devrais-je te la laisser?",
"Parce que si tu refuses, je te tue.",
"Je te paierai plus que les Français. Ça te suffit?",
"Nous savons tous les deux que tu ne veux pas vraiment prendre la mer.",
"Par tous les diables! Voyons si tu es aussi fort que tu le crois!",
"Je vais te montrer, ordure!",
"Je plaisante. Je te paierai plus que les Français.",
"Me payer? Tu finis par admettre que tu as de l'or, hein? Alors pourquoi veux-tu ce travail?",
"Peu importe... Affaire conclue?",
"C'est vrai, mais j'ai vraiment besoin de cet or, alors je n'ai pas vraiment le choix, tu comprends?",
"Si c'est si mal payé que ça, il serait peut-être sage d'attendre une meilleure offre.",
"Je ne sais pas... Bon ,d'accord, mais il t'en coûtera 3 000 pièces d'or!",
"Voilà. 3 000 pièces d'or tout rond.",
"3 000 pièces d'or? Tu plaisantes.",
"Je n'ai pas une telle somme sur moi.",
"Tu veux que je te dise quelque chose? Tu as raison. Au diable tous ces soldats et leurs guerres coloniales! Quelque chose de mieux se présentera avant que je meure de faim.",
"Alors laisse-moi faire ce travail à ta place.",
"J'en ai un, si ça t'intéresse.",
"Non merci, ",
". Qui sait quand je retrouverai du travail? Je ne suis pas doué pour le commerce et je n'ai pas envie de me faire pirate...",
"Alors, je vais devoir te tuer.",
"Je te paierai plus que les Français.",
"Magnifique! Quelqu'un, là-haut, pense à moi!",
"Bien. Calme-toi et passons aux choses sérieuses.",
"Hélas, ",
", je ne peux rien faire pour toi.",
"Alors, je vais devoir te tuer.",
"Toi et moi savons que tu ne veux pas prendre la mer.",
"D'accord, marché conclu. Voici une note du gouverneur au capitaine du port. Montre-la-lui et il te présentera ",
"Virgile Boon",
"...",
"Virgile Boon",
", capitaine de l''Oiseau'.",
"Où puis-je trouver le capitaine du port?",
"Où puis-je trouver le capitaine de l''Oiseau'?",
"Merci. Au revoir.",
"Il est généralement au port, à surveiller le chargement des marchandises. Tu auras besoin de son autorisation pour appareiller.",
"Merci, ",
".",
"Il sera au port, évidemment, à préparer le navire pour le départ.",
"Merci, ",
".",
"Intéressant. Que me proposes-tu?",
"Je ne veux pas que l''Oiseau' atteigne Oxbay.",
"Tu veux que je le coule?",
"Ou je peux le prendre si tu préfères ; ça ne me gêne pas.",
"La vie de pirate, hein? Ça ne me déplairait pas... Et je commencerai ma carrière de pillage avec toi\nJe prendrai 10 000 pièces d'or pour ce travail. D'avance.",
"Oui, tu ferais un bon pirate. Voilà ton argent.",
"Va au diable, ",
"! C'est trop cher pour moi!",
"Je n'ai pas ça autant d'argent.",
"Par tous les diables! C'est mon jour de chance! Merci, ",
"!",
"Une précision : si tu me doubles, tu regretteras de m'avoir rencontré.",
"Tu peux me croire, l'ami! Moi, ",
", jure que ",
"Virgile Boon",
" nourrira bientôt les poissons!",
"Bonne chance, alors. Bonne chance à toi, ",
".",
"Autre chose, ",
"?",
"Souviens-toi : nous n'avons jamais parlé de cet arrangement.",
"Mais bien sûr, bien sûr! Je ne suis pas idiot, mon vieux!",
"Content de l'apprendre. Nous nous reverrons.",

};