string DLG_TEXT[43] = {
"Va au diable!",
"...",
"Bonjour, l'ami! Tu as l'air d'un vrai loup de mer. Que dirais-tu de te joindre à mon équipage?",
"Sous quelles conditions?",
"Belle prouesse! Tu es meilleur que je ne le pensais. Tu pourrais m'être utile.",
"Tu acceptes de croire que je suis capitaine, maintenant?",
"On admire la mer, hein? Je ne m'en lasse jamais, moi non plus. Ça me brise le coeur de penser que tu ne la verras plus jamais.",
"Voyons - j'ai comme l'impression que tu as décidé de rompre notre accord, vieil homme.",
"Tu as tout compris. Tu es peut-être plus malin que tu n'en as l'air. Donne-moi ton épée et ton pistolet et nous allons te renvoyer aux mines d'Oxbay.",
"Vraiment? Et qu'en pensera ton équipage? ",
"Qu'est-ce que ça peut bien faire, ce qu'ils pensent?",
"Ça t'est peut-être égal. Mais je ne peux pas m'empêcher de penser que tes hommes n'apprécient peut-être pas de travailler pour un chien de menteur comme toi. Ce qui pourrait expliquer pourquoi tu as eu tant de mal à trouver des marins pour ton équipage.",
"Cause toujours. Ça ne te servira à rien.",
"Tu as peut-être raison. Je ferais peut-être mieux de parler à tes hommes. Qu'en dites-vous, messieurs? Vous êtes contents du capitaine Gagne-petit ou vous préférez viser plus haut?",
"Tu parles beaucoup pour un condamné. Tu crois vraiment qu'ils vont t'écouter?",
"Regarde derrière toi, capitaine, et repose-moi la question.",
"Je n'ai pas besoin de regarder. J'ai choisi mon équipage avec soin. Le fait est que la plupart d'entre eux ne parlent même pas cett langue.",
"Eh bien, j'aurai essayé. Eh, ce n'est pas le rivage, là-bas, entre la terre et le ciel? Adieu, capitaine!",
"Quoi? Ne l'écoutez, bande d'imbéciles! C'est moi, votre capitaine!",
"Ils n'ont pas l'air de voir les choses sous cet angle. Ils pourraient bien te tuer - si je ne le fais pas avant eux!",
"J'ai besoin de marins sur lesquels je peux compter. J'offre 10 pièces d'or maintenant, et 200 de plus après l'attaque. Qu'en pensez-vous?",
"Pour ce prix-là, je ne pense pas beaucoup. Nomme-moi capitaine, je me remettrai peut-être à penser.",
"Si tu veux vivre, tu vas me dire où se trouve ton navire et prévenir ton équipage que c'est moi qui commande, maintenant.",
"J'ai une offre qui devrait te plaire encore plus : mène-moi à Oxbay et je te paierai dès notre arrivée.",
"Ça ne devrait pas poser de problème. Je m'entends bien avec les Anglais, en général.",
"Alors, marché conclu! On prend la mer?",
"Tu as de l'aplomb, capitaine, et bon goût en plus. Mais non - personne d'autre que moi ne dirige mon navire.",
"Je regrette de ne pas avoir été clair, mais ce n'était pas une requête. Si tu ne cèdes pas, je devrai le prendre par la force.",
"Même si quelqu'un de plus qualifié que toi se présente? ",
"De plus qualifié que moi? Écoute, bonhomme, tu as peut-être commandé toute une flotte dans la baignoire de ta mère en Angleterre, mais ici on parle d'un vrai navire!",
"Et tu as en face de toi un vrai capitaine. Mets-moi à l'épreuve!",
"D'accord. Tu as signé ta perte. Tu as vu le gros balourd assis à la table, là-bas? Affronte-le et si tu réussis à le battre, on en reparlera. Eh, ",
"Gervasio Serrao",
", il y a un type ici qui t'a traité de ver de terre!",
"Parfait, alors je vais l'écraser comme un ver!",
"Je suis épaté. Mais il ne suffit pas d'être une fine lame pour devenir capitaine.",
"Non? Alors remets-moi à l'épreuve. Choisis.",
"Tout ça pour rien? Parfait! Je n'ai plus qu'à te tuer et à prendre ton navire.",
"Écoute, mon garçon, on s'est bien amusés, mais ça commence à me lasser. Si tu ne veux pas travailler pour moi comme matelot, arrête de me faire perdre mon temps.",
"D'accord. Je vais tenter ma chance ailleurs.",
"On va voir à quel point tu seras las quand j'en aurai fini avec toi!",
"Tu cherches les ennuis, hein? On peut arranger ça!",
"Tu peux toujours essayer, vieillard!",

};