string DLG_TEXT[37] = {
"Je t'ai vu combattre contre notre capitaine. Eh bien, selon nos lois, tu es notre nouveau capitaine et le navire t'appartient.",
"Où est-ce que je peux le trouver?",
"Oh, il est près d'ici, dans la baie de Palm Beach. Tourne à gauche en sortant du village et tu ne tarderas pas à le voir.",
"Parfait! Avec moi, vous allez savoir ce que c'est qu'être des loups de mer, les gars!",
"Arg. Tu dois être ce capitaine dont Artois parlait. Tu arrives trop tard... Unghh... Si tu étais arrivé cinq minutes plus tôt, je n'aurais pas cette dague plantée dans la poitrine. Ungh...",
"Bon sang! Quelqu'un a poignardé ce type!",
"Va au diable, crétin!",
"Avec plaisir. Mais pas avant d'avoir découvert pourquoi l'un de mes hommes est allongé par terre, évanoui, et en ta compagnie.",
"C'était ta dernière erreur! Les gars, attrapez-le!",
"Essayez, bande de chacals!",
"Ton homme est mal en point. Il a pris une balle dans le poumon et il a besoin d'un chirurgien.",
"Combien est-ce que ça va me coûter?",
"Beaucoup. Je demande 2 000 pièces d'or pour mes services.",
"Marché conclu. La vie de mon officier est plus importante que le scintillement de l'or.",
"À ce prix-là, je préfère le laisser mourir!",
"Autre chose : ton officier est en plein délire. Il a dit que les attaques allaient continuer. Il lui faudra deux semaines pour se remettre. Tu devrais peut-être désigner quelqu'un pour le garder pendant cette période?",
"Hum... En effet, ce n'est pas la première tentative contre Artois. Je vais le garder moi-même.",
"Deux semaines?! Impossible, ne comptez pas sur moi!",
"Désolé, capitaine, mais je n'ai plus l'intention de naviguer avec toi. Tu es trop assoiffé de sang pour moi. Adieu.",
"Va au diable, crétin!",
"J'en ai marre de naviguer avec une larve comme toi. Au revoir, je vais chercher quelqu'un de plus sanguinaire!",
"Comme tu voudras!",
"Que veux-tu?",
"Je veux que tu m'accompagnes dans mes voyages.",
"Très bien, mais ne t'avise pas de renouveler les raisons de mon dernier départ.",
"Bien.",
"J'ai entendu dire que tu cherchais du travail",
"Peut-être bien. Et j'ai entendu dire que tu cherchais un homme pour vous guider, ton navire et toi.",
"C'est vrai. Je crois que tu es exactement l'homme que je recherche. Acceptes-tu de naviguer avec moi?",
"Combien paies-tu?",
"J'ai besoin que tu me suives jusqu'à ",
" et je te paierai ",
" pièces d'or.",
"J'accepte",
"Je refuse ta proposition",
"Merci, je sens que mon sort est en de bonnes mains. Voilà ton argent.",
"Merci.",

};