string DLG_TEXT[50] = {
"Ça va, espèce de rabat-joie!",
"Adieu.",
"Qu'est-ce que tu veux? Tu vois pas que je suis occupé?!",
"Je veux te parler.",
"Eh, toi... viens ici.",
"Qu'est-ce que tu veux?",
"Désolé de te déranger, mais j'ai des affaires à régler pour Redmond.",
"J'ai des affaires à régler pour la colonie anglaise.",
"Des affaires? Quelles affaires?",
"Thomas O'Reily",
"Thomas O'Reily",
" m'a engagé pour te livrer des marchandises.",
"J'ai été engagé par ",
"Thomas O'Reily",
"Thomas O'Reily",
" pour te livrer des marchandises.",
"Pourquoi toi? Où est le type habituel?",
"Aucune idée. Quand on me paie bien, je pose pas de questions.",
"D'accord, d'accord. Mes hommes vont décharger la cargaison et tu pourras partir.",
"Parfait. C'est un plaisir de faire des affaires avec toi.",
"Où je vais, ça ne regarde que moi. Adieu.",
"Je suis sûr de ne pas être en affaires avec toi, alors dégage!",
"Je t'ai dit qu'il fallait que je te parle.",
"Je t'ai déjà dit que j'étais occupé. Dégage!",
"Je ne cherche pas d'ennuis, mais si c'est ce que tu veux...",
"Je suis venu acheter quelque chose. Mon argent n'est pas assez bon pour toi?",
"Très bien. Je ne t'embêterai plus.",
"Tu es sourd ou quoi? Je vais te le dire une dernière fois : je suis occupé. Et j'ai rien à vendre.",
"Tu cherches les ennuis ou quoi?",
"Très bien. Je ne t'embêterai plus.",
"Je crois vraiment que tu cherches les ennuis. Alors dégaine ton épée, parce que tu en as trouvés!",
"Avec plaisir!",
"Il se trouve que j'ai à faire ailleurs. Adieu.",
"On dit que tu cherches à acheter quelque chose.",
"Peut-être, peut-être pas. Qu'est-ce que ça peut te faire?",
"C'est exact. Tu peux m'aider?",
"Je demandais, c'est tout. Allez, file.",
"Mais...",
"J'ai dit, dégage!",
"Très bien. Mais tu le regretteras!",
"Calme-toi, je suis là pour t'aider. J'ai entendu dire que tu cherchais des marchandises... disons, spéciales.",
"C'est exact. Mais je ne crois pas que tu sois celui qui pourra me les fournir.",
"L'habit ne fait pas le moine. Je crois avoir exactement ce que tu cherches.",
"Prouve-le.",
"Patience. Pour l'instant, écoute-moi bien : il y a une maison, devant la résidence. ",
"Raoul Calmes",
" y habite. Dis-lui que c'est moi qui t'envoie, et il te montrera tout.",
"Vraiment? Et comment savoir si ce n'est pas une ruse?",
"Il va bien falloir que tu me fasses confiance. Un bon homme d'affaires est prêt à prendre quelques risques de temps en temps.",
"Bien. Mais je n'aime pas la tournure que ça prend, je reviendrai te voir.",

};
