string DLG_TEXT[277] = {
"Ah, une nouvelle tête dans ma taverne! Sois le bienvenu ",
"!",
"Ravi de faire ta connaissance. Je m'appelle ",
".",
"Tu peux faire des courbettes à quelqu'un d'autre. Moi, ",
", je n'en ai pas besoin.",
"Tu es un vrai gentilhomme. Ça ne court pas les rues dans le coin. Je m'appelle ",
". Qu'est-ce qui t'amène?",
"Si mon sourire ne te plaît pas, je vais aller voir ailleurs. ",
"Des affaires à régler.",
"On a la grosse tête, hein? Dommage que je n'ai pas le temps de te la ramener à la bonne taille.",
"Des affaires, hein? Tu es dans la meilleure taverne de l'archipel! Ne fais pas cette tête-là, et viens prendre un verre!",
"Ne t'inquiète pas. Tes affaires restent tes affaires. A moins que tu ne veuilles un verre?",
"Tu as raison. Verse-moi un verre de ton meilleur vin.",
"Je prendrai du vin, mais pas l'eau de vaisselle que tu sers d'habitude à tes clients.",
"Hélas, je n'ai pas le temps. Au revoir.",
"Et boire le poison que tu sers à tes clients? Je tiens trop à la vie. Adieu!",
"Pour une seule pièce d'or, je te sers le meilleur vin que tu aies jamais goûté!",
"2 pièces d'or, et je verrai ce que je peux faire pour toi.",
"D'accord, je suis d'humeur à prendre des risques. Mais je veux plus que du vin contre cet or. Je veux aussi des informations.",
"Voilà ton argent, mais garde ton vin. Je préfèrerais que tu répondes à quelques questions.",
"On dirait que ton vin est un peu trop cher pour moi. Tu n'aurais pas plutôt du rhum?",
"Comment oses-tu faire payer pour cette flotte? Apporte-moi du rhum!",
"Le rhum, c'est aussi une pièce d'or. Si tu n'as pas d'argent, c'est pas mon problème.",
"Tu es encore là? Tu ne peux pas non plus payer deux 2 pièces d'or pour le rhum...",
"Très bien, apporte-le, ton vin. Et puis tu pourras aussi répondre à quelques questions...",
"C'est du vol pur et simple! Apporte le vin, et réponds à mes questions.",
"Dommage.",
"Je crois pouvoir me passer de ton vin sans en souffrir.",
"Alors, qu'est-ce que je peux faire pour toi?",
"J'aimerais parler affaires. Des affaires très importantes...",
"Tu as une chambre libre? J'aimerais rester un moment.",
"Il te reste des chambres libres dans ce taudis?",
"Il me faut des informations sur cette ville.",
"Désolé, mais la chambre est déjà occupée par le capitaine ",
"Amiel Berangere",
".",
"Bon sang! Il faut bien que je dorme quelque part!",
"J'ai une chambre. Pour combien de temps?",
"Juste une nuit.",
"Il me faut juste un endroit où dormir un peu jusqu'à ce soir.",
"Ça fera 5 pièces.",
"Voilà ton argent.",
"On dirait que je ne peux pas m'offrir un bon lit douillet en ce moment. Je passerai la nuit dans la salle de la taverne.",
"Pour quoi? La maison tout entière? Laisse tomber. Je passerai la nuit dans la salle.",
"OK, je vais y réfléchir.",
"Ça te coûtera 5 pièces d'or.",
"Voilà ton argent.",
"On dirait que je ne peux pas m'offrir un bon lit douillet en ce moment. Je passerai la nuit dans la salle de la taverne.",
"C'est la chambre du roi que tu me proposes? Non, merci. Je vais rester dans la salle.",
"OK, je vais y réfléchir.",
"J'aimerais te poser une ou deux questions.",
"Je ne connais pas bien la ville. Tu peux m'aider?",
"J'ai besoin d'un équipage.",
"Je cherche une boutique dans le coin.",
"Mon bateau a besoin d'être réparé...",
"Je t'écoute, ",
".",
"On raconte que ce type, là-bas, te doit de l'argent.",
"Qu'est-ce que tu peux me dire sur ",
"Teodoro Fernandez",
"Teodoro Fernandez",
"?",
"On raconte que des marchandises plutôt rares sont arrivées en ville récemment...",
"J'aimerais bien savoir ce que tu penses d'un certain gentilhomme du nom de ",
"Baldewyn Coffier",
"Baldewyn Coffier",
".",
"J'ai essayé d'approcher le gentilhomme dont tu parlais, mais il a refusé de m'adresser la parole.",
"Je cherche quelqu'un du nom d'",
"Amiel Berangere",
"Amiel Berangere",
". C'est le capitaine du brig 'Le Requin'",
"On raconte que vous avez déclaré la guerre aux Anglais.",
"Je cherche un homme du nom de ",
"Raoul Rheims",
"Raoul Rheims",
". Tu l'as vu?",
"Qu'est-ce qu'on raconte sur lui?",
"Il me faut du travail. Tu ne connaîtrais pas sur cette île un type riche qui aurait peur de voyager tout seul?",
"Merci. Il faut que j'y aille.",
"S'il y en a, il préfèrerait peut-être ne pas attirer l'attention avec un tel entourage... mais tu sais déjà tout ça.", 
"C'est vrai, j'ai oublié. Très bien, je reviendrai plus tard, quand j'aurai moins de bateaux, ha-ha.",
"Je ne veux pas t'aider, tu as fait trop de mal à mon pays.",
"Regardez-moi un peu ce patriote. Très bien, alors adieu.", 
"Tes mains sont couvertes de sang. Tu crois vraiment que quelqu'un voudrait voyager en ta compagnie?",
"Tu as raison, tout le monde a peur de moi! Ha-ha!",
"Tu es arrivé juste à temps. Un marchand cherchait à voyager en bonne compagnie. Tu ferais bien de lui parler. Le voilà, il vient de rentrer dans la taverne.",
"Je vais lui parler tout de suite.",
"Non, il n'y a personne pour le moment. La prochaine fois, peut-être.",
"Hmm. Tant pis, j'attendrai.",
"Tout le monde sait ça, ",
".",
"Tu as raison. Tout le monde dans l'archipel en parle, mais ce n'est pas ce que je voulais dire.",
"Qu'est-ce que tu veux dire, exactement?",
"Je cherche du travail. J'ai un bateau et quelques hommes costauds avec qui j'ai fait les quatre cents coups.",
"J'ai bien peur que tu ne trouves rien, ",
". Le gouverneur ne veut pas que les gens de ton espèce prennent part à ce conflit.",
"Mon espèce? Il est toujours aussi difficile? ",
"Pas difficile, non. Mais il se méfie des traîtres. La seule exception, c'est ",
"Amiel Berangere",
" ",
"Amiel Berangere",
", et seulement parce que c'est un Français de pure souche. En fait, il a une mission très importante : il doit livrer des munitions et des armes à notre flotte qui a capturé Oxbay!",
"On dirait que je vais avoir du mal à trouver du travail, à moins que... peut-être que cet ",
"Amiel Berangere",
" pourrait m'arranger une affaire. Tu sais où je peux le trouver?",
"C'est la première fois que j'entends ce nom-là.",
"Dommage. Bon, parlons d'autre chose.",
"Quel dommage, ",
". En fait, c'était un marchand prospère sur cette île, jusqu'à ce qu'il tombe dans un piège que lui avait tendu ",
"Arnaud Matton",
", le propriétaire actuel de la boutique. Il a tout perdu.",
"C'est un honnête homme, non? Sa situation est si désespérée qu'il ne peut même pas rembourser sa dette?",
"Hélas, ",
", sa situation financière est tragique. Et il a une femme et deux gamins à nourrir. ",
"Baldewyn Coffier",
" travaille aussi dur qu'il peut, mais personne ne veut plus l'aider depuis que son affaire s'est effondrée.",
"Merci pour ces informations.",
"Alors, c'est donc ça que tu voulais! Tu as été engagé par ",
"Arnaud Matton",
", pour causer la perte d'un honnête homme?!",
"Calme-toi. Je voulais juste comprendre la situation.",
"Exactement. Et tu peux me croire : ça me fera très plaisir de le faire.",
"Comprendre? Je sais bien ce que 'comprendre' veut dire, va... Très bien. Il n'a pas un sou, et il doit nourrir sa femme et ses gamins...",
"Merci de ton aide.",
"Tu sais, ",
", j'ai connu plus d'une canaille dans ma vie, mais toi... Cette conversation est terminée, monsieur. Bien le bonjour!",
"Je m'en souviendrai.",
"Pour rejoindre la boutique, tourne à gauche en sortant de la taverne et franchis les portes. Tu la verras juste en face de toi...",
"Merci. J'ai encore quelques petites questions pour toi...",
"Merci, c'est tout ce que je voulais savoir.",
"Alors, c'est le chantier naval que tu cherches. Il est juste en face de ma taverne, à gauche en sortant.",
"Merci. J'ai encore quelques petites questions pour toi...",
"Merci, c'est tout ce que je voulais savoir.",
"Jamais entendu parler.",
"Dommage. Désolé de t'avoir dérangé.",
"Voilà une jolie pièce d'or. On dit que ça aide les gens à retrouver la mémoire...",
"Tu as peut-être raison. Il ressemble à quoi, ton bonhomme?",
"Un Espagnol, avec une cicatrice sur le visage.",
"Ça ne nous aide pas beaucoup. Mais maintenant que tu en parles, il y avait un type bizarre qui est venu il y a quatre jours environ, c'est peut-être lui. Mais il se faisait appeler Jeronimo Elcano.",
"Intéressant! Qu'est-ce qu'il faisait là?",
"Il a pris une chambre, il a passé la nuit, et puis il est reparti.",
"Il est parti? Il a parlé à quelqu'un pendant qu'il était là?",
"Je crois bien que oui. Je l'ai vu discuter avec un type du coin, qui s'appelle ",
"Lucien Bescanceny",
"Lucien Bescanceny",
". Ils ont parlé à mi-voix pendant un moment, et puis ils se sont quittés.",
"Où habite-t-il, ce ",
"Lucien Bescanceny",
"Lucien Bescanceny",
"?",
"Je ne te conseille pas d'aller de frotter à lui, ",
", il est dangereux.",
"Détends-toi. Je veux juste savoir où il habite.",
"OK, mais je t'aurai prévenu. Ne viens pas te plaindre après. Il habite.......",
"Merci, je crois bien que je vais aller lui rendre visite.",
"J'ai encore quelques questions.",
"Bonjour, ",
", ça fait un bail. Comment ça va?",
"Très bien, très bien. Je peux te poser quelques questions?",
"Mêle-toi de tes affaires. C'est moi qui pose les questions.",
"Je cherche à recruter quelques marins pour mon équipage.",
"La pire racaille fera l'affaire. Il me faut quelques bons coupe-jarrets pour mon bateau.",
"Tu as une chambre libre? J'aimerais passer la nuit ici.",
"Tu as une chambre libre dans ce taudis?",
"Tu connais la règle : si tu bois pas, tu poses pas de questions.",
"Non, ça ne me plaît pas ; je ne paierai pas.",
"Voilà ton argent.",
"C'est de la contrebande? On ne parle que de ça en ville, mais le capitaine du port ne fait rien pour l'empêcher.",
"Je crois que tu sais de quoi je parle...",
"Qu'est-ce que tu racontes, ",
"?",
"Il faut que je mette la main dessus, mais je ne sais pas qui contacter. Je me suis dit que tu pourrais peut-être m'aider.",
"Parle moins fort, bon sang! Tu vois le Portugais assis là-bas? Il pourra sans doute t'aider.",
"Merci, tu m'as été d'une grande aide.",
"Qu'est-ce que tu racontes?! Je n'ai rien à voir là-dedans!",
"Dommage. Il va falloir que j'aille voir ailleurs.",
"Désolé, ",
", mais je ne peux plus t'aider. Essaie les ouvriers du port.",
"Merci, j'essaierai.",
"Oui, et il me doit même de l'argent : 500 pièces d'or.",
"Je vois. Je me demandais, c'est tout. Au revoir.",
"Je veux payer ses dettes.",
"Je ne vois pas pourquoi, ",
", ce n'est pas un homme très gentil.",
"Tu as peut-être raison. Je suivrai ton conseil.",
"Il me plaît. Un peu rude, mais j'ai l'habitude. Je vais payer ses dettes.",
"Mais de rien! Ça m'a fait plaisir.",
"Adieu!",
"Comme tu voudras, mais je t'aurai prévenu. Il me doit 500 pièces d'or.",
"Oui, bon, tu as peut-être raison. Tant pis.",
"Voilà ton argent.",
"Très bien. Et voilà sa reconnaissance de dette. Il t'appartient, tu pourras en faire ce que tu veux.",
"Au revoir!",
"Quelqu'un du nom d'",
"Amiel Berangere",
"Amiel Berangere",
" m'a loué une chambre. Pour être franc, je ne sais pas si c'est un capitaine, mais il a les manières d'un officier.",
"Parfait! Où puis-je le trouver?",
"Il est en haut. Je crois qu'il est toujours dans sa chambre.",
"Merci.",
"Oh mon Dieu! Tu l'as tué!",
"Je n'ai pas eu le choix. Il ne voulait pas entendre raison.",
"Oui... et j'en suis navré.",
"Que s'est-il passé? Pourquoi l'as-tu tué?!",
"Il m'a contredit. Ça ne me plaît pas. Ça te dérange?",
"Qu'est-ce qu'on fait, maintenant? ",
", qu'est-ce que je vais faire de lui?",
"Je m'en fiche pas mal.",
"Réfléchis un peu. Il y a toujours une solution.",
"Je n'ai rien à voir avec tout ça, ",
", c'est toi qui l'a tué! Je peux appeler la garde!",
"Regarde un peu ce papier que j'ai trouvé sur lui. Tu sais ce que c'est?",
"Ça serait une mauvaise idée. Une très mauvaise idée.",
"Calme-toi. On va trouver quelque chose.",
"Tu as intérêt à trouver de l'or. Il m'en faudra pour payer les porteurs qui vont nous débarrasser de ce corps et tenir leur langue!",
"C'est du chantage!",
"Fais ce que tu veux, mais je ne te donnerai pas un sou.",
"Espèce de pirate! Comment oses-tu me menacer?!",
"Ça fait trop longtemps que tu es sur cette terre.",
"D'accord, très bien. Combien ça va coûter?",
"Puisque je vais m'occuper de tes problèmes pour toi, il me faut au moins ",
" pièces d'or.",
"Je crois qu'il serait plus facile de te trancher la gorge, tout simplement.",
"Voilà ton or! Mais je m'en souviendrai!",
"Attends! Je vais m'en occuper, pas la peine de sortir ton épée!",
"Attention à ce que tu dis! N'oublie pas à qui tu parles!",
"Je suis navré, ",
". Mais ce genre de choses ne m'arrive pas tous les jours.",
"Bon, alors on est quittes?",
"Oui, oui, ",
", bien sûr. Tu peux y aller ; je m'occupe de tout.",
"Alors à bientôt, ",
".",
"Merveilleux. Seulement, la prochaine fois que tu auras envie de tuer un de mes clients, préviens-moi à l'avance, d'accord?",
"Ne t'inquiète pas. Je te préviendrai. Surtout si tu es le prochain sur la liste.",
"Ha-ha, ",
" c'est une plaisanterie, pas vrai? Pas vrai?",
"À plus tard, aubergiste. En attendant, essaie de décider si j'ai l'air d'un plaisantin ou pas.",
"Mmh... Dans tous les cas, il me faut quand même l'argent pour nettoyer tout ça.",
"Parle-moi un peu de ce papier, et je te paierai tout ce que tu veux.",
"Voilà qui est enfin intéressant! Ce papier, c'est un ordre au capitaine du port de te laisser partir, toi et le bateau que tu escortes. On dirait que ce pauvre ",
"Amiel Berangere",
" allait te vendre au capitaine ",
"Turpin Cabanel",
" avant de lever l'ancre.",
"Mmh, je vois. Merci. Adieu!",
"Écoute, concentre-toi sur la façon de régler ce problème. Combien ça va coûter?",
"Eh! Et si tu me donnais de l'argent? Je t'ai dit tout ce que je savais...",
"Parle encore d'argent, et je vais te coupe la langue!",
"Concentre-toi sur la façon de régler ce problème. Combien ça va coûter?",
"Qu'est-ce que tu racontes? Tout le monde est rentré. On est au milieu de la nuit. Si j'étais toi, j'attendrai demain matin. Peut-être aimerais-tu louer une chambre?",
"Tu as une chambre libre?",
"Non. Parlons plutôt d'autre chose.",
"Désolé, capitaine. Je n'ai rien pour toi. Le capitaine ",
"Amiel Berangere",
" doit lever l'ancre demain, mais jusque-là, je ne peux pas le faire sortir de sa chambre.",
"C'est qui, ce ",
"Amiel Berangere",
"?",
"Et où va-t-il?",
"Encore récemment, il était capitaine d'un navire marchan dans le coin. Et puis il a acheté son propre bateau, et il s'est mis à son compte. À faire de la contrebande, sans doute ; sinon, d'où sort-il cet argent? \nMais les affaires ne sont pas florissantes en ce moment. Il doit se contenter de ce qu'il trouve.",
"Au fait, quel genre de travail un capitaine peut-il trouver sur la Falaise de Fleur?",
"Je ne suis pas sûr, mais j'ai entendu dire que c'est ",
" le gouverneur qui l'a engagé pour escorter un navire de guerre rempli de ravitaillement jusqu'à Oxbay. Tu sais sans doute déjà que nous sommes en guerre contre tes compatriotes.",
"Je vois.... Bon, où est-ce que je peux passer la nuit?",
"Oh, toutes sortes de choses : transporter des marchandises, faire des livraisons, pourchasser des pirates. Et ",
"Amiel Berangere",
" a été engagé pour escorter un vaisseau de guerre.",
"Mmh... Quel genre de bateau?",
"On dirait un navire de ravitaillement. Ils livrent probablement de la nourriture à la flotte française. C'est la guerre, tu sais, alors ils l'ont engagé pour s'assurer que la cargaison ne finira pas au fond de l'eau. Il transporte peut-être aussi de la poudre à canon ou des bombes.",
"Je vois... Alors, où est-ce que je peux passer la nuit?",
"Je ne sais pas. Tu peux peut-être lui parler. Il a pas l'air si mauvais. Peut-être qu'il voudra bien partager sa chambre avec toi.",
"Mmh... J'espère qu'il y a deux lits.",
"Arrête ça immédiatement ou j'appelle la garde!",
"D'accord, du calme! Je m'en vais!",

};
