string DLG_TEXT[26] = {
"Je peux t'aider?",
"Non, non. Pardon pour le dérangement.",
"Bonjour. Tu as besoin de quelque chose?",
"Mademoiselle ",
"Arabella Silehard",
", je présume. Je cherche un jeune homme. Un Espagnol qui s'appelle ",
"Lucas Da Saldanha",
". On m'a dit que vous vous connaissiez.",
"C'est possible. Pourquoi le cherches-tu?",
"Lucas Da Saldanha",
" est un veil ami. J'aimerais discuter affaires avec lui.",
"...",
"Lucas Da Saldanha",
" a un père. C'est ce père qui m'a demandé de le retrouver. ",
"Lucas Da Saldanha",
" a disparu et sa famille est très inquiète.",
"Je comprends. Si je me souviens bien, ",
"Lucas Da Saldanha",
" a déclaré avant de partir qu'il comptait rendre visite à son père.",
"Je vois. Merci de cette aide, mademoiselle ",
"Arabella Silehard",
".",
"Oh, oui. Il m'en a parlé. Mais inutile de s'inquiéter : ",
"Lucas Da Saldanha",
" m'a dit qu'il irait voir son père pour discuter avec lui de choses importantes.",
"Je vois. Eh bien, merci de cette aide précieuse.",

};
