string DLG_TEXT[309] = {
"File avant que j'appelle les gardes!",
"Comme tu voudras.",
"Inutile de crier. Je m'en vais!",
"Que puis-je pour toi, ",
"?",
"Je peux faire quelque chose pour toi, ",
"?",
"Que puis-je faire pour toi, capitaine?",
"J'aimerais jeter un coup oeil à tes marchandises.",
"Je dois partir. Au revoir.",
"J'aimerais faire affaire avec toi...",
"J'ai apporté l'argent, comme convenu. Où est ",
"Sabine Matton",
"?!",
"Mes hommes vont l'amener. Montre-moi l'argent.",
"Bien. Mes gars vont l'amener. En attendant, montre-moi l'or.",
"Et si je gardais la fille ET l'or?",
"Tu l'as apporté, hein? Bon, donne-le-moi et va-t'en. Je garde la fille.",
"Va au diable! Je ne veux pas faire affaire avec toi!",
"Comme tu voudras.",
"Hmph!",
"Tu n'as pas vu ma fille? Elle a disparu. La dernière fois qu'on l'a vue, c'était sur le port.",
"Non, je ne l'ai pas vue.",
"Elle s'est peut-être enfuie avec un garçon.",
"Oui, j'ai des renseignements à ce sujet.",
"Bien sûr que je l'ai vue. Je peux même te dire où elle est.",
"Oui, qu'est-ce que je peux faire pour toi?",
"J'ai besoin d'or, tout de suite, et je cherche du travail. Je peux t'être utile à quelque chose?",
"J'écoute.",
"On m'a demandé de te livrer une cargaison.",
"Tu n'aurais pas besoin d'un capitaine par hasard? J'ai un excellent navire et je peux transporter n'importe quoi, n'importe où.",
"J'ai discuté avec ton débiteur. Il n'a pas de quoi te payer.",
"Ton débiteur n'a pas de quoi te payer.",
"Ton débiteur refuse de payer. Si tu veux récupérer ton argent, tu as intérêt à recourir à d'autres... méthodes.",
"Ton débiteur, ce ",
"Baldewyn Coffier",
", refuse de payer.",
"Ton débiteur m'a dit qu'il te paierait ce qu'il te doit aujourd'hui.",
"Un petit sourire : j'ai convaincu ton débiteur de te payer. Il a promis d'apporter l'argent aujourd'hui.",
"J'ai accompli la mission que tu m'avais confiée. Voilà ton argent.",
"Voilà ton argent. J'ai rempli ma part du marché.",
"Un certain ",
"Baldewyn Coffier",
"Baldewyn Coffier",
" m'a demandé de te remettre cet argent.",
"Un certain ",
"Baldewyn Coffier",
" a eu la gentillesse de me remettre cet or pour toi.",
"J'ai eu une discussion avec ton débiteur. Je crois que tu y vas trop fort. Laisse-lui le temps de lancer son affaire et il te remboursera.",
"Ton débiteur, ",
"Baldewyn Coffier",
" est un homme bien. Si tu ne le presses pas trop, il finira par te rembourser.",
"J'ai livré ta cargaison à Redmond.",
"Ta cargaison est à Redmond, ",
".",
"Il faut que je te parle de cette cargaison que tu voulais livrer à Redmond.",
"Eh bien, en fait... la cargaison que tu voulais que je livre à Redmond...",
"J'ai ta cargaison en provenance de ",
"Thomas O'Reily",
"Thomas O'Reily",
" dans ma cale.",
"Thomas O'Reily",
" m'a engagé pour te livrer une cargaison.",
"J'ai emmené ta fille là où tu me l'avais demandé. J'ai aussi cette lettre pour toi.",
"J'ai emmené ta fille là où tu me l'avais demandé.",
"J'ai emmené ta fille là où tu me l'avais demandé.",
"Ta fille est en sécurité à la colonie espagnole.",
"J'ai des nouvelles de ta fille.",
"J'ai réfléchi, tu sais. Tu es un riche marchand et un bon père. Je te propose de te rendre ta fille en échange de quelques milliers de pièces d'or.",
"Désolé, je dois m'en aller.",
"Comment va-t-elle? Où est-elle? Je t'en prie, dis-le-moi. Je t'en supplie!",
"Ta fille s'est enfuie. Elle est sur mon bateau.",
"Ta fille s'est sauvée. Elle est sur mon bateau.",
"Ta fille est sur mon bateau. Je suis sûr que tu n'hésiteras pas à me payer 5 000 pièces d'or pour la revoir.",
"Ta fille est entre mes mains. Si tu ne veux pas que je lui fasse du mal, paie-moi 5 000 pièces d'or.",
"Elle s'est quoi?! Elle va m'entendre quand je l'aurai retrouvée!",
"À ta place, je me calmerais et j'essaierais de comprendre pourquoi ma fille a voulu s'enfuir de la maison.",
"Ça lui apprendra à défier ses parents! Elle voulait de l'aventure, elle est servie!",
"Tu as raison, c'est ce que je vais faire.",
"Bien, je vais te ramener ta fille.",
"Je vais ordonner à mes hommes de ramener ta fille à terre. Ensuite, à toi de te débrouiller.",
"Tu vas le regretter!",
"Tu as peut-être raison, mais il faut savoir prendre des risques dans la vie.",
"Tu n'es pas le premier à me menacer de la sorte. File!",
"Voilà l'argent : exactement 5 000 pièces d'or. Maintenant, où est ma fille?",
"Calme-toi. Tu vas bientôt la retrouver.",
"Du calme! Je t'ai dit que mes hommes allaient la ramener!",
"J'ai changé d'avis. Je prends l'argent et je garde la fille.",
"Ha! Maintenant que j'ai l'argent, tu ne reverras jamais ta fille!",
"Ma chérie, tu vas bien?! Cette brute ne t'a pas fait de mal?",
"Quel tableau émouvant! Des retrouvailles! Je vous laisse entre vous.",
"Épargnez-moi ces émouvantes retrouvailles si vous ne voulez pas que je change d'avis.",
"On m'a dit que ma fille était à bord de ton navire. Combien veux-tu en échange de sa liberté?",
"Très peu pour un père aimant. À peine 5 000 pièces d'or.",
"Je veux 5 000 pièces d'or. Qu'en dis-tu?",
"Très bien. Amène ma fille ici et tu auras l'argent.",
"Comme tu voudras.",
"Très bien. Elle sera bientôt là.",
"Non. Donnons-nous rendez-vous en dehors de la ville, sur la plage. C'est plus sûr.",
"Pour quelle sorte d'imbécile me prends-tu? Apporte l'argent sur la plage, en dehors de la ville, d'ici deux heures, et peut-être que je te rendrai ta petite fille!",
"... D'accord. Dans deux heures, sur la plage, en dehors de la ville.",
"Et n'essaie pas de faire le malin!",
"Et pas d'entourloupe ou tu ne reverras jamais ta fille!",
"Imbécile! Gardes!",
"Va au diable!",
"Je vois que tu as respecté notre marché. Maintenant que ma fille est en sécurité et que tu as gagné ma confiance, nous pouvons parler affaires.",
"De quelles affaires s'agirait-il?",
"Dans ce cas, vide ton sac!",
"Désolé, j'ai d'autres chats à fouetter pour le moment.",
"Peut-être plus tard. J'en ai assez de toi et de tes missions : J'ai besoin de pendre quelques hommes, verser du sang. À une autre fois.",
"Tu ne m'auras pas comme ça. Tu as réclamé une rançon en échange de ma fille bien-aimée! Sors d'ici, sale pirate!",
"C'est dommage. Au revoir.",
"Tu as peut-être de l'argent, mais tu ne vaux pas mieux que moi!",
"...",
"Je n'ai pas de travail pour toi pour le moment, mais j'ai un service à te demander.",
"Quel genre de service?",
"J'ai une fille. Je crois que tu l'as déjà rencontrée.",
"Oui. Elle est très bien. Mais qu'est-ce que tu attends de moi exactement?",
"Tu dois savoir que les relations entre l'Angleterre et la France ne sont pas fameuses.",
"Exact, et le fait que les Français aient pris le contrôle d'Oxbay n'a rien arrangé.",
"Oui, eh bien... On ne parle pas de la politique de notre gouverneur.",
"Qu'est-ce que tu veux dire?",
"Comme je le disais, les relations entre la France et l'Angleterre sont tendues. J'ai bien peur que la perfide Albion n'emploie prochainement la force.",
"Alors tu veux que je te conduise en lieu sûr.",
"Non, non. Je ne peux pas quitter ma boutique... Mais j'ai une fille... Je t'ai vu lui parler.",
"Oui, on a fait connaissance. Alors, comme ça tu veux emmener ta fille loin de ces troubles?",
"Exactement, j'aimerais que tu la conduises à Isla Muelle, chez sa marraine ",
"Sylvie Bondies",
"Sylvie Bondies",
".",
"Très bien. Je vais te rendre ce service.",
"Et combien comptes-tu me payer pour ça?",
"Désolé, je ne peux pas m'en charger.",
"Eh bien, je voyais ça comme un service. Mais puisque tu parles d'argent, je pense que 1 500 pièces d'or constitueraient une somme plus qu'honnête.",
"Marché conclu. Donne-moi l'argent et c'est comme si c'était fait.",
"Non. Désolé, mais je ne peux pas m'en charger.",
"Voici ton argent. Veille sur ma fille jusqu'à ce qu'elle arrive à Isla Muelle.",
"Tu as ma parole.",
"Comme je l'ai déjà dit, conduis ma fille chez sa marraine à Isla Muelle. Elle s'appelle ",
"Sylvie Bondies",
"Sylvie Bondies",
"\nElle est française, mais vit sur une île espagnole depuis plusieurs années. À votre arrivée, remettez-lui cette lettre.",
"Comment vais-je trouver cette femme dans une ville aussi grande?",
"Oh, c'est simple. En arrivant en ville, descends les escaliers sur ta droite, va tout droit jusqu'à ce que tu arrives à d'autres escaliers\nMonte-les ainsi que les suivants puis tourne à gauche. Continue jusqu'à ce que tu te retrouves en face d'une maison. La porte qui t'intéresse est celle de droite.",
"Bien, je pars immédiatement. Dis à ta fille de m'attendre sur mon bateau, '",
"'.",
"Très bien. Je vais devoir trouver quelqu'un d'autre, alors.",
"Au revoir.",
"J'aimerais te parler d'autre chose.",
"Je vois que tu t'es bien débrouillé. Voilà ton dû.",
"Tu n'as pas l'air ravi. Qu'est-ce qui se passe?",
"Pourquoi ce regard?",
"Excuse-moi, mais je dois partir maintenant.",
"Tu sais quelque chose? Ça m'intéresse. Rends-moi un service et attends que je sois parti pour pour t'énerver.",
"Je peux te poser quelques questions?",
"J'aimerais te parler.",
"Enfin! J'ai bien cru qu'il ne me paierait jamais.",
"Excuse-moi, mais il faut que j'y aille.",
"Maintenant que tes affaires sont réglées, je vais m'occuper des miennes. Au revoir.",
"Je peux te poser quelques questions?",
"J'aimerais te parler.",
"Oui, oui, il a déjà apporté l'argent.",
"Dans ce cas, je veux ma part.",
"Mais tu n'as pas l'air content. Pourquoi?",
"Parce que je le déteste! Je le hais et je veux qu'il paie. Il m'a échappé de justesse... J'étais à deux doigts de le faire jeter en prison pour dettes. Je ne sais pas comment il a fait pour rester en liberté...",
"Qu'a-t-il fait pour que tu le détestes autant?",
"Ça ne te regarde pas. Au revoir.",
"Ça ne te regarde pas!",
"D'accord, d'accord, calme-toi. Je m'en vais.",
"Changeons de sujet. Je peux te poser quelques questions?",
"Bien sûr, voilà ton argent. Tu l'as bien mérité.",
"Bon, il faut que j'y aille.",
"Je peux te poser quelques questions?",
"Tu sais, ",
", je ne vois pas en quoi ça te regarde.",
"Comme tu veux, mais je te croyais meilleur que ça.",
"Vraiment? Moi qui croyais que ce vieux renard allait tirer parti de la tension entre l'Angleterre et la France pour me jouer un sale tour.",
"Comme tu le vois, il ne l'a pas fait. Allez, on décharge... Je n'ai pas envie de m'attarder ici.",
"Bien sûr, ",
". Ça ne devrait pas être long.",
"J'espère que tu as raison.",
"Bon, on a fini, ",
". Merci pour cette livraison et bonne chance.",
"Au revoir.",
"Oui?",
"J'ai livré ta cargaison à Redmond.",
"Désolé, je n'ai pas pu livrer ta cargaison à Redmond.",
"Non, je n'ai pas besoin de tes services. Du moins, pas tant que tu couleras des navires français.",
"Dans ce cas, au revoir.",
"Désolé, je n'ai rien pour toi pour le moment.",
"Je reviendrai plus tard, alors.",
"Je suis désolé, mais ton navire n'est pas assez grand pour ce que j'ai en tête.",
"Je reviendrai plus tard, alors.",
"Oh! J'allais te demander un service. Voilà, je dois faire livrer une cargaison à ",
" au plus vite. Si tu parviens à le faire en un mois, tu recevras ",
" pièces d'or à ton arrivée. Qu'est-ce que tu en dis?",
"J'accepte volontiers.",
"Je ne peux pas accepter.",
"Je t'ai déjà dit aujourd'hui que je n'avais rien pour toi.",
"Oh, désolé.",
"Tu t'es souvenu de ta mission un peu tard, tu ne trouves pas? J'ai déjà reçu tout ce qu'il me fallait. Au revoir.",
"Adieu.",
"Oh! J'attends cela depuis si longtemps. Voilà ta récompense, jeune homme.",
"Je t'en prie.",
"Non, je n'ai pas de travail pour toi pour le moment.",
"Je reviendrai plus tard, alors.",
"Je t'ai déjà confié un travail et je ne suis pas prêt à t'en donner un autre avant que tu m'aies montré que tu étais capable de finir ce que tu commençais.",
"Désolé. Tu as raison, bien sûr.",
"Tu devrais avoir honte de toi! ",
"Thomas O'Reily",
" m'a adressé une lettre dans laquelle il explique clairement que tu as essayé de l'escroquer.",
"Attends! Je peux tout expliquer.",
"Oui, je sais. ",
"Thomas O'Reily",
" m'a déjà adressé une lettre dans laquelle il m'informe que tu as essayé de me voler.",
"Je t'en prie! Je peux tout expliquer!",
"Inutile. Bon, tes machinations m'ont fait perdre 1 500 pièces d'or. Dédommage-moi et je passerai l'éponge sur ce malheureux incident... Pour cette fois.",
"Je n'ai pas cet argent!",
"Très bien, voilà ton argent. Je paie pour mon erreur et je jure que ça ne se reproduira plus.",
"Quoi?! Fiche le camp avant que j'appelle les gardes! Il est hors de question que je refasse affaire avec toi.",
"Ha! C'est fou ce que ça me contrarie!",
"Tu es peut-être plus sensé que je le pensais. Veille à ce que ça ne se reproduise plus.",
"Ah ça, non, ",
".",
"Ah, tu arrives à temps! J'ai une cargaison à livrer à Redmond. C'est payé 600 pièces d'or.",
"Attends. L'Angleterre n'est-elle pas en guerre contre la France?",
"Marché conclu, ",
".",
"Désolé, mais je n'ai pas assez de place dans ma cale pour accepter cette mission.",
"Très bien, je reviendrai plus tard.",
"Mes affaires n'ont que faire de la guerre. Crois-moi, ce voyage ne présente pas plus de risques que d'habitude.",
"Et la cargaison?",
"Facile pour toi qui te trouves sur la terre ferme de dire ça. C'est plus risqué que d'habitude, voilà pourquoi j'exige d'être payé plus.",
"Tu es plus dur en affaires que mes partenaires habituels.... Très bien, je peux te proposer 800 pièces d'or, mais c'est mon dernier mot.",
"Très bien. De quel type de cargaison s'agit-il?",
"Non, non, non. J'ai déjà envoyé des navires à Redmond et tout s'est bien passé. 600 pièces d'or, c'est ma dernière offre.",
"Très bien, ça marche. Et la cargaison?",
"Désolé. C'est trop risqué. Au revoir.",
"Eh bien, puisque nous sommes partenaires maintenant, permets-moi de me présenter. Je suis ",
".",
"Je suis ",
".",
"Eh bien, puisque nous sommes partenaires maintenant, permets-moi de me présenter. Je suis ",
".",
"Je suis ",
".",
"La cargaison se compose de 100 tonnes de cacao. Livre-la à Thomas O'Reily, le marchand de Redmond.",
"Parfait.",
"Tu as des marchandises à vendre ou tu as juste besoin d'objets personnels, capitaine?",
"J'aimerais vendre la cargaison que j'ai apportée.",
"J'aimerais acheter quelques objets pour moi.",
"Nous ne ferons pas affaire. Au revoir.",
"Parfait, parfait! Franchement, je craignais pour la cargaison à cause de cette maudite guerre...",
"Tu n'as pas oublié quelque chose?",
"Oh, si, l'argent. Bien sûr. Voilà. J'espère qu'on pourra retravailler ensemble à l'avenir.",
"On verra bien. Pour l'instant, il faut que j'y aille. Au revoir.",
"Oui, j'ai des problèmes à résoudre au plus vite.",
"Quelle sorte de problèmes?",
"Tu vois, ",
", il m'arrive de prêter de l'argent aux gens qui en ont besoin.",
"Alors comme ça, tu es marchand ET usurier.",
"Usurier est souvent péjoratif. Je ne vois rien de négatif dans ce que je fais. Donc, un certain ",
"Baldewyn Coffier",
"Baldewyn Coffier",
" m'a emprunté 5 000 pièces d'or et maintenant, il doit rembourser,\nmais il se dit à sec!\nJe suis sûr qu'il a l'argent. Il ne veut pas me payer, c'est tout. En fait, j'ai entendu dire qu'il avait tenté d'escroquer une autre personne en lui promettant une fortune.\nDieu merci, ça n'a pas marché, mais qui sait le nombre d'imprudents qu'il a déjà pu piéger?",
"Je comprends, je comprends. Je vais lui faire cracher son argent sur-le-champ...",
"Pas si vite, ",
". Si tu réussis à récupérer mon argent, tu auras ta part. Disons, dix pour cent...",
"500 pièces d'or, c'est ça? Pas si mal pour quelque chose d'aussi simple. Marché conclu.",
"500 pièces d'or, c'est tout? Sans vouloir t'offenser, ",
", je ne trouve pas ça très généreux.",
"Très bien. Je vais te donner quinze pour cent, soit 750 pièces d'or.",
"Marché conclu.",
"Au contraire, je trouve ça déjà TROP généreux pour un travail aussi simple, alors ne compte pas sur moi pour t'en donner plus!",
"Compte tenu de ta réputation, tu ferais mieux de t'en contenter. Un homme comme toi pourrait bien prendre mon argent et disparaître. 500 pièces d'or et pas une de plus!",
"Très bien, mais n'oublie pas que c'est la dernière fois que je travaille pour si peu.",
"Ridicule. Tu ne crois quand même pas que je vais accepter si peu. Au revoir.",
"Comme tu voudras. Je vais trouver quelqu'un d'autre. Les capitaines ne manquent pas dans le coin.",
"Au revoir.",
"Oui, eh bien... Tu sais, je crois que je vais accepter ce travail... Il n'y a pas de petits profits!",
"Parfait! Alors, pars à la recherche de ce scélérat. Il se balade souvent en ville et se cache à la taverne à la recherche de sa prochaine victime.",
"Je serai vite de retour. Ça ne devrait pas me prendre beaucoup de temps.",
"Très bien. Tu ne me laisses pas d'autre choix que de déposer une plainte officielle qui mènera à son arrestation pour dettes!",
"C'est ton problème. Comme tu voudras.",
"Pourquoi ne l'as-tu pas fait avant? Pourquoi tout ce manège pour récupérer ton argent?!",
"Attends, ne t'en va pas!",
"Quoi?",
"Désolé. J'ai à faire et je n'ai pas le temps de discuter. Au revoir.",
"Eh bien... Tu sais, une plainte officielle doit être signée par la partie lésée, en l'occurrence moi, et d'au moins un témoin.",
"Et tu veux que je sois ce témoin? Oublie, je préfère rester en dehors de tout ça.",
"Qu'y a-t-il à la clé? Un témoignage, ça se monnaie.",
"Je te donnerai ce que je t'ai promis pour récupérer mon argent.",
"Eh bien, c'est une offre intéressante. J'accepte.",
"Double la mise et on pourra en rediscuter.",
"Eh bien, dommage! Je comptais sur toi.",
"Au revoir, ",
".",
"J'aimerais te poser quelques questions.",
"Parfait. J'ai déjà rédigé la plainte. Si tu veux bien signer ici...",
"Voilà. Bon, maintenant, donne-moi mon argent et je file.",
"Voilà. Bon, maintenant, j'ai quelques questions à te poser.",
"Très bien, je double la mise. Ce qui fait ",
" pièces d'or. J'ai déjà rédigé la plainte, alors si tu veux bien signer ici...",
"Voilà. Bon, maintenant, donne-moi mon argent et je file.",
"Voilà. Bon, maintenant, j'ai quelques questions à te poser.",
"Dommage. Je pensais qu'on aurait pu faire affaire.",
"Au revoir, ",
".",
"Attends! J'accepte ton offre.",

};