string DLG_TEXT[31] = {
"Merci mille fois. Nigel Blythe à toujours été prompt à punir les gens. Si tu n'étais pas intervenu, je serais sans doute mort.",
"Ouais, j'ai remarqué que tu avais quelques petites difficultés avec lui.",
"Ouais, j'ai remarqué que tu avais quelques petites difficultés avec lui.",
"C'est vrai. Je servais comme navigateur sur le navire de Nigel. Pour être honnête, ce n'est pas un très bon marin\nIl n'y a pas si longtemps, nous avons pris chargé un grand volume de marchandises à destination d'une île inconnue de nous tous. Le bateau a fini par s'échouer après une tempête\nOn s'est échappé, mais le navire et la marchandise ont été détruits. Et Nigel dit que tout est ma faute.",
"Et maintenant, tu n'as plus de capitaine.",
"Je ne me suis pas présenté. Je suis ",
". ",
"Je m'appelle Artois Voisey, et je suis en effet sans navire. Je serais ravi de te servir, si tu m'en trouves digne.",
"Merci, mais j'ai déjà un navigateur.",
"Marché conclu. Mais s'il te plaît, essaie de ne pas couler mon bateau.",
"Que puis-je faire pour toi, capitaine?",
"Quoi?",
"Je ne fais que passer.",
"Repos.",
"Capitaine, ces hommes ont tué mon ami... un vieil ami, et ils veulent me tuer moi aussi...",
"Oui, d'accord. Mais dis-moi : pourquoi t'ont-ils attaqué?",
"J'ai bien peur que cela soit un secret, un secret qui n'est pas le mien. Je suis constraint par le code de Morgan et Bartholemew.",
"Peut-être, mais tu n'es pas vraiment un pirate, et je suis ton capitaine. Et si tu n'as pas envie de voir ton existence prendre fin avant l'heure, je te conseille de parler, et vite!",
"Tu es un homme d'honneur, Artois. C'est quelque chose que je respecte. Garde ton secret.",
"Tu sais être convaincant. Je te dirai ce que je sais\nNigel Blythe a entendu parler d'un navire échoué près de Conceicao qui transportait un trésor dans ses cales. Nous étions en route pour le trouver lorsque nous avons fait naufrage nous aussi\nMaintenant que tu as tué Nigel, je suis le seul homme en vie sachant encore comment trouver le trésor. C'est pour ça que l'ancien équipage de Blythe est à mes trousses\nJe ne leur dirai jamais ce que je sais, mais je te le dirai à toi, parce que tu es honnête. Enfin, plus ou moins. Le trésor se trouve sur Douwesen. Tu trouveras le chemin qui mène à l'épave sous la cascade.",
"Voilà qui est intéressant!",
"Merci, capitaine. Je savais que je pouvais compter sur toi.",
"De rien. Content de te trouver en bonne santé.",
"Il y a autre chose qui t'inquiète?",
"Oui ; je ne suis pas très populaire auprès des autorités locales, à cause de ce petit trouble à l'ordre public...",
"Oh, ne t'inquiète pas, je crois que je peux arranger ça.",
"Oui, peut-être, tu as été... hé-hé... témoin de toute la scène.",
"Merci, capitaine! Tu m'as encore une fois sauvé la vie. Je crois que je peux te confier mon secret maintenant\nNigel Blythe a entendu parler d'un navire échoué près de Conceicao et qui transportait un trésor dans ses cales. Nous étions en route pour le trouver lorsque nous avons fait naufrage nous aussi\nMaintenant que tu as tué Nigel, je suis le seul homme en vie sachant encore comment trouver le trésor. C'est pour ça que l'ancien équipage de Blythe est à mes trousses\nJe ne leur dirai jamais ce que je sais, mais je te le dirai à toi, parce que tu es un honnête homme. Enfin, plus ou moins. Le trésor se trouve sur Douwesen. Tu trouveras le chemin qui mène à l'épave sous la cascade.",
"Merci, Artois, je n'oublierai pas ce que tu as fait pour moi.",
"Je n'ai qu'une requête, capitaine : j'ai juré que si je me sortais de cette aventure en vie, je ferais don de 4 000 pièces d'or à l'église de Redmond.",
"Bien sûr, pas de problème! Et maintenant, allons-y.",

};
