string DLG_TEXT[141] = {
"Bonjour, ",
", à quoi doit-on l'honneur de ta présence?",
"Pardonne-moi, mais ne serais-tu pas ",
"?",
"Eh, toi! Oui, toi. Tu t'appelles bien ",
", non?",
"Rien. Je visite, c'est tout. Histoire de goûter à l'atmosphère de la ville.",
"Ce n'est pas tes affaires!",
"J'ai parlé à quelques personnes dans le coin, et on dit que tu es un type honnête.",
"J'ai parlé à l'aubergiste, tu sais, et il n'a pas confirmé ce que tu m'as dit. Je serais enclin à penser que tu m'as menti.",
"J'aimerais te parler de ce petit problème entre le marchand et toi.",
"Je cherche un commissaire pour mon bateau, et je crois que tu feras l'affaire. Qu'en dis-tu?",
"J'ai payé ce que tu devais à ",
"Arnaud Matton",
". Te voilà donc libre de servir comme commissaire sur mon bateau.",
"Non. Je n'ai pas besoin de tes services.",
"J'ai payé ta dette.",
"Veux-tu m'engager comme commissaire sur ton bateau?",
"Oui. Je crois que tu feras un très bon membre d'équipage.",
"Oh, te voilà. Je me demandais quand tu allais te montrer.",
"À en juger par ta mine réjouie, les affaires ont repris, pas vrai?",
"Je suis navré, je t'ai pris pour un autre.",
"Je ne fais que passer. Je n'ai pas de temps à perdre avec les gens de ton espèce.",
"Très bien. Mais si tu as un jour besoin d'un commissaire, je suis ton homme.",
"Ouais, c'est ça, j'y penserai.",
"Tu es capitaine, pas vrai?",
"Oui, c'est exact... mais comment le sais-tu?",
"Oui, comme si c'était tes oignons... je suis capitaine. Mais comment le sais-tu? Et qu'est-ce que ça peut te faire?",
"Je suis désolé, mais je n'ai pas le temps de te parler.",
"Je n'ai pas de temps à perdre avec les gens de ton espèce. Fiche-moi la paix!",
"C'est mon travail de savoir, en regardant quelqu'un, ce qu'il fait et quel genre d'homme il est.",
"Ton travail? Tu ne m'as pas l'air d'un capitaine de la garde. Non, tu ressembles plutôt à un banquier.",
"Oh, vraiment? Quelqu'un d'aussi intelligent que toi doit au moins être capitaine de la garde. Ou serais-tu un simple usurier?",
"Oui, c'est un tour amusant, mais j'ai  à faire ailleurs.",
"Tu m'as fait perdre assez de temps comme ça. Fiche-moi la paix.",
"Non, ",
", je ne suis pas banquier. Et certainement pas capitaine de la garde. Je suis un humble marchand. Du moins, je l'étais.",
"Et tu ne l'es plus? Drôle d'endroit pour prendre sa retraite.",
"Et qu'est-ce que tu fais maintenant? Tu as volé assez de clients pour prendre ta retraite?",
"Hélas, non. Je ne suis pas à la retraite. Pas par choix, en tout cas. Mon magasin a été volé, juste sous mon nez. Mais bien sûr, ce n'est pas ton problème. Je suis navré de t'embêter avec mes soucis.",
"Pas du tout. Dis-m'en davantage. Je peux peut-être t'aider.",
"Tu sais, j'ai l'habitude. Les gens veulent toujours que j'arrange leurs histoires. Je peux peut-être t'aider, toi aussi. Mais pas gratuitement. Même quelqu'un comme toi doit avoir quelque chose à offrir en échange.",
"Non, non. Tout va bien. Il faut que j'y aille.",
"OK. Moi aussi. Au revoir.",
"Ce n'est pas une longue histoire. J'étais propriétaire du magasin du coin, mais mon assistant, ",
"Arnaud Matton",
"Arnaud Matton",
", a réussi à me dévaliser et à me prendre mon magasin\nJ'étais prêt à travailler pour me refaire, mais personne n'a accepté de me prêter de l'argent... sauf ",
"Arnaud Matton",
"lui-même\nJ'étais aux abois. Je n'avais pas le choix. Mais il a réussi à me piéger encore une fois, et maintenant, j'ai touché le fond. Je croule sous les dettes.",
"Je peux peut-être t'aider.",
"Je serai ravi de t'aider... mais pas pour rien, bien sûr.",
"Ton histoire est bien triste, mais je ne vois pas ce que je peux y faire. Et puis, il faut que j'y aille.",
"On dirait que tu l'as bien cherché. Si tu n'avais pas été aussi naïf, tu n'aurais jamais perdu ton affaire. Au revoir!",
"Voilà ce que je te propose, ",
" : si tu me prêtes 10 000 pièces d'or, je pourrais rembourser ce que je dois à ",
"Arnaud Matton",
". J'investirai le reste de l'argent dans mon magasin, et en un mois, je pourrai te rembourser. Je te le garantis.",
"Bon, je suppose que je pourrais te prêter l'argent, mais pour un mois, pas plus.",
"J'ai une meilleure idée. Il me faut un commissaire sur mon bateau, et tu as l'air de savoir comment distribuer l'argent aux autres. Ce n'est pas la profession la plus prestigieuse qui soit, mais ça devrait t'aider à te refaire. Qu'en dis-tu?",
"J'ai bien peur de ne pas pouvoir t'aider.",
"Désolé, ",
", mais je ne pense pas que tu pourras m'aider, après tout.",
"Désolé que tu le prennes comme ça. Au revoir, alors.",
"Je ne peux pas faire mieux. Si ça ne t'intéresse pas, je m'en vais.",
"Il se peut que ça soit mon nom. Qui es-tu, et que me veux-tu?",
"C'est le marchand ",
"Arnaud Matton",
", qui m'envoie, pour récupérer l'argent que tu lui dois.",
"Pas de petits jeux avec moi. On m'a dit que tu devais de l'argent à un respectable citoyen, mais que tu refusais de le rembourser.",
"Je serais ravi de payer mes dettes, si seulement je pouvais. Mais je n'ai vraiment pas d'argent.",
"Arnaud Matton",
" m'a prévenu que tu dirais ça. Et il m'a dit de ne pas tomber dans le panneau.",
"Est-ce que j'ai l'air d'un imbécile? ",
"Arnaud Matton",
" m'a bien dit que tu étais un escroc et un menteur et que tu ne manques pas d'argent, en réalité. Et je te conseille de le rendre pendant que tu le peux.",
"Personne n'a jamais osé me traiter de menteur, ",
"!",
"Ça ne veut pas dire que tu es honnête pour autant. Quelqu'un peut témoigner de ton honnêteté?",
"Peut-être pas. Mais je fais confiance à ",
"Arnaud Matton",
" sur ce point. Tu ne m'auras pas avec tes belles paroles.",
"Pas la peine de monter sur tes grands chevaux. Je ne suis pas un des ploucs du coin!",
"Demande à qui tu veux. À l'aubergiste, si tu veux! Il te dira que je suis un honnête homme, ",
".",
"Très bien. Je vais me renseigner.",
"Qu'est-ce que tu vas faire?",
"Je vais aller parler à ",
"Arnaud Matton",
", et puis on verra.",
"Je peux peut-être t'aider.",
"Tu sais, ",
"Arnaud Matton",
", je peux peut-être t'aider. Contre une petite pièce d'or, bien sûr.",
"Très bien. Je vais attendre qu'",
"Arnaud Matton",
" prenne une décision, mais je suis sûr qu'il va m'envoyer en prison.",
"Arrête avec la boule de cristal. Qui vivra verra.",
"Tu l'as dit, ",
".",
"Adieu.",
"Ça fait un moment que tu cherches à finir en prison, et c'est moi qui vais finalement t'y mettre!",
"Que dis-tu de cette idée, ",
" : si tu me prêtes 10 000 pièces d'or, je pourrai rembourser ",
"Arnaud Matton",
" et investir le reste de l'argent dans mon magasin. En un mois, je pourrai te rembourser toute la somme.",
"Bon, je suppose que je pourrais te prêter l'argent, mais pour un mois, pas plus.",
" J'ai une meilleure idée. Il me faut un commissaire sur mon bateau, et tu as l'air de savoir comment distribuer l'argent aux autres. C'est un travail, en tout cas. Qu'en dis-tu?",
"J'ai bien peur d'avoir parlé trop vite. Je ne pense pas pouvoir t'aider.",
"Désolé, ",
", mais je ne crois pas pouvoir t'aider.",
"Quel dommage. Au revoir.",
"Je ne peux pas faire mieux. Si ça ne t'intéresse pas, je vais y aller.",
"Voilà une offre intéressante, ",
", et je suppose que je serais idiot de refuser. Mais il me faut 2 500 pièces d'or par mois.",
"2 500? Désolé, mais je crois qu'on s'est mal compris. Allez, salut.",
"C'est honnête. Sois le bienvenu dans mon équipage.",
"C'est une offre très intéressante, ",
", mais ça ne serait pas honnête de ma part de quitter la ville alors que je dois encore de l'argent à ",
"Arnaud Matton",
".",
"Et si je payais ta dette et que tu travaillais pour moi gratuitement, pendant deux mois? Après ça, je te paierai 2 500 par mois. Marché conclu?",
"Désolé, mais on dirait que je ne peux rien pour toi. Adieu!",
"Merci beaucoup, ",
". Je te rembourserai dans un mois. Tu verras!",
"Parfait. À dans un mois, alors.",
"Marché conclu, ",
"! Si tu peux payer ",
"Arnaud Matton",
" je serai ravi de rejoindre ton équipage.",
"Parfait. Et maintenant, si tu veux bien m'excuser...",
"Pardon, capitaine, mais où dois-je t'attendre?",
"Mon bateau est le '",
"'. Attends-moi là-bas.",
"Excellent, capitaine. Merci de ton aide. Où dois-je t'attendre?",
"Mon bateau est le '",
"'. Attends-moi là-bas.",
"Oui, bien sûr, ",
". Voilà ton argent, comme convenu. Tu verras que j'ai ajouté une prime, en témoignage de ma gratitude.",
"Excellent! Je suis ravi de voir que j'ai eu raison de te faire confiance. Maintenant, si tu veux bien m'excuser, il faut que j'y aille.",
"J'ai une proposition à te faire : que dirais-tu de faire partie de mon équipage, en tant que commissaire?",

};
