string DLG_TEXT[20] = {
"Alors dis-moi : qu'est-ce que tu fais sur mon bateau?!",
"Je suis venu pour affaires.",
"Je suis en mission pour le gouverneur.",
"Hein? Ce n'est pas mon bateau? Oh pardon... j'ai dû me tromper!",
"Quoi? Ce chien qui se prend pour un gentilhomme?",
"Oui, c'est bien le chien dont je parle. Il m'a ordonné de fouiller ton bateau, car on te soupçonne d'enlèvement.",
"Fouiller mon bateau? Je vais te faire passer sous la quille : comme ça, tu pourras regarder si tu trouves des berniques sur la coque quand on lèvera l'ancre!",
"Tu peux toujours essayer. Mais je te préviens que les canons du fort ont reçu l'ordre de ne pas laisser ton navire quitter le port.",
"Ça m'étonnerait, ",
"Corentin Lucay",
"! La fille m'appartient! Et personne ne me donne d'ordres!",
"...",
"Je vais te tuer!",
"...",
"De quelles affaires tu parles? Tu veux que j'escorte ton bateau quelque part?",
"Non. Je cherche à savoir ce qui est arrivé à une certaine jeune fille...",
"Quoi? Ce chien t'a envoyé reprendre sa garce?!",
"C'est à peu près ça, oui.",
"Je vais te faire une offre amicale, marin d'eau douce, puisque tu n'as pas l'air de savoir à qui tu as affaire : tu laisses ton argent, tes armes et tes vêtements sur mon bateau, et je te laisse repartir en vie.",
"C'est une proposition intéressante, mais mon épée et moi en avons une autre. En garde!",

};
