string DLG_TEXT[251] = {
"Oh, c'est toi, ",
". Qu'est-ce que tu fais ici?",
"Ça ne te regarde pas ",
". Et je pourrais te poser la même question, mais je suis trop occupé pour ça.\nAlors trouve une place où t'asseoir et laisse-moi tranquille.",
"Je ne m'attendais pas à te trouver ici!",
"Content de te voir, ",
". On m'a dit que tu passais ton temps à sauver les vieillards, ces derniers temps.",
"À mon tour maintenant, de t'interrompre. Où as-tu trouvé un type aussi serviable, ",
"?",
"C'est mon secret, ",
". Mais tu as entendu ce qu'il avait à dire. Alors maintenant, on peut travailler ensemble, comme je te l'avais proposé.",
"Content de voir que tu m'as attendu. Maintenant, on peut partir ensemble.",
"Bien sûr. Dès que ",
"Vincent Bethune",
" ici présent nous aura dit où on va.",
"C'est une embuscade! Allez chez lui et enfermez-vous.\nJe les retiendrai le plus longtemps possible.",
"Fais attention à toi!",
"Qu'est-ce qui se passe ici, bon sang?!",
"Ah. ",
"Vincent Bethune",
" m'a parlé de toi. Tu es le garçon de courses de ",
"Robert Christopher Silehard",
" le garçon de courses de ",
"Finalement réveillé, hein?",
"Qu'est-ce qui s'est passé?",
"Le moment est venu de payer une visite au gouverneur et de lui poser quelques questions importantes.",
"Je te suis. Allons-y.",
"Bien, mais on ne peut pas faire irruption dans la résidence en plein jour. Attendons la tombée de la nuit à la taverne.",
"Bien pensé. En plus, je boirais bien quelque chose.",
"Écoute, plus tôt le gouverneur aura répondu à mes questions, plus tôt la confiance sera rétablie entre nous.",
"Oui. Je suppose que tu as raison.",
"Pour commencer, quittons cette ville.",
"D'accord.",
"Il vaut mieux qu'on se sépare ici, sinon on risque davantage d'ennuis.\nTu pistes ce type qui a copié la légende et je pars à la recherche de l'idole.",
"Ça me va. On peut se retrouver au phare, là où vit le vieux.",
"??? Qu'est-ce que tu fais ici?!",
"Je te cherchais! Comment ai-je pu être aussi stupide?!",
"Tiens! Regarde ce que nous envoie la marée. Je croyais qu'on devait se retrouver au phare.",
"J'en ai eu marre d'attendre.",
"Eh bien, je pense que tu conviendras que ça valait la peine d'attendre. J'ai trouvé un journal de bord. Voyons, alors... attends... Diable! Il n'y a rien sur l'endroit où le trouver! Attends! Chut! Je suis sûr d'avoir entendu un grincement de porte. Quelqu'un vient!",
"Et alors? Je vais enfin pouvoir trouver ce corsaire espagnol qui est censé avoir enlevé la fille.",
"Va au navire du pirate.",
"Pas tout de suite. Ce n'est pas le moment.",
"Il faut que je retrouve cette fille. Si je ne la trouve pas ici, j'aurai de sérieux ennuis.",
"...",
"J'ai échappé à ces fanatiques de justesse! Cette affaire est plus dangereuse que je ne le pensais.",
"...",
"Les ravisseurs de Lucas ont demandé que la rançon soit apportée dans cette taverne, mais ils n'ont pas l'air d'être là.\nAha, ces deux types au bar semblent attendre quelqu'un...",
"Pas la peine de perdre du temps. Ce sont probablement ceux que je cherche. (leur montre le signe)",
"Je devrais peut-être d'abord écouter un peu leur conversation? (écoute la conversation.)",
"La chance me sourit aujourd'hui. ",
"Pepin Bertillon",
" a son navire à quai, ce qui veut dire que le capitaine ne doit pas être loin. Il ne me reste plus qu'à le trouver et à lui faire quelques trous dans le ventre.\nMais je dois d'abord vérifier que c'est bien lui que je tue - Les gens du coin sont plutôt violents et une erreur pourrait m'attirer pas mal d'ennuis.",
"...",
"Ne t'en fais pas pour ça. Je ne crois pas que tu sois du genre à perdre ton temps, alors...\nJe parierais que tu es ici pour un type du nom de ",
"Raoul Rheims",
". Que ça te plaise ou non, je viens avec toi.",
"Très bien, ",
", tu peux m'accompagner.",
"Combien de temps faut-il attendre?",
"Researcher",
" a dit que ça pouvait prendre plusieurs jours.",
"Ça fait déjà une semaine. J'ai besoin d'action!",
"Plusieurs centaines de livres d'or sont en jeu. Tu ne crois pas que ça vaut la peine d'attendre une semaine?",
"Pour toi, peut-être. Moi, j'en ai assez. J'ai la bougeotte. Pourquoi est-ce qu'il ne finit pas la traduction à bord?",
"Tu sais, je n'y avais pas pensé.",
"Ouais, je suppose que les pirates n'ont pas vraiment besoin de bon sens, hein? Alors, à quoi vas-tu utiliser cet or, ",
"?",
"Quoi?",
"Tu veux que je parle plus lentement? Que. Vas. Tu. Faire. De. Ta part du trésor?",
"J'achèterai une île anglaise, je crois, pour y vivre selon mes règles. Ou je me ferai peut-être pair anglais. Ça pourrait avoir des avantages. Et toi?",
"C'est un secret.",
"D'accord. Comme tu veux.",
"Est-ce que tu t'opposeras à la flotte régulière?",
"Non. Je vais la détruire!",
"Je commanderai le fort! Prépare-toi à une sacrée canonnade!",
"Contente-toi de toucher ce que tu vises!",
"On a gagné! On écrira des chansons sur cette bataille ou je ne suis qu'un vieux morse! On pourrait prendre tout l'archipel à nous deux! Ou toutes les Caraïbes!",
"C'est sûr. Mais il vaudrait mieux avoir une petite discussion avec ",
"Moses Blinman",
" pour commencer.",
"Écoute-toi, ",
"! Tu devrais avoir honte de toi! Tu viens de détruire les rêves d'une douce jeune fille avec ta logique assommante!",
"Le trésor passe toujours en premier, ma chère. Ensuite, si tu veux toujours conquérir les Caraïbes, je serai avec toi. Considère cela comme une promesse.",
"J'espère que le lettré a eu assez de temps pour examiner ces gribouillis. Je doute que nous puissions résister à une seconde attaque.",
"Je ne sais pas si le gouverneur a d'autres navires de guerre.",
", le temple semble situé à l'intérieur des terres. En route!",
"D'accord, mais il ne faut pas attirer l'attention. Laissons l'équipage ici jusqu'à ce que nous ayons examiné ce temple de nos propres yeux.",
"J'ai du mal à croire qu'on ait réussi! Ce n'est plus qu'une question de temps avant qu'on se roule dans de l'or antique!",
"S'il y a de l'or ici.",
"Ne dis pas ça! On ne peut pas être venu d'aussi loin pour rien!",
"On verra bien.",
"Il y a trois passages, ici, et n'importe lequel peut être le bon. Comment choisir?",
"Je ne sais pas. Ça peut être le piège dont ",
"Researcher",
" parlait.",
"Alors, mieux vaut se séparer. Ça nous permettra de couvrir plus de terrain. Je prends le chemin de gauche et on verra qui trouvera le trésor le premier!",
"Eh, attends...",
"Je crois qu'on peut aller à Khael Roa maintenant!",
"Ce ne sera peut-être pas aussi simple.",
"On devrait peut-être se mettre à la recherche du temple pendant qu'il lit ces gribouillis.",
"Pas sans une idée de l'endroit où aller! Le diable en personne pourrait se perdre dans ce labyrinthe!",
"Comme tu voudras, mais je vais me dégourdir les jambes. Oh! Je vois déjà quelque chose! N'oublie pas que je l'ai trouvé en premier!",
"Quoi?",
"Ça doit être l'alcôve dont ",
"Researcher",
" parlait. Mais où est le trésor?",
"Je ne sais pas. Même si on prenait tout l'or caché dans ces murs, ça ne ferait pas beaucoup...",
"On ne peut pas perdre trop de temps à chercher, ",
". Ils vont prendre la ville!",
"Je veux juste m'assurer que tu n'as pas l'intention de me couler, moi aussi, une fois qu'on se sera occupé de la flotte anglaise.",
"Là, tu me fais de la peine, ",
".",
"Je plaisante! Je plaisante, c'est tout. Bonne chance!",
"Nom de Nom! Qu'est-ce que c'était?",
"Je ne sais pas!",
"Par tous les diables, ",
"! Personne n'a pu survivre à ça! Mon trésor! Est-ce qu'on ne pourrait pas essayer d'en récupérer au moins une partie? Juste une toute petite partie?",
"Je ne sais pas. Je suppose que ce n'est pas le seul trésor au monde.",
"Qu'est-ce que ça change? Oh, quelle terrible perte!",
"J'ai l'impression curieuse que ta déception est en partie feinte.",
"Je ne dois pas retourner là-bas. Il faut que je quitte Redmond, et vite!",
"Ça a été dur, non? Tu es toujours en un seul morceau?",
"Oh, je ne crois pas que je mourrai aujourd'hui, en tout cas.",
"Voilà qui fait plaisir à entendre... même si je crois que la mort se fiche pas mal de ce que les gens croient.",
"Allons cueillir ",
"Researcher",
" à la prison.",
", une chose à la fois. Commençons par sauver le pauvre vieil homme.",
"Comme tu voudras.",
"Qu'allons-nous faire maintenant? On ne peut pas trouver le trésor si on ne réussit pas à traduire cette légende. Et j'ai bien peur que ce vieil homme...",
"On s'est déjà mis Silehard et la couronne anglaise à dos. Qu'est-ce qu'on a à perdre en prenant cette ville minable et en libérant Aurentius?",
"Je ne savais pas que tu avais des tendances suicidaires, mais si tu parles sérieusement, alors on va s'amuser un peu!",
"Bien dit! Et j'ai l'impression d'être un vrai pirate. Je vais attaquer le fort par la mer. Tes hommes et toi, vous pouvez assiéger la ville par l'intérieur. Qu'en dis-tu?",
"J'ai l'impression d'avoir créé un monstre, ",
". Mais je suis prêt!",
"Calme-toi! Qu'est-ce qui s'est passé?",
"Ce qui s'est passé? On m'a annoncé ta mort! J'ai navigué jusqu'à Greenford pour savoir ce qui s'était vraiment passé. Le tavernier m'a dit qu'il ne t'avait pas vu. Puis un type sorti de nulle part s'est approché de moi et m'a dit qu'il savait où te trouver. Et j'ai mordu à l'hameçon comme une imbécile!",
"Du calme. Tout va bien maintenant. Que s'est-il passé ensuite?",
"J'ai navigué ici jusqu'à Isla Muelle avec cette ordure de menteur. Il m'a dit qu'on allait rencontrer les pirates qui te retenaient. Il m'a conduite dans la jungle - et s'est enfui quand deux de ses copains m'ont sauté dessus. Le temps que je m'occupe d'eux et que je retourne au rivage, il était déjà parti. Et mon bateau aussi!",
"Tu as fait tout ça pour moi? La froide et arrogante Danielle s'est précipitée à mon secours sans arrière-pensée!",
"Continue de parler comme ça et tu finiras par marmonner avec un sabre planté dans le ventre!",
"J'arrête! Pas un mot de plus, je te le promets! Alors... nous avons complètement perdu les tablettes?",
"Tu me prends vraiment pour une arriérée, n'est-ce pas? Non, je les ai gardées.",
", ma chère, je ne t'ai jamais dit que tu étais la femme pirate la plus intelligente que je connaisse?",
"Non. Si je me souviens bien, tu as surtout été ravi par ma 'langue incroyablement acérée'. Maintenant dis-moi : par quel miracle es-tu arrivé jusqu'ici?",
"Après avoir capturé le navire envoyé pour livrer l'idole à Silehard, j'ai mis le cap sur notre point de rendez-vous. Mais j'ai essuyé une tempête et je suis passé par-dessus bord comme quelqu'un qui n'aurait jamais quitté la terre ferme. Je me croyais fini, mais le courant m'a entraîné sur le rivage près de Douwesen.",
"Oui. La bonne fortune favorise les imbéciles.",
"Doucement, maintenant! Ça n'a pas été facile. Quand j'ai repris connaissance, je me suis traîné jusqu'à Douwesen et j'ai réussi à trouver un petit bateau. Peu de temps après, je me suis retrouvé ici. Tu peux imaginer ma surprise quand j'ai vu mon vieux navire dans le port de Muelle. Il était encore en cours de réparation après la tempête.",
"Incroyable! La bonne fortune favorise les imbéciles, mais même toi, tu n'es pas assez idiot pour avoir AUTANT de chance!",
"Eh bien, dans ce cas... J'ai tout inventé. Oui! Juste une histoire à dormir debout, rien que pour te divertir. En tout cas, je suis là.",
"Moi aussi, je suis là. Et maintenant, nous avons l'idole. On devrait voyager ensemble jusqu'à Oxbay et demander à Aurentius de traduire cette légende.",
"Oh, je n'osais pas espérer que tu dirais ça! Voyager ensemble... C'est... de si doux à entendre!",
", trésor, ferme-la!",
"Oui, je travaille pour lui.",
"Sale monstre! Et tu m'as tendu une embuscade aux portes de la ville?!",
"Non...",
"Crève!",
"Toujours aussi difficile, hein? D'accord...",
"Tais-toi, ",
", tu veux bien?",
"Ça te fait rire? J'aimerais te voir rire avec une pile de petit bois à tes pieds!",
"Alors il parlait sérieusement? Je croyais que tu l'avais aidé à transporter de la nourriture ou quelque chose comme ça.",
"Mais sérieusement, qu'est-ce que tu fais ici?",
"Je cherche quelqu'un, mais plus j'approche du but, plus les choses se corsent pour moi.",
"Moi aussi, j'ai eu ma dose d'ennuis.\nEt tout ça à cause d'un type. Il est capitaine, lui aussi, justement. On l'appelle ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Tu parles sérieusement? On recherche le même homme! Mais pourquoi le recherches-tu?",
"Pour de l'or, évidemment! Un homme très haut placé veut régler son compte à ce démon et il m'a promis une belle somme si je lui amenais.",
"Je vois. On pourrait peut-être le chercher ensemble.",
"Avec joie, mais je te dis tout de suite que je ne sais pas où il est.",
"On en est au même point, alors... moi non plus.",
"Bon, on ne peut pas faire pire ensemble que chacun de notre côté. Et ça doit être le destin qu'on se soit rencontré comme ça.\nQuand veux-tu partir à la recherche de notre 'ami' mutuel?",
"Eh bien, j'ai des affaires à régler ici...",
"Pas de problème. D'ailleurs, j'ai moi aussi deux-trois choses à régler.",
"Parfait. Retrouvons-nous ici dans une semaine. Qu'en dis-tu?",
"Excellente idée. Alors, à la semaine prochaine.",
"Bonne chance!",
"Tu ne te souviens de rien?",
"Ne me brusque pas, ",
", j'ai l'impression que ma tête va exploser. Et si tu m'expliquais ce que tu fais ici?!",
"Eh, si quelqu'un ici a le droit d'être furieux, c'est bien moi! Prendre cette dague là où je l'ai prise n'a pas été la chose la plus agréable qui me soit arrivée!",
"C'est mérité! Je sais que tu es à ma recherche pour le compte du gouverneur anglais. Réglons ça tout de suite. Sors ta lame!",
"Calme-toi, ",
". Tu as tout faux. Je ne suis pas du tout à ta recherche. Je ne savais même pas que ",
"Robert Christopher Silehard",
" voulait ta mort.",
"Tu ne vas pas me faire croire ça, ",
"! Tu as toujours dit que tu ferais n'importe quoi pour de l'argent!",
"Oh, allez, ",
"! Je plaisantais! Tu voulais que je sois une ordure. Tu aimes les ordures! Je ne pouvais pas te décevoir.",
"Qu'est-ce que tu racontes?! Je t'ai toujours considéré comme un honnête homme!",
"Oh, non! Depuis qu'on se connaît, on a toujours été en conflit.",
"C'est vrai! Tu essayais toujours de rafler les meilleures missions sous mon nez!",
"Mais je ne crois pas t'avoir jamais fait de tort? J'ai plutôt l'impression que c'était toujours moi qui te sauvais la peau!",
"Peut-être. Il n'empêche que tu travailles pour un homme qui veut ma mort!",
"Oui, c'était le cas, ",
". J'ai récemment pris... ma retraite. Mais ",
"Robert Christopher Silehard",
" ne le sait pas encore.",
"Quoi? Il ne te payait pas assez?",
"L'argent n'est pas la question. Pas cette fois. J'ai tout simplement décidé que je ne voulais plus travailler pour un homme comme lui.",
"Qu'est-ce que tu racontes? Tu es un homme libre? Alors, fiche-moi la paix!",
"Très bien! Je vois que tu n'as pas perdu ton entêtement. Bonne chance avec les trois cadavres que tu as sur les bras.",
"?!",
"Qu'est-ce que tu veux encore?",
"...",
"Avais-tu autre chose à dire ou est-ce que je peux partir?",
"...Merci... pour ton aide, ",
". J'aurais perdu la vie sans toi.",
"Ce n'est rien. Je peux y aller?",
"Attends, ",
"! Qu'est-ce que tu vas faire, maintenant?",
"Je vais poser quelques questions à une certaine pourriture de gouverneur.",
"Attends une minute, tu veux? Tu ne peux pas y aller sans escorte. C'est du suicide! Si ",
"Robert Christopher Silehard",
" se doute de quoi que ce soit, il te tuera, ne serait-ce que par mesure de précaution!",
"Merci, mais je prends le risque!",
"Pas sans moi, pas question!",
"Pourquoi? Ça ira tout seul.",
"Premièrement, j'ai des questions à lui poser. Et deuxièmement - ",
"Quoi?",
"Je connais un bon endroit où jeter l'ancre à Redmond, un endroit où personne ne nous attend.",
"D'accord, très bien. Associons nos forces pour le moment.",
"Parfait! Mais si tu me trahis une fois de plus, ",
", je te tue, je le jure!",
"Qu'est-ce qui se passe? Ces soldats essayaient de nous tuer!",
"Je ne sais pas, ",
", mais tu devrais quitter la ville... C'est dangereux ici.",
"Alors... où a-t-il bien pu mettre ce papier? Voyons.",
"(commence à chercher)",
"Toute la ville est sens dessus dessous! Ils crient que le port est en feu. On ne peut pas aller par là.",
"J'ai une idée. On va dire qu'il y a des troupes françaises en ville. Crie-le à pleins poumons! Ça va embrouiller les gardes!",
"Je crois que c'est la silhouette de Nigel Blythe droit devant. Intéressant. Je me demande où il va.",
"...",
"Hum... Je me trompe peut-être, mais j'ai l'impression qu'un membre de mon équipage - Artois Voysey - vient d'arriver en ville.",
"...",
"L'officier Edgar Attwood vient de quitter mon navire sans mon autorisation.",
"...",
"Diable! Quelqu'un a tiré sur Artois! Il faut que je l'emmène à la taverne et que je lui trouve un médecin!",
"...",
"Snorri :... Ça fait deux semaines qu'on pourrit dans ce trou et toujours pas d'or! Tu nous as promis que le vieux paierait!",
"...",
"Billy : Il paiera, c'est certain. Mais rassembler autant d'or prend du temps.",
"...",
"Snorri : Et s'il se moquait complètement de son crétin de fils?! Et si en fait d'or, il nous envoyait un galion rempli d'Espagnols assoiffés de sang?!",
"...",
"Billy : Ça suffit! As-tu déjà vu un père abandonner son fils dans ce genre de situation? Ne t'en fais pas, l'amiral paiera la rançon. Il n'a pas le choix.",
"J'en ai assez entendu. C'est d'eux que j'ai besoin. (leur montre le signe)",

};