string DLG_TEXT[32] = {
"Capitaine... (tousse)... Tu dois m'aider... Il faut que j'aille à Redmond!",
"Redmond? Pourquoi?",
"J'ai un message pour Silehard, le gouverneur de Sa Majesté. Mais je n'ai pas réussi à quitter l'île à cause de la guerre...",
"Un message urgent, je suppose?",
"Urgent, bien sûr... (tousse)... dois aller à Redmond dès que possible. Je suis mourant... si je ne contacte pas le gouverneur très bientôt, j'ai peur qu'il ne reçoive jamais le message.",
"Mourant? Qu'est-ce que tu as?",
"C'est la fièvre des marais, Dieu me protège... je ne sais pas combien de temps je vais tenir. Tu peux me prendre à ton bord?",
"Ce n'est pas une très bonne idée de prendre la mer avec un homme dans ton état, mais... d'accord. Promets-moi de rester à distance et je t'emmène. Mon bateau est au port de Greenford. C'est le '",
"'.",
"Il faut faire voile immédiatement, capitaine ",
"! Mes forces... me quittent un peu plus chaque minute.",
"Je ne suis pas sûr de vouloir risquer la fièvre à bord de mon bateau, désolé. Tu pourrais me confier le message, tout simplement.",
"Garde ton souffle et tes forces. On y sera bientôt!",
"Non, non! C'est... confidentiel... on me l'a confié, à moi seul. Je dois le livrer en personne!",
"Très bien.",
"Je ne suis pas sûr que tu survivras au voyage. Tu devrais peut-être voir d'abord un médecin.",
"Non! Les médecins du coin ne vont rien faire à part me couvrir de sangsues sur mon lit de mort! Le message... doit être livré.",
"Je comprends. Je ne peux pas dire que ça me plaise, mais je comprends.",
"Capitaine...",
"Approche-toi. Écoute-moi. Je vais bientôt mourir... mais mon message doit être livré... à tout prix.",
"Alors donne-moi le message, vite. Je le transmettrai au gouverneur et à personne d'autre. Tu as ma parole!",
"Non... j'ai une lettre. Prends-la. Remets-la au gouverneur en mains propres. Le gouverneur, et personne d'autre! Tu comprends? Personne d'autre ne doit la lire!",
"Du calme, ",
".",
"Le trésor... le trésor y est caché...",
"Raoul Rheims",
", il en était tellement sûr!... Mais c'est impossible...",
"Il délire. Je crois qu'on est en train de le perdre.",
"... un orage... une tempête. On ne pouvait que rejoindre... l'île des pirates. Quebradas! Costillas. Et puis la guerre...",
"Mais qu'est-ce qu'il raconte?",
"Le message! Message... pour le gouverneur. Et ils attendent... sur Quebradas. Oui! Oh mon Dieu, tellement d'o...",
"De l'or? C'est d'or dont tu parles? Bien sûr. Allez, parle!",

};
