string DLG_TEXT[28] = {
"Je vais devoir te demander de quitter ma maison immédiatement. Je suis occupé.",
"...",
"Alors, le Gouverneur ",
"Robert Christopher Silehard",
" m'envoie son bras droit. Qu'est-ce qu'il me veut, mon garçon?",
"Qui a dit que je travaillais pour lui?",
"Qu'est-ce qui te fait croire que c'est le gouverneur qui m'envoie?",
"Excuse-moi, mais est-ce que j'ai l'air de l'idiot du village? Dès que j'ai appris que quelqu'un me cherchait, j'ai mené mon enquête\nTu oserais me regarder en face et me dire que tu ne travailles pas pour lui depuis des mois?",
"D'accord, disons que tu as raison, et que c'est le gouverneur qui m'envoie. Et après? Tu refuserais de parler à un émissaire du gouverneur?",
"Écoute, j'en ai assez de jouer au chat et à la souris. Tu me parles ou tu préfères choisir laquelle de tes deux jambes tu veux garder?",
"Capitaine, je me demande si tu sais à qui tu parles. Crois-moi : si je ne voulais pas te parler, tu ne serais pas devant moi.",
"Oh, pas besoin d'user de violence physique, petit. Je vais te parler, parce que je suis curieux : qu'est-ce que ce vieux renard de gouverneur peut bien me vouloir?",
"Très bien. Je veux savoir où je peux trouver un gentilhomme du nom de ",
"Raoul Rheims",
". Je sais qu'il se cache quelque part sur cette île.",
"Tes informations datent un peu, jeune homme. ",
"Raoul Rheims",
" a bien passé quelques jours ici. Il n'a pratiquement pas quitté sa maison, en fait.\nMais il a déjà repris la mer et n'a confié sa destination à personne, même pas à moi. Quelque chose l'inquiétait, de toute évidence, mais j'ignore quoi.",
"Il a une maison ici? Où ça?",
"Alors comme ça, il a une cabane sur cette île, hein? Où ça?",
"Une petite minute, gamin. Tu es peut-être l'envoyé du gouverneur de Sa Majesté, mais ça ne te donne pas le droit d'entrer chez quelqu'un et de fouiller ses affaires. Je me fais bien comprendre?",
"Je te supplie de faire une exception pour moi. Il faut que je sache où il est parti ",
"Raoul Rheims",
", et vite!",
"Oh, allez. Tu es un contrebandier, célèbre dans tout l'archipel pour ton manque flagrant de principes. Et c'est toi qui me donnes des leçons de morale?",
"Je vois que tu n'as pas l'intention d'entendre raison. Si je ne peux pas te convaincre de ne pas entrer dans cette maison, j'ordonnerai à mes hommes de la garder et de tirer à vue. Peut-être que les mousquets sauront être plus persuasifs. Et maintenant, sors d'ici!",
"Adieu.",
"Tu entendras parler de moi!",

};
