string DLG_TEXT[24] = {
"Que veux-tu? Je n'aime guère parler aux étrangers.",
"Je vois ça. Si tu veux que je te laisse tranquille, dis-moi où est parti Blythe?",
"Nigel?",
"Oui. Ne fais pas semblant de ne pas le connaître.",
"Je ne vois pas de quoi tu veux parler. Va au diable!",
"Ce type travaille pour moi...",
"Il travaille pour toi? Il n'a jamais dit qu'il travaillait pour quelqu'un.",
"D'accord, il travaillait pour moi. Jusqu'au jour où il a disparu avec l'un de mes navires.",
"Hé-hé. Quelle mauvaise surprise...",
"Ehé, je ne vois pas ce qu'il y a de drôle! Tu sais que le rire est parfois mauvais pour la santé?",
"D'accord, d'accord... J'en connais qui seraient prêt à payer cher pour ne pas ébruiter un secret aussi gênant. 'Il s'est fait piquer son navire sous son nez?' Eh ben... Un secret comme ça, ça vaut bien au moins cinq mille pièces d'or, non?",
"Et si je te mettais quelques grammes de plomb dans la cervelle?",
"Les menaces ne te mèneront nulle part. Tout le monde sait que tu es du genre gentil qui aide la veuve et l'orphelin. Hé-hé!",
"D'accord, d'accord, j'accepte.",
"Tout a une fin, tu ne sais pas ça?",
"Parfait. Maintenant, parle.",
"C'est juste, mais...",
"Il n'y a pas de 'mais', ordure! Ma patience est épuisée!",
"D'accord, d'accord. Je vais parler. Alors, tu as dit - Nigel. Il est parti chercher ses anciens membres d'équipage à Quebradas Costillas.",
"Dans quel but?",
"Il a dit que son navire était coincé sur un banc de sable quelque part, mais je ne lui en ai pas demandé plus.",
"J'ai compris. Adieu.",
"Je ne suis pas d'humeur à parler avec un mollusque.",
"Qui est-ce que tu tu traites de mollusque?",

};