string DLG_TEXT[90] = {
"Bienvenue, ",
". Tu es ici chez toi, mon ami. Considère-toi comme un membre de la famille!",
"Euh... ouais. Merci. Je suis ",
".",
"Eh, ",
"! ",
".",
"Ça alors! C'est la marée qui t'a amené ici? Je suis heureux de te voir, ",
".",
"C'est une joie de t'avoir parmi nous, ",
". Que puis-je faire pour toi, aujourd'hui?",
"J'ai besoin d'hommes robustes pour m'aider sur mon navire. Je les préfèrerais intelligents, mais s'ils sont discrets, ce sera déjà bien.",
"J'espère que tu as une minute pour que nous puissions parler.",
"J'ai besoin d'une chambre. Propre.",
"Aurais-tu un tas de foin libre dans cette grange?",
"Désolé. Je m'apprêtais à sortir, ",
". Je te verrai plus tard.",
"Oh, tu vas pouvoir t'en assurer toi-même, ",
". Je m'appelle ",
". Je suis le tenancier de cette humble taverne.",
"J'ai besoin d'engager un équipage, ",
".",
", discutons...",
"Est-ce que tu aurais une chambre pour moi? ",
"J'aimerais séjourner quelque temps ici.",
"Je passerai peut-être te voir tout à l'heure.",
"Certainement. De quoi souhaites-tu parler, capitaine ",
"?",
"Un homme ouvert comme toi doit entendre des rumeurs intéressantes. Je voudrais savoir ce qui se raconte en ce moment.",
"Quelque chose me travaille...",
"Oui?",
", un homme appelé ",
"Ewan Glover",
"Ewan Glover",
" a dit qu'il m'attendrait ici.",
"Je cherche du travail. Connais-tu des capitaines qui auraient peur de voyager seuls?",
"Bonjour. Que puis-je faire pour toi?",
"Je cherche un jeune Espagnol du nom de Lucas Da Saldanha. Tu l'as peut-être vu.",
"Tu sais, ",
", on parlera une autre fois.",
"Si c'est celui auquel je pense, il préfère naviguer avec moins de satellites, tu le sais",
"Oui, j'avais oublié. D'accord, je reviendrai plus tard quand j'aurai moins de navires, ha-ha.",
"Je ne veux pas t'aider, mon vieux. Tu as causé trop de tort à mon pays",
"Regarde-moi un peu ce patriote. Allez, au revoir",
"Tes mains sont couvertes de sang. Tu ne crois pas sérieusement que quelqu'un acceptera de voyager avec toi",
"Tu as raison, tout le monde a peur de moi! Ha-ha!",
"Tu tombes à pic. Un marchand est passé ici ; il cherchait à voyager en bonne compagnie. Va donc le voir. Le voilà qui entre dans la taverne.",
"D'accord.",
"Non, je ne vois personne pour le moment. La prochaine fois, peut-être.",
"Mmh, alors j'attendrai.",
"Intéressant. Au fait, je recherche des hommes forts pour mon équipage.",
"J'aimerais te parler, si tu as un moment.",
"Désolé, je sortais justement, ",
". Je te verrai une autre fois.",
"Quand tu veux.",
"J'ai besoin d'hommes forts pour mon équipage.",
"As-tu un moment pour parler?",
"Désolé, je sortais justement, ",
". À bientôt.",
"Oui, D'ailleurs, il est passé ici. ",
"Ewan Glover",
" est sorti tout à l'heure avec une femme, je crois. Si tu peux attendre, ",
", je suis sûr qu'il ne tardera pas à revenir.",
"Merci. Je vais attendre ici.",
"Oh, cet endroit est généralement plein d'hommes qui ne demandent qu'à partir sur un bon navire. Mais il est tard. Ils commenceront à arriver dans la matinée \nTu veux peut-être louer une chambre et attendre?",
"D'accord. As-tu une chambre libre?",
"C'est peut-être bien ce que je vais faire, mais j'ai d'abord d'autres questions à te poser.",
"J'ai effectivement une chambre ou deux. Combien de temps penses-tu rester?",
"Jusqu'au matin.",
"Jusqu'à ce soir.",
"Bien, bien. Ce sera 5 piastres.",
"Bien, les voilà.",
"C'est trop cher pour moi. Je crois que je vais devoir passer la nuit dans la salle commune avec les autres indigents et les grippe-sous.",
"Ça me donne droit à quoi? Une danseuse rien que pour moi? Peu importe. Ce ne sera pas la première fois que je passerai la nuit dans une salle de taverne.",
"Je vais y réfléchir.",
"Cela te coûtera 5 pièces d'or.",
"D'accord, voici ton argent",
"C'est trop pour une nuit. S'il le faut, je poserai la tête sur l'une des tables de la taverne pour me reposer.",
"Ça me donne droit à quoi? Une danseuse rien que pour moi? Peu importe. Ce ne sera pas la première fois que je passerai la nuit dans une salle de taverne.",
"Je vais y réfléchir. Parlons d'autre chose.",
"Messieurs, s'il vous plaît! Arrêtez tout de suite ou j'appelle la garde!",
"D'accord. Ça va. Je m'en vais.",
"Oui, je me souviens de lui. Un type sympathique et un bon client - Il dépensait toujours sans compter.",
"Sais-tu où je peux le trouver?",
"Je ne sais pas où il est parti, mais je peux te dire ce qui l'a poussé à partir...",
"Vas-y. Il faut absolument que je le sache!",
"Eh bien, selon la rumeur, le jeune Espagnol a essayé de passer un moment avec la fille du gouverneur Silehard. Je ne sais pas ce qui s'est passé, mais il est revenu ici d'une humeur noire. Le lendemain matin, son voilier et lui étaient partis et plus personne ne l'a revu depuis.",
"La fille du gouverneur? Il a du goût, on dirait? On peut espérer lui parler ou Silehard la surveille-t-il de près?",
"Oh, une chose est sûre, lui ne la surveille pas. Il paie du monde pour ça. Enfin, on peut le comprendre, n'est-ce pas? Elle est très jolie. Elle se promène hors de la ville de temps en temps, mais elle est toujours accompagnée de plusieurs gardes.",
"Ces gardes ne devraient pas poser de problème. Je n'ai pas l'intention de l'enlever, je veux juste lui poser quelques questions. Merci, Charles, tu m'as bien aidé.",

};