string DLG_TEXT[76] = {
"...",
"...",
"Salut, mon vieux! Tu ne serais pas capitaine, par hasard?",
"Si, je le suis. Pourquoi cette question?",
"Je suis surtout un homme occupé.",
"Compris. Je reviendrai plus tard.",
"C'est peut-être un jour de chance pour nous deux. Je m'apprête à me lancer dans une aventure risquée et quelque chose me dit que tu ferais un excellent partenaire.",
"Risquée à quel point?",
"Disons que les bénéfices potentiels sont à la hauteur du danger. Que dirais-tu de mettre la main sur une véritable montagne d'or?",
"C'est une question piège? Continue.",
"Question risques, je suis au maximum de ce que je peux supporter et je n'en recherche pas d'autres. Désolé.",
"Ha! Je savais que tu étais l'homme de la situation. Écoute : tout ce que l'on a à faire, c'est accoster dans un lieu sûr et prendre l'or. Un plan brillant!",
"J'ai comme l'impression que tu as oublié deux détails essentiels. Premièrement : accoster où? Deuxièmement : prendre l'or à qui?",
"Ces détails sont tous réglés, je t'assure. Mais je ne peux pas te révéler le reste de mon plan avant d'être certain que nous sommes partenaires. Une fois en route, je te dirai tout!",
"Je n'ai rien à perdre, je suppose. Quand peux-tu partir?",
"Désolé. Je n'ai pas de temps à perdre à courir après des fantômes.",
"Le plus tôt sera le mieux! Mon navire m'attend déjà au port. Rejoins-moi et nous partirons pour Oxbay.",
"Bien. J'ai règle mes affaires ici et je te rejoins. Au fait, quelles sont tes conditions?",
"Les conditions habituelles : partage du butin à parts égales entre nos équipages.",
"C'est équitable. D'accord, je te retrouve au port.",
"On a déjà fait la moitié du travail, mon ami! Il ne reste plus qu'à s'emparer des mines et l'or sera à nous.",
"De l'or anglais? Tu ne m'avais pas dit que c'était de l'or anglais.",
"Et alors?",
"Laisse tomber.",
"Non, non. Je comprends. Moi non plus, je ne veux pas d'ennuis avec les Anglais. Mais si on suit mon plan à la lettre, personne ne saura qu'on est passé par là.",
"Attends. Tu es en train de me dire qu'il faudra tous les tuer? C'est ça, ton plan brillant?",
"Exactement!",
"J'aurais dû m'en douter. Écoute, calme-toi et on n'aura peut-être pas à verser le sang.",
"Sacrée agitation, mon ami!",
"C'est vrai, mais je ne vois pas d'or.",
"Tu as raison. Bon sang! Ils l'ont déjà embarqué. Dépêche-toi - les traces de chariot sont encore fraîches. On peut encore les rattraper. Je suis sûr qu'ils emportent l'or à Oxbay, comme d'habitude.",
"Je suppose qu'on est allé trop loin pour faire demi-tour. Il faut les rattraper!",
"Non! J'en ai assez de ces idioties! Je regrette de m'être embarqué dans cette histoire de fous.",
"Si on réussit à rattraper ce convoi, je ferai personnellement don d'une croix géante en or à l'église!",
"Arrête de jacasser! Ils ne vont pas nous attendre.",
"Non! On est partenaires. Tu vas m'aider à nous sortir de là ou je t'écrase!",
"Essaie. On verra s'il te reste de quoi te battre!",
"D'accord, d'accord. Je n'ai plus assez de courage pour me battre.",
"Les voilà! Il ne faut pas les laisser filer!",
"En avant!",
"Bon sang! On les a perdus! Maintenant, il ne nous reste plus qu'à repartir les mains vides.",
"Et vite, avant qu'ils ne décident de faire demi-tour et de nous courir après!",
"On a réussi!",
"Oui, mais maintenant, il faut sortir d'ici... et on ne réussira jamais à se frayer un chemin jusqu'aux navires.",
"Tu ne crois pas si bien dire. Il nous faut un plan. On ne peut pas laisser cet or nous filer entre les doigts.",
"Écoute ça : et si on envoyait quelques-uns de tes hommes sur les navires? Ils pourraient guider les autres jusqu'à une baie proche.",
"Bien, bien. C'est ce qu'on va faire. Maintenant, filons d'ici, et vite!",
"...",
"On est au bon endroit, mais je ne vois pas nos navires. Il va falloir attendre.",
"Chut. J'entends des voix. On a de la compagnie!",
"Oh! Tu parles d'une journée! Dieu merci, nos navires sont enfin entrés dans la baie. On peut se partager le butin et filer.",
"D'accord. La moitié pour toi et l'autre moitié pour moi, comme convenu.",
"Pas d'accord. Cette entreprise est bien plus risquée que je ne le croyais. Je vais avoir besoin d'une plus grosse part des bénéfices.",
"Ah non! Tu as failli me faire tuer avec ton plan brillant. Je prends tout l'or.",
"Parfait! Tu sais tenir parole. L'or que nous avons pris vaut ",
" en pièces. Alors ta part s'élève à ",
".",
"Pas mal pour une journée de travail.",
"Pas mal du tout. Et si on continuait notre partenariat et faisions voile ensemble?",
"Ça m'intéresse.",
"Je ne crois pas que ce soit une bonne idée.",
"Je suis heureux de l'entendre.",
"Alors, bienvenue parmi les membres de l'équipage, ",
". Maintenant, retournons à nos navires.",
"Je vais retourner à Isla Muelle. Tu me trouveras là-bas si tu as besoin de moi.",
"Très bien.",
"Tu réfléchis toujours à mon offre?",
"Oui, je ne l'ai pas oubliée.",
"Non, j'ai déjà pris ma décision. Bienvenue parmi les membres de mon équipage.",
"Parfait! Rien ne peut nous arrêter!",
"Oui, oui. Mais pour l'instant, on a plein d'affaires à régler.",
"Quoi?! Tu vas te contenter de la moitié ou je t'étripe sur place!",
"Du calme. Je... plaisantais. La moitié me suffira.",
"Ce n'est pas une question, c'est une affirmation. Je veux une part plus importante!",
"Il va falloir me tuer pour ça!",
"Je n'aurais pas mieux dit! En garde!",

};