string DLG_TEXT[114] = {
"Ah! Un nouveau visiteur dans ma taverne! Bienvenue, ",
"! La meilleure hospitalité de l'archipel est à ta disposition!",
"Bonjour. Je m'appelle ",
".",
"Merci. Mon nom est ",
".",
"Tu es le bienvenu. Je t'en prie, assieds-toi, bois un peu de rhum, goûte quelques-unes de mes spécialités! Tu m'en diras des nouvelles!",
"Content de te revoir, ",
". Installe-toi à l'une des tables libres et repose ta carcasse.",
"Oh, c'est toi! Ça faisait une éternité que je ne t'avais pas vu. Que dirais-tu d'un verre de vin pour humecter ton gosier asséché?",
"Si ça ne t'ennuie pas, je voudrais passer directement aux choses sérieuses.",
"J'ai peu de temps, l'ami, et j'ai des affaires graves à traiter.",
"Je suis désolé. Je suis trop pressé pour l'hospitalité.",
"Calme-toi. Je suis juste passé voir qui était ici ; je repars tout de suite.",
"Heureux de faire ta connaissance, ",
". Je m'appelle ",
".",
"Bien sûr, ",
", c'est toi le patron. Qu'est-ce que je peux faire pour toi?",
"Je cherche à étoffer mon équipage. Pourrais-tu m'indiquer des hommes qui cherchent du travail?",
"Les récents combats m'ont laissé à court de main-d'oeuvre. Il me faut trouver des hommes qui cherchent du travail.",
"Je veux parler affaires.",
"As-tu une chambre libre? J'aimerais séjourner quelque temps ici.",
"Je cherche une chambre propre avec un lit propre. Rien de plus, rien de moins.",
"Je n'ai pas le temps de parler pour le moment. Je repasserai plus tard.",
"Désolé, je suis pressé, mais je repasserai discuter plus tard, quand j'aurai du temps.",
"De quel genre?",
"Je recherche un homme que tu connais peut-être. Je ne connais pas son nom, mais je sais qu'il étudie les langues indigènes.",
"Je recherche un homme que tu connais peut-être. Je ne connais pas son nom, mais je sais qu'il étudie les langues indigènes.",
"Je recherche un homme du nom de ",
"Raoul Rheims",
"Raoul Rheims",
". Sais-tu s'il est passé sur l'île?",
"Est-ce que ",
"Ferro Cerezo",
" est venu ici récemment?",
"Je dois trouver ",
"Ferro Cerezo",
". Est-ce que tu l'as vu?",
"Qu'est-ce qu'on raconte à propos de l'enlèvement du prêtre de la paroisse?",
"Je voudrais savoir si un homme est venu ici. Il s'appelle Nigel Blythe et a une belle tête de truand.",
"Je cherche du travail. Tu ne connaîtrais pas,sur cette île, quelqu'un de riche qui aurait peur de voyager seul?",
"Tu sais, maintenant que j'y pense, je n'ai pas d'affaires à traiter.",
"Ha ha! Pour que tu parles ainsi de lui, il a dû te causer pas mal d'ennuis.",
"C'est vrai, mais tu n'as pas répondu à ma question. Il est passé ici, oui ou non?",
"Oui, quelques heures seulement avant ton arrivée. Il parlait avec un homme.\nSi je me souviens bien, ils se sont querellés puis ont eu l'air de tomber d'accord.",
"Tu n'as rien entendu d'autre? Où est-il parti?",
"Je ne sais pas. Mais le type à qui il parlait est du coin. Je l'ai déjà vu.",
"Où? Où habite-t-il?!",
"Du calme! Il vit dans une maison derrière ma taverne. En quittant la taverne, tu verras des portes qui donnent sur une petite cour. Et l'homme est un gros type vêtu de cuir.",
"C'est l'homme qu'il me faut! Merci.",
"Toute la colonie en parle! Imagine ça : faire irruption dans une église en plein jour et enlever le padre! Et ils ont disparu avant que qui que ce soit ait pu intervenir.",
"Qui c'était? Des hommes en robe noire?",
"Non. D'après ce que j'ai entendu dire, ils ressemblaient à n'importe quel brigand. Mais c'est drôle que tu me parles de robes noires...",
"Drôle? Pourquoi?",
"Il n'y a pas si longtemps, un homme en robe noire s'est présenté ici.",
"Vraiment? Que voulait-il?",
"Pourquoi y attaches-tu tant d'importance? Je ne suis pas sûr de pouvoir parler de ses affaires avec d'autres clients.",
"Je crois qu'il est impliqué dans l'enlèvement du prêtre. Tu veux aider à régler cette affaire, n'est-ce pas?",
"Oui, je suppose. D'accord : il y a trois semaines, cet homme est apparu, vêtu d'une robe noire. Très courtois, surtout pour notre époque. Pas un mot désobligeant à quiconque.",
"Continue.",
"Eh bien, les gens du coin ne savaient pas trop quoi penser de lui. Il ne faisait rien de mal, il passait juste beaucoup de temps avec les jeunes du coin... Rien à redire à ça. Pour une fois qu'ils se tenaient tranquilles...",
"Et puis?",
"Et puis... il s'est passé quelque chose. Tous les jeunes étaient prêts à partir en campagne avec lui. Le fils du forgeron avait déjà quitté son foyer. Le forgeron est allé parler à notre homme mystérieux, mais il n'a pas tardé à sortir de la maison en trombe, comme s'il avait vu des diables par milliers\nLe soir même, le forgeron s'est tellement saoulé qu'il s'est noyé. Qu'est-ce qui lui a pris de marcher le long de l'embarcadère la nuit, alors qu'il tenait à peine debout?! Et tu sais quoi? Ça n'a fait ni chaud ni froid à son fils.",
"C'est étrange, en effet. Où puis-je trouver ce type?",
"Le fils du forgeron? Il doit traîner quelque part en ville. Il a l'air complètement perdu depuis que l'homme en robe a disparu.",
"Je le trouverai. Comment s'appelle-t-il?",
"Jordano",
" est son nom.",
"Merci.",
"Bien sûr, ",
". En fait, il est assis à la table, là.",
"Merci.",
"Bien sûr, ",
". Il était ici, mais il est parti pour Conceicao, il n'y a pas longtemps.",
"Merci.",
"Raoul Rheims",
"? Ce nom me dit quelque chose, mais cela fait un moment que je ne l'ai pas entendu. Désolé de ne pas pouvoir t'aider davantage.",
"Ne t'en fais pas pour ça. Je vais continuer de chercher. Laisse-moi te poser une autre question.",
"Hélas, je ne peux pas t'aider.",
"Désolé d'entendre ça. Tu as peut-être vu une femme appelée ",
"Danielle",
"Danielle",
"?",
"Oui, je l'ai vue. Elle est passée il y a quelques minutes. Elle avait l'air troublée, mais je ne lui ai pas demandé pourquoi.",
"Bien. Je pourrai peut-être la rattraper.",
"Il est un peut tard pour ça. Tu auras plus de chance si tu reviens dans la matinée. À moins que tu ne préfères passer une nuit à la taverne.",
"Peut-être. As-tu une chambre libre?",
"Peut-être. Mais laisse-moi d'abord te poser une question.",
"J'ai effectivement une chambre libre. Combien de temps comptes-tu rester?",
"Jusqu'au matin.",
"Juste jusqu'à la tombée de la nuit.",
"Parfait. Ce sera 5 pièces d'or.",
"D'accord. Voilà.",
"Dans ce cas, j'ai peur que ma bourse et moi ne passions la nuit dans la salle commune.",
"Non merci. Si c'est ton prix, j'économiserai quelques pièces en passant la nuit dans la salle commune.",
"Peut-être plus tard. Laisse-moi te poser une question.",
"Parfait. Il t'en coûtera 5 pièces d'or.",
"D'accord. Les Voilà.",
"Dans ce cas, j'ai peur que ma bourse et moi ne passions la nuit dans la salle commune.",
"Non merci. Si c'est ton prix, j'économiserai quelques pièces en passant la nuit dans la salle commune.",
"Je vais y réfléchir. Merci.",
"Je t'en prie! Arrête tout de suite! Ne me force pas à appeler les gardes!",
"D'accord! Je m'en vais.",
"Si cette personne existe, elle préfère sans doute éviter d'attirer l'attention avec tant de compagnie - comme tu dois le savoir.", 
"Oui, j'avais oublié. D'accord, je reviendrai plus tard, quand j'aurai moins de navires, ha-ha.",
"Je ne veux pas t'aider, pas après tout le mal que tu as fait à mon pays.",
"Regarde-moi un peu ce patriote! Allez, au revoir.", 
"Tes mains sont couvertes de sang. Crois-tu sérieusement que quelqu'un acceptera de voyager avec toi?",
"Tu as raison. Tout le monde a peur de moi. C'est amusant.",
"Tu tombes à pic. Un marchand cherche de la compagnie pour voyager. Tu devrais lui parler. Le voilà qui entre dans la taverne.",
"D'accord.",
"Non, je ne vois personne pour le moment. La prochaine fois peut-être.",
"Mmh. Alors j'attendrai.",

};