string DLG_TEXT[29] = {
"J'ai l'impression qu'il se passe quelque chose d'illégal, ici...",
"Pas du tout, mes amis et moi faisons juste un petit pique-nique en bord de mer.",
"Je donne juste de l'or à ces hommes. Ce n'est pas illégal, si?",
"Ça ne te regarde pas, soldat. Va-t-en!.",
"Tu me déçois, capitaine ",
". Qui aurait pu croire qu'un homme aussi respecté que toi donnait dans la contrebande?",
"C'est vrai, tu as raison. Je n'aurais pas dû, je le réalise, maintenant.",
"Tu seras plus que déçu quand je t'aurai coupé en deux!",
"Compte tenu de tout les échos flatteurs que j'ai entendus à ton sujet, je veux bien fermer les yeux sur cette première infraction, mais veille à ne pas recommencer. Quant à ces gredins, ils vont me suivre en prison.",
"Merci de ton indulgence. Tu ne le regretteras pas.",
"Inutile d'essayer de me berner, je ne suis pas aveugle! Vous êtes tous en état d'arrestation et vos biens sont confisqués!",
"Il faudra me passer sur le corps!",
"Pas du tout, si tu as de quoi partager. Combien comptais-tu me proposer?",
"Je pense que ",
" pièces d'or constitue une offre assez généreuse.",
"Que dirais-tu de ",
" pièces d'or?",
"Pour toi? Disons... ",
" pièces d'or, ça te va?",
"Essaierais-tu de me corrompre? L'honneur ne s'achète pas, comme tu vas vite t'en apercevoir. Suis-moi!",
"Je regrette de te décevoir, mais tu n'iras nulle part.",
"Essaierais-tu de me corrompre? L'honneur ne s'achète pas, comme tu vas vite t'en apercevoir. Suis-moi!",
"Je regrette de te décevoir, mais tu n'iras nulle part.",
"Mais... mais je dois t'arrêter!",
"Encore là? Tu en as donc assez de la vie?",
"Je... je ferai un rapport! Tu ne t'en tireras pas comme ça!",
"Hmph!",
"C'en est trop! Tu ne quitteras pas cette plage en vie!",
"C'est ce qu'on va voir!",

};
