string DLG_TEXT[28] = {       
"Tu ne vois pas que je suis de garde? Laisse-moi tranquille!",
"D'accord, d'accord!",
"Tu viens signaler une infraction?",
"Bien sûr que non. Je suis capitaine, après tout... mais je vois bien que tu n'écoutes pas.",
"N'oublie pas qu'il est interdit de se battre dans les rues. Mais tu peux bien sûr te défendre si on t'attaque.",
"Très bien, je vais y réfléchir.",
"Ce temps est vraiment insupportable! Quand je pense que je dois rester planté là! Tu ne me croiras sans doute pas, mais mon seul passe-temps est de chasser les mouches qui cherchent à se poser sur mon nez.",
"C'est regrettable, mais je ne peux rien pour toi. Tu fais ton devoir.",
"Si tu veux discuter, trouve-toi quelqu'un d'autre. Je suis en service, et il ne consiste pas à te parler.",
"Je me demandais juste si tu étais vivant. Tu es aussi immobile qu'une statue.",
"Tu crois que protéger cette ville est une tâche facile? Pas du tout! C'est un travail très important et extrêmement dangereux. Un jour, je me souviens...",
"Tu m'en parleras une autre fois. Il faut que j'y aille.",
"Passe ton chemin et cesse de m'importuner.",
"Comme tu veux, soldat.",
"Eh! Tu veux bien aller me chercher une coupe de rhum à la taverne?",
"Peut-être... mais est-ce que je ne risque pas de finir pendu si j'aide un soldat à se saouler alors qu'il est en service? Attends la relève et tu pourras boire tout ton saoul.",
"Pourquoi faut-il que ce soit un marin aussi moche que toi qui veuille me parler? Il n'y a pas de jolies filles, ici?",
"C'est ça que tu appelles faire ton devoir? Tu ne voudrais quand même pas rater l'occasion d'arrêter un dangereux criminel tel que moi, si? Ha, ha, ha!",
"Tu m'as l'air en bonne santé. Tu ne veux pas t'engager? Il y a de la place à la caserne, la pitance est bonne, et le rhum est gratuit.",
"C'est tentant, mais je dois refuser. La discipline et moi, ça fait deux.",
"Quelle chaleur! Je donnerais tout pour retourner au Portugal.",
"On dirait que le climat ne te convient pas, en effet.",
"Qu'est-ce que tu veux?",
"Espèce de... hic... gredin! Tu as fait du mal à mon... hic... ami!",
"Quel ami? Tu es tout seul, ",
".",
"Hein? Mais... il était là, tout à l'heure. Je vais le chercher. Toi... hic... attends ici, et je te mettrai une sacrée rouste à mon... hic... retour....",
"Comment oses-tu me contredire? Je vais t'étrangler!",

};