string DLG_TEXT[174] = {
", ",
". Mon nom est ",
". Puis-je savoir le tien?",
"Bonjour, ",
". Je m'appelle ",
". A qui ai-je l'honneur?",
"Je me nomme ",
". Que puis-je pour toi, ",
"?",
"Je suis ",
", propriétaire et capitaine du '",
"'.",
"On m'appelle ",
".",
"Tu peux m'appeler capitaine ",
".",
"Bonjour. As-tu entendu parler d'un officier nommé ",
"Artois Voysey",
"Artois Voysey",
"? Il s'est enfui de mon bateau il y a peu et doit maintenant être quelque part dans cette ville.",
"Bonjour. As-tu entendu parler d'un officier nommé ",
"Nigel Blythe",
"Nigel Blythe",
"? Il s'est enfui de mon bateau il y a peu et doit maintenant être quelque part dans cette ville.",
"Je regrette, mais pourrions-nous parler plus tard, quand j'aurai fini mon service?",
"D'accord.",
"Re-bonjour, capitaine ",
".",
"Ah, c'est toi, ",
". Qu'est-ce qui t'amène?",
"Ah ça, mais qui voilà! Bienvenue, ",
"!",
"Peux-tu me dire de quoi on parle, en ville, ces derniers temps?",
"Quelles sont les rumeurs qui courent à la taverne, cette semaine?",
"J'étais en mer, alors toutes les nouvelles sont fraîches pour moi. Qu'est-ce qui se raconte?",
"Je cherche quelqu'un. Tu peux peut-être m'aider à le trouver...",
"Tu connais bien la ville?",
"Pourrais-tu m'indiquer mon chemin?",
"Si tu as quelques instants, j'aimerais bien te demander ton avis à propos de quelqu'un...",
"J'aurais une question au sujet de quelqu'un que tu connais peut-être.",
"Tu pourrais me parler des gens du coin?",
"Parle-moi de la colonie.",
"Que sais-tu sur Conceicao?",
"J'aurais besoin d'informations sur Conceicao...",
"Bonjour. As-tu entendu parler d'un officier nommé ",
"Artois Voysey",
"Artois Voysey",
"? Il s'est enfui de mon bateau il y a peu et doit maintenant être quelque part dans cette ville.",
"Bonjour. As-tu entendu parler d'un officier nommé ",
"Nigel Blythe",
"Nigel Blythe",
"? Il s'est enfui de mon bateau il y a peu et doit maintenant être quelque part dans cette ville.",
"Je regrette, mais je dois filer. À la prochaine.",
"Si tu veux retrouver ton officier, tu devrais aller te renseigner à la taverne. Ses clients en sauront d'avantage que moi sur ce qui se passe ici.",
"Merci.",
"Eh bien, maintenant que nous nous connaissons un peu mieux, qu'est-ce que tu attends de moi?",
"C'est un plaisir de faire ta connaissance. Tu as besoin de quelque chose, ",
"?",
"Splendide, capitaine! Mais tu n'interpelles pas les gens juste pour te présenter, si?",
"Je me demandais quelles étaient les dernières rumeurs circulant à Conceicao...",
"Est-ce qu'il s'est passé quelque chose de spécial, ces derniers temps?",
"Je cherche à me tenir au courant des dernières rumeurs.",
"Pourrais-tu m'indiquer mon chemin?",
"Je cherche un lieu bien précis, mais je ne sais pas comment m'y rendre.",
"J'aurais besoin d'aide; je ne connais pas bien la ville.",
"J'aimerais que tu me donnes ton avis sur quelqu'un, si ça ne te dérange pas.",
"J'aurais une question au sujet de quelqu'un que tu connais peut-être.",
"Pourrais-tu me parler des gens du coin?",
"Parle-moi de la colonie.",
"Que sais-tu sur Conceicao?",
"J'aurais besoin d'informations sur Conceicao...",
"Merci, je profite simplement de la ville.",
"Je vois. Il y aurait encore une petite chose...",
"Merci du renseignement. Au revoir.",
"Que veux-tu savoir d'autre, ",
"?",
"Oui, oui, ",
". De quoi s'agit-il?",
"Dans ce cas, demande-moi, ",
".",
"J'aimerais savoir ce qui se raconte, par ici, ces derniers temps...",
"Est-ce qu'il s'est passé quelque chose de spécial, ces temps-ci?",
"Je cherche à me tenir au courant des dernières rumeurs.",
"Pourrais-tu m'indiquer mon chemin?",
"Je cherche un lieu bien précis, mais j'ignore comment m'y rendre.",
"J'aurais besoin d'aide ; je ne connais pas bien la ville.",
"J'aimerais que tu me donnes ton avis sur quelqu'un, si ça ne te dérange pas.",
"J'aurais une question au sujet de quelqu'un que tu connais peut-être.",
"Pourrais-tu me parler des gens du coin?",
"Parle-moi de la colonie.",
"Que sais-tu sur Conceicao?",
"J'aurais besoin d'informations sur Conceicao...",
"Je crois que je sais tout ce que je voulais savoir, maintenant. A plus tard.",
"Quelle est cette personne, ",
"?",
"Avec plaisir, ",
". Dis-moi juste de qui tu veux parler.",
"Qui a attiré ton attention, ",
"?",
"Je veux parler du gouverneur.",
"Le propriétaire de la taverne, ",
"Duarte Correja",
"Duarte Correja",
".",
"Le propriétaire du chantier naval, ",
"Humberto de Paiva",
".",
"Je m'intéresse à ",
"Martinho Guterres",
"Martinho Guterres",
", le marchand.",
"Personne. N'en parlons plus.",
"Le gouverneur est un parfait gentleman. Nous n'avons pas connu de problème sérieux depuis qu'il est là. La seule chose que je pourrais lui reprocher, c'est d'être un peu trop... euh... près de ses sous. Mais peut-être est-ce mieux ainsi...",
"Je vois. J'aurais une question à te poser...",
"Merci. Au revoir.",
"Je serais toi, je ne confierais pas mon argent à ce type. On dit qu'il est en cheville avec les pirates et les contrebandiers.",
"Je vois. J'aurais une question à te poser...",
"Merci. Au revoir.",
"Il fabrique de bons bateaux, mais je ne le connais pas vraiment. Il vit assez humblement. Je crois que c'est quelqu'un de bien. ",
"Je vois. J'aurais une question à te poser...",
"Merci. Au revoir.",
"C'est le fournisseur principal du gouverneur, et il en joue. Mais je dois dire que c'est un honnête homme. Du moins, personne n'affirme le contraire.",
"Je vois. J'aurais une question à te poser...",
"Merci. Au revoir.",
"Je connais bien la ville.",
"Avec plaisir, ",
". Où veux-tu te rendre?",
"La ville est si grande qu'on peut s'y perdre, ",
". Mais si je peux t'aider, ce sera avec plaisir.",
"Peux-tu m'indiquer où se trouve la taverne?",
"Où se trouve le chantier naval?",
"Où puis-je vendre les marchandises que j'apporte?",
"",
"Duarte Correja",
"Duarte Correja",
"? Tu trouveras sa taverne à l'intérieur de la ville, près des portes du port. Une maison sur la gauche.",
"Je vois. Merci et au revoir.",
"Et où est le chantier naval?",
"Où puis-je vendre les marchandises que j'apporte?",
"Le bureau du chantier naval donne sur la place. Il est situé juste en face de la résidence du gouverneur. Cherche son enseigne... 'Estaleiro Naval'... ça veut dire chantier naval en portugais.",
"Peux-tu m'indiquer où se trouve la taverne?",
"Où puis-je vendre les marchandises que j'apporte?",
"Merci du renseignement. C'est tout ce que je voulais savoir.",
"Tu trouveras ce que tu cherches à droite de portes du port, juste en face de la taverne, ",
".",
"Et où est le chantier naval?",
"Peux-tu m'indiquer où se trouve la taverne?",
"Je vois. C'est tout ce que je voulais savoir.",
"Je ne sais pas quoi te dire.",
"De quoi veux-tu parler?",
"Je t'en prie.",
"Que sais-tu de l'histoire de la colonie?",
"Qu'y a-t-il d'intéressant sur cette île, à part la ville?",
"Que sais-tu au sujet du fort qui protège la ville?",
"Changeons de sujet...",
"Ça t'intéresse vraiment? Merveilleux! Notre colonie a été fondée il y a seulement quarante ans,\nmais son emplacement a permis aux fondateurs d'instaurer des voies commerciales qui ont fait prospérer la ville.\nEt notre croissance compte aujourd'hui parmi les plus importantes de tout l'archipel.",
"Continue...",
"D'accord. Et si on laissait un peu l'histoire de côté, pour le moment?",
"Il a fallu construire un fort pour protéger la colonie, mais il y a des jours où je me dis qu'il ne sert à rien, car personne n'a jamais cherché à nous attaquer.",
"Je vois. Bien, si on parlait d'autre chose?",
"Je ne connais pas bien les environs. L'île ne comprend que des côtes désertes, quelques montagnes, et la jungle, qui commence dès la sortie de la ville. On dit aussi qu'il y a une ou deux criques bien commodes, dans lesquelles on peut jeter l'ancre sans être vu de la mer. Voilà, je crois que c'est à peu près tout.",
"C'est ennuyeux à mourir. Parle-moi d'autre chose.",
"L'île n'a été explorée qu'en partie, mais qui cherche à se perdre dans la nature? Il paraît que les contrebandiers ont établi une belle petite planque, dans le coin.",
"Je vois. Continue...",
"Des contrebandiers se sont installés dans la jungle. J'ai entendu dire qu'ils avaient dégagé un passage dans la jungle entre leur campement et une petite crique tranquille.",
"Je vois. Continue...",
"Je vois. J'aurais une autre question à te poser...",
"Ça ne m'intéresse pas vraiment, capitaine.",
"Dommage. Que peux-tu me dire d'autre?",
"L'aristocratie locale a dépensé sans compter pour construire ce fort, alors il est en bon état. Tout le monde sait que notre ville est riche,\nce qui explique l'augmentation du nombre de soldats postés au fort. Ils sont déjà un bon millier.",
"Je vois. Continue...",
"Je ne devrais pas discuter de ça. Je ne te connais pas bien, après tout. Je pense que tu me comprends...",
"Ne t'en fais pas, ce n'est pas grave.",
"Je vois. J'aurais une autre question à te poser, si ça ne te dérange pas...",

};