string DLG_TEXT[75] = {       
"Suis-je en présence du capitaine ",
"?",
"Qui le demande?",
"Je m'appelle ",
". Je suis en mission pour le compte de Sa Majesté, et je crois savoir que tu dois m'amener à Oxbay.",
"C'est exact. Tu as un plan, j'imagine?",
"Pas vraiment. Il faut juste que je m'infiltre dans les rangs des Français afin de leur causer quelques dégâts.",
"Je vois. C'est un peu vague à mon goût, mais je devrais tout de même pouvoir t'aider.",
"Je t'en serais reconnaissant. Comment comptes-tu procéder?",
"Disons que j'ai quelques relations parmi les Français. Allons-y, je t'expliquerai en route.",
"Pardon? Tu comptes partir sans attendre?",
"Tu es si pressé de te jeter dans la gueule du loup?",
"A quoi bon attendre? Plus vite on commencera, plus vite on aura fini.",
"C'est vrai. Ne t'inquiète pas, nous lèverons bientôt l'ancre.",
"Chut! C'était la porte? Je n'aime pas ça. Surveille l'escalier et reste sur tes gardes!",
"Tu crains des ennuis?",
"Qui es-tu, et que veux-tu?",
"Surveille ta langue, si tu ne veux pas que je te la coupe. Je sers le gouverneur.",
"Enfin! Dieu soit loué! Excuse mes manières, mais je dois me faire passer pour un soldat français.",
"Je comprends parfaitement. Sir Silehard m'a chargé de t'aider.",
"Alors, écoute attentivement : j'ai récemment appris qu'un capitaine français avait perdu une petite fortune au le tric trac. Tu connais ce jeu?",
"Évidemment! Mais qu'est-ce que cela a à voir avec ta mission?",
"J'ai fait la connaissance de ce capitaine, d'accord? J'ai gagné sa confiance et il m'a avoué qu'il avait perdu tellement d'argent qu'il n'arriverait jamais à rembourser ses dettes. Il était même prêt à se suicider avant que je ne lui offre une porte de sortie.\nJe lui ai proposé de régler ses dettes à sa place s'il acceptait d'amener son navire à Redmond et de le remettre à nos soldats. Il a accepté.",
"Incroyable! Il devait vraiment être désespéré pour accepter! Combien a-t-il perdu?",
"Peu importe. Nous devons nous retrouver aujourd'hui. Je lui remettrai l'argent et, en échange, la flotte anglaise gagnera un navire.",
"Excellent! Mais pourquoi as-tu besoin de moi?",
"Malédiction! Je suis découvert! Il faut filer immédiatement!",
"Comment? Ils doivent certainement nous attendre à l'entrée de la ville!",
"Je ne quitte pas la ville ; je n'ai pas encore accompli ma mission. Mais je connais quelqu'un qui pourrait nous cacher jusqu'à ce que l'affaire se tasse.",
"Qui donc?",
"Le propriétaire du chantier naval local, ",
"Oweyn McDorey",
"Oweyn McDorey",
". Allons le trouver sans attendre.",
"J'imagine que nous n'avons pas le choix. Très bien, allons-y.",
"Essaie d'éviter les soldats français en chemin, sans quoi nous n'atteindrons jamais le chantier naval.",
"Crois-moi, s'il faut se battre, ce ne sera pas parce que je l'aurai cherché.",
"Nous devons atteindre le chantier naval!",
"Je le sais bien! Où va-t-on, à ton avis?",
"Il faut absolument que je respecte mon accord avec ce capitaine français. Capturer un navire ennemi sans verser de sang est une occasion à ne pas laisser passer. Mais je ne vois pas comment le rejoindre. Les portes menant à la jungle doivent être gardées.",
"Quel est ton plan?",
"J'ai l'argent que j'ai promis au Français, mais les gardes me connaissent et je n'ai aucune chance d'arriver jusqu'à lui.",
"Où et quand devez-vous vous retrouver?",
"Il sera à la taverne ce soir, mais je ne peux pas y aller, c'est trop risqué.",
"Que peut-on faire, alors?",
"Il faut lui faire savoir qu'il doit nous retrouver ailleurs, dans un endroit sûr. Personne ne te connaît, ici, non? Va lui dire que je l'attendrai derrière la taverne, le long du mur d'enceinte.",
"Je ne sais pas... je ne suis pas un parfait inconnu, ici... je me suis déjà retrouvé mêlé à une rixe...",
"Ne te fais pas de soucis à ce sujet. Tes adversaires ne sont plus en état de parler, si? Quant à ",
"Everard Gordon",
", pas de risque qu'il te trahisse. Et puis, si tu n'y vas pas, je ne vois pas ce nous pourrons faire.",
"Bon, d'accord. Comment s'appelle ce Français?",
"Rabel Iverneau",
"Rabel Iverneau",
". Il devrait être assis au comptoir, sous l'escalier.",
"C'est noté. Bon, tâchons de prendre un peu de repos avant la nuit.",
"C'est l'heure. Si tu y vas prudemment, l'air de rien, les gardes ne te causeront pas d'ennuis.",
"Dieu t'entende, mon ami.",
"C'est comme ça que ça se passe, d'habitude. Au fait, j'ai failli oublier : nous quitterons l'île à bord du navire français et tes hommes devront regagner ton bateau et l'amener à Redmond.",
"C'est bon, j'ai tout noté. Souhaite-moi bonne chance.",
"Espérons que tu n'en auras pas besoin. Vas-y!",
"Je suis parti.",
"Bonjour. Tu dois être ",
"Rabel Iverneau",
", j'imagine...",
"Bon, et maintenant? Comment monter à bord du navire de ",
"Rabel Iverneau",
"?",
"Voici ce que nous allons faire : ",
"Rabel Iverneau",
" va rejoindre son bateau le premier, comme à l'accoutumée, et nous le suivrons comme si nous étions ses hommes ou ses prisonniers.",
"C'est un plan tellement insensé qu'il risque de marcher.",
"Il va falloir rester tout près de lui. Espérons que personne ne nous arrêtera.",
"Oui, sans quoi le Français risque d'avoir de sérieux ennuis.",
"Bien dit, mon ami. Mais je suis persuadé que tout se passera bien. Nous serons bientôt partis.",
"Je le croirai quand nous serons à bord. D'ici là, croisons les doigts!",

};