string DLG_TEXT[24] = {
"Eh, l'ami, tu as quelque chose à nous. Donne-nous gentiment ce coffre et on t'épargnera.",
"Quel coffre?",
"Pourquoi ne disparaissez-vous pas tranquillement, les gars?",
"Celui que tu as rapporté d'Oxbay. Donne-le-nous. Il est à nous!",
"Bon sang! J'avais presque réussi à le transporter à destination!",
"Je déteste les menaces. Et tu n'auras pas le coffre.",
"Si tu t'entêtes comme ça, tu vas mourir! Et ne compte pas sur les soldats pour te sauver!",
"On verra bien!",
"Très bien, prends le coffre et fiche le camp!",
"Ha! Eh bien, je suis vraiment désolé! Maintenant, boucle-la et donne-nous le coffre!",
"Pas question! Il faudra d'abord me passer sur le corps!",
"Très bien, prends ton coffre et va-t-en!",
"Ha-ha-ha! Ton épée ne peut rien contre nous! Tu veux essayer, courageux guerrier?",
"Bon, prépare-toi à mourir!",
"Quelle surprise! Qui aurait pensé que tu serais assez rusé pour éviter de te battre?",
"Tu as eu ce que tu voulais, alors va au diable!",
"Oui, nous partons. Mais avant, écoute ça : le type qui t'a demandé de livrer ce coffre t'a bien coincé! On pourrait te tuer, tu sais!",
"...",
"Alors, tu vois que tu ne peux pas nous battre! Pour la dernière fois : donne-nous ce coffre ou tu es un homme mort!",
"Jamais! Bon, je vais m'occuper de toi!",
"Mais c'est impossible! Je n'en crois pas mes yeux!",
"Je t'ai dit que tu ne pouvais pas nous tuer! Détends-toi et va te saouler pour oublier tout ça! Ha-ha! Bon, arrête de jacasser et donne-nous le coffre!",
"Ah, qu'il t'accompagne en enfer! Prenez-le!",
"Non, je vais te tuer quand même!",

};
