string DLG_TEXT[22] = {
"Laisse-moi tranquille, mon garçon. Tu me déranges.",
"...",
"Eh bien, voyez donc ça! Un berger qui dégaine son épée pensant que cela va suffire à nous empêcher de festoyer!",
"Alors, c'est toi qui voles les éleveurs du coin?",
"Hé, c'est la fille qui a tué nos gars! Attrapez-la!",
"Par exemple! Vous êtes combien?",
"Attends! J'ai besoin de parler.",
"gambled_girl",
"Il paraît que tu es récemment devenu propriétaire d'une jeune fille. J'aimerais te la racheter.",
"Elle n'est pas à vendre.",
"Tu arrives à temps. Je pensais me débarrasser d'elle.",
"Bon, tu veux bien la vendre. Je te propose 5 000 pièces d'or. Alors, marché conclu?",
"Désolé, ça ne va pas être possible.",
"J'accepte ton offre!",
"Très bien. 5 500 pièces d'or. C'est à prendre ou à laisser.",
"Je prends!",
"Non. Finalement, je ne pense pas qu'on puisse faire affaire.",
"Bien tenté. Tu es plutôt rusé pour un rustre. Bon... Si tu tiens à la vie, lâche cette épée rouillée et déguerpis!",
"Lâchez vos épées avant que je vous tranche les mains!",
"Tais-toi ou je te coupe la langue!",
"Je vais t'apprendre le respect!",
"Essaie un peu!",

};
