string DLG_TEXT[384] = {
"...",
"...",
"Tu es d'accord pour faire voile, ",
"?",
"Oui.",
"Bonjour, ",
"Blaze",
". Je ne pensais pas te voir ici.",
"Crois-moi, ça me surprend autant que toi. On ne se quitte plus ces temps-ci.",
"Ralph Fawn",
" est mort et quelqu'un va payer!",
"C'est triste. ",
"Ralph Fawn",
" était un type bien.",
"??? Qu'est-ce que tu fais ici?",
"??? Tu es vraiment quelqu'un de surprenant!",
"Tu as réussi à obtenir les informations que tu voulais?",
"Eh bien, je pense qu'on peut faire confiance à ce type. Mais il ne me dira pas où se cache ",
"Raoul Rheims",
".",
"Mon Dieu, ",
"! Pourquoi as-tu mis autant de temps?!",
"Du calme. Je t'avais dit que j'avais d'autres choses à faire.",
", ",
"Vincent Bethune",
" est allé à la taverne. Il a dit qu'on devait l'y retrouver.",
"Visiblement, ce type prépare quelque chose.",
"Où est allé ",
"Vincent Bethune",
"?",
"Il a dit qu'il avait à faire.",
"!!! On dirait qu'on est suivis par des petits plaisantins. Occupe-toi d'eux et rattrape-nous. Va tout droit au prochain croisement, puis à gauche au suivant!",
"OK. Mais attention, il me faut ",
"Raoul Rheims",
" en vie!",
"...",
"Quoi? ",
"Raoul Rheims",
" est mort?! Et que vais-je dire au gouverneur?",
"?!",
"Oui, ça me fait plaisir de te voir, à moi aussi. Même pas un sourire pour la personne qui vient de te sauver la vie?",
"On ferait mieux d'attendre la nuit. Ce sera plus facile de se faufiler en ville.",
"Ouais. Bonne idée.",
"Qu'est-ce que tu attends? On doit rejoindre la résidence avant l'aube!",
"On va devoir trouver un autre moyen d'entrer... Pourquoi pas une fenêtre?",
"On devrait peut-être se séparer.",
"Pourquoi? On forme une bonne équipe.",
"L'enjeu est de taille. J'ai besoin de temps pour préparer mon équipage avant d'attaquer ces maudites mines.",
"...",
"Les gars! J'ai décidé d'attaquer les mines d'or d'Oxbay. Ça va être dangereux et certains risquent d'y laisser la vie. Mais le jeu en vaut la chandelle!",
"Pensez à tout cet or qui n'attend que de solides gaillards pour être ramassé! Que représente le danger en échange? Qui me suit?",
"Cette ordure d'Enrique a volé mon navire! Maudit soit-il!",
"Je dois repartir de zéro. Je ferais mieux d'aller en ville et de chercher du travail.",
"Eh bien! Au moins ce traître ne mentait pas lorsqu'il prétendait avoir éliminé ces bandits...",
"Maudit soit-il! Cette ordure d'",
"Enrique Forneris",
" a filé avec mon navire!",
"Je dois repartir de zéro. Je ferais mieux d'aller en ville et de chercher du travail.",
"Et alors? Je vais enfin pouvoir trouver ce corsaire espagnol qui est censé avoir enlevé la fille.",
"Va au navire du pirate.",
"Pas tout de suite. Ce n'est pas le moment.",
"Il faut que je retrouve cette fille. Si je ne la trouve pas ici, j'aurai de sérieux ennuis.",
"...",
"J'ai échappé à ces fanatiques de justesse! Cette affaire est plus dangereuse que je ne le pensais.",
"...",
" Il a failli me tuer! Faut que je file d'ici!",
"...",
"Tu ne comprends pas! Ecoute, le dernier emplacement connu de l'idole était Greenford et il m'est impossible d'aller dans les colonies anglaises. Tu dois t'y rendre et récupérer cette idole avant que ",
"Robert Christopher Silehard",
" ne révèle ta 'trahison' à tout le monde.\n Je l'ai donnée à un certain ",
"Giraldo Figuiera",
"Giraldo Figuiera",
".\nMais il est déjà mort, à cause de l'idole sans doute. Tu vas devoir enquêter à la taverne et essayer de recueillir des indices.",
"Et que vas-tu faire? Enquêter sur la dernière partie de la légende?",
"Exactement. Vite - le temps presse!",
"Ne t'inquiète pas pour moi. Occupe-toi de ton affaire.",
"Oh, ",
", tu ne pourrais pas être aimable une minute? Bon, qu'importe, on se retrouve à Oxbay, chez ce drôle de vieux. D'accord?",
"Oui, oui, très cher capitaine.",
"Tu as raison. Mais tu vas devoir y aller sans moi, inutile d'attirer l'attention.",
"Ça marche. On y va.",
"Qu'est-ce qui s'est passé? Qui sont ces gens?",
"Tu ne te souviens de rien?",
"Ne me brusque pas, ",
", j'ai l'impression que ma tête va exploser. Et si tu m'expliquais ce que tu fais ici?!",
"Du calme! Si quelqu'un a le droit d'être furieux, c'est moi. Ton poignard ne me chatouillait pas vraiment!",
"J'aurais dû le faire bien avant! Je sais que tu travailles pour le gouverneur anglais. Et que tu en veux à ma tête. Alors, réglons ça une fois pour toutes. En garde!",
"Ne sois pas ridicule, ",
", je ne suis pas à tes trousses. Je ne savais même pas que ",
"Robert Christopher Silehard",
" voulait ta mort!",
"Tu mens! Et ce n'est pas la première fois, ",
"! Tu ferais n'importe quoi pour de l'or, pas vrai?!",
"Oh, pour ce qui est de crier, ",
", je ne faisais que jouer un rôle! Tu croyais dur comme fer que j'étais une canaille, je ne voulais pas te décevoir!",
"De quoi tu parles? Je t'ai toujours pris pour un honnête homme!",
"Oh, bien sûr! Ecoute, on se connaît depuis longtemps et on a toujours été rivaux. Mais ce n'est pas pour ça que je veux ta mort!\nTu as peut-être un problème avec moi parce que je suis un homme?",
"Et alors? Les hommes sont des porcs et tu ne fais pas exception à la règle!",
"Vraiment? Qu'ai-je fait pour te blesser? N'oublie pas que je t'ai plusieurs fois sauvé la vie!",
"Ça se discute. Mais le fait est que tu travailles pour un homme qui ne souhaite qu'une chose : ma mort!",
"Rectification. Je travaillais, ",
". Ce n'est plus le cas même si",
"Robert Christopher Silehard",
" ne le sait pas encore.",
"Pourquoi? Il ne te payait pas assez?",
"Crois-le si tu veux, mais l'or n'a rien à voir dans tout ça. Tout l'or du monde ne suffirait pas pour me mettre au service d'un homme comme lui.",
"Mais alors, pourquoi es-tu ici? Si tu es libre, pars!",
"Bien. Je vois que tu n'as pas changé. Il vaut mieux que je m'en aille et toi aussi. Restons-en là. Ces cadavres vont attirer des ennuis avant d'attirer les mouches.",
"!!!",
"Qu'est-ce qu'il y a maintenant?",
"...",
"Tu as quelque chose à ajouter ou je peux y aller?",
"... Merci, ",
", sans toi, je ne serais plus de ce monde.",
"Oublie ça. Bon, je peux y aller?",
"Attends, ",
"! Où vas-tu comme ça?",
"Je vais poser quelques questions à un certain gouverneur véreux.",
"Eh, attends une minute! Tu ne peux pas y aller sans escorte. C'est du suicide! Si ",
"Robert Christopher Silehard",
" a des soupçons, il n'hésitera pas à te tuer!",
"Merci de me prévenir. Mais, je tente ma chance.",
"Alors, je t'accompagne!",
"A quoi bon? Je peux me débrouiller sans toi.",
"D'abord, j'ai moi aussi des questions à poser au gouverneur et puis... et puis...",
"Et puis quoi?",
"Je connais un endroit de Redmond où on pourra débarquer en toute sécurité, sans être dérangés.",
"Bon, très bien. On est partenaires, mais juste pour cette fois.",
"D'accord. Mais attention : si tu me doubles, ",
", je jure que je te tue.",
"OK.",
"Alors, comme ça tu travailles pour ce sale anglais?",
"Oui, trésor. On peut dire que je suis son bras droit.",
"Quelle affaire? Il ne m'en a jamais parlé!",
"Comment je le saurais? On ferait mieux de s'adresser à notre fugitif.",
"Je ne peux pas m'empêcher de penser que tu me caches quelque chose, ",
".",
"S'il te plaît, ",
" tu vas me faire confiance, pour une fois?",
"Très bien. On en reparlera plus tard.",
"Raoul Rheims",
", il est ici, pas vrai?",
"Oui, il est assis à cette table, là. Offrons-lui un verre pour discuter un peu.",
"Oh, du calme, ",
"! Il est juste venu pour savoir si ",
"Raoul Rheims",
" vit toujours ici. C'est tout.",
"Bon, allons à la taverne.",
"D'accord, mais tu n'avais pas dit que tu devais disparaître plusieurs jours!",
"Serait-il possible tu t'inquiètes pour moi, ",
"Danielle",
"?",
"Oui, c'est possible. Dans tes rêves les plus fous!",
"Bon. Eh bien, je suis là maintenant. Où est ",
"Vincent Bethune",
"?",
"Il est sur mon navire à livrer un courageux combat contre l'ennui le plus total.",
"Écoute, je regrette pour le retard, d'accord? On va où maintenant?",
"À Douwesen. ",
"Vincent Bethune",
" prétend y vivre.",
"Parfait. Ne perdons pas une minute.",
"Attends. Ton équipage n'est-il pas trop important?",
"Tu as peut-être raison - je vais voir qui je peux laisser à terre.",
"Prends la mer et je t'accompagnerai.",
"Très bien.",
"Alors, tu voulais le trouver par toi-même? Cela ne plaît guère, ",
"!",
"Du calme, ça n'a jamais été mon plan. Écoute, allons le chercher tous les deux. Tu lui parleras, apprendras ce que tu dois savoir puis je le conduirai à l'homme qui veut le voir.",
"Ça marche. Mais j'ai d'abord à faire. On peut se retrouver ici dans quelques jours?",
"D'accord. Cela va me laisser le temps de rendre compte à mon employeur.",
"Je ne suis pas d'humeur à plaisanter pour le moment, ",
" - j'ai passé une sale journée.",
"Moi aussi, crois-moi. Qui est ce dandy qui t'accompagne? Je dois m'inquiéter?",
"Ne sois pas bête, ",
"! C'est un ami... c'est tout. ",
"Vincent Bethune",
". Il m'aide à retrouver le capitaine ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Tu plaisantes! Je le cherche moi aussi, mais pour être honnête, je crois avoir perdu sa trace.",
"Qu'est-ce que tu lui veux?",
"De l'argent, mon cœur. Il m'a promis un bon paquet d'argent.",
"Attention avec ce mon cœur, ", 
"! J'ai toujours pensé que tu faisais partie de ces gens que seul l'appât du gain intéresse!",
"Je n'ai jamais prétendu être quelqu'un d'autre, ",
". Alors, tu sais où se cache ",
"Raoul Rheims",
"?",
"Non. Mais ",
"Vincent Bethune",
" dit savoir où notre type s'est installé.",
"C'est presque trop facile. On tombe pile poil sur la personne qui sait où se trouve l'homme qu'on cherche?",
"Quelle méfiance, ",
"! Il n'y a pas que des canailles comme toi.",
"Qu'est-ce que ça veut dire, ",
"? J'essaie juste de mieux comprendre la situation. Comment ",
"Vincent Bethune",
" sait-il où se cache ",
"Raoul Rheims",
"?",
"Pourquoi ne le lui demandes-tu pas toi-même?",
"Eh bien, je crois que je vais le faire.",
"Je ne vois pas ce qu'il y a de drôle, ",
"Blaze",
". Jette ton dévolu sur quelqu'un d'autre si tu n'as rien de mieux à faire.",
"Tu continues à cacher tout l'amour que tu me portes, pas vrai? Très bien. Si tu préfères la solitude, alors je te laisse.",
"Épargne-moi ta compassion, ",
"! Je n'en ai pas besoin.",
"Comme tu veux. Mais comment expliques-tu que ces soldats nous aient attaqués? Je ne me souviens pas avoir eu de différend avec les Anglais. Et toi?",
"Ça ne te regarde pas! En tout cas, il est hors de question que je m'approche d'un autre pavillon anglais. Je quitte cette ville et je te conseille d'en faire autant.",
"Attends!",
"?!? Comment as-tu atterri ici?",
"?!? Qu'est-ce que tu fais ici?",
"Je suis ici pour toi! J'avais peur que tu aies déjà servi d'appât aux requins!",
"Tu te faisais du souci pour moi? Ça me touche.",
"Pour toi?! Non, je me faisais du souci pour l'idole! J'aurais eu beaucoup de mal à mettre la main dessus si elle s'était retrouvée au fond de la mer avec ton navire.",
"L'idole est en sécurité avec moi. Mais à propos de navire, où est le tien?",
"J'ai dû l'échanger contre cette tablette, mais ça vaudra le coup lorsque j'aurai trouvé le trésor! Je pourrai alors m'acheter les meilleurs navires!",
"J'espère que tu as raison. Bon, où se trouve cette précieuse tablette d'argile?",
"Elle est trop lourde pour être transportée. J'ai recopié tout le texte sur papier.",
"Mmh. ",
", j'ai comme l'impression que tu me caches quelque chose!",
"Peut-être, peut-être pas. De toute façon, il va falloir que tu fasses avec. Voilà le texte. Tu as d'autres questions?",
"Oui, une : qu'est-ce qu'on fait maintenant?",
"Y a-t-il une cabine de libre pour moi sur ton navire? Je préférerais ne pas être avec le reste de l'équipage.",
"Ne t'inquiète pas, tu auras une cabine. Mais pour le moment, j'ai des tas de choses à te dire.",
"Plus tard. Quand tu auras fini ici, monte là-haut. On va discuter.",
"Bien.",
"On a volé mon navire et la tablette avec. Heureusement que j'en avais fait une copie.",
"Ce n'est pas ta faute, ",
". Il peut arriver pire en mer, tu sais.",
"Épargne-moi ces balivernes, ",
"! Je sais que je n'y suis pour rien. Ah, j'enrage, mais ça ne va pas durer. Je vais bientôt avoir un nouveau bateau et là, je m'occuperai de ce maudit voleur!",
"Écoute-toi! On dirait un pirate!",
"Non, un capitaine, ce que je suis. Si tu n'aimes pas mes manières, va travailler pour Silehard!",
"Non, merci. J'ai moi aussi l'œil sur ce trésor.",
"Bon, alors continuons. Essayons de trouver quelqu'un capable de traduire ce charabia antique! Si on ne veut pas finir comme Rheims, il va falloir qu'on lise le texte dans son intégralité.",
"Exact. Eh bien, si j'ai bonne mémoire, ",
"Researcher",
" s'est toujours vanté de connaître des langues anciennes...",
"C'est vrai! Allons le voir.",
"À Greenford, alors! Je t'attendrai à bord du navire demain matin.",
"Tu en as mis du temps? On peut y aller?",
"Bien sûr. Le navire est en parfait état.",
"Bon, on y va alors!",
"N'oublie pas qui est le capitaine ici.",
"Bon, on y va alors!",
"N'oublie pas qui est le capitaine ici.",
"Je crois qu'on va devoir faire sortir ",
"Researcher",
" de la prison de Greenford.",
"Oui. Ou trouver une autre personne capable de lire la légende.",
"Impossible de trouver quelqu'un d'aussi érudit que lui. Du moins, pas sur ces îles!",
"Bon, alors qu'est-ce que tu proposes? On se faufile en ville et on déboule dans la prison?",
"Pourquoi se faufiler en ville quand on peut s'en emparer?",
"S'en emparer?! Mais tu as perdu la tête?",
"Non, pas du tout. Tu attaques le fort depuis la mer et j'emmène mon équipage dans la jungle pour un assaut terrestre. Ils ne vont rien comprendre!",
"À t'entendre, il n'y a rien de plus facile. Ce n'est pas toi qui dois attaquer le fort!",
"Tu préfères peut-être affronter la jungle et ses animaux venimeux? Pas de problème, je te laisse la place!",
"Non, non. Ce ne serait pas... juste par rapport à toi. Je vais attaquer le fort.",
"Je savais que tu serais d'accord. Il va nous falloir un certain temps pour préparer cet assaut et ça ne va pas être du gâteau. Lorsqu'on sera prêts, tu pourras nous débarquer, mon équipage et moi, près du phare.",
"Très bien. Bon, retournons au bateau.",
"Pourquoi perdre du temps? Attaquons maintenant avant de changer d'avis!",
"Tu crois? Cette fois, il va falloir affronter des soldats et non des hommes d'équipage!",
"On a assez d'hommes pour capturer la colonie!",
"Eh bien, on devrait peut-être prendre le temps de préparer cet assaut.",
"Je donnerais cher pour voir la tête du gouverneur quand il apprendra ça!",
"En avant!",
"On retourne au navire, ",
"? Ou on va faire une petite balade?",
"Évidemment qu'on retourne au bateau.",
"Le plus dur, c'est quand tout est prêt et qu'il faut attendre le bon moment.",
"Je connais plusieurs façons de passer le temps... mais bon, qu'importe.",
"Allons semer la terreur parmi ces marins d'eau douce!",
"Oui! Le gouverneur va regretter d'avoir utilisé mes services!",
"Attends! Les préparatifs ne sont pas terminés.",
"S'il te plaît, ",
"! Vite!",
"Ne me bouscule pas! Je n'ai pas l'habitude de me précipiter comme ça au combat.",
"Une fois la fumée dissipée, on se retrouvera au centre de Greenford! Et pas de pillage... On n'aura pas besoin des vieilleries de cette ville une fois qu'on aura trouvé le trésor!",
"Et ne laisse pas le feu de l'action t'éloigner de ton affaire!",
"Ne te fais pas de souci pour moi! ",
" Essaie juste de rester en vie, d'accord?",
"Ce n'est pas une ville comme celle-là qui aura raison de moi. Bonne chance, ",
".",
"Quelle bataille! Ça va?",
"Bien sûr! Je n'avais pas prévu de mourir aujourd'hui!",
"Eh bien, la mort ne prévient pas toujours, tu sais!",
"C'est vrai. Allons libérer ",
"Researcher",
".",
", on discutera plus tard. Il faut d'abord libérer ce vieil homme.",
"D'accord.",
"Et ça va prendre combien de temps?",
"Researcher",
" dit qu'il lui faut plusieurs jours pour traduire ce texte.",
"Ça fait déjà une semaine! Je commence à m'ennuyer.",
"Pense à ces montagnes d'or et ton ennui s'envolera.",
"J'ai hâte de larguer les amarres! Et pourquoi est-ce qu'il ne ferait pas sa traduction en allant au temple?",
"Je ne sais pas... Je n'y avais pas pensé.",
"Ouais, j'imagine qu'un pirate ne fait pas tellement travailler ses méninges. Tu ne sais peut-être pas non plus que faire de l'or ",
"?",
"Quoi?",
"Je te demande ce que tu vas faire avec ta part du trésor. Je t'écoute.",
"Je ne sais pas. Je vais acheter une île anglaise, j'imagine, et y vivre selon mes règles. Ou je vais devenir un pair anglais. Ça peut être intéressant. Et toi?",
"Je ne te le dirai pas. C'est un secret.",
"Très bien. Comme tu voudras.",
"Tu vas t'attaquer à la flotte régulière?",
"Non, je vais l'écraser!",
"Je vais prendre le contrôle du fort! Veille à ce que qu'on puisse utiliser le canon.",
"Et toi, regarde où tu tires!",
"On a gagné! On écrira des chansons sur cette bataille ou je ne suis qu'un vieux morse! Ensemble, on pourrait prendre le contrôle de tout l'archipel! Ou de toutes les Caraïbes!",
"Bien sûr qu'on le pourrait. Mais on devrait d'abord en parler à ",
"Moses Blinman",
".",
"Écoute-toi, ",
"! Tu devrais avoir honte de toi, anéantir les rêves d'une gentille fille avec ta logique ennuyeuse!",
"Le trésor passe avant tout, très chère. Après, si tu veux toujours conquérir les Caraïbes, tu pourras compter sur moi. Je te le promets.",
"J'espère que cet érudit a eu le temps de déchiffrer ce charabia. Je ne pense pas qu'on puisse résister à une seconde attaque.",
"Je doute que le gouverneur ait d'autres navires de guerre.",
", le temple semble situé quelque part dans les terres. Allons voir!",
"D'accord, mais tâchons de ne pas nous faire remarquer. On devrait laisser l'équipage ici le temps d'examiner nous-mêmes le temple.",
"Incroyable, on l'a trouvé! Plus que quelques heures et on roulera sur l'or!",
"À condition qu'il abrite bien de l'or.",
"Ne dis pas ça! On n'a quand même pas fait tout ce chemin pour rien!",
"On verra bien.",
"Il y a trois passages ici et n'importe lequel peut être le bon. Lequel choisir?",
"Je ne sais pas. C'est peut-être le piège dont a parlé ",
"Researcher",
".",
"Alors, il faut se séparer. On progressera plus vite. Je prends le passage de gauche et on verra bien qui trouve le trésor le premier!",
"Eh, attends...",
"On dirait qu'on peut aller à Khael Rhoa maintenant!",
"Quelque chose me dit que ça ne va pas être aussi simple.",
"On devrait peut-être continuer et fouiller le temple pendant qu'il déchiffre ce charabia.",
"Non, pas sans savoir où on va! Même le diable pourrait se perdre dans ce labyrinthe!",
"Comme tu voudras, mais j'y vais quand même. Je vois déjà se profiler ma part du butin!",
"Quoi?",
"Ça doit être la niche dont ",
"Researcher",
" a parlé. Mais où est le trésor?",
"Je ne sais pas. Même en dépouillant ces murs de tout leur or, ça ne ferait pas lourd...",
"On ne peut pas perdre de temps à fouiller, ",
". Ils vont s'emparer de la ville!",
"Je veux juste m'assurer que tu ne me couleras pas une fois la flotte anglaise évincée.",
"Ce n'est pas gentil, ça, ",
".",
"Je plaisante! Je plaisante. Bonne chance!",
"Grand Dieu! C'était quoi?",
"Aucune idée!",
"Par tous les diables, ",
"! Personne n'a pu survivre à ça! Mon trésor! On pourrait essayer d'en prendre une partie? Une toute petite partie?",
"Eh, ce n'est certainement pas le seul trésor au monde!",
"Et alors? C'est quand même perdu!",
"J'ai l'impression que l'or t'intéresse moins que tu ne le prétends...",
"Je ferais mieux de ne pas retourner là-bas et de quitter Redmond au plus vite!",
"Pauvre ",
"Ralph Fawn",
"! Le gouverneur va payer pour sa mort, je le jure! Mais pourquoi aurait-il donné un tel ordre? Il a peut-être pensé que ",
"Brendan Applin",
" m'en avait trop dit? Il faut que j'en ai le coeur net!",
"Brendan Applin",
" a marmonné quelque chose à propos du trésor. Et le trésor est un bon remède contre l'ennui. Je crois que je vais aller voir Quebradas Costillas. ",
"Brendan Applin",
" a également parlé d'un certain ",
"Raoul Rheims",
"... Je devrais peut-être le chercher.",
"Hum... On dirait un journal. Son auteur est probablement ",
"Raoul Rheims",
", l'homme que je cherche. Mince! La plupart des pages ont été abîmées par l'eau. Seules les dernières sont lisibles : '... les réparations vont bientôt avoir lieu,\net je vais devoir aller à Redmond pour informer Sa Grâce de notre échec... La clé doit se trouver dans la partie de la légende que je n'ai pas pu lire. Je vais chercher toutes les traces de ce mythe et, la prochaine fois, je TROUVERAI le temple... '\nHum. Et ça dit ensuite : ' Dieu, à l'aide, on m'a tiré dessus aujourd'hui! Cette ordure s'est enfuie, mais je crois l'avoir reconnue. Je suis sûr de l'avoir déjà vue chez le gouverneur. Ne serait-ce pas ce ",
"Robert Christopher Silehard",
" qui a commandité ma mort? Visiblement, je vais devoir me faire oublier un moment.\n",
"Camilo Machado",
" ne refusera pas de m'accueillir. Je pourrai alors essayer de savoir ce qui se passe... Ça me chagrine d'abandonner mon navigateur, ",
"Giraldo Figuiera",
" ici, mais il a attrapé la malaria et il ne survivra pas au voyage. J'espère qu'il saura tenir sa langue.'",
"(Lit encore.)",
"(Arrête de lire.)",
"Oh non, encore Quebradas Costillas! Mais c'est ma seule piste.",
"Nous avons pris la mer aujourd'hui. Le ciel est dégagé et j'espère qu'il va le rester jusqu'à ce qu'on arrive à Conceicao. Les événements des derniers jours m'ont laminé. Je ne sais plus quoi penser... Plus quoi faire. Je n'aurais peut-être pas dû prendre part à tout ça... '\nAha, ce passage a été consigné quelques jours plus tard : ' Je me sens enfin mieux. ",
"Camilo Machado",
" m'a accueilli les bras ouverts et m'a offert sa protection. Le temps de la réflexion est venu. '\nEt voici le dernier passage : ' J'ai eu une idée aujourd'hui. Au lieu de perdre mon temps ici, je ferais mieux de chercher la source de la légende qui m'a mené au temple ancien. J'ai acheté une petite maison à un type du coin ; elle fera office de base. Je pars demain et je vais laisser tout ce dont je n'ai pas besoin ici.'",

};
