string DLG_TEXT[27] = {
", mon ami. Je suis ",
", Je dirige le chantier naval de la région.",
"Heureux de te rencontrer. Je suis ",
", le capitaine du '",
"'.",
", ",
". Alors, que puis-je faire pour toi, ",
"?",
"Je voudrais juste aveugler deux trous et rapiécer mes voiles. Sans qu'on me pose de questions.",
"Pour le moment, je voudrais surtout des renseignements.",
"Non, j'ai juste du temps à tuer. Je me suis dit que je pourrais tuer un peu de ton temps aussi pendant que j'y étais.",
"Eh bien, si tu es le capitaine, mon chantier naval est à ton service.",
"Parfait, ",
". Jetons un coup d'oeil à mon navire et voyons ce qui a besoin d'être réparé.",
"Je te remercie. Mais pour le moment, je voudrais juste te poser quelques questions.",
"Peut-être la prochaine fois. Je n'ai pas besoin de tes services pour le moment.",
"Qu'est-ce qui t'intéresse, exactement, ",
"?",
"Pas pour le moment, non.",
"Est-ce que je peux faire autre chose pour toi, ",
"?",
"Si tu pouvais réparer deux ou trois choses sur mon rafiot, je pourrais partir!",
"Merci, c'est bon. Au revoir!",
"De quoi as-tu besoin, exactement?",
"Mon navire a besoin d'être réparé. Ou je pourrais peut-être en acheter un neuf si le prix est raisonnable.",
"J'ai besoin d'un petit peu plus de puissance de feu. Tu peux peut-être m'aider.",
"Tout va bien, merci.",

};