string DLG_TEXT[99] = {
", ",
". Qui es-tu et que puis-je faire pour toi?",
"Que veux-tu, ",
"? Comment t'appelles-tu?",
"Bonjour. As-tu besoin de quelque chose, ",
"? Tu cherches quelqu'un?",
"Je suis ",
", le capitaine et le propriétaire du navire '",
"'.",
"Je m'appelle ",
".",
"Appelle-moi capitaine ",
".",
"Bonne journée à toi, capitaine ",
". Tu as quelque chose à charger?",
", capitaine. Heureux de te voir en vie et bien portant.",
"Ah, ",
"! Qu'est-ce qui t'amène parmi de modestes ouvriers du port comme nous? Tu veux peut-être nous embaucher?",
"Pas pour le moment. Pour l'instant, je veux juste connaître les nouvelles de Redmond.",
"Non. Quelles sont les nouvelles par ici?",
"Je veux juste connaître les dernières rumeurs.",
"J'ai besoin que tu m'indiques une direction.",
"Tu connais bien la ville?",
"J'ai besoin que tu m'indiques une direction.",
"J'ai besoin de renseignements sur une personne que tu connais peut-être.",
"J'ai besoin de te poser des questions sur quelqu'un.",
"Qu'est-ce que tu peux me dire sur les gens du coin?",
"Non, merci. Au revoir.",
"Oh, c'est toi, capitaine! Tu as quelque chose à charger? On ne demande pas cher!",
"Capitaine, ",
"? Est-ce que je peux faire quelque chose pour toi?",
"Si je peux faire quelque chose pour toi, ",
", tu n'as qu'à le demander.",
"Je ne crois pas. Je voudrais juste connaître les nouvelles de Redmond.",
"Non, merci. Qu'est-ce qui s'est passé, ces derniers temps, par ici?",
"Je veux juste connaître les dernières rumeurs.",
"J'ai besoin que tu m'indiques une direction.",
"Tu connais bien la ville?",
"J'ai besoin que tu m'indiques une direction.",
"J'ai besoin de renseignements sur une personne que tu connais peut-être.",
"J'ai besoin de te poser des questions sur quelqu'un.",
"Qu'est-ce que tu peux me dire sur les gens du coin?",
"Désolé, j'ai changé d'avis. Au revoir.",
"Je vois. Tu peux peut-être répondre à une autre question pour moi.",
"Merci pour ce renseignement. Au revoir.",
"Autre chose, ",
"?",
"Ça me fait toujours plaisir de rendre service, ",
".",
"Bien sûr, ",
", bien sûr. Pose tes questions.",
"Je ne crois pas. Je voudrais juste connaître les nouvelles de Redmond.",
"Non. Qu'est-ce qui s'est passé, ces derniers temps, ici?",
"Je veux juste connaître les dernières rumeurs.",
"J'ai besoin que tu m'indiques une direction.",
"Tu connais bien la ville?",
"J'ai besoin que tu m'indiques une direction.",
"J'ai besoin de renseignements sur une personne que tu connais peut-être.",
"J'ai besoin de te poser des questions sur quelqu'un.",
"Qu'est-ce que tu peux me dire sur les gens du coin?",
"Une autre fois. Au revoir.",
"Que veux-tu dire, ",
"?",
"Quelqu'un en particulier, ",
"?",
"Dis-moi son nom, ",
", et je te dirai si je le connais.",
"Qu'est-ce qu'on raconte sur le gouverneur Silehard?",
"Que penses-tu de Charles Windem, l'aubergiste?",
"Parle-moi de Murrey, l'architecte naval.",
"Parle-moi de Thomas O'Reily, le marchand.",
"Laisse-moi te poser une autre question.",
"Je m'en souviendrai. Merci. J'ai une autre question.",
"Je vois. Merci et au revoir.",
"Je m'en souviendrai. Merci. J'ai une autre question.",
"Je vois. Merci et au revoir.",
"Je peux t'aider à trouver ton chemin. J'habite ici depuis cinq ans.",
"Bien sûr, ",
"! Où veux-tu aller exactement?",
"Donne-moi juste le nom de l'endroit, ",
", et je te montrerai comment y aller.",
"Comment trouver la taverne?",
"Où est le chantier naval?",
"Où puis-je obtenir un bon prix pour mes marchandises?",
"Va tout droit des portes de la ville à la place qui se trouve devant le domicile du gouverneur, puis regarde à ta gauche. Tu verras la taverne.",
"Merci. Au revoir.",
"Où est le chantier naval?",
"Où puis-je obtenir un bon prix pour mes marchandises?",
"Le chantier naval se trouve à l'extérieur de la ville, au bord de la mer, mais le bureau, ",
", est facile à trouver si tu regardes à gauche des portes de la ville.\n Il y a une pancarte, ",
", alors tu ne peux pas le manquer.",
"Je vois. Comment trouver la taverne?",
"Où puis-je vendre mes marchandises?",
"Merci pour ce conseil. Au revoir.",
"Prends la rue centrale à partir des portes de la ville, ",
", puis une fois arrivé à la place de la fontaine, regarde sur ta droite. Tu verras ce que tu cherches.",
"Où est le chantier naval?",
"Comment aller jusqu'à la taverne?",
"Je vois. Merci et au revoir.",

};