string DLG_TEXT[162] = {
", ",
". Je m'appelle ",
". Et toi?",
"Bonjour à toi, ",
"! Je suis ",
". Puis-je connaître ton nom?",
"Oui, oui, ",
"! Que veux-tu? Je m'appelle ",
".",
"Je suis ",
", capitaine du navire '",
"'.",
"Je m'appelle ",
".",
"Tu peux m'appeler capitaine ",
".",
"Heureux de te revoir, capitaine ",
".",
"Ah. C'est encore toi, ",
". Tu as d'autres questions?",
"Bonjour, ",
"!",
"Heureux de te revoir, capitaine ",
".",
"Ah, c'est toi, ",
". De quoi as-tu besoin?",
"Bonjour, ",
"!",
"Quelles sont les nouvelles, par ici?",
"Il s'est passé quelque chose d'intéressant, dernièrement?",
"Il s'est passé quelque chose d'intéressant, dernièrement?",
"Pourrais-tu me donner les dernières nouvelles du coin?",
"Je ne connais pas très bien la ville. Pourrais-tu m'aider?",
"J'ai besoin que tu m'indiques une direction.",
"Pourrais-tu me montrer comment rejoindre...",
"Pourrais-tu me parler de l'un des habitants?",
"Qu'est-ce que tu peux me dire sur les gens du coin?",
"Parle-moi de ta colonie.",
"Qu'est-ce que tu sais sur Douwesen?",
"Je voudrais des renseignements sur Douwesen.",
"Rien. Merci.",
"Tu voulais me demander quelque chose, capitaine?",
"Heureux de te rencontrer. Que puis-je faire pour toi, ",
"?",
"Alors, capitaine... Que puis-je faire pour toi?",
"Quoi de neuf par ici?",
"Y a-t-il eu des événements notables, ces derniers temps?",
"Je voudrais juste connaître les dernières rumeurs.",
"Pourrais-tu m'indiquer comment rejoindre...",
"Je sais où je dois aller, mais je ne sais pas comment m'y rendre.",
"J'ai besoin d'aide pour me déplacer dans la ville.",
"L'un des habitants du coin m'intéresse.",
"Je cherche quelqu'un. Tu le connais peut-être?",
"Pourrais-tu me parler de l'un des habitants du coin?",
"Parle-moi de la colonie.",
"Que sais-tu sur Douwesen?",
"Je voudrais te poser des questions sur Douwesen.",
"Je ne fais que flâner. Au revoir.",
"Je vois. Laisse-moi te poser une autre question.",
"Merci. Au revoir.",
"J'écoute, ",
".",
"Oui, ",
"?",
"Tu aimes discuter, hein, ",
". Alors, vas-y, pose tes questions.",
"Quoi de neuf par ici?",
"Y a-t-il eu des événements notables, ces derniers temps?",
"Pourrais-tu me raconter les dernières nouvelles du coin?",
"Je ne connais pas très bien la ville. Pourrais-tu m'aider?",
"J'ai besoin que tu m'indiques une direction.",
"Pourrais-tu me montrer comment aller à...",
"Pourrais-tu me parler de l'un des habitants du coin?",
"L'un des habitants m'intéresse. Tu le connais peut-être.",
"Parle-moi des gens du coin.",
"Parle-moi de ta colonie.",
"Qu'est-ce que tu sais sur Douwesen?",
"Laisse-moi te poser une question sur Douwesen.",
"Laisse tomber. Au revoir.",
"De qui veux-tu parler, ",
"?",
"Alors, sur qui veux-tu des renseignements?",
"Je me demande qui a bien pu attirer ton attention sur Douwesen, capitaine ",
"?",
"Le gouverneur, ",
"Reynard Grueneveldt",
"Reynard Grueneveldt",
".",
"L'aubergiste, ",
"Friedrich Corleis",
"Friedrich Corleis",
".",
"Le propriétaire du chantier naval, ",
"Lambrecht Fobes",
"Lambrecht Fobes",
".",
"Un commerçant du nom de ",
"Gheerlof Darlang",
"Gheerlof Darlang",
".",
"Laisse tomber. Désolé de t'avoir dérangé.",
"Hélas! Même si, au fond, notre gouverneur est un homme bon, il manque de volonté. Un gouverneur plus énergique ferait de notre colonie un endroit plus sûr et nos commerçants traiteraient leurs affaires dans des conditions plus rentables. En plus, notre fort a besoin d'être réparé.",
"Je vois. J'ai une autre question, si ça ne t'ennuie pas.",
"Merci. Au revoir.",
"Que puis-je dire à son sujet? C'est un petit lâche pas très malin. En plus, il est très gourmand! Mais il est toujours au courant de tout.",
"Je vois. J'ai une autre question, si ça ne t'ennuie pas.",
"Merci. Au revoir.",
"C'est un homme bon, mais on dit qu'il est trop dur. On dit aussi qu'il change souvent d'ouvriers. Mais il connaît ses navires à fond.",
"Je vois. J'ai une autre question, si ça ne t'ennuie pas.",
"Merci. Au revoir.",
"Dis-moi simplement où tu dois te rendre, ",
".",
"D'accord, ",
". Où veux-tu aller?",
"Je serai content de t'aider, ",
".",
"Où est la taverne?",
"Où est le chantier naval?",
"Où puis-je vendre mes marchandises?",
"Des deux rues qui partent de la porte du port, prends celle de droite et tu ne tarderas pas à voir la taverne.",
"Merci. Au revoir.",
"Et où est le chantier naval?",
"Où puis-je vendre mes marchandises?",
"Le bureau du chantier naval est juste devant la porte du port, ",
". Tu ne peux pas le manquer.",
"Merci. Et comment trouver la taverne?",
"Où puis-je vendre mes marchandises?",
"Merci pour ce conseil. C'est tout ce dont j'ai besoin.",
"Prends à droite à partir de la porte du port. Tu ne peux pas la manquer. ",
"Gheerlof Darlang",
"Gheerlof Darlang",
"Le magasin de  est près de la taverne.",
"Où puis-je trouver le chantier naval?",
"Comment trouver la taverne?",
"Je vois. Merci.",
"Eh bien, je ne sais pas... Qu'est-ce que tu veux savoir?",
"Qu'est-ce qui t'intéresse, capitaine?",
"Qu'aimerais-tu savoir, ",
"?",
"Parle-moi de l'histoire de la colonie.",
"Y a-t-il d'autres villes sur cette île?",
"Est-ce que tu sais quelque chose sur le fort qui protège la ville?",
"Laisse-moi te poser une autre question.",
"Tu as fait tout ce chemin pour apprendre l'histoire locale? Bon, d'accord. La colonie a été fondée il y a 54 ans.\nOn a trouvé de riches gisements sur l'île et la ville s'est progressivement développée. On s'en sort très bien aujourd'hui.",
"Je t'en prie, continue.",
"En effet. Laisse-moi te poser une autre question.",
"Ça n'a jamais été un coin très paisible par ici. Cette terre a eu plus que son compte de batailles.",
"Je vois. Puis-je te poser une autre question?",
"J'ai entendu des rumeurs selon lesquelles un aristocrate aurait acheté une maison dans la jungle, or personne n'a jamais vu ni la maison ni l'aristocrate.",
"Continue.",
"Toute l'île est couverte d'une jungle épaisse. Les rivages sont rocheux et les récifs nombreux. Notre port est situé dans la seule baie convenable de l'île.",
"Je vois. Continue.",
"Il n'y pas grand chose à ajouter. De la jungle et des rochers - comme toutes les autres îles. Tout ce qui a de la valeur se trouve dans l'enceinte de cette ville.",
"Continue...",
"Je vois. Laisse-moi te poser une autre question, si je puis me permettre.",
"Pour être franc, capitaine, je ne sais rien sur le fort.",
"Eh bien, laisse-moi te poser une autre question, si ça ne t'ennuie pas.",
"Notre fort a été construit à une époque plus prospère et ils ont vraiment fait du bon travail. Il reste un magnifique bâtiment, même s'il a traversé bien des épreuves. La garnison est elle aussi impressionnante... environ 1 500 hommes.",
"Je vois. Continue.",
"Je ne suis pas sûr que l'on puisse parler du fort. Et si tu étais un pirate envisageant de l'attaquer?",
"D'accord. Alors, laisse-moi te poser une autre question.",
"Je vois. Alors, essayons un autre sujet de conversation.",

};