string DLG_TEXT[27] = {       
"Tu ne vois pas que je suis de garde? Ne me dérange pas!",
"D'accord, d'accord!",
"Tu viens signaler un crime?",
"Bien sûr que non. Je suis capitaine, après tout... mais je vois bien que tu n'écoutes pas.",
"N'oublie pas qu'il est interdit de se battre dans les rues. Mais tu peux bien sûr te défendre si on t'attaque.",
"Très bien, je n'oublierai pas.",
"Ce temps est vraiment insupportable! Quand je pense que je dois rester planté là! Tu ne me croiras sans doute pas, mais mon unique passe-temps consiste à chasser les mouches qui cherchent à se poser sur mon visage.",
"C'est regrettable, mais je ne peux rien pour toi. Tu ne fais que ton devoir.",
"Si tu veux discuter, trouve quelqu'un d'autre. J'ai une tâche à remplir, et elle ne consiste pas à te parler.",
"Je me demandais juste si tu étais vivant... Tu restes planté là comme une statue.",
"Tu crois qu'il est facile de protéger notre ville? Pas du tout! C'est un travail très important et extrêmement dangereux. Un jour, je me souviens...",
"Tu m'en parleras une autre fois. Il faut que j'y aille.",
"Va-t-en et cesse de m'importuner.",
"Comme tu veux, soldat.",
"Eh! Tu veux bien aller me chercher un godet de rhum à la taverne?",
"Si je le fais, je me retrouverai pendu pour avoir transformé un soldat en ivrogne. Attends plutôt la relève et tu pourras boire autant que tu voudras.",
"Pourquoi faut-il que ce soit un marin aussi moche que toi qui veuille me parler? Il n'y a pas de jolies filles, ici?",
"C'est ça que tu appelles faire ton devoir? Tu ne voudrais quand même pas rater l'occasion d'arrêter un dangereux criminel tel que moi, si? Ha, ha, ha!",
"Tu m'as l'air en bonne santé. Tu ne veux pas t'engager? Il y a de la place dans la caserne, la pitance est bonne, et on ne paie pas notre rhum.",
"C'est vrai que c'est une offre alléchante, mais il me faut la refuser. La discipline et moi, ça fait deux.",
"Cette chaleur! Je donnerais tout pour revoir ma Hollande bien-aimée.",
"On dirait que le climat ne te convient pas, en effet.",
"Espèce de... hic... gredin! Tu as fait du mal à mon... hic... ami!",
"Quel ami? Tu es tout seul, ",
".",
"Hein? Mais... il était là, tout à l'heure. Je vais le chercher. Toi... hic... attends ici, et je te mettrai une sacrée rouste à mon... hic... retour....",
"Comment oses-tu me contredire? Je vais t'étrangler!",

};