string DLG_TEXT[25] = {
"Ne reste pas là, voyons! Entre, entre!",
"...",
"Où crois-tu aller comme ça, marin d'eau douce? Fais demi-tour tout de suite. Les types comme toi n'ont rien à faire ici.",
"Je suis venu parler à ",
"Alistair Garcilaso",
"Alistair Garcilaso",
".",
"Un instant. Ne serais-tu pas ",
", dont le seul nom fait trembler les marchands à la panse rebondie?",
"Il se trouve que si. Pourquoi?",
"Attends! Personne n'embauche, chez vous?",
"A l'heure actuelle, le vieil ",
"Anacleto Rui Sa Pinto",
" est le seul qui cherche des hommes, mais il faut avoir perdu la tête pour vouloir travailler pour ce fou. Tente ta chance avec lui si ça te chante, mais je t'aurai prévenu.",
"Où puis-je trouver cet ",
"Anacleto Rui Sa Pinto",
"?",
"Sûrement à la taverne. C'est du rhum, pas du sang, qui coule dans ses veines.",
"Merci. Je vais me mettre à sa recherche.",
"Oh, toutes mes excuses. Mets-toi à ton aise.",
"Ne t'inquiète pas, c'est bien ce que je compte faire.",
"Je regrette, mais je ne me souviens pas l'avoir entendu dire qu'il attendait un coquin aux manières déplorables. Dehors!",
"Je vais aller lui demander personnellement s'il veut me parler. Et tu vas me laisser faire.",
"C'est ce que nous allons voir, maraud!",
"Oh, que oui!",

};