string DLG_TEXT[89] = {
"Il ne me semble pas t'avoir déjà vu par ici.",
"C'est exact. C'est la première fois que je viens ici. Je m'appelle ",
".",
"Pourquoi? Tu te souviens de la tête et du nom de tout le monde?",
"Je suis ",
", propriétaire de cette taverne.",
"Heureux de te rencontrer, ",
". Qu'as-tu à offrir, en dehors de la bière et d'une oreille attentive?",
"Du calme, je ne cherche pas les ennuis. Je m'appelle ",
" et je viens parler affaires avec toi.",
"Très bien, je t'écoute.",
"Je suis à la recherche d'un équipage. Peut-être sauras-tu me dire qui cherche un bateau...",
"Il me manque des hommes depuis mon dernier voyage. Indique-moi quides clients de ta taverne qui pourraient me servir de chair à canon et je m'en vais.",
"J'aurais besoin de renseignements, si tu as quelques instants à m'accorder.",
"Aurais-tu une paillasse qu'il ne me faudrait pas partager avec un nid d'insectes?",
"Je cherche une chambre avec un lit. Propre, le lit. La chambre aussi, d'ailleurs.",
"Je regrette, mais je n'ai pas le temps de bavarder. Salut.",
"Ça dépend de ce que tu veux dire, ",
".",
"Je me suis laissé dire que ",
"Raoul Rheims",
" était arrivé en ville il y a peu.",
"Je suis à la recherche d'un certain ",
"Raoul Rheims",
"Raoul Rheims",
". Sais-tu s'il se trouve sur l'île?",
"Je cherche ",
"Ferro Cerezo",
"Ferro Cerezo",
". Peut-être pourras-tu m'indiquer où le trouver...",
"Je recherche un homme qui est venu sur cette île il n'y a pas longtemps. Il s'agit d'un Italien assez âgé. Ça te dit quelque chose?",
"Je m'intéresse à un certain Artois Voysey, un homme grand aux cheveux noirs. Tu ne l'aurais pas vu dans le coin?",
"Je cherche du travail. Tu ne connaîtrais pas un richard qui aurait peur de voyager seul, dans le coin?",
"Parlons plutôt d'autre chose...",
"Je l'ai vu, en effet, mais ça m'étonnerait que ça te fasse plaisir.\nCe gamin est entré accompagné d'un gredin et, moins de cinq minutes plus tard, deux individus masqués sont arrivés à leur tour.\nIls ont emmené ton Artois avec eux, après avoir gravement blessé son ami. Ce dernier se trouve actuellement dans une des chambres, à l'étage.",
"Malédiction! Il faut que je le voie! Peut-être pourra-t-il me dire qui étaient leurs agresseurs...",
"Que je réfléchisse... oui, bien sûr! Le senor ",
"Vito Leone",
" correspond parfaitement à cette description. Il est venu ici la semaine dernière et m'a loué une chambre. Il a dit que quelqu'un viendrait le chercher et que je devais dire qu'il attend à l'église.",
"Merci.",
"Si je ne m'abuse, c'est le nom de l'homme assis à la table située près de la fenêtre.",
"Merci. Je vais aller le voir.",
"Pas si fort! Les murs ont des oreilles, l'ami!",
"Et alors? Je n'ai de secrets pour personne.",
"Fais un peu attention! On dit qu'il travaille pour ",
"Camilo Machado",
"Camilo Machado",
" en personne, lequel n'est autre que le chef des contrebandiers locaux. Je ne veux pas d'ennuis avec lui. Ce serait mauvais pour les affaires.",
"Oui, ",
"Raoul Rheims",
" est en effet sur l'île. Tu le trouveras en compagnie de ",
"Camilo Machado",
"? Où puis-je le trouver?",
"C'est la première fois que j'en entends parler. Tu fais peut-être erreur...",
"Je sais sans le moindre doute possible qu'il est arrivé depuis plusieurs jours. Il devait rencontrer ",
"Camilo Machado",
"Camilo Machado",
".",
"Silence! Si tu tiens à la vie, ne prononce plus jamais ce nom à voix haute! Tu as vu l'homme qui vient de quitter la taverne? Pars tout de suite ou le ciel va me tomber sur la tête!",
"Reprends-toi, mon vieux, tu trembles comme une feuille. Et tu ne sais rien d'utile, pas vrai? Bah. Au revoir.",
"Détends-toi, je vois bien que tu ne pourras pas m'être utile. Au revoir.",
"Je regrette, mais il se fait tard et tout le monde a trouvé un endroit où passer la nuit. Reviens demain matin... à moins que tu ne préfères passer la nuit ici.",
"Peut-être que c'est ce que je vais faire. Il te reste une chambre?",
"Il est possible que je le fasse. Mais avant, j'aurais quelques questions à te poser...",
"Il se trouve que oui. Tu comptes rester jusqu'à quand?",
"Demain matin.",
"Jusqu'à la tombée de la nuit seulement.",
"Il t'en coûtera 5 pièces d'or.",
"Très bien, voilà ton argent.",
"Hélas, on dirait que je n'ai pas les moyens de me l'offrir. Tant pis, je vais dormir dans la salle de la taverne.",
"Combien? Et j'ai droit à un panier de fruits, en guise de bienvenue? Merci, mais je préfère dormir dans la salle de la taverne.",
"Je vais y réfléchir. En attendant, j'aurais besoin d'autres renseignements...",
"Il t'en coûtera 5 pièces d'or.",
"Voilà ton argent.",
"Hélas, je n'ai pas envie de dépenser une telle somme pour ça. Je dormirai dans la salle de la taverne.",
"C'est pour la suite nuptiale, ou quoi? Non merci. Je dormirai dans la salle de la taverne.",
"Je vais y réfléchir.",
"C'est un établissement respectable, ici! Arrête tout de suite ou j'appelle les gardes!",
"Très bien, très bien, je m'en vais.",
"Si cet homme existe, il ne désire sans doute pas attirer l'attention... comme tu devrais normalement le savoir...",
"C'est vrai, j'avais oublié. Très bien, je reviendrai plus tard, quand j'aurai moins de bateaux. Ha, ha, ha!",
"Je ne tiens pas à t'aider alors que tu as fait tant de mal à mon pays.",
"Très bien. Au revoir.",
"Tu as beaucoup de sang sur les mains. Crois-tu sérieusement que quelqu'un acceptera de t'accompagner?",
"Tu as raison, tout le monde a peur de moi! Ha, ha, ha!",
"Tu arrives à point nommé. Un marchand cherche justement quelqu'un pour l'accompagner. Tu devrais aller lui parler. Tiens, le voilà qui entre dans la taverne.",
"C'est ce que je vais faire.",
"Non, personne, pour le moment. La prochaine fois, peut-être...",
"Mmh... Dans ce cas, j'attendrai.",

};