string DLG_TEXT[47] = {
"Ne me dérange pas pendant que je travaille!.",
"...",
"Tu as des ordres pour moi, capitaine?",
"Non, pas encore.",
"Un nouveau prisonnier? Hé, hé, hé...",
"Qu'est-ce qui te rend si joyeux?",
"Voici ton arme. Pour sortir d'ici, il va te falloir tuer tous les soldats de garde. Il doit y en avoir deux ou trois.",
"Merci mille fois. Je te retrouve au port.",
"Merci pour cette épée... mais je suis très rancunier. Tu te rappelles m'avoir menacé de marcher avec des béquilles jusqu'à la fin de mes jours? Eh bien, j'ai l'impression qu'elles vont être pour toi, les béquilles.",
"De quoi as-tu besoin?",
"Tu dis avoir été canonnier dans le passé. J'aimerais que tu travailles pour moi.",
"Je suis heureux que tu aies réussi à te libérer, capitaine. Notre accord tient toujours?",
"Oui. Combien veux-tu pour tes services?",
"Non. Je n'ai pas besoin de tes services.",
"Moi? C'est une plaisanterie, capitaine?",
"Ai-je une tête à plaisanter? Combien monnaies-tu tes services?",
"Pour seulement 1 500 pièces d'or, je suis à ton service, capitaine.",
"Très bien, je t'engage. Bienvenue dans mon équipage.",
"Je ne crois pas que cela vaille autant. Au revoir.",
"Tu ne comprends pas? A chaque nouveau prisonnier, le gouverneur nous donne une rallonge pour le nourrir... et j'en prélève une partie. Hé, hé, hé...",
"Comment en es-tu arrivé à mener une telle vie?",
"Un prisonnier qui souhaite discuter? D'accord, allons-y. Mais je doute que tu veuilles longtemps parler. Bientôt, tu resteras sur ton lit, le regard rivé au plafond, comme les autres. Des prisonniers, j'en ai vu des tas.",
"Tu n'as pas répondu à ma question.",
"C'est une longue histoire... mais tu as du temps à perdre, alors, je peux bien te la raconter, après tout...",
"Tu as raison. J'ai largement le temps, alors, dis-moi tout...",
"Ne m'interromps pas ou je vais t'apprendre la politesse... et tu passeras le reste de ta vie à marcher avec des béquilles.",
"Surveille ta langue! Ce n'est pas parce que je suis enfermé dans cette cellule que je dois supporter les insultes d'un misérable geôlier!",
"C'est moi que tu traites de misérable geôlier? Pour ta gouverne, j'étais autrefois le meilleur canonnier de ce maudit archipel!",
"Et tu penses vraiment que je vais le croire? Qui se débarrasserait d'un canonnier de première classe, hein?",
"Moi non plus, je ne pensais pas que ça pouvait m'arriver. Toute cette malchance à cause de ce maudit rhum! On m'a chassé comme un malpropre, et sans me régler mes six derniers mois de travail, encore!",
"Aide-moi à sortir d'ici et je t'engage comme canonnier. Je t'interdis de toucher à l'alcool tant que tu seras à bord, mais tu pourras boire tout ton saoul quand nous serons à terre.",
"Repartir en mer? Bon sang, ne me torture pas comme ça, capitaine!",
"Je suis sérieux. Ouvre cette porte, rends-moi mon arme et je te retrouve au port, à côté de mon bateau, '",
"'.",
"Ça ne me plaît pas. Pourquoi risquer ma vie bêtement? Rassieds-toi et laisse-moi vaquer à mes affaires.",
"Attends!",
"Ça marche, capitaine, mais tu n'as pas intérêt à te moquer de moi...",
"Ne t'inquiète pas, je suis un homme de parole.",
"...",
"Encore saoul, Attwood?",
"Je croyais qu'on avait un accord, capitaine. Ce que je fais à terre ne regarde que moi. Ne t'en fais pas, je ne bois jamais à bord.",
"Et tu t'es encore retrouvé mêlé à une rixe...",
"C'était pas une rixe, mais une affaire d'honneur, capitaine! Ce type m'a traité de fils de chacal et de marin d'eau douce!",
"Tes excuses ne m'intéressent pas! Retourne à bord du bateau!",
"Une affaire d'honneur? Nul n'a le droit d'insulter mes officiers. En garde, scélérat!",
"Je croyais que tu étais un type bien, capitaine...",
"...",

};