string DLG_TEXT[37] = {
"Merci de ton aide, ",
".",
"De rien. Le fait de voir que tu as retrouvé ta vie d'antan est la plus belle des récompenses. Bonne chance!",
"Qui es-tu et que fais-tu chez moi? Va-t-en tout de suite!",
"Pardon pour cette intrusion. Je m'en vais.",
"Qui es-tu et que fais-tu chez moi?",
"C'est le prêtre qui m'a demandé de venir.",
"Merci de ce que tu as fait pour moi, ",
".",
"Le fait de voir que tu as retrouvé ta vie d'antan est la plus belle des récompenses. Bonne chance!",
"Qui es-tu et que fais-tu chez moi? Va-t-en tout de suite!",
"Pardon pour cette intrusion. Je m'en vais.",
"Pourquoi? Cet hypocrite s'est-il enfin résolu à ne jamais me voir à l'église?",
"J'imagine que oui. Il ne croit plus pouvoir te faire changer d'avis. Selon lui, tu as la tête trop dure.",
"La tête dure? Ça, non!",
"Que dois-je lui dire, alors? Que tu refuses de revenir vers Dieu?",
"Je n'ai jamais quitté Dieu, c'est lui qui m'a abandonnée. Où était-il quand les Anglais ont tué mon mari après avoir attaqué son bateau?",
"Toutes mes condoléances. J'imagine que cela doit être très dur, mais...",
"Et où était-il quand mon fils a été renversé par un chariot? Il n'a même pas cinq ans et le voilà paralysé!",
"Je ne peux répondre à cette question, sinon en disant que d'aucuns pensent que les coups du sort sont justement là pour mettre notre foi à l'épreuve...",
"Et où était Dieu quand je cherchais désespérément un travail afin de payer les soins de mon fils? Où était-il, hein?",
"Je vois bien que rien de ce que je pourrai dire ne te fera changer d'avis. Au revoir.",
"Peut-être que Dieu m'envoie t'aider.",
"M'aider? Et comment? Pourras-tu me rendre mon mari, ou refaire marcher mon fils?",
"Non, car je ne suis pas Dieu. Mais cela ne signifie pas que je suis incapable de t'aider.",
"J'ai eu plus que mon lot de belles paroles! Elles me rendent malade! Tu es comme ce prêtre : tu débites de belles paroles, mais rien ne change jamais.",
"Tu sais, je crois que tu as raison. Je perds mon temps, ici. Au revoir.",
"Si seulement tu m'écoutais quelques instants. Laisse-moi t'exp...",
"Personne ne peut m'aider! Va-t-en!",
"Très bien. On ne peut pas aider les gens qui refusent la main qu'on leur tend.",
"Tu réclames un signe en provenance de Dieu, et pourtant tu refuses de le voir quand il se présente devant toi. Je ne suis pas un ange, mais tu dis avoir besoin d'argent pour soigner ton fils, et cela, je peux te le donner. Si Dieu le veut, ton fils sera guéri.",
"Tu dis avoir besoin d'argent pour soigner ton fils. Je ne l'ai pas encore, mais je le trouverai et je te l'amènerai. C'est le seul miracle que je peux te promettre.",
"Je t'en prie, ne te joue pas de moi, car cela ne fait que rendre la situation plus insupportable. Nul ne donnerait autant d'argent à une étrangère sur la maudite terre où nous vivons.",
"C'est un plaisir pour moi de te montrer que tu te trompes. Tiens, voici 1 000 pièces d'or. Cela devrait suffire pour soigner ton fils.",
"Je comprends, tu as perdu foi en l'homme et en Dieu. Je ne perdrai pas mon temps à te montrer que tu te trompes. Au revoir.",
"Tu me donnerais tout cet argent sans rien demander en retour?",
"Je ne te demande qu'une seule chose : si la foi t'a apporté quelque consolation par le passé, j'espère que tu retrouveras confiance, sinon en Dieu, du moins en l'homme. Au revoir.",

};