string DLG_TEXT[52] = {
"Bienvenue dans ma boutique, ",
". Je m'appelle ",
".",
"C'est un plaisir de faire ta connaissance. Je suis ",
", capitaine libre de son destin.",
"Je me nomme ",
" et je suis capitaine d'un beau bateau qui m'appartient également.",
"Bienvenue dans ma boutique, ",
".",
"Merci de ton accueil, mais je suis là pour parler affaires avec toi.",
"Vous dites tous la même chose, vous autres marchands : bienvenue, capitaine! Bienvenidos! Wellcome! Willkommen! Vous allez tous à la même école, ou quoi? J'aimerais parler affaires pendant que tu te creuses la cervelle pour trouver une réponse originale.",
"Bien sûr, bien sûr! Que puis-je pour toi?",
"Montre-moi ce que tu as en stock.",
"Montre-moi ce que tu as à vendre.",
"Je suis à la recherche d'informations...",
"Les informations m'intéressent plus que les achats.",
"Je regrette, mais je dois m'en aller.",
"Notre petite discussion était fort agréable, mais j'ai à faire ailleurs.",
"As-tu quelque marchandise à vendre ou viens-tu acheter les miennes?",
"Je souhaiterais te vendre ma cargaison.",
"J'aurais quelques petites choses à t'acheter.",
"Je ne tiens pas à faire affaire avec toi. Au revoir.",
"Certainement. Que cherches-tu au juste?",
"Je t'écoute.",
"On m'a demandé de te livrer une cargaison.",
"Tu dois bien avoir besoin que quelqu'un travaille pour toi, non? Je le ferai avec plaisir en échange d'espèces sonnantes et trébuchantes.",
"On m'a chargé de te livrer une cargaison de chocolat...",
"Je ne peux pas te parler pour le moment.",
"Déjà? Je ne manquerai pas de faire appel à toi à l'avenir!",
"Merci.",
"Vraiment? Et tu n'aurais pas pu prendre un peu plus ton temps? Quelques années de plus, par exemple. Tu sais ce que tu peux en faire, de ton chocolat? J'en ai déjà acheté une autre cargaison.",
"Bon sang!",
"Non, je n'ai pas besoin de tes services... du moins, pas tant que tu couleras des bateaux espagnols.",
"Dans ce cas, au revoir.",
"Je regrette, mais je n'ai rien pour toi à l'heure actuelle.",
"Dans ce cas, je reviendrai plus tard.",
"Je regrette, mais le tonnage de ton bateau n'est pas assez important pour que je te confie la tâche à laquelle je pense.",
"Dans ce cas, je reviendrai plus tard.",
"Oh! J'allais justement te demander si tu ne pouvais pas me rendre service. J'ai une cargaison à livrer à ",
", et dans les plus brefs délais. Si tu y arrives en moins d'un mois, tu recevras ",
" pièces d'or à la livraison. Qu'en dis-tu?",
"Ça me va.",
"Je ne peux pas accepter.",
"Je t'ai déjà dit que je n'avais rien à te proposer.",
"Oh, pardon.",
"Tu t'es rappelé ta mission un peu tard, non? J'ai déjà reçu tout ce dont j'avais besoin. Au revoir.",
"Au revoir.",
"Oh! Cela faisait tellement longtemps que j'attendais cette cargaison! Tiens, voilà pour toi.",
"Ç'a été un plaisir.",
"Je regrette, mais je n'ai rien à te proposer pour le moment.",
"C'est bien dommage, mais peut-être que tu accepteras de répondre à mes questions?",
"Dommage? Tu accepterais au moins de répondre à mes questions?",

};