string DLG_TEXT[38] = {       
"Tu n'aurais pas besoin d'un officier, capitaine?",
"Un officier? Qu'est-ce que tu sais faire?",
"Non, j'en ai suffisamment pour le moment.",
"Eh bien, on dit de moi que je suis un bon ",
". Engage-moi et tu verras par toi-même, capitaine.",
"Combien demandes-tu?",
"Hélas, j'ai déjà un ",
".",
"As-tu changé d'avis, capitaine? Tu as compris qu'il te serait utile d'engager un ",
"?",
"Peut-être, oui. Combien demandes-tu?",
"Non, tu te trompes. Au revoir.",
"Nous devrions pouvoir nous entendre sur la somme de ",
" pièces d'or.",
"Ce n'est pas trop pour toi?",
"C'est d'accord. Considère-toi comme recruté.",
"Tu ne vaux pas tant. Au revoir.",
"Très bien. Dans ce cas, je peux accepter ",
" pièces d'or. Qu'en dis-tu?",
"C'est mieux. Bienvenue dans mon équipage.",
"C'est toujours trop. Au revoir.",
"Hélas, capitaine, je suis persuadé de valoir ce que je demande. Si c'est au-dessus de tes moyens, trouve-toi quelqu'un qui te demandera moins.",
"Eh bien... tu es engagé.",
"C'est bien ce que je compte faire. Au revoir.",
"Merci, capitaine. Tu ne regretteras pas ton investissement quand tu m'auras vu à l'œuvre.",
"Souhaitons-le.",
"Eh, on dirait que tu n'as pas assez d'argent. Je regrette, capitaine, mais je ne travaille pas à crédit.",
"Malédiction!",
"Laisse-moi juste finir mon verre, capitaine. Mais je te rassure, je serai à bord avant qu'on ne prenne la mer.",
"D'accord. Mais si je dois t'attendre, je te ferai briquer le pont tout seul!",
"A ton service, capitaine. Quels sont les ordres?",
"Repos, je n'ai rien à te demander.",
"Tu es viré. Je n'ai pas besoin de tes services!",
"C'est toi qui vois, capitaine. Mais si tu me renvoies, je ne retournerai jamais sur ton bateau. À toi de décider.",
"J'ai changé d'avis. J'ai encore besoin de toi.",
"Parfait! Tire-toi!",
"Je t'ai prévenu, capitaine, je ne reviendrai pas. J'ai ma fierté.",
"Et moi, je n'ai pas besoin de toi!",

};