string DLG_TEXT[44] = {
"Arrête! Lâche ton arme! La bourse ou la vie!",
"Eh, voyageur! Arrête-toi et montre-nous le contenu de ta bourse!",
"Eh, toi! Halte! Si tu veux passer, il faut acquitter le péage!",
"Qu'est-ce que c'est que cette ânerie?",
"Qu'est-ce que c'est que ça?",
"Qu'est-ce que ça signifie?",
"Des brigands? Eh bien, le crime doit être puni. Aux armes!",
"Je ne supporte pas les bandits de grand chemin... surtout s'ils puent la crasse. En garde!",
"Je vais t'arracher le cœur pour te faire payer ton impudence!",
"Oh, il n'a pas compris. C'est pourtant simple : remets-nous tout ton or et nous te laissons la vie sauve.",
"Tu n'as jamais entendu parler des frais de voyage? C'est nous, ça. Bon, qu'est-ce que tu préfères perdre? Ton or, ou la tête?",
"Je vais traduire pour le marin stupide que tu es : donne-nous tout ton argent, bonhomme! On adore les doublons et les pièces de huit!",
"Scélérats! Je n'ai que ",
" pièces d'or sur moi.",
"Je ne vous abandonnerai pas mon or sans combattre!",
"Eh, pas la peine de s'énerver pour si peu! Je plaisantais, c'est tout.",
"Dans ce cas, nous avons changé d'avis. Tu peux partir.",
"Nous allons te laisser partir, car tu es courageux. Mais qu'on ne t'attrape plus!",
"Dans ce cas, salut.",
"Vous devriez changer de métier, car vous êtes nuls, comme bandits de grand chemin. Au revoir.",
"C'est une sage décision. Au revoir.",
"Trop tard pour reculer, maintenant. Tu as rendez-vous avec le Créateur!",
"Alors, on a la frousse? Mais je ne peux pas te laisser t'en sortir, maintenant...",
"Je n'irai nulle part tant que cette affaire ne sera pas réglée.",
"Très bien. Tu as eu ta chance, mais tu vas mourir!",
"Là, tu as réussi à me mettre en rogne. Meurs!",
"Quoi? Je vais faire un collier de tes boyaux!",
"Essaie, pour voir!",
"Très bien. Donne-moi tout et tu pourras partir.",
"Pour cette fois, ça suffira pour acheter ta vie. Allez, file.",
"Un petit conseil : si tu te laisses marcher dessus par tout le monde, tu ne devrais pas t'aventurer dans la jungle. Reste plutôt au port, à boire ton rhum. Tu vivras plus vieux.",
"Soyez tous maudits!",
"Tu m'as l'air plus riche que ça, mais ce n'est pas grave. Quand on en aura fini avec toi, on te secouera par les pieds pour voir ce qui tombe de tes poches.",
"Malédiction!",
"Encore toi? Tu devrais courir comme si tu avais le diable aux fesses, des fois qu'il nous prenne l'envie de changer d'avis à ton sujet.",
"Tu reviens nous apporter de l'or? Comme c'est gentil à toi!",
"Je ne le répéterai pas : hors de ma vue ou je te tue!",
"Oui, oui, je m'en vais...",
"Je ne tiens pas à ce que vous me causiez davantage d'ennuis, alors, j'ai décidé de me débarrasser de vous.",
"Qu'est-ce que tu nous veux? On t'a laissé partir!",
"Laisse-nous tranquille, petit. Tu as tes affaires et nous les nôtres. Chacun chez soi.",
"Tire-toi, petit! Tu veux vraiment nous donner ton argent?",
"D'accord, je m'en vais.",
"J'ai décidé de vous châtier, mécréants que vous êtes!",

};