string DLG_TEXT[232] = {      
"Bonjour, étranger. J'ai un humble conseil pour toi.",
"Avec grand plaisir.",
"Je n'ai pas besoin de conseils.",
"Bonjour, voyageur. Où te rends-tu?",
"Oh, m'occuper de mes affaires.",
"Ça ne te regarde pas.",
"Bonjour, étranger. Comment ça va?",
"Bien, merci.",
"Je n'ai pas le temps de te parler.",
"Bonjour. C'est la première fois que je te vois par ici. Tu es de la ville?",
"Oui, je viens tout juste d'arriver.",
"Je n'ai pas le temps de te parler.",
"Bonjour, étranger. C'est un plaisir de te voir ici.",
"Bonjour.",
"Excuse-moi, mais je n'ai pas le temps de parler avec toi pour le moment.",
"Bonjour, marin. Souhaites-tu entendre un bon conseil?",
"Bonjour. Je t'écoute.",
"Je n'ai pas de temps à perdre.",
"Bonjour, étranger. J'ai des marchandises qui pourraient t'intéresser.",
"Dans ce cas, faisons affaire.",
"Je n'ai pas le temps de te parler.",
"Bonjour, étranger. Tu as l'air fatigué. Je peux te proposer un remède magique soignant toutes les maladies. Il est à toi pour 200 pièces d'or seulement, mais décide-toi vite, car cette offre ne durera pas!",
"Donne-moi ton breuvage.",
"Je n'ai jamais cru aux potions magiques.",
"Bonjour, marin. J'ai des soucis d'argent, ces temps-ci. Pourrais-tu m'aider?",
"Et pourquoi?",
"C'est ton problème.",
"Accepterais-tu de donner quelques pièces à un pauvre malade?",
"Bien sûr. L'Eglise nous enseigne à aider notre prochain.",
"Du balai, mendiant, et ne viens plus m'importuner!",
"Ne me laisse pas dans un tel état de pauvreté! Jette-moi une petite pièce, je t'en prie, que je puisse m'acheter à manger.",
"Tiens, voilà 10 pièces d'or pour toi.",
"Va-t-en et ne me demande plus rien, mendiant.",
"Bonjour. À l'assurance que tu affiches, je parie que tu dois souvent combattre.",
"Oui, c'est le cas.",
"Ça ne regarde que moi. Au revoir.",
"Bonjour. Il est rare de rencontrer des gens aussi respectables, par ici. Tu es capitaine, j'imagine?",
"Oui. Que puis-je pour toi?",
"Je suis très pressé, tu sais. Au revoir.",
"Bonjour. Tu n'es pas trop occupé pour me parler?",
"Non. Ce sera un plaisir de discuter avec toi.",
"Si, je suis occupé.",
"Écoute, étranger, ne sors pas par ici à la nuit tombée. On dit que les morts se promènent la nuit...",
"Merci du conseil.",
"Je te conseille de ne pas te promener par ici si tu as eu des ennuis avec la loi. Il y a beaucoup de soldats, dans le coin. Il vaudrait peut-être mieux que tu quittes l'île.",
"Voilà qui est très intéressant...",
"Ce genre de conseil ne m'intéresse pas. Au revoir.",
"Sache-le, quand tu reviendras par ici, tu ne seras peut-être pas le bienvenu.",
"Très bien, je m'en souviendrai.",
"Si tu es malade, je connais un excellent moyen de se guérir. Il suffit d'acheter une bouteille de remède au marchand de la ville.",
"Et à part ça?",
"Je n'ai pas le temps de te parler.",
"Te reposer un moment dans un lit de la taverne te permettra également d'aller mieux.",
"Merci.",
"Tu sais, quand j'ai besoin de renseignements sur les derniers événements, je vais voir un tavernier. Ces types-là ont les réponses à toutes les questions, ou peu s'en faut.",
"Excellent conseil! Je vais le suivre.",
"Je vois que tu es un capitaine habitué au combat. N'oublie pas d'engager davantage d'officiers. Il est parfois difficile de survivre sans eux.",
"Oui, bien sûr.",
"Je vois à ta démarche que tu es un capitaine. Si tu as besoin d'un navire, va l'acheter à notre chantier naval. Si tu n'y trouves pas le modèle que tu recherches, attends un ou deux jours, et peut-être qu'il sera là.",
"C'est un très bon conseil. Merci.",
"Tu rencontreras parfois des gens qui ont fait le tour du monde. N'hésite pas à les questionner, cela te permettra d'accroître tes connaissances. Et je suis bien placé pour te dire que cela n'a pas de prix.",
"Utile, comme conseil. Merci.",
"Si tu me donnes 20 pièces d'or, je ferai part de ta bonté à tout le monde. Je suis pauvre, c'est vrai, mais ne t'arrête pas à ça. J'ai de nombreux amis et ils seront tous heureux de te voir.",
"Que je gaspille de l'argent pour qu'un mendiant parle de moi? Merci bien!",
"C'est vrai? D'accord. Après tout, 20 pièces d'or, ce n'est pas grand-chose, et tu en as bien besoin.",
"Je te remercie de ton geste. Tiens, bois ce remède ; il te soignera.",
"Merci à toi aussi.",
"Merci. Je ne possède pas grand-chose pour te prouver ma gratitude, mais prends au moins ceci. Peut-être en auras-tu l'usage...",
"Avec plaisir.",
"Merci, mon brave.",
"De rien.",
"Veux-tu de moi à bord de ton navire, capitaine? Cela fait si longtemps que je rêve de longs voyages et de batailles en mer...",
"D'accord. Je t'engage comme officier.",
"Non, je n'ai pas besoin de marins débutants.",
"Paie-moi et je te montrerai quelques trucs qui te permettront de battre n'importe qui lors d'une bagarre. À moins que tu ne préfères apprendre à te défendre...",
"Je n'ai pas besoin de tes conseils. Je connais le sujet sur le bout des doigts et je pourrais même te donner des cours.",
"Montre-moi comment tu te défends.",
"Je n'ai pas besoin de tes conseils. Je connais le sujet sur le bout des doigts et je pourrais même te donner des cours.",
"Montre-moi comment tu te bats.",
"Merci, mais je n'ai pas besoin d'aide, pour le moment.",
"Il y a quelque temps, j'étais marin, moi aussi... et j'étais même un célèbre aventurier. Je peux t'enseigner comment gérer ton équipage.",
"Je n'ai pas besoin de tes conseils. Je connais le sujet sur le bout des doigts et je pourrais même te donner des cours.",
"J'aimerais que tu m'en dises davantage.",
"Merci, mais je n'ai pas besoin d'aide, pour le moment.",
"Je suis marin, moi aussi... navigateur, pour être précis. En échange de quelques pièces d'or, j'accepte de te révéler les secrets qui te permettront de mieux diriger ton bateau.",
"Je n'ai pas besoin de tes conseils. Je connais le sujet sur le bout des doigts et je pourrais même te donner des cours.",
"J'aimerais en apprendre davantage sur la manoeuvre, en effet.",
"Merci, mais je n'ai pas besoin d'aide, pour le moment.",
"Je suis canonnier sur un vaisseau de guerre anglais. Je peux t'apprendre à calculer la trajectoire de tes boulets afin d'atteindre ta cible à coup sûr.",
"Je n'ai pas besoin de tes conseils. Je connais le sujet sur le bout des doigts et je pourrais même te donner des cours.",
"Dis-le moi et je te verserai la somme que tu réclames.",
"Merci, mais je n'ai pas besoin d'aide, pour le moment.",
"Je suis canonnier sur un vaisseau de guerre anglais. Je peux t'apprendre comment recharger tes canons plus rapidement.",
"Je n'ai pas besoin de tes conseils. Je connais le sujet sur le bout des doigts et je pourrais même te donner des cours.",
"Dis-le moi et je te verserai la somme que tu réclames.",
"Merci, mais je n'ai pas besoin d'aide, pour le moment.",
"Je suis canonnier sur un vaisseau de guerre anglais. Je peux t'apprendre à mieux utiliser les grappins.",
"Je n'ai pas besoin de tes conseils. Je connais le sujet sur le bout des doigts et je pourrais même te donner des cours.",
"Dis-le moi et je te verserai la somme que tu réclames.",
"Merci, mais je n'ai pas besoin d'aide, pour le moment.",
"Je travaille au chantier naval et je sais tout de la construction et de la réparation de bateaux. Si tu me paies, j'apprendrai à ton équipage à réparer ton navire plus rapidement.",
"Je n'ai pas besoin de tes conseils. Je connais le sujet sur le bout des doigts et je pourrais même te donner des cours.",
"Dis-le moi et je te verserai la somme que tu réclames.",
"Merci, mais je n'ai pas besoin d'aide, pour le moment.",
"Je suis un marchand. Je peux te révéler quelques astuces qui t'aideront à augmenter tes bénéfices lors de toutes tes transactions.",
"Je n'ai pas besoin de tes conseils. Je connais le sujet sur le bout des doigts et je pourrais même te donner des cours.",
"Dis-le moi et je te verserai la somme que tu réclames.",
"Merci, mais je n'ai pas besoin d'aide, pour le moment.",
"Alors, acceptes-tu de me verser ce que je demande, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande pour apprendre à te battre, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande pour apprendre à te défendre, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande pour apprendre à mieux gérer ton équipage, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande pour apprendre à mieux manoeuvrer, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande pour apprendre à tirer au canon avec davantage de précision, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande, ",
"?", 
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande pour apprendre à recharger tes canons plus vite, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande pour apprendre à mieux te servir des grappins, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande pour connaître mes secrets de réparation, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Alors, acceptes-tu de me verser ce que je demande pour que je t'apprenne à mieux marchander, ",
"?",
"Je crois bien que je n'ai pas assez d'argent...",
"Oui. Enseigne-moi tes secrets.",
"Non, tu es trop cher.",
"Merci, c'est trop aimable de ta part.",
"De rien.",
"Souhaites-tu m'acheter davantage de remèdes?",
"Oui.",
"Non. Désolé de t'avoir interrompu.",
"Ainsi, tu souhaites faire affaire?",
"Oui, j'aimerais faire d'autres achats.",
"Non. Désolé de t'avoir dérangé.",
"De quoi as-tu besoin? Il me semblait pourtant que nous avions tout évoqué.",
"Rien.",
"Quels sont les ordres, capitaine?",
"Rien.",
"Veux-tu entendre un conseil?",
"Oui, ce que tu as à me dire m'intéresse.",
"Non. Désolé de t'avoir dérangé.",
"Écoute, étranger, ne sors pas par ici à la nuit tombée. On dit que les morts se mettent à marcher dans le noir...",
"Merci du conseil.",
"Je te conseille de ne pas te promener par ici si tu as eu des ennuis avec la loi. Il y a beaucoup de soldats, dans le coin. Il vaudrait peut-être mieux que tu quittes l'île.",
"Voilà qui est très intéressant.",
"Ce genre de conseil ne m'intéresse pas. Au revoir.",
"Sache-le, quand tu reviendras par ici, tu ne seras peut-être pas le bienvenu.",
"Et à part ça?",
"Je n'ai pas le temps de te parler.",
"Tu sais, quand j'ai besoin de renseignements sur les derniers événements, je vais voir un tavernier. Ces types-là ont les réponses à toutes les questions, ou peu s'en faut.",
"Excellent conseil! Je vais le suivre.",
"Je vois que tu es un capitaine habitué au combat. N'oublie pas d'engager davantage d'officiers. Il est parfois difficile de survivre sans eux.",
"Oui, bien sûr.",
"Je vois à ta démarche que tu es un capitaine. Si tu as besoin d'un navire, va l'acheter à notre chantier naval. Si tu n'y trouves pas le modèle que tu recherches, attends un ou deux jours, et peut-être qu'il sera là.",
"C'est un très bon conseil. Merci.",
"Tu rencontreras parfois des gens qui ont fait le tour du monde. N'hésite pas à les questionner, cela te permettra d'accroître tes connaissances. Et je suis bien placé pour te dire que cela n'a pas de prix.",
"Utile, comme conseil. Merci.",

};