string DLG_TEXT[38] = {
"Je peux t'aider, ",
"?",
"Ah, c'est toi, ",
".",
"Je discuterais bien avec toi, mais je n'ai pas le temps. Quand ça marche à la taverne, ce n'est pas le moment de bavarder!",
"...",
"Oh, capitaine, je t'en prie, ne commence pas à tout saccager! Tu ne peux pas imaginer le travail que ça représente de tout nettoyer après!",
"Euh... Ce n'est pas ce que j'avais en tête.",
"Oh, capitaine! Tu ne voudrais pas goûter mes charmes? Ce n'est pas pour me vanter, mais...",
"Désolé, je n'ai pas le temps. La prochaine fois, d'accord?",
"Si tu veux commander un verre, adresse-toi au patron. Il est au comptoir.",
"Merci du conseil.",
"Si tu veux te reposer et retrouver la santé, loue une chambre pour la nuit. La salle commune n'offre pas un repos très réparateur, tu sais.",
"Merci, c'est bon à savoir.",
"Oui? Que puis-je faire pour toi?",
"Je voulais te parler de ",
"Father Jerald",
"Father Jerald",
", le prêtre.",
"Tu parles d'un prêtre! Il me fait sans arrêt des avances. Tu imagines? Je me suis plainte, mais personne ne me croit.\nIl m'a même écrit des lettres d'amour!",
"Ce sont ces lettres?",
"Oui. Tu a dû les avoir par ",
"Gilbert Ballester",
"Gilbert Ballester",
". Alors c'est à cause de sa plainte que tu es là?",
"Comment sais-tu qu'il a déposé une plainte?",
"Il m'en a parlé quand je lui ai apporté les lettres.",
"Très bien, je te remercie. Je vais te laisser travailler.",
"Tu reprends tes esprits?",
"Ohhh...",
"Ça va? Comment va ta tête?",
"Où est-ce que je suis?",
"Tu ne te souviens pas? Tu t'es fait voler!",
"Quoi? Oh... ma tête.... qui a osé...?",
"Comment est-ce que je le saurais? Ils sont venus, ont menacé, t'ont fait les poches, et ils sont partis.",
"Bon, ce qui est perdu est perdu.",
"Eh, Raymond! Est-ce que tout est annulé? Je dois rendre l'argent?!",
"...",

};