string DLG_TEXT[29] = {
"Cof, cof... Saleté de temps! Je m'appelle ",
", et je suis le meilleur constructeur de bateaux de toutes ces îles.",
"Je ne suis pas d'accord, je trouve le temps magnifique. Je m'appelle ",
".",
"Arrête de te plaindre! Mon nom est ",
". Tu as dû entendre parler de moi.",
"Oh, encore toi et tes problèmes... Cof cof!",
"Tu n'as peut-être pas la santé, mais tu as une bonne mémoire. Parlons de choses sérieuses, à présent.",
"Et oui, c'est encore moi, et tu es toujours aussi pénible. Venons-en aux choses sérieuses.",
"Désolé de te déranger. Je vais y aller.",
"Tu sais, j'en ai vraiment marre de t'entendre te plaindre. Au revoir.",
"Vous autres, les jeunes, vous ne respectez plus rien! Vous avez la passion et la force, qu'est-ce qu'il vous faut de plus?",
"Toi aussi, tu as été jeune. Sois un peu patient.",
"Oui, et je parie que ça fait belle lurette que tu as oublié ce qu'était la jeunesse.",
"Un peu de respect pour tes aînés, s'il te plaît!",
"Ne me parle plus jamais comme ça. On peut passer aux choses sérieuses?",
"Fais attention à ce que tu dis, le vieux, ou tu vas le regretter. À ta place, je la fermerais et je passerais aux choses sérieuses.",
"Désolé, je vois que ça ne sert à rien d'essayer de te parler.",
"Assez de bavardages! Au revoir.",
"D'accord, d'accord! Qu'est-ce que tu me veux, ",
"?",
"Je voudrais utiliser les services de ton chantier naval.",
"J'ai besoin des services de ton chantier naval. ",
"Désolé, il faut que j'y aille.",
"Des affaires urgentes m'attendent ailleurs. Je dois y aller.",
"Qu'est-ce que tu veux, exactement?",
"Mon bateau a besoin d'être réparé. Mais je pourrais aussi en acheter un neuf.",
"Je dois installer de nouveaux canons à mon bord.",
"Rien, merci.",

};