string DLG_TEXT[161] = {
"Bienvenue, bienvenue, ",
". Tu trouveras tout ce que tu veux à la taverne d'Everard Gordon. Et s'il te manque quelque chose, je te le trouverai!",
"Merci pour ton accueil chaleureux. Je suis ",
".",
"Bienvenue, très cher ",
". Je suis très content de te revoir dans ma taverne.",
"! Qu'est-ce que tu veux?",
"Salut, ",
".",
"Je cherche à renforcer mon équipage.",
"Je voudrais te parler, si tu as un moment.",
"Je vais rester ici pendant un moment.",
"Est-ce qu'il y a un lit de libre dans cette bicoque?",
"Il faut que j'y aille, ",
". Adieu.",
"Que puis-je faire pour toi, mon ami ",
"?",
"Il faut que j'engage quelques loups de mer pour mon équipage - de préférence plus malins que des animaux.",
", parlons un peu.",
"Je suis coincé ici pendant quelque temps.",
"Y a-t-il un lit de libre dans ce trou?",
"A plus tard, ",
". Adieu.",
"En fait, j'ai des chambres de libre. Combien de temps comptes-tu rester?",
"Jusqu'à demain matin. J'ai besoin de me reposer.",
"Jusqu'à ce soir seulement.",
"Ca te coûtera 5 pièces d'or.",
"Je suppose que tu peux te permettre de tels prix parce que tu es le seul en ville. Voilà ton or.",
"C'est malheureux. Mon pauvre dos me réclame un lit propre, mais ma bourse me dit que je vais dormir dans la salle de la taverne.",
"Cinq?! Quoi, tu tirerais le gouverneur lui-même de son lit pour moi? Laisse tomber. Je vais garder mon argent et dormir dans la salle commune.",
"D'accord, je vais y réfléchir.",
"Ca te coûtera 5 pièces d'or.",
"D'accord. Voilà ton argent.",
"C'est au-delà de mes moyens actuels. Je suppose que je vais devoir passer la nuit dans la salle commune, avec la racaille.",
"Pour une somme pareille, j'attends un lit, une baignoire et un repas à sept plats! Laisse tomber. La salle commune me semble tout à coup préférable.",
"Je vais y réfléchir. En attendant, j'ai une autre question à te poser.",
"Bien sûr. Que veux-tu savoir, capitaine ",
"?",
"Je voudrais savoir ce que pensent les habitants de la présence de la garnison de soldats français.",
"Tout ragot sera le bienvenu.",
"Je souhaiterais te parler de quelques affaires...",
"Affaires? Parlons-en maintenant!",
"Tu sais, maintenant que j'y pense, il n'y a rien dont nous devrions discuter.",
"As-tu vu dans le coin un homme qui s'appelle ",
"Counterspy",
"?",
"Te souviens-tu de l'officier français à qui j'ai parlé la dernière fois que je suis venu?",
"Il semblerait que la flotte française compte un nouveau bateau depuis peu.",
"Est-ce que ton bateau est prêt, ",
"?",
"J'ai besoin de toute information que tu pourras me donner sur un homme que tu as dû voir dans le coin. Difficile de le rater - il porte toujours une robe noire, et est seulement connu sous le nom de 'professeur'.",
"Il me faut un travail. Est-ce que tu connaîtrais des hommes riches sur cette île qui auraient peur de voyager seuls?",
"Si ces personnes existent, elles préféreront probablement éviter d'attirer l'attention avec autant de compagnie - comme tu dois le savoir.", 
"Oui, j'avais oublié. D'accord, je reviendrai plus tard, quand j'aurai moins de bateaux, ah ah.",
"Je ne veux pas t'aider. Tu as causé trop de tort à mon pays.",
"Plutôt patriote, hein? Eh bien, au revoir alors.", 
"Tes mains sont couvertes de sang. Tu ne penses pas sérieusement que quelqu'un voudrait voyager avec toi?",
"Tu as raison, tout le monde a peur de moi! Ah ah!",
"Tu arrives juste à temps. Un marchand cherchait de la compagnie pour voyager. Tu ferais mieux de lui parler - le voilà justement, il entre dans la taverne.",
"Je vais m'en occuper.",
"Non, je ne vois personne pour le moment. La prochaine fois, peut-être.",
"Mmh, j'attendrai, alors.",
"Oui, je m'en souviens. Il s'est fait arrêter à Greenford. On dit qu'il a cherché à lancer une insurrection. Si tu veux lui parler, tu le trouveras sûrement à la prison de Greenford.",
"Merci de ton aide.",
"Intéressant. Oh, au fait, je cherche d'autres membres d'équipage.",
"Je voudrais te parler.",
"Je vais prendre congé, ",
". Adieu.",
"Comme tu veux, capitaine. Comme tu veux.",
"Merci. Ca pourrait être utile à l'avenir. En attendant, j'ai besoin d'un équipage.",
"Je voudrais te parler.",
"A la prochaine, ",
". Adieu.",
"Regarde autour de toi, capitaine! Qui veux-tu engager? Tous les hommes valides ont été pris par les Français pour travailler sur leurs navires.",
"Je vois. Dommage. Tu peux peut-être m'aider pour autre chose, alors.",
"Pardonne-moi, mais il faut que j'y aille, ",
". Bonne chance.",
"Les Français? Qu'est-ce qu'on en pense d'après toi? \nIls ont promis qu'ils ne feraient aucun mal, et ils ont mis à sac la moitié de la ville! \nLa pauvre ",
"Mildred Backer",
" a dû s'enfuir pour survivre\nEt son père a été abattu comme un chien parce qu'il a résisté!",
"C'est bien pire que ce que j'imaginais. Dis-moi, ",
", aimerais-tu revoir le drapeau anglais flotter sur Oxbay?",
"C'est épouvantable, capitaine! Les Français ont pris le fort par surprise, presque sans pertes dans leurs rangs. Ensuite, ils ont déclaré que \nnous étions sous la protection de la couronne française. Protection, tu parles! Peu de temps après, ils ont commencé à tout mettre à sac! À remplir leurs cales de marchandises à nos dépens.",
"Il est donc juste de dire que la 'protection' des Français ne vous plaît pas?",
"Capitaine, je prie pour qu'arrive le jour où ces envahisseurs seront enfin jetés à la mer. Ils boivent des tonneaux entiers de mon meilleur rhum et de ma meilleure bière, et j'ai même peur de leur demander de payer!",
"Alors, tu seras peut-être ravi d'apprendre que je viens te voir sur ordre de Sir Robert Christopher Silehard.",
"Le gouverneur de Redmond? Son Excellence est donc au courant de l'attaque? Pourquoi ne descend-t-il pas de son... trône... si confortable pour reprendre la colonie?!",
"Chaque chose en son temps. Pour le moment, je glane des informations sur les plans des Français.",
"Je vois, oui. Si je peux t'aider en quoi que ce soit dans ta mission, n'hésite pas.",
"Qu'est-ce qui se passe actuellement dans la ville?",
"Pratiquement rien. La plupart de la population reste terrée dans les maisons ou dans la jungle. Les Français ont placé des gardes à la porte de la ville, mais plusieurs citoyens réussissent chaque jour à les contourner et à sortir\nQuant aux soldats français, ils voient apparemment cette occupation comme une grande beuverie. La plupart d'entre eux sont ivres en permanence\nEn plus, ils sont à court de personnel. Les commandants de la flotte engagent de plus en plus de marins. Leur solde est plutôt bonne, d'après ce qu'on dit\nMais pour en revenir à nos moutons, ",
", ce serait peut-être le moment d'envoyer un émissaire chez les Français.",
"Un bon tavernier entend beaucoup de choses. As-tu réussi à glaner des informations sur les Français et sur leurs plans?",
"Eh bien... cela n'a peut-être aucune importance, mais... l'autre nuit, deux officiers français ivres disaient qu'ils attendaient un bateau chargé de munitions\nIls semblaient espérer qu'il n'arrive pas trop vite afin de pouvoir continuer à faire la fête aux frais de la ville! \nJ'ai l'impression que dès que leur cargaison de munitions arrivera, la flotte lèvera l'ancre et passera à l'étape suivante de leur plan de conquête, quel qu'il soit.",
"Merci. C'est exactement le genre d'informations dont j'ai besoin.",
"J'en suis ravi. Si jamais j'entends autre chose d'utile, je te le ferai savoir tout de suite! \nLorsque ces porcs sont ivres, ils ont la langue bien pendue. S'ils ne paient pas ma bière avec de l'or, ils la paieront avec des informations, qu'ils le veuillent ou non!",
"Un soldat français ivre est donc aussi efficace qu'un espion, c'est ça?",
"Ça résume bien la situation, ",
"! Si seulement tu pouvais savoir ce qui se passe ici pendant la nuit!",
"Je le pourrais peut-être un peu, avec ton aide.",
"As-tu une idée? Je suis à ton service!",
"Mon plan est assez simple : tu vois ce Français là-bas? Tu le connais?",
"Bien sûr. C'est un officier de la frégate française. Tu parles d'un officier - il passe le plus clair de son temps ici.",
"Parfait. Et serais-tu prêt à dépenser un peu d'or pour la libération d'Oxbay?",
"De l'or? ",
", je ne te suis plus.",
"C'est très simple. Je vais m'asseoir avec cet homme et tu vas lui servir tout ce qu'il demandera. Vin, bière, rhum... On va le faire boire et je vais récupérer toutes les informations utiles qui pourraient traîner dans sa caboche.",
"Mais, ",
", je suis déjà en train de faire faillite! Qui va payer toutes ces boissons? Je suis prêt à contribuer à la libération d'Oxbay, mais pas à me ruiner!",
"Écoute, le gouverneur Silehard acceptera volontiers de rembourser toutes tes dépenses - et il ajoutera même un supplément pour ta peine!",
"À quel prix estimes-tu ta propre liberté?",
"Tu crois vraiment qu'il me récompensera? D'accord, alors. Parlons affaires!",
"Je savais que tu me comprendrais. Dépêche-toi et apporte à boire!",
"Désolé, mais je ne peux pas me contenter d'une promesse d'un homme du gouverneur. Non, ce Français boit comme un trou. C'est une vraie outre! Je ne peux pas le servir gratuitement.",
"Tu plaisantes? Tu viens de me dire qu'il ne paie déjà pas ses boissons. Quel genre de patriote es-tu donc?",
"Bien! Si l'argent compte autant pour toi, dis-moi combien tu veux.",
"Un moment... Laisse-moi réfléchir... ",
" pièces d'or. Pas une de moins! Écoute, je sais que ça représente beaucoup d'or, mais nous sommes en guerre, non?",
"De là où je viens, on appelle ça profiter de la situation! Voilà ton or. Et apporte-moi la même chose que ce que commandera le Français, mais coupe mes boissons avec de l'eau. Je veux avoir les idées claires!",
"Everard, écoute - je n'ai pas d'argent.",
"À ta place, je me calmerais. Les Français ont des yeux et des oreilles partout. Menace-moi et je te livre à eux!",
"Espèce de voleur! Combien veux-tu?",
"Ne t'inquiète pas, ",
", tout se passera comme tu l'as prévu!",
"Eh bien.",
"Pas d'argent du tout? Je suppose que je n'ai pas d'autre choix que de compter sur les bonnes grâces du gouverneur. Je me souviendrai de ce que tu as promis.",
"Merci, Everard!",
"Ce n'est pas à leur goût?! Ils viennent tous les jours dans ma taverne vider des tonneaux de bière et de rhum et j'ai même peur de leur demander de payer lorsqu'ils partent en titubant, à l'aube!",
"Et si je dis...",
"Aucun problème. Tu peux avoir une chambre pour 10 pièces d'or.",
"C'est beaucoup trop!",
"D'accord. Voilà ton argent.",
"Hardouin Beauvallet",
"Hardouin Beauvallet",
"? Bien sûr. C'est aussi un client régulier de ma taverne. Il vient ici tous les soirs et boit deux bouteilles de mon meilleur vin. Sans payer, bien sûr!",
"Je l'attendrai ici, alors.",
"En fait, un bâtiment de guerre français est entré dans le port il y a un ou deux jours. S'ils se lancent dans une bataille navale directe, de nombreux Anglais périront noyés.",
"Nous devrions donc détruire ce bateau avant le début d'une éventuelle bataille ne commence, qu'en penses-tu?",
"Bonne idée. Mais je ne vois pas comment tu pourrais t'y prendre. Impossible de l'approcher à partir de la mer - le port est trop bien défendu. Et l'approcher depuis la terre serait un suicide. A moins que... Oui, bien sûr! La plupart de l'équipage du bateau est en ville en ce moment, en permission à terre. Il n'y a qu'un équipage réduit à bord",
"Où veux-tu en venir?",
"Il est peut-être possible d'atteindre le bâtiment avec un seul bateau venant de nuit de la côte. Si quelques hommes courageux étaient décidés à tenter le coup, je suis sûr de pouvoir trouver le bateau approprié.",
"Trouve le bateau, alors, ",
"!",
"Amène ce bateau jusqu'au port. Nous l'y attendrons.",
"Bien, bien. La nuit ne tombera pas avant plusieurs heures. Si tu veux, tu peux d'ici là te reposer dans une de mes chambres. Aux frais de la maison! Ton argent n'est pas le bienvenu ici aujourd'hui.",
"Oui, c'est une bonne idée. J'apprécie ton hospitalité.",
"C'est l'heure, ",
"! Le bateau est prêt. As-tu trouvé des volontaires?",
"Oui. Ce soir, le bateau devra se trouver près de la jetée.",
"J'y serai...",
"Attendons que la nuit tombe, alors.",
"Je t'en prie, prends une chambre dans ma taverne. Gratuitement, pour cette fois.",
"Merci, ",
".",
"Silence! Il est au premier étage. Il portera un uniforme français, mais ça fait partie de son plan.",
"Merci.",
"Tu ne trouveras pas grand monde maintenant. Il fait nuit et tout le monde est chez soi\nSi j'étais toi, j'attendrai jusqu'à demain matin. Veux-tu louer une chambre?",
"As-tu une chambre libre?",
"Pas encore. J'ai besoin que tu m'accordes encore un peu de temps.",
"Arrête! Arrête immédiatement ou je serai obligé d'appeler les gardes!",
"Calme-toi. Je suis déjà parti.",

};