string DLG_TEXT[71] = {
"Bonjour, ",
". Je m'appelle ",
"Ewan Glover",
"Ewan Glover",
", capitaine du sloop 'Albion'",
"Ravi de te rencontrer, ",
"Ewan Glover",
".",
"Tout le plaisir est pour moi, capitaine. Silehard lui-même m'a dit comment tu avais laissé les Français sans poudre et sans boulets. Et avec quelle adresse! Je peux te l'avouer, tu m'as vraiment impressionné.",
"Merci, ",
"Ewan Glover",
", tu me flattes.",
"Pas le moins du monde. Mais je suis sûr que nous trouverons bientôt un peu de temps pour discuter de nos aventures devant une chope de bière. Pour le moment, nous avons du travail.",
"Es-tu prêt à prendre la mer?",
"Oui, mais, ",
", ta flotte est trop importante. Trop encombrante pour être efficace. Laisse un de tes bateaux ici, à Redmond, et je te rejoindrai quand tu seras prêt.",
"D'accord, ",
"Je suis prêt à partir. Dès que tu prendras la mer, je te suivrai.",
"Parfait. Je te verrai en mer!",
"Je t'attendrai à la taverne. Renseigne-toi auprès de ",
"Charles Windem",
" à mon sujet.",
"Entendu. Je viendrai te chercher.",
"Désolé, ",
", mais je suis pressé. Je dois prendre la mer bientôt.",
"Bien sûr, tu as raison. Je ne vais pas davantage te retarder.",
"Bonjour, ",
". Bon, y a-t-il une place pour moi?",
"Pas pour le moment, désolé. Tu devras attendre encore un peu.",
"On se prépare à prendre la mer. Es-tu prêt?",
"Aussi prêt qu'on peut l'être, mais je suis triste d'avoir à quitter un port aussi agréable et un rhum aussi exquis.",
"Je vais bientôt revenir.",
"Je suis toujours prêt. Je te retrouverai au port.",
"À plus tard",
"Il faut qu'on y aille. J'ai envie d'en finir avec ça le plus vite possible.",
"Moi aussi. Allons-y, partons en mer.",
"Allons à la taverne, ",
". Pour attendre la tombée de la nuit, la meilleure chose à faire est de patienter avec une chope de bonne bière à la main.",
"Que veux-tu que je réponde à ça. En avant!",
"Je te rejoindrai plus tard. J'ai d'autres affaires à régler avant.",
"D'accord. Quand tu auras fini, viens à la taverne. Je demanderai au tavernier de te garder un peu de vin chaud aux épices!",
"Trop aimable. Je ne serai pas long.",
"Bon, où est ce gars de la ville qui devait nous rencontrer?",
"Attendons un peu. Il ne devrait pas tarder.",
"... et cette fille superbe a alors déclaré : 'Si tu ne deviens pas un capitaine respectable, oublie-moi!'",
"Et tu es donc devenu capitaine?",
"Oui. Mais en cours de route, j'ai réalisé que cette femme ne représentait rien pour moi, aussi belle qu'elle soit. Ce n'était pas moi qu'elle voulait ; elle voulait juste dépenser l'argent d'un capitaine! Pourquoi serais-je revenu?",
"Ça me semble logique.",
"On va bientôt partir. Il fait presque nuit!",
"Au fait, as-tu déjà entendu l'histoire de cet officier collet monté qui utilisait une frégate royale à des fins personnelles?",
"De quoi tu parles, là?",
"J'aimerais beaucoup l'entendre - plus tard. Allons-y maintenant!",
"Il n'y a pas si longtemps, une frégate est allée de Glasgow à Redmond. Elle devait servir de nouveau navire amiral pour la flotte de Redmond. À Londres, ils ont pensé que des troubles risquaient d'éclater dans les colonies...",
"Et alors?",
"Eh bien, lorsque les Français ont pris Oxbay, le capitaine de la frégate a reçu un ordre secret émanant directement du gouverneur Silehard\nLe lendemain, la frégate a pris la mer et le gouverneur a fini par demander à des bateaux civils de défier la flotte française!",
"Intéressant. Mais il n'y a pas vraiment lieu de suspecter un méfait.",
"Quoi? La guerre était à sa porte et le gouverneur a envoyé le bateau le plus puissant de la flotte Dieu seul sait où? Il avait peut-être conclu un accord avec les Français!",
"Est-ce que tu réalises la portée de ton accusation? Mais je poserai la question à Silehard à propos de cette frégate.",
"Bien sûr. Vas-y. Et fais-moi connaître sa réponse. Je serais vraiment intéressé de l'entendre.",
"Entendu. Maintenant, remettons-nous au travail.",
"Enfin te voilà, capitaine. Assieds-toi, s'il te plaît, ",
". Ton vin chaud aux épices va arriver.",
"Merci.",
"Mon travail ici est terminé. Je rentre à Redmond. Veux-tu que nous naviguions ensemble? Plus on est nombreux, moins on court de risques.",
"Non, désolé. Je ne peux pas partir pour le moment.",
"Tu as une autre mission à terminer, n'est-ce pas? Eh bien, bonne chance alors, ",
".",
"A toi aussi. A bientôt, ",
".",
"Eh! On s'est perdus! On devait aller au port de Greenford, pas sur cette plage déserte.",
"Non, c'est normal. J'ai une affaire à régler ici ; nous irons ensuite à Greenford.",

};