string DLG_TEXT[35] = {
"Bienvenue! Assieds-toi à la table libre. Que veux-tu commander, ",
"?",
"Rien. Je suis ici pour affaires.",
"Oh! Désolé. Je ne voulais pas t'importuner. Je retourne à mon travail.",
"Non, attends - tu ne m'importunes pas. En fait, c'est à toi que je voulais parler.",
"Pas si vite. Je veux te parler.",
"Je suis tout ouïe. Qu'est-ce que je peux faire pour toi?",
"J'ai besoin d'engager des marins.",
"Je cherche à renforcer mon équipage.",
"Parlons affaires.",
"Je voudrais une chambre.",
"Aurais-tu une chambre?",
"Pas grave. Il faut que j'y aille.",
"Bien sûr, ",
". Qu'est-ce que tu veux?",
"Dis-moi : à qui appartient la maison à côté de ta taverne?",
"En fait, ce n'est pas important.",
"J'ai une chambre libre. Combien de temps comptes-tu rester?",
"Juste pour la nuit.",
"Jusqu'au coucher du soleil.",
"Bien. Ca te coûtera cinq pièces d'or.",
"D'accord. Les voilà.",
"Tout ça? Je crois que je vais passer la nuit dans la salle de la taverne.",
"Et tu me donnes quoi pour ce prix - la résidence du gouverneur? Non merci.",
"Je vais y réfléchir. En attendant, j'ai une autre question à te poser.",
"Ca te coûtera 5 pièces d'or.",
"D'accord. Les voilà.",
"Tout ça? Je crois que je vais passer la nuit dans la salle de la taverne.",
"Et tu me donnes quoi pour ce prix - la résidence du gouverneur? Non merci.",
"D'accord, je vais y réfléchir.",
"Eh bien, il est assez tard. Toutes les personnes que tu pourrais engager ont trouvé un endroit où passer la nuit.\nTu ferais mieux d'attendre jusqu'au matin. Désires-tu une chambre? ",
"As-tu une chambre libre?",
"Non. J'ai une autre question à te poser.",
"Mes amis, s'il vous plaît. Du calme. Je ne tiens pas à appeler la garde!",
"Calme-toi. Je pars.",

};