string DLG_TEXT[28] = {       
"Je suis de service, tu n'as pas remarqué? Allez, file!",
"D'accord, d'accord.",
"Tu ne souhaites pas me rapporter un crime?",
"Non, bien sûr. Après tout, je suis capitaine. Je vois que tu n'écoutes pas.",
"N'oublie surtout pas - nous n'autorisons pas les bagarres dans les rues! Tu ne peux te battre que si quelqu'un t'attaque.",
"Bien, je n'oublierai pas.",
"Un temps pareil, et il faut que je reste ici. Crois-moi si tu veux, ma seule distraction consiste à me battre avec les mouches qui essaient de se poser sur mon visage.",
"C'est dommage, mais je ne peux pas t'aider. C'est ton travail.",
"Si tu veux bavarder, trouve quelqu'un d'autre. Je dois me concentrer sur mon travail et je ne peux pas te parler.",
"Je me demandais juste si tu étais vivant. Tu restes là planté comme une statue.",
"Tu crois que c'est facile de protéger notre ville? Eh bien non, pas du tout! C'est un travail très important et dangereux. Je me souviens, une fois...",
"Tu me raconteras ça une autre fois, je dois partir.",
"Va-t-en, ne me dérange pas.",
"C'est toi qui le dis, soldat.",
"Eh! Tu veux pas m'apporter un godet de rhum de la taverne?",
"Ouais, et après on me pendra pour avoir transformé un soldat en ivrogne. Attends plutôt la relève ; tu pourras boire autant que tu veux ensuite.",
"Pourquoi seuls les marins lourdauds comme toi viennent me parler?! Il n'y a donc aucune superbe femme dans cette ville?",
"Et t'appelles ça servir? Surtout, ne rate pas les criminels dangereux comme moi. Ah ah!",
"Tu as l'air bien portant! Tu ne veux pas t'engager dans notre armée? On a plein de place dans nos casernes, de la bonne nourriture, du rhum gratuit.",
"C'est tentant, mais je dois refuser. Je ne supporterais la discipline de l'armée.",
"Cette chaleur... Je donnerais tout pour retourner dans ma France adorée avec ses superbes fleurs et son odeur d'herbe.",
"Oui, on dirait que ce temps ne te convient pas.",
"Qu'est-ce que tu veux?",
"Toi... hic... espèce de sale bâtard! Tu as blessé mon... hic...  mon ami!",
"Quel ami? Tu es tout seul, ",
".",
"Quoi? Il était...  là il y a une minute. Je vais aller le chercher. Toi... hic... tu attends ici si tu veux ta raclée!",
"Comment oses-tu me contredire! Je vais t'étrangler!",

};
