string DLG_TEXT[147] = {
"Qu'y a-t-il, ",
"?",
"Je peux t'aider, ",
"?",
"C'est la première fois que tu viens en ville, ",
"? Je ne t'ai encore jamais vu.",
"Je m'appelle ",
", capitaine et propriétaire du bateau appelé '",
".' J'aurais quelques questions à te poser, si tu as un moment.",
"Je m'appelle ",
". J'aimerais te poser quelques questions.",
"Tu peux m'appeler capitaine ",
". Je voudrais juste quelques informations.",
"Bonjour, capitaine",
". Qu'est-ce qui t'amène dans notre colonie?",
"Ah, capitaine ",
". ",
", encore toi. J'espère que ton voyage a été agréable. Quoi de neuf?",
"Bonjour, ",
". Qu'est-ce que je peux faire pour toi?",
"Est-ce que j'ai raté quelque chose pendant que mon absence?",
"Est-ce qu'il s'est passé quelque chose d'intéressant pendant mon absence?",
"De quoi parlent les loups de mer devant leur rhum, ces temps-ci?",
"Quels sont les ragots qui circulent dans les tavernes?",
"Je cherche des potins, des rumeurs, des histoires invraisemblables... tout ce que j'ignore peut m'être utile.",
"Sers-moi tes ragots les plus récents, mon ami. Même le potin le plus insignifiant peut être synonyme d'aventure ou d'argent.",
"Je n'arrive toujours pas à trouver...",
"Impossible de trouver quoi que ce soit dans ce labyrinthe! Où est...",
"Je suis aussi perdu qu'un navigateur ivre. Encore!",
"Tu es d'ici, on dirait. Dis-moi où je peux trouver...",
"Peux-tu me dire comment aller à...",
"J'ai passé une journée pourrie, et tu nous épargneras de la peine à tous deux si tu me dis comment trouver...",
"J'aimerais avoir ton avis sur un gars d'ici.",
"J'ai besoin de savoir tout ce que tu pourras me dire sur une personne qui habite en ville.",
"Qu'est-ce que tu peux me dire sur...",
"Dis-moi tout ce que tu sais sur un gars...",
"J'espère que tu pourras me fournir des informations sur une personne que tu connais peut-être.",
"Cette ville n'est pas très grande - je parie que tu connais toutes les âmes qui y vivent. Discutons un peu.",
"Parle-moi de Falaise de Fleur.",
"Que peux-tu me dire sur ce trou perdu?",
"J'aimerais en savoir plus sur cette superbe colonie.",
"Peux-tu me raconter l'histoire de cette ville et de l'île?",
"Aurais-tu des informations intéressantes sur Falaise de Fleur?",
"...",
"Désolé. Je t'ai pris pour quelqu'un d'autre.",
"Je ne fais que passer, alors laisse-moi tranquille.",
"Qu'est-ce que tu voudrais savoir, ",
"?",
"Qu'est-ce qui t'intéresse, capitaine?",
"Qu'est-ce que tu veux de moi?",
"Les villes comme celles-ci sont toujours remplies de ragots. Donne-moi les meilleurs.",
"Est-ce que quelque chose d'intéressant s'est produit par ici, récemment?",
"Je veux juste savoir ce qui se passe dans le voisinage. Quelqu'un a escroqué un de ses amis? Quelqu'un a été tué? L'aubergiste est vraiment une femme? Tu piges?.",
"Comment est-ce que je peux aller à...",
"Peux-tu m'aider à trouver mon chemin en ville?",
"Où puis-je trouver...",
"Peux-tu me parler d'une personne qui m'intéresse?",
"Je voudrais des informations sur un gars d'ici. Peux-tu m'aider?",
"J'aimerais savoir ce que les habitants de la ville savent sur une certaine personne...",
"Que peux-tu me dire sur Falaise de Fleur?",
"J'aimerais connaître l'histoire de ta ville.",
"J'aimerais avoir des informations sur cette colonie.",
"Je ne fais que passer. Je te verrai plus tard.",
"Merci. Encore une chose...",
"Content d'avoir parlé avec toi. Au revoir!",
"Autre chose, capitaine",
"?",
"Voyons ça, ",
".",
"J'écoute, ",
".",
"De quoi parle-t-on en ville ces jours-ci?",
"De quoi parlent les loups de mer devant leur rhum ces temps-ci?",
"Cela fait longtemps que je n'ai pas accosté sur ces rivages. Qu'est-ce que j'ai raté?",
"Pourrais-tu m'indiquer mon chemin?",
"Je me suis complètement perdu dans ces rues.",
"C'est la première fois que je viens dans cette ville, et j'aurais besoin qu'on m'indique mon chemin.",
"J'aimerais ton avis sur un gars d'ici.",
"J'ai besoin de savoir tout ce que tu pourras me dire sur une personne qui habite en ville.",
"Pourrais-tu me donner des informations sur les habitants?",
"Parle-moi de Falaise de Fleur.",
"Que peux-tu me dire sur cette colonie?",
"J'aimerais avoir des informations sur Falaise de Fleur.",
"Je viens de réaliser qu'on m'attend ailleurs. Au revoir.",
"De qui veux-tu parler, ",
"?",
"Est-ce que quelqu'un en particulier t'intéresse?",
"Sur qui exactement veux-tu des informations?",
"Je veux parler du gouverneur.",
"C'est le propriétaire de la taverne qui m'intéresse.",
"Le propriétaire du chantier naval.",
"Je veux parler du marchand local.",
"De personne. Laisse tomber.",
"Mmh... Ça ne fait pas très longtemps qu'il est arrivé dans notre colonie. Il est jeune et dynamique, et l'a rendue prospère.",
"Je vois. J'ai une autre question à te poser.",
"Merci, au revoir.",
"Tu sais, c'est un gars agréable. Il a le sens de l'humour et sa taverne est propre. Plus important encore : il arrive toujours à y maintenir l'ordre.",
"Je vois. J'ai une autre question à te poser.",
"Merci, au revoir.",
"Je ne le connais pas vraiment bien. On dit que c'est un gars borné. Au moins, personne ne le voit jamais à la taverne. D'après ce que j'ai entendu, il rêve de construire un bateau immense.",
"Je vois. J'ai une autre question à te poser.",
"Merci, au revoir.",
"Il est très cupide. Certaines personnes disent que c'était l'assistant de Baldewin Coffier et que quand le magasin a fait faillite, il l'a racheté à bas prix. Je ne connais pas la qualité ni le prix de ses marchandises, mais apparemment, ce n'est pas une personne très... fréquentable.",
"Je vois. J'ai une autre question à te poser.",
"Merci, au revoir.",
"Où vas-tu, ",
"?",
"Pas de problème, capitaine. Où dois-tu aller?",
"Je serais ravi de te guider, ",
". Mais où veux-tu aller?",
"Comment puis-je aller à la taverne?",
"Où est le chantier naval?",
"Où puis-je vendre mes marchandises?",
"La taverne se trouve sur la place principale, pratiquement en face de la résidence du gouverneur et près de l'église. Tu ne peux pas la rater.",
"Parfait. Merci de ton aide.",
"Où est le chantier naval?",
"Où est-ce que je pourrais tirer un prix décent des bonnes marchandises que j'ai amenées en ville?",
"Le bureau du responsable du chantier naval se trouve au centre ville, juste à gauche lorsque vous êtes face à la résidence du gouverneur.",
"Je vois. Et la taverne?",
"Où est-ce que je pourrais tirer un prix décent des excellentes marchandises que j'ai apportées en ville?",
"Je crois que c'est tout. Merci de ton aide.",
"Depuis le centre de la ville, traverse les portes sur la droite. Là-bas, tu verras une enseigne sur un bâtiment. C'est là que se trouve le magasin.",
"Où se trouve le chantier naval local?",
"Comment puis-je aller à la taverne?",
"Je vois. Merci pour les informations.",
"Je ne vois pas en quoi ça pourrait t'intéresser, mais pourquoi pas?",
"Qu'est-ce qui t'intéresse exactement, ",
"?",
"Bien sûr, ",
". Heureusement, c'est une histoire assez courte.",
"C'est l'histoire de la colonie qui m'intéresse...",
"Parle-moi de la colonie.",
"À part la ville, y a-t-il autre chose sur l'île?",
"J'aurais encore quelques questions à te poser, si ça ne te dérange pas.",
"Eh bien, notre colonie a été fondée il y a environ 50 ans, et elle fut l'une des premières de l'archipel. Mais à l'origine, elle se trouvait de l'autre côté de l'île ; à cette époque, les indigènes vivaient ici.\nPlusieurs mois après sa création, la colonie d'origine a été détruite par les Espagnols. Elle a été reconstruite ici 10 ans plus tard.\nLe fort a été bâti pour protéger la colonie, et ils notre gouverneur est arrivé peu de temps après.",
"Merci. J'ai encore quelques questions à te poser.",
"Tu vois, je pensais vraiment que ce serait plus intéressant. J'ai autre chose à te demander.",
"C'est tout ce que j'ai besoin de savoir. Merci.",
"Merci de ton aide. Adieu.",
"Pas vraiment. A part quelques plantations, le reste de l'île est complètement désert.",
"Que peux-tu me dire d'autre sur la colonie?",
"Que peux-tu me dire d'autre?",
"Il n'y a en réalité rien d'autre à dire. Il n'y a rien à part la ville. On a essayé de creuser des mines, à une époque, mais ça n'a rien donné.",
"Je vois. Quoi d'autre?",
"Non. Tu trouveras quelques plantations et quelques maisons sur cette partie de l'île, mais elle reste largement inexploitée.",
"Dans ce cas, pourrais-tu m'en dire plus sur la colonie?",
"Compris. J'ai autre chose à te demander.",

};