string DLG_TEXT[75] = {
", mon fils! Que puis-je pour toi, en tant que serviteur de Dieu?",
"Je suis ",
", capitaine du '",
"'.",
"Je te souhaite la bienvenue, ",
", mon fils! Heureux de constater que ton séjour en mer ne t'a pas fait oublier la foi.",
"Bonjour, ",
". Approche et livre-moi tes péchés.",
"Je suis content de te voir et prêt à t'entendre en confession, mon fils.",
", j'aimerais faire un don à l'Église.",
"J'ai juste besoin de te parler, mon père.",
"Je t'en suis reconnaissant. Peut-être une autre fois.",
"Je suis très heureux de compter un nouveau membre au sein de ma congrégation. Je suis ",
".",
"Merveilleux. Dans ce cas, j'espère que accepteras mon don à l'Église.",
"Pouvons-nous parler, mon père?",
"Merci, mon père, mais je dois partir.",
"Cela concerne-t-il ta foi,?",
"En réalité, cela concerne ta foi.",
"En fait, cela te concerne.",
"Je suis désolé, mais j'ai accumulé des éléments prouvant que tu as brisé tes vœux de prêtre.",
"Non. Et parlons d'autre chose.",
"Que veux-tu dire?",
"J'ai été envoyé ici afin de vérifier si les rumeurs qui souillaient ton nom étaient fondées.",
"Des rumeurs? Quelles rumeurs?",
"Je suppose que tu plaides non coupable. Malheureusement, j'ai des lettres qui indiquent ta culpabilité.",
"Vraiment? Quelles lettres? Je jure que je n'ai rien fait!",
"Les voilà. Tu ferais aussi bien d'avouer, mon père.",
"Mais je ne les ai jamais vues.",
"C'est ton écriture, mon père. Et elles prouvent l'étendue de ta déchéance.",
"Cela ne me dit toujours pas de quoi tu veux parler!",
"Je veux parler des lettres que tu as écrites à une certaine jeune personne.",
"Je t'assure que je n'ai jamais écrit de telles lettres! Mais, Seigneur, qui me croira après les avoir vues?!",
"Mmh. Soit tu es un excellent acteur, mon père, soit tu n'es pas l'auteur de ces lettres. Je suis content de ne pas avoir à en décider moi-même.",
"Ne perds pas espoir, mon père. Je vois bien que tu dis la vérité. Il reste de l'espoir.",
"De l'espoir? Ma réputation est ruinée!",
"Tu sais, il pourrait m'arriver de 'perdre' ces lettres.",
"Que puis-je faire pour te convaincre de me les remettre?",
"Je pense que 2 000 pièces d'or pourraient me distraire suffisamment pour que je les laisse ici.",
"Non! Je ne te graisserai pas la patte avec l'argent de l'Église. Va-t-en, je t'en prie.",
"Comme tu veux.",
"Très bien. Voilà ton argent.",
"Et voilà tes lettres.",
"Merci. Maintenant, je vais partir. Et emporter ces lettres.",
"Quoi? Je croyais que nous avions un accord!",
"Tu as eu tort. Je vérifiais tes dires. Un innocent n'aurait pas cherché à acheter son salut. Maintenant, je sais que tu es coupable.",
"Que veux-tu dire, mon fils?",
"J'ai été envoyé par ",
"Father Bernard",
"Father Bernard",
", afin de vérifier quelques rumeurs déplaisantes à ton sujet.",
"Quel genre de rumeurs? Je ne vois absolument pas de quoi tu veux parler.",
"Tu es en train de me dire que tu n'as pas trahi tes vœux de prêtre? Et que tu ne sais pas qui a répandu ces rumeurs?",
"Au nom du ciel, non! J'ignore qui peut chercher à me nuire de la sorte.\nDemande à n'importe qui en ville! Demande à mon assistant! Tous te diront que je n'ai rien fait de mal.",
"C'est peut-être une bonne idée.",
"Très bien. Mais je dois dire qu'un tel mépris n'apporte jamais rien de bon.",
"J'en suis conscient. Accepte mon don à l'Église.",
"Je regrette, mon père, mais je dois y aller.",
"Naturellement, mon fils. Combien souhaite-tu donner?",
"Je suis désolé, mon père, mais je ne peux rien donner pour l'instant.",
"Je crains de ne pouvoir donner plus de 1 000 pièces d'or pour l'instant.",
"Je pense que le Seigneur sera satisfait de ces 1 000 pièces d'or.",
"Je ne me débrouille pas trop mal, ces temps-ci. Je peux donner 5 000 pièces d'or.",
"Cette décision t'appartient, mon fils. Il n'est jamais trop tard pour changer. Rappelle-toi qu'il en sera tenu compte au jour de ta mort.",
"Ma mort n'est pas pour demain, si Dieu en veut ainsi! Parlons d'autre chose.",
"Je regrette, mon père. Je dois partir.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Je dois te parler, mon père.",
"Je regrette, mon père, mais je dois filer.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Je dois te parler, mon père.",
"Je regrette, mon père, mais je dois filer.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Je dois te parler, mon père.",
"Je regrette, mon père, mais je dois filer.",

};