string DLG_TEXT[134] = {
", mon fils! Que peut pour toi l'humble serviteur de Dieu que je suis?",
"Je suis ",
", capitaine et propriétaire du navire appelé '",
"'.",
"Bienvenue dans la maison de Dieu, ",
" mon fils. Content de voir un marin qui ne néglige pas le salut de son âme.",
"Bonjour, ",
". Es-tu ici pour te confesser?",
"Mon fils, Je suis content de te voir et prêt à entendre ta confession, si tu le souhaites. Le Seigneur sait que le péché est inévitable en ce monde.",
", j'aimerais offrir quelque chose à l'Église.",
"Je dois t'entretenir de quelque chose, mon père.",
"Merci. Peut-être une autre fois.",
"Ravi d'accueillir une nouvelle brebis au sein du troupeau ",
".",
"Alors accepte mon cadeau.",
"Pouvons-nous parler, mon père?",
"Merci, mon père, mais je dois filer.",
"Ta foi est-elle en cause, mon fils?",
"Peut-être. Je ne peux m'empêcher de remarquer que quelque chose te préoccupe. Puis-je t'aider de quelque manière?",
"Ceci concerne l'affaire que tu m'as confiée.",
"Peut-être. Je vois sur ton visage que quelque chose t'ennuie. Peut-être puis-je t'aider?.",
"J'ai une lettre pour toi.",
"Qui aurait cru que ",
"Father Gareth",
" servait le prince des ténèbres? Qui aurait pu penser...",
"Mais je sais maintenant qui blâmer pour mes récents ennuis. C'est lui qui a signalé tous mes déplacements aux moines!",
"Il me faut l'autorisation de libérer un prisonnier détenu à Oxbay.",
"J'ai réussi à obtenir l'autorisation que tu souhaitais obtenir. La voilà. Et rappelle-toi que j'ai foi en toi.",
"Ne t'inquiète pas. J'agirai comme il faut.",
"Non. Parlons d'autre chose.",
"Il y a autre chose : mes hommes et moi avons anéanti la secte.",
"Non. Ce qu'il y a, c'est qu'un homme souhaite faire don d'une certaine somme d'or à ton église. Je m'occupe de cette tâche pour lui.",
"Hum... Non. Changeons de sujet, d'accord?",
"Dieu soit loué! Tu as réussi! Je vais ordonner une messe pour célébrer cette prouesse!",
"Maintenant, si tu veux bien m'excuser, je dois regagner Douwesen afin de ramener les enfants disparus.",
"Je crains que ce soit au-delà de mes compétences...",
"Je ne crois pas. Ce prisonnier et celui que tu m'as demandé d'éliminer.",
"Dans ce cas, pourquoi le libérer?",
"J'ai besoin de gagner sa confiance. Il sait où se trouve leur repaire et il sera bien plus susceptible de me l'indiquer s'il me croit de son côté.",
"Je comprends. Bien, je vais voir ce que je peux faire. Attends ici.",
"Très bien.",
"Des moines? Ce ne sont pas des moines, mais des serviteurs du Malin!",
"Si tu le dis, mon père. Mais ils portaient tous des robes de moine.",
"Oui, bien entendu. Mais nous devons avant tout trouver le repaire de ces démons. Je pense qu'il serait sage de ta part de gagner Isla Muelle et de te renseigner là-bas.",
"Alors bénis-moi, mon père.",
"Que Dieu soit avec toi, mon fils.",
"Je ne trahirai pas ta confiance.",
"Il y a autre chose. J'aimerais te présenter quelqu'un...",
"Oui?",
"Mais nous perdons notre temps. Acceptes-tu mon offre?",
"Si je me souviens bien, tu m'avais proposé 15 000 pièces d'or pour éliminer la secte. C'est bien ça?",
"Aha! Je me demandais si ",
"Padre Domingues",
" avait réussi à l'envoyer.",
"Que veux-tu dire?",
"Suis-je bête! Tu ne le sais probablement pas encore : l'homme qui t'a remis cette lettre a été enlevé! J'ai peur que mes pires craintes soient encore à venir.",
"Que veux-tu dire?",
"Il y a quelques années, un repaire d'animistes a été démantelé en Italie. Malheureusement, le chef de cet ordre est parvenu à s'enfuir et s'est installé ici, dans l'archipel\nLa disparition des enfants et d'un prêtre laissent supposer qu'il a repris ses coupables activités et entend accomplir un ancien rituel. Il faut l'arrêter!",
"Et moi, dans tout ça?",
"J'ai besoin que tu sois l'épée de Dieu, Son bras vengeur. Mais je sais que tu es un homme d'argent, aussi suis-je prêt à t'offrir 15 000 pièces d'or pour tes services envers l'Église.",
"Ce n'est pas mal...",
"Ah, c'est toi. Content de voir que tu te rends toujours dans la maison de Dieu. Et c'est une vraie bénédiction de te voir aujourd'hui. J'ai besoin de ton aide.",
"Je t'écoute, mon père.",
"Je crains que ta réputation douteuse ne m'empêche de te demander ton aide pour une affaire concernant l'Église.",
"Très franchement, ça ne me gêne pas plus que ça.",
"Cette affaire est urgente et plus complexe qu'elle n'en a l'air.",
"Peut-être auras-tu l'obligeance de me donner quelques détails?",
"Plusieurs enfants de la colonie hollandaise ont été enlevés...",
"J'en ai entendu parler, mais tout ce que je sais, c'est qu'ils ont été emmenés sur la frégate noire appelée 'Mefisto' et qu'elle est partie pour une destination inconnue.",
"Je l'ignorais. Je pense que cette nouvelle explique certaines choses\nMais revenons à notre affaire : je veux que tu portes un message à Isla Muelle et le remettes à un homme du nom de ",
"Padre Domingues",
"Padre Domingues",
".\n C'est un prêtre espagnol. Il te donnera d'autres instructions, si besoin est.",
"Ça me paraît très simple. Qu'y a-t-il de complexe là-dedans?",
"Le dernier homme à accepter de porter mon message a été retrouvé mort aujourd'hui sur le seuil de sa maison\nDans ses dernières paroles, il a mentionné des hommes en soutane noire armés de dagues.\nIl semble que quelqu'un tienne à s'assurer que ce message ne trouve pas son destinataire.",
"Alors quelqu'un risque de chercher à me tuer, moi aussi.",
"Je le crains. Si tu refuses, je comprendrai...",
"Oh, j'aime trop l'argent pour refuser, mon père.",
"Parfait. Voici la lettre. Rappelle-toi, tu dois la remettre au ",
"Padre Domingues",
", et à personne d'autre. Tu le trouveras à Isla Muelle.",
"Très bien. Cela ne devrait pas me prendre beaucoup de temps.",
"Qu'as-tu découvert?",
"Father Jerald",
"Father Jerald",
" est coupable des crimes dont il est accusé.",
"Father Jerald",
"Father Jerald",
" est innocent des crimes dont il est accusé.",
"En as-tu la preuve?",
"Oui. Ces lettres semblent salir la réputation du prêtre, mais elles ont en réalité été écrites par son assistant.",
"Quelle cruelle tromperie! Je vais régler ça immédiatement. Tu as fait un excellent travail au service de l'Église. Je suis ravi de te remettre ta récompense.",
"Merci, mon père.",
"En as-tu la preuve?",
"Oui. Ces lettres révèlent toute l'histoire.",
"Je vois. J'espérais le contraire. Mais tu as accompli ta tâche. Voici ta récompense.",
"Merci.",
"Tu vois, j'ai besoin d'aide dans une affaire sérieuse, et je préférerais trouver cette aide en dehors de l'Église.",
"On dit parfois que je suis très éloigné de l'Église, mon père. Mais dis-moi ce qui te préoccupe. Peut-être pourrai-je t'aider?",
"Je crains que ta réputation ne m'autorise pas à accepter ton aide.",
"Comme tu veux.",
"Très bien. J'ai le sentiment que je peux te faire confiance. Mais jure-moi d'abord que personne n'apprendra la teneur de cette conversation.",
"Tu peux te considérer comme au confessionnal, mon père.",
"Bien. Dans ce cas, écoute : selon certaines rumeurs, l'un des mes frères de foi a oublié ses vœux et sombré dans le péché.\nJe ne peux hélas m'éloigner de mon troupeau pour vérifier moi-même ces rumeurs, et expédier un religieux ne ferait qu'éveiller les soupçons\nD'un autre côté, je suis le seul à pouvoir l'amener à parler de cela et à plonger dans son âme pour savoir s'il dit la vérité...",
"En fait, tu me demandes de réunir des preuves contre l'un de tes frères prêtres?",
"Pas du tout! Non, je cherche simplement à savoir s'il est ou non coupable des péchés dont on l'accuse\nS'il est innocent, alors je tiens à savoir qui a sali sa réputation.",
"Très bien, mon père. Donne-moi son nom, et je verrai ce que je peux découvrir.",
"Il sert l'Église à Greenford. C'est le ",
"Father Jerald",
"Father Jerald",
". Il devrait être assez facile à trouver, une fois sur place.",
"Je reviendrai le plus vite possible, mon père.",
"Puisse Dieu te guider vers la vérité, mon fils. Approche et accepte ma bénédiction.",
"C'est bon, mon père. Je suis sûr que tout ira bien.",
"Comme tu veux. Mais il est de mon devoir de te dire qu'un tel mépris envers la fois est mal avisé.",
"Je sais. Accepte mon cadeau destiné à la Sainte Église.",
"Je regrette, mon père, mais je dois y aller.",
"Bien entendu, mon fils. Combien souhaites-tu donner à la Sainte Église?",
"Je regrette, mon père, mais je viens de me rendre compte que je ne pouvais rien donner pour l'instant.",
"Je crains de ne pouvoir donner plus de 1 000 pièces d'or pour l'instant.",
"Je pense que le Seigneur sera satisfait de ces 1 000 pièces d'or.",
"Je ne me débrouille pas trop mal, ces temps-ci. Je peux donner 5 000 pièces d'or.",
"Cette décision t'appartient, mon fils. Il n'est jamais trop tard pour changer. Rappelle-toi qu'il en sera tenu compte au jour de ta mort.",
"Ma mort n'est pas pour demain, si Dieu en veut ainsi! Parlons d'autre chose.",
"Je regrette, mon père. Je dois partir.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Je dois te parler, mon père.",
"Je regrette, mon père, mais je dois filer.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Je dois te parler, mon père.",
"Je regrette, mon père, mais je dois filer.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Je dois te parler, mon père.",
"Je regrette, mon père, mais je dois filer.",

};