string DLG_TEXT[56] = {       
"! Laisse-moi te montrer toute la ville pour une seule pièce d'or!",
"Qui es-tu?",
"Je ne suis pas un touriste, et je n'ai pas besoin de guide!",
"Je m'appelle ",
", ",
". Je suis un marin de l'Oiseau. Nous attendons ici un navire d'escorte.",
"Je vois. Laisse-moi te poser quelques questions.",
"Très bien. Tu peux y aller, marin.",
"Oui, ",
" capitaine. Je comprends.",
"Tu peux y aller.",
"Oui, ",
"! Mais les informations coûtent un peu plus cher!",
"Combien veux-tu?",
"Cinq pièces d'or, ",
".",
"Très bien. Prends cet argent.",
"Je n'ai pas cette somme sur moi.",
"Je ne vais pas te payer pour répondre à des questions!",
"Merci, ",
". Bon, que voulais-tu savoir?",
"Tu dis que tu es embarqué sur l'Oiseau...",
"Je regrette, ",
". Mais j'attendrai que tu m'apportes l'argent ",
"Marché conclu.",
"Oui, ",
". C'est ma troisième année à bord.",
"Et tu attends l'arrivée d'un navire d'escorte?",
"Où doit aller ton navire?",
"Non, ",
", il est déjà au port. Il est actuellement chargé de vivres et de munitions, mais nous allons partir d'un jour à l'autre.",
"De quel type de navire s'agit-il?",
"Où est le capitaine de ce navire?",
"C'est tout ce que je voulais savoir. Tu peux disposer.",
"Hélas, ",
", je n'en sais rien. On ne dit rien aux simples matelots. C'est probablement un secret. Une opération militaire, peut-être.",
"Et tu attends un navire d'escorte?",
"C'est tout ce que je voulais savoir. Merci.",
"C'est un brig appelé 'Le Requin'. Il n'appartient pas à la marine du roi de France. Le capitaine est un civil récemment engagé pour garder notre navire.",
"Où est le capitaine de ce bateau?",
"Je sais ce que je voulais savoir. Tu peux t'en aller.",
"Je ne sais pas, ",
". Mais tu peux demander à la taverne. Je sais qu'il y était ; il y est peut-être toujours.",
"Et comment s'appelle le capitaine du 'Requin'?",
"Amiel Berangere",
"Amiel Berangere",
", ",
".",
"Merci, ",
".",
"Re-bonjour, ",
". Tu as encore besoin de Ksurso... Vorsa... Hélas, je ne me rappelle plus comment tu m'as appelé l'autre fois.",
"Re-bonjour, ",
". Je crois que tu avais dit que tu n'avais pas besoin de mes services, pas vrai?",
"Non, mais j'ai une question.",
"Tu as raison. Au revoir, matelot.",

};