string DLG_TEXT[40] = {
"Hé, capitaine! C'est la première fois que tu viens à Quebradas Costillas?",
"Et alors?",
"Non, l'ami. Trouve quelqu'un d'autre à qui parler.",
"Eh bien, je pourrais te faire visiter le coin... Moyennant finance.",
"Combien?",
"Non merci. Je peux trouver mon chemin moi-même.",
"Je n'ai pas besoin d'or, capitaine. Mais tu pourrais réaliser un de mes vœux un de ces jours.",
"Un vœu? Tu es sûr que ton aide en vaut vraiment la peine?",
"Je ne comprends pas, mon gars. Va-t-en.",
"Eh bien, je connais presque tout sur tout le monde ici.\nSi tu veux faire des affaires, je peux t'obtenir un bon prix. Et si tu cherches quelque chose de plus intéressant, mes relations pourraient se révéler précieuses.",
"Très bien. Mais si ton vœu offense mon honneur...",
"Je peux me débrouiller seul. Tu peux disposer.",
"Je ne souhaite pas mourir jeune, capitaine. Mon vœu n'a rien à voir avec ta personne. Alors... qu'est-ce qui t'amène à Quebradas Costillas?",
"Je cherche un quelqu'un. Un homme.",
"Essaie de te renseigner à la taverne. S'il est venu ici, ",
"Ines Diaz",
" devrait pouvoir t'en dire davantage.",
"Ce conseil ne semble pas à la hauteur de la promesse que je t'ai faite.",
"Eh bien, je peux moi-même essayer d'en savoir plus sur cet homme, si tu veux bien me dire son nom.",
"Il s'appelle ",
"Raoul Rheims",
". Trouve-moi des informations utiles sur lui et j'exaucerai ton vœu.",
"Tu n'as pas besoin de savoir ça.",
"Marché conclu, ",
". Et si tu souhaites rejoindre la ville, descends cette allée puis tourne à droite.",
"Merci.",
"D'accord, ",
". À propos, si tu souhaites aller en ville, descends cette allée puis tourne à droite.",
"Merci.",
"Non, capitaine. Nous n'avons plus rien à nous dire.",
"Je vois.",
"Capitaine, attends! J'ai réussi à apprendre quelque chose!",
"Vraiment?",
"Raoul Rheims",
" est effectivement venu ici! Il est rentré au port pour effectuer des réparations avant de repartir.",
"C'est tout? C'est tout ce que tu as pour moi?",
"Non, ce n'est pas tout. Je sais où il est parti! Il est allé à Conceicao. Il semble être en affaires avec le chef des contrebandiers de cette île.",
"Bon, très bien! J'y vais immédiatement.",
"N'oublie pas mon vœu, capitaine!",
"Ne t'inquiète pas! Je n'ai qu'une parole.",

};

