string DLG_TEXT[98] = {
"Du vent! Je n'ai aucune envie de discuter les gens de ton genre!",
"...",
"Qu'est-ce que tu me veux? Tu vois bien que je suis occupé!",
"Il faut que je te parle, ",
".",
"Tu n'as encore jamais rencontré ",
"Ferro Cerezo",
" , n'est-ce pas? Il est temps d'y remédier.",
"Tu dis que tu t'appelles ",
"? Alors, c'est toi que je cherche!",
"Bien sûr! Tout le monde me réclame!",
"Ne sois pas ridicule. Je suis là pour récupérer les papiers que tu as volés à l'église d'Isla Muelle.",
"Oui. Je savais que ",
"Padre Domingues",
" serait contrarié d'apprendre que je détiens la preuve de son prêt.",
"Si tu as lu ces papiers, cette discussion amicale va changer de tournure.",
"Si c'est ce que prouvent ces papiers, tu devrais les remettre à la garde.",
"Écoute, et si je t'achetais les papiers?", 
"Que veux-tu dire?",
"Tu as sûrement entendu parler de moi, je suis ",
"Mon Dieu! Bien sûr que j'ai entendu parler du bandit le plus sanguinaire de ces eaux!",
"Tais-toi et donne-moi les papiers. J'en ferai meilleur usage que toi.",
"Mais... j'allais...",
"Tu as dit quelque chose?!",
"Non, non! Rien. Tiens, prends-les!",
"Au revoir.",
"Je n'en doute pas. Heureusement que je t'ai rencontré. Mon navire n'est pas fait pour un long voyage.\nPromets-moi d'emporter les papiers en Europe et je te les remettrai volontiers.",
"D'accord. De tels méfaits méritent d'être punis.",
"Tu pourrais t'en charger... pour 10 000 pièces d'or.",
"Disons 5 000?",
"Marché conclu.",
"Pas question. Je n'ai pas de temps à perdre. Je suis sur le point de partir.",
"Tu regretteras t'avoir été si bête!",
"Ah, tu aimes marchander? Moi aussi! 9 000.",
"6 000.",
"Bien. Voilà l'argent.",
"Pas question. Je n'ai pas de temps à perdre. Je suis sur le point de partir.",
"Comme tu voudras.",
"Tu essaies de me voler! 8 000, c'est ma dernière offre.",
"C'est plus que je ne suis prêt à dépenser.",
"D'accord. Voilà ton or.",
"Pas question. Je n'ai pas de temps à perdre. Je suis sur le point de partir.",
"D'accord.",
"Alors, file et ne viens plus me déranger! J'ai besoin de me reposer avant de prendre la mer.",
"À un de ces jours, peut-être.",
"J'espère que tu pourras tirer profit de cette affaire.",
"Ce sont mes affaires, pas les tiennes.",
"Tu connais mon nom, n'est-ce pas? Bon alors, qu'est-ce que tu veux?",
"J'ai besoin des papiers que tu as volés à l'église d'Isla Muelle.",
"Alors, c'est ce vieux renard de ",
"Padre Domingues",
" qui t'envoie.",
"Peu importe qui m'envoie. Je veux ces papiers.",
"À supposer un instant que je sache de quoi tu parles, pourquoi est-ce que je te les donnerais? Sais-tu seulement ce que contiennent ces papiers?",
"Non, mais une chose est sûre, il me les faut.",
"Alors, ce vieil hypocrite n'a même pas expliqué à son garçon de courses que ces papiers le discréditaient? Je savais que ça le contrarierait d'apprendre que je détiens la preuve de son prêt.",
"Si tu sais ce que contiennent ces papiers, je suppose que notre conversation va changer de tournure.",
"Écoute, et si je t'achetais les papiers?",
"Que veux-tu dire?",
"Tu as sûrement entendu parler de moi, je suis ",
".",
"Mon Dieu! Bien sûr que j'ai entendu parler de l'ordure la plus sanguinaire de ces eaux!",
" Ne t'avise pas de me traiter à nouveau d'ordure ou je te coupe la langue.",
"Excuse-moi! Ça m'a échappé. Je t'en prie, ce n'est pas ce que j'ai voulu dire!",
"Tais-toi et donne-moi les papiers. Je sais ce que je vais en faire.",
"Mais... j'allais...",
"Tu as dit quelque chose?!",
"Non, non! Rien. Tiens, prends-les!",
"Au revoir.",
"Tu pourrais t'en charger... pour 10 000 pièces d'or.",
"Disons 5 000?",
"Marché conclu.",
"C'est du vol!",
"Ça ne m'intéresse pas. Tu devrais t'en aller.",
"Eh bien, puisque tu as conscience de la valeur de ces papiers, je suppose que notre conversation va prendre une nouvelle tournure.",
"Tu vas le regretter.",
"J'en doute. Écoute, si tu ne veux pas payer, disparais.",
"Très bien. Mais un jour, tu regretteras de ne pas m'avoir aidé.",
"Ton style me plaît, l'ami! Que dirais-tu de 9 000?",
"Je préférerais 6 000.",
"D'accord. Voilà ton argent.",
"Non, ça n'ira pas. File, j'ai à faire. Je dois bientôt prendre la mer.",
"Comme tu voudras. Mais tu le regretteras.",
"Tu essaies de me voler! 8 000 et pas une pièce de moins.",
"Non. C'est trop pour moi.",
"Très bien. Voilà l'argent.",
"Non, c'est impossible. File, j'ai à faire. Je dois bientôt prendre la mer.",
"D'accord. À la prochaine. Et peut-être que j'aurai l'avantage.",
"Alors, file et ne viens plus me déranger! J'ai besoin de me reposer avant de prendre la mer.",
"Tu as tort de me décevoir, tu sais.",
"C'est une menace?",
"Oui. Si tu tiens à la vie, tu as intérêt à me remettre ces papiers.",
"Attends une minute. Je te reconnais maintenant. Tu travailles pour le gouverneur anglais!",
"C'est vrai. Alors, tu me prends au sérieux maintenant?",
"Je crois que je vais prendre le risque. File!",
"Je t'avais prévenu.",
"D'accord, d'accord! Prends les papiers, mais je me demande en quoi ils intéressent ton patron. Prends-les et disparais.",
"À la bonne heure!",

};