string DLG_TEXT[39] = {
"Capitaine! C'est vraiment toi?",
"C'est bien moi! En chair et en os.",
"Quel miracle! Comment as-tu fait pour t'en sortir?",
"Calme-toi! Je t'ai posé une question.",
"Excuse-moi, capitaine. On est juste ravis de te voir sain et sauf.",
"Moi aussi. Mais tu n'as pas répondu à ma question : qu'est-ce que tu fais ici?",
"Eh bien, après que tu sois passé par-dessus bord, on est restés plusieurs heures dans la tempête. Lorsqu'elle s'est enfin calmée, on a réalisé que la terre la plus proche était Isla Muelle. Le navire avait souffert et on a fait appel aux services d'un chantier espagnol\nÇa a mis un certain temps, mais le ",
"ship storage",
" est réparé.",
"Bonne nouvelle. Et comment avez-vous fait pour payer les réparations?",
"On a mis notre or en commun. Certains ont un peu rechigné... mais leurs traces de coups vont bien finir par guérir. Après tout, c'est aussi notre navire... Même si l'équipage sera ravi d'apprendre que notre capitaine est de retour!",
"Eh bien, je vous suis tous très reconnaissant.",
"Ça se fête! Et si on allait à la taverne?",
"Mieux encore, que la taverne vienne à nous! Je vais faire livrer dix tonneaux de rhum sur le navire. C'est moi qui régale!",
"Vive le capitaine! Dieu te bénisse, ",
"!",
"Un grand merci à tous.",
"Ta survie relève du miracle! Dieu doit être avec toi, capitaine!",
"J'aimerais qu'il en soit ainsi, même s'il m'arrive de me le demander...",
"... À moins que ce ne soit le diable des mers! Il paraît qu'il apprécie les marins audacieux et qu'il les protège du danger!",
"Je ne connais pas cette histoire.",
"Quelle histoire? Jovannie Speckled du brig 'Ardent' m'a dit avoir vu le diable des mers de ses propres yeux!",
"Le diable des mers? Au fond d'une bouteille de rhum, je parie.",
"Non, capitaine. Il a juré qu'il n'avait pas bu une goutte.",
"Attendez-moi ici, les gars!",
"Non, capitaine! Je viens avec toi! Ne va pas seul dans l'antre du lion!",
"Je ne suis pas une petite fille, je n'ai pas besoin de chaperon.",
"Certes non, capitaine. Mais... Tu reviens de très loin! Accepte, pour ma tranquillité d'esprit.",
"Non, non. Plusieurs personnes ne feraient qu'attirer l'attention.",
"Mais qu'allons-nous faire en ton absence?",
"Vous profiterez du rhum. Oh, et demande à quelques marins de m'attendre à la sortie d'Oxbay.",
"Tu penses devoir quitter précipitamment la ville?",
"J'espère que non, mais on ne sait jamais!",
"Ai-je une chance de te faire changer d'avis, capitaine? Deux solides gaillards pourraient t'aider à venir à bout des ennuis qu'ils risquent de s'attirer.",
"Alors, laisse-les garder le navire. Je serai revenu avant même que tu ne t'aperçoives de mon absence.",
"Très bien. On va t'attendre ici, capitaine! En cas de problème, reviens ici au plus vite. On te couvrira!",
"D'accord. Mais ne te montre pas avant!",
"On va l'emmener au navire, capitaine, je suis ravi que tout se soit bien terminé.",
"Vraiment? Va, maintenant. Je te rejoins très vite!",

};
