string DLG_TEXT[88] = {
"Bienvenue dans ma taverne, étranger. Je m'appelle ",
". Qu'est-ce qui t'amène dans mon humble établissement? Tu cherches un endroit où te reposer?",
"Merci. Je m'appelle ",
". Je suis ici pour affaire.",
"Je m'appelle ",
"et je n'ai pas besoin de ton hospitalité. Je suis ici pour affaires.",
"Quel genre d'affaires?",
"J'ai besoin de renseignements et pour cela, j'ai l'habitude de m'adresser à l'aubergiste du coin.",
"Je voudrais engager des marins à bord de mon navire.",
"Désigne-moi les clients susceptibles de chercher du travail. J'ai besoin d'hommes pour mon équipage et peu importe si ce sont des assassins.",
"Est-ce que tu aurais une chambre? Je voudrais séjourner ici un moment.",
"Aurais-tu un lit de libre dans cette masure?",
"Je n'ai pas besoin de toi pour le moment. Au revoir.",
"C'est vrai. J'entends presque tout ce qui se dit ici. Qu'est-ce que tu veux savoir?",
"On dit qu'il y a un fort de pirates quelque part dans la jungle. Je voudrais en connaître le chemin.",
"Je me demande si le navire '",
"Ship Storage",
"' est venu au port.",
"Je cherche un certain ",
"Raoul Rheims",
"Raoul Rheims",
". Est-ce que tu sais s'il se trouve sur l'île?",
"J'ai entendu dire que des pirates ont fait leur apparition sur l'île. Est-ce que c'est vrai?",
"Je cherche un certain Rheims. Est-ce que tu l'as vu?",
"Quoi? Mon or ne t'a pas porté chance?",
"J'ai besoin de travailler. Y a-t-il sur cette île des gens riches qui ont peur de voyager seuls?",
"Je n'ai pas de question pour le moment. Changeons de sujet.",
"Peut-être. Les rumeurs, ce n'est pas ce qui manque par ici.",
"J'ai l'impression que tu en sais plus que ça. Comme l'emplacement de la planque des pirates!",
"Désolé, tu avais une question à me poser? J'entends très mal.\nMais avec 3 000 pièces, ça pourrait s'arranger.",
"Voilà ton remède : exactement 3 000 pièces.",
"Ça fait cher le renseignement, non?",
"Bien, bien. Tu voulais trouver la cachette des pirates? Elle se trouve dans la jungle, à l'abri des regards indiscrets. ",
"Ça, je le savais déjà. Continue.",
"Écoute-moi bien, mon ami. La route qui part de la porte de la ville mène droit à la jungle. Tu verras d'abord un chemin allant vers la gauche. Ne le prends pas, continue tout droit. À la bifurcation suivante, tourne à droite.\nÀ la troisième, prends à gauche et tu y seras.",
"Merci. Ça n'a pas été un bien gros travail pour une telle somme, n'est-ce pas?",
"Eh bien, à toi de voir. Mais ça m'étonnerait que tu la trouves tout seul.",
"D'accord, je vais payer. Parle.",
"On verra.",
"Oh, je te demande pardon, ",
"! Je t'en prie, pardonne-moi. Je ne me rendais pas compte que tu étais... Tiens, je te rends tout. Je te paierai même davantage!",
"Eh bien, merci.",
"Tu as de la chance, mon ami. C'est lui, à la table près de la fenêtre.",
"Merci!",
"Il est venu ici plusieurs fois, mais il y a longtemps. Je me souviens de lui parce qu'il me payait avec des pièces indiennes en or massif.",
"Eh bien, merci. C'est toujours mieux que rien. J'ai autre chose à te demander.",
"Je suis désolé. Je n'en sais rien.",
"C'est dommage. Et je n'ai pas de quoi payer la location d'un navire...",
"Alors, tu cherches du travail? Pour être franc, il n'y en a pas beaucoup par ici. Mais on dit qu'il y a des pirates quelque part sur notre île qui acceptent n'importe qui dans leurs rangs.",
"Je suppose que je n'ai pas d'autre choix que d'aller leur proposer mes services.",
"Pourquoi veux-tu aller là-bas, si ce n'est pas indiscret?",
"Je dois parler à ",
"Alistair Garcilaso",
"Alistair Garcilaso",
". J'aimerais lui acheter quelque chose.",
"Si je comprends bien, tu parles de...",
"Tu vérifies mon histoire, hein? D'accord, je vais jouer le jeu. Il s'agit de babioles indiennes.",
"Ça n'a rien de personnel. Je dois contrôler tout le monde en ces temps difficiles. Attends-moi ici, je vais voir ce que je peux faire.",
"Je ne bouge pas.",
"Dépêche-toi. Je n'ai pas que ça à faire.",
"Il est un peu trop tard pour trouver de bons marins aujourd'hui. Ils sont tous rentrés se coucher à l'heure qu'il est. Reviens demain matin. Ou passe la nuit ici, à la taverne.",
"D'accord. Tu as une chambre?",
"Je n'ai pas besoin de chambre pour le moment. Changeons de sujet.",
"J'ai une chambre libre. Combien de temps comptes-tu rester?",
"Une nuit.",
"Jusqu'à la tombée de la nuit.",
"Bien. Ça fera 5 pièces d'or.",
"D'accord. Tiens.",
"Hélas, je crois que je n'ai pas les moyens de m'offrir mieux qu'une nuit dans la salle de la taverne.",
"Quoi? Avec des serviteurs rien que pour moi? Je passe.",
"Je vais y réfléchir.",
"Peut-être plus tard. Pour le moment, j'ai autre chose à te demander.",
"Bien. Ça fera 5 pièces d'or.",
"D'accord. Tiens.",
"Hélas, je crois que je n'ai pas les moyens de m'offrir mieux qu'une nuit dans la salle de la taverne.",
"Je vais y réfléchir.",
"Chers visiteurs! Arrêtez ça! Ne m'obligez pas à appeler les gardes!",
"D'accord, d'accord! Je m'en vais!",
"Ils préfèrent peut-être voyager avec moins de compagnie.", 
"Oui, j'ai oublié. D'accord, je reviendrai plus tard, quand j'aurai moins de navires, ha ha.",
"Je ne veux pas t'aider. Tu as causé beaucoup trop d'ennuis à mon pays",
"Quel patriote! Bon, au revoir", 
"Tu as du sang plein les mains. Comment veux-tu que quelqu'un accepte de voyager avec toi?",
"Tu as raison, tout le monde a peur de moi! Ha ha!",
"Tu arrives au bon moment. Un marchand du coin cherche quelqu'un avec qui voyager. Tu devrais aller lui parler. Le voilà, il entre dans la taverne.",
"D'accord.",
"Non, il n'y a personne pour le moment. Peut-être une autre fois.",
"Hum, alors je vais attendre.",

};