string DLG_TEXT[28] = {
"Où que tu ailles, étranger, passe ton chemin.",
"Attends, étranger! Ne me tue pas.",
"Désolé! J'ai dit que je t'éliminerais et je compte tenir ma promesse.",
"Qu'est-ce que tu veux?",
"Content de te revoir. Tu t'es enfin décidé à m'engager?",
"Oui. Combien pour tes services?",
"À la prochaine fois.",
"Je ne veux pas me battre avec toi. Je ne suis pas assez bête pour affronter plus fort que moi.",
"Tu te débines? Tu ne veux pas relever un vrai défi, pour une fois? Ça te changerait des amateurs!",
"Ça me paraît raisonnable. Alors, qu'est-ce que tu veux?",
"Te servir! Personne ne m'a encore jamais vaincu lors d'un combat direct. À part toi.",
"Désolé, mais je n'ai pas besoin de tes services pour le moment.",
"Dans ce cas, bienvenue dans mon équipage.",
"Ravi d'être à ton service, capitaine. Je m'appelle ",
".",
"Et moi, je suis ",
". Parlons de ton salaire.",
"Je suppose que 2 000 pièces d'or par mois suffiront.",
"Voilà ton argent.",
"Le problème, c'est que je suis à court d'argent en ce moment. Mon navire a disparu corps et biens dans la tempête. Je ne peux pas te payer tout de suite.",
"Non, c'est trop pour moi.",
"Ce n'est pas un problème. J'attendrai aussi longtemps qu'il le faudra.",
"Eh bien, dans ce cas, marché conclu. ",
"Désolé, c'est impossible. Mais reviens quand tu auras l'argent.",
"D'accord.",
"C'est dommage. Eh bien, reviens me voir si tu changes d'avis.",
"À bientôt.",
"Tu n'auras pas à attendre. Je vais te tuer!",

};