string DLG_TEXT[42] = {
"Ravi de te rencontrer, ",
". Je m'appelle ",
"et je suis à ton service.",
"Je m'appelle ",
", capitaine.",
"Content de te revoir, ",
".",
"Toi?! J'espérais ne jamais te revoir.",
"Bonne journée à toi aussi, ",
".",
"Pas question.",
"Veux-tu jeter un coup d'œil à mes marchandises?",
"Bien sûr. Montre-moi ça.",
"Plus tard. Discutons d'abord.",
"Peut-être la prochaine fois.",
"As-tu des marchandises à vendre ou cherches-tu simplement quelques objets personnels, capitaine?, ",
"J'aimerais vendre la cargaison que j'ai transportée.",
"J'aimerais acheter quelques bricoles pour moi.",
"Nous ne ferons pas affaire. Au revoir.",
"J'écoute.",
"On m'a demandé de te livrer une cargaison.",
"Tu as sûrement besoin du travail à confier. Je serais ravi de te proposer mes services.",
"Désolé, mais cette conversation ne m'intéresse plus.",
"Non, je n'ai pas besoin de tes services... Pas tant que tu couleras des navires hollandais.",
"Dans ce cas, au revoir.",
"Je suis désolé, mais je n'ai rien à te proposer pour le moment.",
"Alors, je reviendrai plus tard.",
"Je suis désolé, mais ton navire n'est pas fait pour la mission que j'ai en tête.",
"Alors, je reviendrai plus tard.",
"Oh! J'allais justement te demander de me rendre un service. En fait, je voudrais que tu livres une cargaison à ",
" et au plus vite. Si le voyage ne dépasse pas un mois, tu recevras ",
" pièces d'or à ton arrivée. Que dis-tu de cette offre?",
"Elle me convient.",
"Je ne peux pas l'accepter.",
"Je t'ai déjà dit aujourd'hui que je n'ai rien pour toi.",
"Oh, désolé.",
"Tu t'es souvenu de ta mission un peu tard, tu ne crois pas? J'ai déjà reçu tout ce qu'il me fallait. Au revoir.",
"Adieu.",
"Oh! C'est ce que j'attendais. Voilà ta récompense, jeune homme.",
"Je t'en prie.",
"Désolé. Je n'ai rien pour toi pour le moment.",
"C'est dommage. Alors, tu répondras peut-être à quelques questions.",

};