string DLG_TEXT[24] = {
"Bienvenue dans la maison du Seigneur, mon fils. En quoi puis-je t'être utile?",
"...",
"Je voudrais te poser quelques questions sur un prêtre, un certain ",
"Father Jerald",
"Father Jerald",
".",
"Ah! Tu dois être l'inquisiteur. Mes requêtes portent enfin leurs fruits!",
"Penchons-nous sur quelques détails. Si je comprends bien, tu prétends que ce prêtre mène une vie cupide et dépravée.",
"Oui. Et je ne porte pas ces accusations à la légère. J'ai des preuves. ",
"Quel genre de preuves?",
"J'ai en ma possession des lettres d'amour qu'il a écrites à une jeune femme.",
"C'est scandaleux! Puis-je te les emprunter?",
"Bien sûr. Tiens, les voilà.",
"Pardonne-moi, mais je dois te demander comment tu as mis la main dessus.",
"La jeune femme me les a remises en espérant que je l'aiderais à mettre un terme aux agissements du prêtre.",
"Je vois. Eh bien, je dois lui parler pour vérifier si tu dis vrai. Peux-tu m'indiquer comment elle s'appelle et où je peux la trouver?",
"Certainement. Elle s'appelle ",
"Greenford_officiant",
"Greenford_officiant",
". Elle travaille à la taverne.",
"Tout cela est très intéressant. Mais je dois te prévenir que j'ai déjà conclu à l'innocence du prêtre. Il a été accusé à tort.",
"Merci de ton aide.",
"Innocent, lui? Qui préfères-tu croire? Les gens d'ici, qui ont avalé l'histoire du prêtre alors qu'il était complètement saoul ou moi qui viens de te remettre la preuve de sa culpabilité?",
"Je n'ai encore rien décidé. Mais je vais enquêter sur ton histoire et tu peux être certain que, dans cette affaire, les coupables seront punis.",

};