string DLG_TEXT[44] = {
"Qu'est-ce qui t'amène ici?",
"Le gouverneur ",
"Robert Christopher Silehard",
"Robert Christopher Silehard",
" m'a chargé de te remettre cette lettre et de prendre un prisonnier.",
"Le gouverneur ",
"Robert Christopher Silehard",
" m'a chargé de lui rapporter l'idole inca sacrée.",
"J'ai ordre de libérer un de tes prisonniers.",
"Je dois parler à un prisonnier.",
"Bon vas-y. Parle-lui.",
"D'accord.",
"Je ne fais que passer.",
"C'est que, en général, nous n'acceptons pas les visiteurs...",
"Mais il s'agit d'une importante affaire d'état!",
"Quelle affaire? De quoi parles-tu?",
"Tu as dû entendre parler des rapts d'enfants et autres choses étranges qui ont lieu dans l'archipel. Je pense que ton prisonnier peut m'aider à éclaircir tout ça!",
"S'il te plaît, je dois parler à cet homme!",
"D'accord. Je n'y vois pas d'inconvénient. Après tout, on le pend cet après-midi.",
"Bien. Merci.",
"Tu perds ton temps. Bien que... si tu pouvais me rendre un service...",
"Quel service?",
"Mon fils se marie bientôt. Je voudrais qu'il ait un bon mariage. Si tu veux parler au prisonnier, ça te coûtera 5 000 pièces d'or.",
"Voici ton argent.",
"Ça m'étonnerait que ça arrive. Je peux te proposer une autre solution?",
"Tu me fatigues. Va-t-en. Tu ne parleras à personne!",
"Dommage qu'on en soit arrivé là, mais tu ne me laisses pas le choix...",
"C'est bon. Mais je reviendrai.",
"Qu'est-ce que...",
"Tu vas m'amener le prisonnier maintenant, sinon je t'étripe!",
"Tu vas payer pour ça!",
"Probablement. Mais pas aujourd'hui. Aujourd'hui, tu es mon prisonnier et je veux parler au tien.",
"D'accord! Tu peux lui parler.",
"...",
"Montre-moi ça. Mmh...le Professeur en personne, hein? D'accord, tu peux l'emmener.",
"Bien.",
"D'accord. Mais montre-moi les ordres d'abord.",
"Ça ne va pas? Tu sais que je travaille directement pour le gouverneur et tu me demandes de te montrer un bout de papier?!",
"Désolé, mais moi aussi j'ai mes ordres. Je dois envoyer l'idole par vaisseau de guerre à Redmond, et j'ai ordre d'arrêter quiconque essaiera de la prendre sans les bons documents. Gardes!",
"Bon sang!",
"Désolé, mais je ne peux pas te remettre le prisonnier pour le moment.",
"Que veux-tu dire, tu ne peux pas me le remettre?",
"Dis au Gouverneur que le prisonnier... s'est échappé hier soir, et que nous ne l'avons toujours pas retrouvé.",
"Compte sur moi, je le lui dirai. Si j'étais toi, je retrouverais cette fripouille!",

};
