string DLG_TEXT[31] = {
"Je regrette, il faut que je m'en aille.",
"...",
"Je t'en supplie, ",
"! Aide-moi!",
"Que se passe-t-il ici?",
"Ils veulent tuer le vieillard!",
"Où sont donc les soldats? Ce sont eux qui maintiennent l'ordre dans cette ville, pas moi.",
"Les soldats doivent vivre ici, pas toi! Et tu m'as l'air de quelqu'un de bien : tu ne pourrais pas sauver ce pauvre vieillard? Ces barbares vont le brûler!",
"Pourquoi? Qu'est-ce qu'il a fait?",
"Tu continues à me poser des questions pendant qu'ils le tuent?",
"La foule est en train de préparer le feu. Tu as tout le temps qu'il faut pour répondre à mes questions.",
"Comment peux-tu être aussi calme?!",
"Appelle-ça une déformation professionnelle. Ils attachent en ce moment le vieillard au bûcher. Parle avant qu'il ne soit trop tard.",
"D'accord! Il est accusé de sorcellerie mais, crois-moi, c'est un homme tout à fait normal. Il vit seul dans le phare et n'a jamais fait de mal à personne!",
"Pourquoi veulent-ils tous le brûler, alors? Et pourquoi personne d'autre ne cherche à le sauver?",
"C'est un fou inoffensif. Il n'arrête pas d'inventer des choses, mais la plupart d'entre elles n'ont pas marché comme prévu, et il a donc froissé pas mal de gens.",
"Oui, ils semblent furieux en effet.",
"Quelque chose a explosé dans le phare ce matin, et un nuage nauséabond a envahi toute la ville.",
"Il a dû créer un sacré nuage pour mériter un sort pareil. Mais dis-moi pourquoi personne d'autre ne cherche à le sauver.",
"Ma fille est tombée gravement malade et personne n'a pu rien pu faire elle. Mais le lettré ",
"researcher",
", lui, a trouvé un remède dans un vieux manuscrit indien!",
"En effet, il mérite d'être sauvé. Je ferai de mon mieux. Il s'appelle comment, déjà? ",
"researcher",
"?",
"C'est une histoire très émouvante. Mais je ne sais pas si elle l'est assez pour me pousser à affronter une foule en colère.",
"Oh, Dieu te bénisse! Tu fais quelque chose de bien!",
"Je ferai de mon mieux.",
"Tu n'as donc pas de cœur?! Tu n'es pas mieux que tous ces assassins qui préparent le bûcher!",
"Pas de cœur?! J'ai un cœur gros comme une baleine! Et s'il faut te le prouver, je le ferai!",
"Je n'ai peut-être pas de cœur, mais je ne peux pas rester là sans ne rien faire. Je ferai ce que je peux pour aider ce vieillard.",

};
