string DLG_TEXT[87] = {       
"Tu ne vois pas que je suis de service? Laisse-moi tranquille.",
"D'accord, d'accord.",
"Tu voulais signaler un crime?",
"Non, bien sûr. Je suis capitaine, après tout...mais je vois que tu n'écoutes pas.",
"N'oublie pas : les combats de rue sont interdits. Mais tu peux te défendre, bien sûr, si on t'attaque.",
"Bien, je tiendrai compte de cette information.",
"Quel temps...et je dois rester ici. Difficile à croire, mais mon seul passe-temps est d'essayer d'empêcher les mouches de se poser sur mon visage.",
"C'est fort dommage, mais je ne peux rien y faire. C'est ton travail.",
"Si tu veux bavarder, trouve quelqu'un d'autre. J'ai du travail, et il ne consiste pas à bavarder avec toi.",
"Je me demandais juste si tu étais vivant. Tu es là, debout comme une statue.",
"Tu penses qu'il est facile de protéger notre ville? Pas du tout! C'est une tâche aussi importante que périlleuse. Je me souviens, une fois...",
"Tu me raconteras ça une autre fois. Je dois m'en aller.",
"Poursuis ton chemin, ne m'importune pas.",
"Comme tu voudras, soldat.",
"Eh! Tu pourrais me ramener un godet de rhum de la taverne?",
"Peut-être. Mais je ne risque pas d'être pendu si j'aide un soldat de garde à se saouler? Non, attends la relève et tu pourras boire autant que tu voudras.",
"Pourquoi dois-je parler à un marin aussi vilain que toi?! N'y a-t-il aucune jolie femme dans cette ville?",
"Et tu appelles ça être de service? Dis-moi, tu ne voudrais pas rater pas l'occasion de capturer un dangereux criminel comme moi, si? Ha-ha!",
"Tu as l'air en bonne santé. Tu ne voudrais pas t'engager dans notre armée? Nous avons beaucoup de place dans notre caserne, la chère est bonne et le rhum est gratuit.",
"C'est une offre alléchante, mais je ne peux pas l'accepter. Je n'aime pas la discipline militaire.",
"Quelle chaleur.... Je donnerais tout pour retourner dans mon beau Portugal.",
"Oui, on dirait que le climat ne te convient pas.",
"J'ai besoin que tu m'aides à sauver un homme.",
"Je voudrais en savoir plus sur ce qui se passe en ville.",
"Qu'est-ce que tu veux savoir exactement? Il se passe toujours quelque chose en ville. Je ne connais pas toutes les rumeurs. Tu devrais demander à la taverne.",
"Je pense que tu peux m'aider. Je voudrais des informations sur un homme qui a pris la fuite après avoir été accusé de meurtre.",
"Ah, oui! Bien sûr, je suis au courant",
"Raconte-moi tout. Son Excellence le gouverneur, m'a chargé d'enquêter sur cette affaire.",
"Comment savoir si tu représentes le gouverneur?",
"Regarde, cette lettre a été signée par le gouverneur lui-même.",
"De toute façon, il faudrait que tu parles au commandant de la prison, ",
", il est plus informé à ce sujet.",
"Je lui parlerai plus tard, mais pour l'instant, je voudrais savoir ce que tu sais.",
"D'accord, pose tes questions.",
"Raconte-moi tout : comment il a été arrêté, ce qu'il avait sur lui et comment il s'est échappé.",
"Il était tard, la nuit, et mon collègue et moi faisions une patrouille dans les rues...",
"Tu veux dire que c'est toi qui l'as arrêté?",
"C'est vrai.",
"Continue.",
"Tout à coup, nous avons vu une fille habillée en homme sortir d'une maison avec du sang sur les bottes.",
"Tu dis que tu as vu du sang sur ses bottes cette nuit-là?",
"Je l'ai vue à la lumière de la rue.",
"Ah. Et alors?",
"Nous l'avons arrêtée, et puis, quand on a vu un cadavre dans une mare de sang, nous avons embarqué la fille.",
"Je vois. As-tu trouvé quelque chose d'intéressant sur elle?",
"J'avais commencé à la fouiller, et puis on m'a interrompu.",
"Que veux-tu dire?",
"Devine un peu? Un type a essayé de voler un petit bateau et, quand on l'a attrapé, il avait sur lui une étrange idole en or.",
"Très intéressant. Et où est cette idole?",
"Pour mon malheur, le capitaine était en patrouille de nuit. Il a pris l'idole.",
"Merci de ton aide, soldat.",
"De rien, ",
", il est de mon devoir de protéger les citoyens.",
"Parfait! Dans ce cas, aide-moi à empêcher l'assassinat d'un homme.",
"Euh.... Écoute, ",
" Je ne peux pas t'aider.",
"Et pourquoi pas, soldat? N'est-il pas un citoyen de la ville?",
"Bien sûr.",
"Et alors? J'espère que tu ne le considères pas comme un sorcier...",
"Non! S'il en était un, il se serait envolé et échappé.",
"Alors pourquoi refuses-tu de m'aider?",
"Il faut comprendre, tout le monde croit que c'est un suppôt de Satan, et ça, la ville ne l'accepte pas.",
"Tu crains des troubles à l'ordre public?",
"En quelque sorte, ",
".",
"Et si je vous offrais 200 pièces d'or, à toi et à ton collègue?",
"Je suis de garde!",
"Je vois que je n'arriverai pas à te persuader.",
"D'accord, ",
". Donne-moi l'argent. Nous sommes six en tout ici, cela fait donc 1200 pièces d'or. Ne t'en fais pas, l'homme est sain et sauf.",
"Bien, voici ton argent.",
"Non, je n'ai pas autant d'argent.",
"Va-t-en, ",
".",
"Amène-moi le vieil homme, j'attendrai près de la porte.",
"Ne me parle pas comme ça, ",
"! Je sers l'Angleterre!",
"Écoute! Un innocent meurt et tu ne fais rien? Tu ne sers rien ni personne... Tu es trop timoré pour faire face au moindre danger!",
"Peut-être, ",
"! Mais pour te montrer que je ne suis pas une mauviette, je t'amènerai ton homme. Attends près de la porte.",
"Ça me va, mon ami.",
"Qu'est-ce que tu veux?",
"Tu... hic... espèce de canaille! Tu as fait mal à... hic... mon ami!",
"Quel ami? Tu es tout seul ici, ",
".",
"Quoi? Il était... là il y a une minute. Je vais le retrouver. Toi... hic... tu ne bouges pas d'ici si tu veux ta raclée....",
"Comment oses-tu me contredire! Je vais t'étrangler!",

};
