string DLG_TEXT[98] = {
"Eh, garçon, tu m'as l'air d'un marin expérimenté! Tu m'offres un godet de rhum, dis?",
"Je ne suis pas d'humeur charitable.",
"Bien sûr. J'en prendrai une, moi aussi.",
"Eh! Tu veux jouer aux dés? Je reviens d'une expédition très enrichissante et j'ai de l'argent à perdre!",
"Vraiment? Tu n'en as pas l'air.",
"Ne me dérange pas, je bois!",
"...",
"Du balai! Tout le monde dit que tu es le meilleur joueur de dés de ces îles. Tu ne m'y prendras pas.",
"D'accord.",
"On dit que tu es un bon joueur de dés. Tu veux essayer?",
"Pourquoi pas? Allons-y.",
"Pas pour l'instant.",
"Eh, garçon! Tu veux faire une partie de dés?",
"Oh! Content de te voir, ",
". Tu veux jouer aux dés? Faire rouler les vieux os?",
"Oui, bien sûr! Allons-y.",
"Une autre fois, peut-être.",
"J'ai déjà perdu une fortune, mais il me reste quelque chose à miser!",
"Tu miserais quoi? Ton vieux manteau tout miteux?",
"Non, non, non! J'ai encore du butin. Regarde!",
"D'accord. Voyons ce que tu caches.",
"Euh... Je ne peux pas te montrer ça ici. Mais j'ai loué une chambre tout près. On y va?",
"Non, merci. Une autre fois, peut-être.",
"D'accord. Je le regretterai probablement, mais tu as éveillé ma curiosité. Faisons quelques pas.",
"Tavernier! Garde-nous cette table! Nous serons de retour bientôt.",
"Personne ne va la prendre. Allons-y.",
"Tu vois cette beauté? Je la miserai si tu me laisses gagner un peu de ton argent.",
"C'est vrai qu'elle est belle...",
"Une déesse! Mais le jeu passe avant.",
"D'accord. Jouons!",
"Comment oses-tu faire une telle mise?!",
"Bon, d'accord! On suit les règles habituelles! 100 pièces d'or à chaque tour!",
"Parfait, mais jouons ici. Tu as les dés?",
"Oui. Je commence... ",
"!!!",
"C'est mon tour. J'ai... ",
"! Tu as perdu, mon garçon!",
"Bon sang! La chance m'a quitté! Bon, prends la fille et dégage!",
"Avec plaisir.",
"Quoi?",
"Sale porc! Tu ne mérites pas de vivre!",
"Tu essaies de me jouer un tour? Ça ne marchera pas!",
"Si ce sont les ennuis que tu cherches, tu les a trouvés!",
"Allons-y! Je mise 100 pièces d'or.",
"Je te suis. Jette les dés.",
"Je ne joue pas.",
"Assez! Je ne joue plus avec toi.",
"Comme tu veux. Je vais trouver quelqu'un d'autre.",
"! J'ai vu de meilleurs lancers. À ton tour.",
"! Ce n'est pas brillant, mais voyons si tu peux faire mieux.",
"! Pas mal, pas mal! Mais il faut que tu fasses encore mieux.",
"! Je me sens en forme aujourd'hui!",
"Passe-moi les dés.",
"! ",
"Tu as perdu, mon garçon!",
"Tu prends. Mais je te parie que je gagnerai cette fois-ci!",
"D'accord, tu gagnes. Je ne joue plus.",
"! ",
"Tu as gagné! Saleté! Bon, encore une fois.",
"Essaie, mais tu ne gagneras pas.",
"Pas cette fois-ci.",
"Hum. Égalité. J'ai horreur des matches nuls. Encore une fois?",
"D'accord. Jette les dés.",
"Non, je ne veux pas tenter le diable.",
"Ça, j'aime bien! Alors, tu me l'offres, ce godet de rhum?",
"Certainement! Tavernier! Du rhum!",
"Tu es un ami! À notre santé!",
"Ahhh! C'est fort!",
"À ta santé et à ta générosité!",
"Kof, kof, kof... Une vraie douceur! Bon, il faut que je parte. A bientôt.",
"On en prend un autre?",
"Pourquoi pas, puisque tu insistes!",
"Tavernier! Encore du rhum!",
"Tu... tu essaies de me saouler pour me voler mon argent!",
"Calme-toi! Je suis ton ami, tu as oublié?",
"Ferme-la, vermine, avant que je ne t'étripe!",
"Écoute, tu es un type bien. Tu pourrais m'aider à sortir... d'une situation délicate?",
"Non. Je dois m'en aller.",
"Bien sûr! On est amis, non?",
"... Et puis j'ai saisi la lame de son épée et...",
"... et elle me dit, elle me dit...",
"À la tienne! Ah, qui c'est, ça?",
"Hein? Quoi? Où?",
"C'est que, tu vois, l'un des soldats m'a insulté... ouais!",
"Des soldats? Non, non. Je passe.",
"Insulté? Où est-il? Montre-le moi!",
"Tu n'es pas mon ami! Non! Tu veux... me... me tuer! C'est ça. Tu veux me tuer!",
"Bon, je vois que tu en as eu assez pour aujourd'hui. A bientôt!",
"Quoi? Je ne veux pas te tuer! Arrête de dire ça ou te tranche la tête!",
"À l'aide! Éloignez-le de moi!",
"Calme-toi, ça ne fera pas mal!",
"Ahhh! Je vais te saigner comme un porc!",
"C'est ce qu'on va voir!",
"Quel entêtement! Viens ici ou je me plaindrai à ton maître et il te jettera à la rue!",
"Tu es saoul, espèce de porc! Tu as de la chance que je n'aie pas envie de me salir les mains en te donnant une leçon!",
"Quoi? C'est moi qui vais te jeter dehors!",
"Où as-tu obtenu une épée? Je vais te montrer!",
"La seule chose que tu puisses me montrer, c'est comment se rendre ridicule! Lève-toi et nous verrons si tu es à la hauteur!",

};