string DLG_TEXT[30] = {
"Bonjour. Je suis un officier ",
" de sa Majesté le roi de France.",
"Je m'appelle ",
".",
"Tu veux juste faire un brin de causette ou tu as quelque chose d'important à me dire? ",
"J'ai pensé qu'on pourrait peut-être discuter un peu.",
"Je suis ici pour affaire, officier. Une affaire plutôt importante.",
"J'ai peur de te décevoir dans ce cas, ",
". Je n'ai pas le temps de bavarder.",
"Désolé.",
"Quel genre d'affaire?",
"Il s'agit d'un marchand qui s'appelle ",
"Patric Cardone",
"Patric Cardone",
".",
"L'homme à qui on a volé les reliques indiennes.",
"C'est cela.",
"Et en quoi cela me concerne-t-il?",
"Est-ce que tu sais où habite ",
"Lucien Bescanceny",
"Lucien Bescanceny",
"?",
"Bien sûr, oui. Il est bien connu pour ses activités illégales.",
"En effet. Et si tu lui rends visite, tu verras qu'il a beaucoup de choses intéressantes à raconter au sujet des statuettes qui ont disparu.",
"Qu'est-ce qui te fait croire qu'il acceptera de me parler?",
"Peut-être qu'il ne te parlera pas. S'il refuse, fouille sa chambre. Tu y trouveras les statuettes.",
"Comment peux-tu en être certain?",
"J'ai déjà été chez lui. Il a tout avoué.",
"D'accord, je vais lui parler. Mais si c'est une embrouille...",
"Ce n'en est pas une, officier. Tu verras.",

};