string DLG_TEXT[195] = {
"Fais don d'une pièce à un pauvre malheureux, ",
" et Dieu remerciera ta générosité!",
"De grâce, aide-moi à acheter de la nourriture et... peut-être un verre! Je t'en supplie!",
"Oh, ",
", sois charitable envers ceux qui ont moins de chance que toi, de grâce!",
"Désolé, mais je ne fais pas la charité.",
"Je n'ai pas plus petit qu'une pièce d'or. Est-ce qu'elle te suffira à te nourrir pendant quelques jours?",
"Je ne te donnerai pas d'argent, mais je vais te permettre d'en gagner, si tu le veux.",
"Merci, ",
"! Que la chance t'accompagne partout! Elle le fera, tu verras!",
"Bon, je t'ai donné une pièce. À présent, tu peux me remercier en répondant à quelques questions.",
"Merci. Tu peux t'en aller maintenant.",
"Se pourrait-il, ",
", que tu n'aies même pas assez d'argent pour faire la charité? Tu devrais peut-être, euh, travailler avec moi. ",
"(Return.)",
"Mes connaissances sont aussi pauvres que moi. Mais pose toujours tes questions, ",
", et j'essaierai d'y répondre.",
"Tu connais bien la ville?",
"As-tu des informations sur le gouverneur de Redmond?",
"Tu as peut-être raison. Je perds mon temps à poser des questions à un mendiant.",
"Désolé, ",
", mais je ne suis qu'un pauvre malheureux abandonné par la chance et les amis. Je ne sais rien qui puisse t'être utile\n Tu ferais mieux de demander aux soldats du coin.",
"Tu as peut-être raison. Je perds mon temps à poser des questions à un mendiant.",
"Pour le moment, je ne demande à personne d'autre. Je te demande à toi.",
"Se pourrait-il, ",
", que tu n'aies même pas assez d'argent pour faire la charité? Tu devrais peut-être, euh, travailler avec moi. ",
"(Return.)",
"Oh! Je le connais mieux que sa propre mère, si j'ose dire! Que veux-tu savoir, au juste, ",
"?",
"Où puis-je trouver la taverne?",
"Où est le chantier naval?",
"Où pourrai-je vendre les marchandises que j'ai apportées avec moi?",
"La charité est une vertu, ",
", mais les renseignements, ça se paie.",
"Tu rigoles? Je ne vais pas payer un mendiant pour avoir des renseignements!",
"Combien?",
"J'écoute, ",
"Tu connais bien la ville?",
"As-tu des informations sur le gouverneur de Redmond?",
"Tu as peut-être raison. Je perds mon temps à poser des questions à un mendiant.",
"Tu cherches un endroit pour te reposer après un long voyage? Prends cette rue et va tout droit. Arrivé à la place, tu verras la résidence du gouverneur devant toi. La taverne est sur ta droite.",
"Parfait. Merci.",
"Où est le chantier naval?",
"Où pourrai-je vendre les marchandises que j'ai apportées avec moi?",
"Le chantier naval est derrière les portes de la ville, sur le rivage, mais le bureau du directeur, ",
", se trouve à gauche des portes. Tu verras le panneau, ",
".",
"Merci. Et où pourrais-je trouver la taverne?",
"Où pourrai-je vendre certaines des marchandises que j'ai apportées avec moi?",
"Merci pour les renseignements. Ca sera tout pour le moment.",
"Prends la rue centrale ",
". Arrivé à la place, tu verras une fontaine. Regarde à droite. Tu trouveras ce que tu cherches.",
"Où est le chantier naval de la ville?",
"Peux-tu me dire où se trouve la taverne?",
"Merci. Ca sera tout pour le moment.",
" pièces d'or, s'il te plait, ",
". Tu comprends, je prends des risques en te donnant ces renseignements.",
"D'accord, voici ton argent. Allez, crache!",
"Je ne paierai pas un tel prix. Je veux juste quelques réponses et tu n'as pas à les graver dans de l'or.",
"D'accord, d'accord. Approche, ",
". Garde ça pour toi : le gouverneur n'est pas quelqu'un de bien.",
"C'est tout? Rien d'autre à me dire? Il va falloir que tu me rembourses.",
"Apprends-moi quelque chose. Mieux : arrête de me faire perdre mon temps. File!",
"Je suis désolé, ",
". Il est clair que tu n'as pas beaucoup d'argent en ce moment.",
"(Return.)",
"Pas du tout, ",
"! Le gouverneur est cupide. Il cache bien ses intentions, mais rien ne l'arrête quand il est question d'or!",
"Jusqu'à présent, mon retour sur investissement laisse à désirer.",
"Parfait. Je garderai ça en tête. Au revoir.",
"Bon, écoute bien : le gouverneur a récemment armé un navire pour une longue expédition. On dit qu'il est à la recherche d'un trésor.",
"Beaucoup d'imbéciles perdent leur temps à chercher des trésors dans l'archipel. Pourquoi le gouverneur serait-il une exception? Je commence à croire que tu n'as rien d'important à me dire.",
"Fais don d'une pièce à un pauvre malheureux ",
" et Dieu remerciera ta générosité!",
"De grâce, aide-moi à acheter de la nourriture et... peut-être un verre! Je t'en supplie!",
", sois charitable envers ceux qui ont moins de chance que toi, de grâce!",
"Tu as oublié? Je n'aime pas la charité.",
"Encore toi? Bon, prends.",
"Je te donnerai de l'argent, mais tu répondras à quelques questions en retour.",
"Merci, ",
"! La générosité te sied à merveille! Que la chance t'accompagne toujours!",
"Au fait, je voudrais savoir quelque chose.",
"Merci. Tu peux t'en aller.",
"Hélas, ",
", il est clair que tu n'as pas assez d'argent pour faire la charité.",
"(Return.)",
"Bien sûr, ",
". C'est le moins que je puisse faire pour quelqu'un de si gentil. Demande-moi ce que tu veux.",
"Tu connais bien la ville?",
"Que sais-tu du Gouverneur de Redmond?",
"Tu sais, je n'arrive plus à trouver des questions à te poser.",
"Je suis vraiment désolé, ",
", mais je ne vois pas comment un pauvre type comme moi pourrait t'aider. Tu ferais mieux de demander aux soldats du coin.",
"Peut-être. Mais c'est à toi que je demande.",
"Tu as peut-être raison. Tu n'as pas les renseignements dont j'ai besoin.",
"Hélas, ",
", il est clair que tu n'as pas assez d'argent pour faire la charité.",
"(Return.)",
"Oh! Je le connais mieux que sa propre mère, si j'ose dire! Que veux-tu savoir, au juste, ",
"?",
"Où pourrais-je boire un coup et discuter?",
"Où se trouve le chantier naval?",
"Où pourrai-je obtenir le meilleur prix pour les marchandises que j'ai apportées avec moi?",
"Désolé, ",
". La charité est une vertu, mais les affaires sont les affaires. Pour les renseignements, il me faut de l'argent.",
"Tu rigoles? Je ne vais pas acheter des réponses à un misérable mendiant!",
"Combien?",
"J'écoute.",
"Tu connais bien la ville?",
"Que sais-tu à propos du gouverneur de Redmond?",
"Tu as peut-être raison. Tu n'as pas les renseignements dont j'ai besoin.",
"Ah, oui! Rien ne vaut un bon coup de rhum après une traversée. Prends cette rue et va tout droit. Arrivé à la place, tu verras la résidence du gouverneur devant toi. La taverne est sur ta droite.",
"Compris. Merci!",
"Où se trouve le chantier naval?",
"Où pourrai-je obtenir le meilleur prix pour les marchandises que j'ai apportées avec moi?",
"Le chantier naval est derrière les portes de la ville, sur le rivage, mais le bureau du directeur, ",
", se trouve à gauche des portes. Tu vois le panneau, ",
"?",
"Oui. Et où est la taverne?",
"Où pourrai-je vendre les bonnes marchandises que j'ai apportées avec moi?",
"Merci pour les renseignements. Ca sera tout pour le moment.",
"Prends la rue centrale ",
". Arrivé à la place, tu verras une fontaine. Regarde à droite. Tu trouveras ce que tu cherches.",
"Où se trouve la taverne?",
"Où est le chantier naval?",
"Merci. C'est tout ce que je voulais savoir.",
" de grâce, ",
", essaie de comprendre ce qui pourrait m'arriver si quelqu'un découvrait que je t'ai donné un renseignement que je ne devais pas te donner.",
"D'accord, c'est bon. Prends ton argent et parle!",
"A ce prix, je crois que je me passerai des secrets d'un mendiant.",
"Approche, ",
". Garde ça pour toi : le gouverneur n'est pas quelqu'un de bien.",
"C'est tout? C'est tout ce que tu as à me dire? Il va falloir que tu me rembourses.",
"Apprends-moi quelque chose. Mieux : arrête de me faire perdre mon temps. File!",
"Je suis désolé, ",
". Il est clair que tu n'as pas beaucoup d'argent en ce moment.",
"(Return.)",
"Pas du tout, ",
"! Le gouverneur est cupide. Il cache bien ses intentions, mais rien ne l'arrête quand il est question d'or!",
"Jusqu'à présent, mon retour sur investissement laisse à désirer.",
"Parfait. Je garderai ça en tête. Au revoir.",
"Bon, écoute bien : le gouverneur a récemment armé un navire pour une longue expédition. On dit qu'il est à la recherche d'un trésor.",
"Beaucoup d'imbéciles perdent leur temps à chercher des trésors dans l'archipel. Pourquoi le gouverneur serait-il une exception? Je commence à croire que tu n'as rien d'important à me dire.",
"Donne une pièce à un pauvre homme, ",
", et tu en recevras dix en retour!",
"De grâce, aide-moi à acheter de la nourriture et... peut-être un verre! Je t'en supplie!",
"Oh ",
", sois charitable envers ceux qui ont moins de chance que toi, de grâce!",
"Désolé, mais je ne fais pas la charité.",
"Encore toi? Bon, prends.",
"Merci, ",
". Ta générosité est un puits sans fond!",
"J'espère que tu pourras m'en dire plus sur une ou deux choses dont on a déjà parlé.",
"Merci. Tu peux t'en aller.",
"Se pourrait-il, ",
", que tu n'aies même pas assez d'argent pour faire la charité? Tu devrais peut-être, euh, travailler avec moi. ",
"(Return.)",
"Avec plaisir, ",
". Demande-moi n'importe quoi. C'est à propos du gouverneur?",
"Non, ça n'a rien à voir avec le gouverneur. Je suis juste un peu distrait en ce moment.",
"Exactement. Que m'as-tu dit à propos de lui?",
"Je n'ai aucune question pour toi pour le moment.",
"Je suis sûr que c'est entièrement ma faute si tu as oublié. J'ai tendance à dire des bêtises. Approche, ",
", pour que je puisse te parler en privé.",
"Je suis tout ouïe.",
"Tu trembles presque de peur! Parlons d'autre chose.",
"Ah! Pas de problème, ",
". Dis à ton vieil ami Henry où tu veux aller et je t'indiquerai le chemin, comme un bon compas de marine.",
"Où pourrai-je trouver la taverne?",
"Je cherche le chantier naval de Redmond.",
"J'ai des marchandises. Où pourrai-je les vendre?",
"Merci, ",
". Que puis-je faire d'autre pour toi?",
"J'ai besoin qu'on m'aide à trouver un endroit. ",
"Je n'ai besoin de rien, merci. Au revoir!",
"Ah, je comprends! Rien de mieux qu'un bon godet de rhum pour remonter le moral d'un marin après un long voyage. Prends cette rue et va tout droit. Arrivé à la place, tu verras la résidence du gouverneur devant toi. La taverne est sur ta droite.",
"Compris. Merci!",
"Où est le chantier naval?",
"Où pourrai-je vendre les bonnes marchandises que j'ai apportées avec moi?",
"Le chantier naval est derrière les portes de la ville, sur le rivage, mais le bureau du directeur, ",
", se trouve à gauche des portes. Tu vois le panneau, ",
"?",
"Oui. Et la taverne?",
"Où pourrai-je vendre mes marchandises?",
"Je vois. Merci de ton aide.",
"Prends la rue centrale ",
", et une fois sur la place, tu verras une fontaine. Regarde à droite. Tu trouveras ce que tu cherches.",
"Où se trouve le chantier naval?",
"Comment faire pour aller à la taverne?",
"Je vois. C'est tout ce que je voulais savoir.",
"N'oublie pas. Je t'ai dit que le gouverneur était un homme cupide qui ne reculerait devant rien pour s'enrichir davantage.",
"C'est juste. Et quoi d'autre?",
"Oui, je m'en souviens maintenant. Merci.",
"Le gouverneur a récemment armé un navire pour une longue expédition. On dit qu'il l'a envoyé à la recherche d'un trésor.",
"Oui. Ça me revient maintenant. Et j'ai dit qu'il y avait beaucoup d'imbéciles comme le gouverneur qui perdaient leur temps à chercher des trésors dans cette région.",

};