string DLG_TEXT[27] = {
", cher visiteur. Je suis ",
", propriétaire du chantier naval.",
"Moi, je suis ",
", capitaine du '",
"'.",
", ",
". Veux-tu utiliser les services de mon chantier naval, ",
"?",
"Oui, mon navire a besoin d'être réparé.",
"En fait, je préfèrerais discuter.",
"Non, merci.",
"Eh bien, je suis content de faire ta connaissance. Si tu es capitaine, tu as frappé à la bonne porte.",
"Parfait, ",
". Commençons ces réparations.",
"Merci. Mais laisse-moi d'abord te poser une question.",
"Peut-être la prochaine fois. Je dois m'en aller.",
"Qu'est-ce que tu veux savoir, exactement, ",
"?",
"Non, pas pour le moment.",
"Je vois. Te faut-il autre chose, ",
"?",
"Oui. Je voudrais utiliser les services de ton chantier naval.",
"C'est tout pour le moment, merci. Au revoir!",
"Que veux-tu exactement?",
"J'ai besoin de faire réparer mon navire ou j'envisagerai peut-être d'en acheter un autre.",
"Je veux faire installer de nouveaux canons sur mon navire.",
"Rien, merci.",

};