string DLG_TEXT[162] = {
"Que regardes-tu comme ça? Tu ne t'attendais pas à voir une femme aux commandes, c'est ça? Eh bien, la vieille ",
" peut te montrer qu'elle sait encore faire parler la poudre!",
"Hé, tu as été élevé chez les paysans, ",
"?",
"Eh, où as-tu appris les bonnes manières?",
"Je les ai apprises là où j'ai passé mon enfance... dans une cabane pourrie des faubourgs de Lisbonne. Elles suffisaient à l'époque, alors je ne vois pas pourquoi j'en changerais.",
"Les gosses, de nos jours... Comme tu voudras -- comporte-toi comme un loup de mer si tu veux, mais suis mon conseil : ne parle pas comme ça sans savoir à qui tu t'adresses!",
"Eh bien, je m'appelle ",
".",
"Garde tes conseils pour toi, ",
".",
"Que veux-tu? Tu es venu ici pour boire un coup?",
"Dis-moi : comment es-tu devenue tavernière?",
"Je veux savoir quelque chose.",
"Tout ce que je veux, c'est trouver des hommes pour mon navire.",
"Tu n'as pas dit que tu avais une chambre libre?",
"As-tu un lit libre dans ton auberge?",
"Désolé. Je dois partir.",
"Oui, en effet. Son navigateur avait le palu, alors Rheims n'a pas pu l'emmener.",
"Est-ce qu'il est toujours sur l'île?",
"Non, non. Il est rétabli depuis longtemps. Rhino est venu le voir. Ils ont eu une longue conversation, puis le navigateur est parti.",
"C'est tout ce que tu sais? Où est-il parti?",
"Eh bien, je l'ai entendu parler de Greenford. Il a dit qu'il avait une maison là-bas. C'est probablement faux... mais, qui sait? \n Si tu le cherches, demande ",
"Giraldo Figuiera",
"Giraldo Figuiera",
" sur Greenford.",
"Merci.",
"J'ai bien une chambre... mais combien de temps comptes-tu rester?",
"Jusqu'au matin.",
"Juste jusqu'à la tombée de la nuit.",
"Très bien. Ça te coûtera 5 pièces d'or.",
"D'accord. Voici ton argent.",
"Tant que ça? Je crois bien que ma bourse et moi allons passer la nuit sous une table ici, dans la taverne.",
"Si tel est ton prix, non merci. Je peux toujours dormir dans la salle commune.",
"Je vais y réfléchir.",
"Ça te coûtera 5 pièces d'or.",
"D'accord. Les voilà.",
"Tant que ça? Je crois bien que ma bourse et moi allons passer la nuit sous une table ici, dans la taverne.",
"Si tel est ton prix, non merci. Je peux toujours dormir dans la salle commune.",
"Peut-être plus tard. Parlons d'autre chose.",
"Oh, bon Dieu! J'ai dû raconter cette histoire une bonne centaine de fois!",
"Je suis sûr que tu es fatiguée de raconter ton histoire à tout le monde, mais elle m'intéresse vraiment. Tu pourrais peut-être faire une exception pour moi?",
"Alors, raconte-la pour la 101ème fois! Ne fais pas semblant de ne pas aimer parler de toi.",
"Voyons... N'as-tu pas la langue bien pendue?",
"Et si tu me racontais tout simplement ton histoire?",
"N'interromps pas tes aînés, morveux! J'y viens. Ça s'est passé il y a une trentaine d'années... J'étais encore jeune à l'époque\n Je passais le plus clair de mon temps à rêver au bruit des vagues, à l'odeur de la mer, aux nuits étoilées... aux hommes...",
"Continue.",
"D'accord. J'en ai assez entendu. Parlons affaires.",
"Un jour, un jeune marin est venu. J'en suis tombée éperdument amoureuse\n Il m'a convaincue de partir pour un monde fabuleux où tout le monde pouvait faire fortune rapidement et vivre heureux.",
"Il parlait du Nouveau Monde?",
"D'accord, j'ai compris l'essentiel. Parlons affaires.",
"Tu es perspicace, hein? Oui, il parlait du Nouveau Monde\n Comme je te l'ai dit, j'étais jeune et naïve. Alors je suis partie avec lui.",
"Mais comment un matelot ordinaire a-t-il fait pour te faire monter à bord d'un navire de la marine? c'est interdit par le règlement!",
"Je crois pouvoir imaginer la suite. Parlons affaires.",
"Oui, c'était déjà interdit l'époque.  Alors il m'a aidé à embarquer clandestinement dans la cale, et juste à côté des pétards en plus!",
"Tu es restée là tout ce temps-là?",
"D'accord. j'en ai assez entendu. Parlons affaires.",
"Eh bien, non. On m'a découverte, évidemment. J'ai fini par me rendre compte que je n'avais pas le pied marin\n J'ai eu le mal de mer, quelque chose de terrible, vraiment. Une demi-heure en mer, et j'ai cru que j'allais mourir! J'ai commencé à crier à l'aide\n Qu'est-ce que je pouvais faire d'autre?",
"Alors que s'est-il passé?",
"D'accord, je crois pouvoir imaginer la suite. Parlons affaires.",
"Mon marin chéri a été exécuté pour infraction au règlement et ils ont décidé de me passer par-dessus bord et de me donner en pâture aux requins\n Ils l'auraient fait si un navire au pavillon noir n'était pas apparu à l'horizon à ce moment précis.",
"Tu es passée de la poêle à frire à la flamme, hein?",
"Je crois pouvoir imaginer la suite. Parlons affaires.",
"À peu près. Ils m'ont enfermée dans une cabine pendant qu'ils combattaient les pirates. Je pense qu'ils se sont dit que mon cas pouvait attendre un peu\n La chance a voulu que les pirates gagnent.",
"Alors tu es tombée entre les mains des pirates... Tu appelles ça une chance?!",
"Le reste est entré dans l'histoire, je suppose? D'accord. Parlons affaires.",
"D'une certaine manière, oui. Un jeune homme a ouvert la porte de ma cabine. Oh, ce qu'il était beau! \nJ'ai oublié toutes mes peurs quand je l'ai vu dans l'encadrement de la porte.",
"Que s'est-il passé ensuite?",
"Je crois pouvoir imaginer la suite. Parlons affaires.",
"Tu veux le savoir? Même une vieille femme a droit à ses petits secrets!",
"Désolé! Je ne voulais pas...",
"Comme si tu allais te sentir gênée! Ne joue pas les saintes-nitouches!",
"Comme tu voudras. Garde tes secrets et parlons affaires.",
"Ha! Tu ne voulais pas devenir indiscret! Regarde-toi : je n'avais encore jamais vu un marin rougir!",
"Que tu es intelligent!? On fera peut-être quelque chose de toi un jour... si les requins ne te mangent pas avant.",
"Pourquoi ne pas me raconter ce qui t'est arrivé une fois à terre?",
"Allez. Raconte-moi le reste de l'histoire, ",
".",
"D'accord. J'en ai assez entendu. Parlons affaires.",
"D'accord, d'accord. Là-bas, sur le navire, j'ai rencontré un homme qui aujourd'hui, se fait appeler ",
"Isenbrandt Jurcksen",
"Isenbrandt Jurcksen",
". À l'époque, ce n'était qu'un grand gaillard aux yeux bleus\nEt je crois que je lui ai plu aussi. Il s'est battu en duel contre le capitaine pour moi et a pris sa place.",
"Qui est cet ",
"Isenbrandt Jurcksen",
"?",
"Je crois pouvoir imaginer la suite. Parlons affaires.",
"Tu n'as jamais entendu parler de lui? Comment est-il possible que tu ne saches rien du plus célèbre capitaine des pirates de l'archipel, qui dirige la lie de la société depuis trente ans?",
"D'accord, maintenant je sais. Parle-moi encore de cette époque.",
"D'accord, je crois pouvoir imaginer la suite. Parlons affaires.",
"Eh bien, nous avons navigué ensemble pendant quelque temps... et j'ai fini par adorer ce style de vie. Mais un jour, nous avons eu une épouvantable dispute pour une broutille. J'avais mon propre argent à l'époque, alors je suis partie et j'ai embarqué sur mon propre navire.",
"Tu es devenue capitaine d'un vaisseau pirate?",
"D'accord. J'en ai assez entendu. Parlons affaires.",
"Ça oui! Je suis devenue un très bon capitaine! Tous les marchands de ces eaux avaient peur de moi. Ma tête était mise à prix, mais j'ai toujours réussi à semer mes poursuivants ou à les couler.",
"Que s'est-il passé ensuite?",
"C'est une histoire fantastique. Laisse-moi te poser une autre question.",
"J'ai été gravement blessée en montant à l'abordage d'une corvette anglaise commandée par un type qui me pourchassait depuis plusieurs mois. J'ai failli y laisser la vie. Après m'être remise de cette blessure, j'ai décidé qu'il était temps de prendre ma retraite\nL'idée d'une vie paisible sur la terre ferme a commencé à me séduire. Alors j'ai ouvert cette taverne.",
"Quelle histoire! Merci de me l'avoir racontée. Maintenant, laisse-moi te poser une autre question.",
"Tu es douée pour raconter les histoires, vieille femme! Je t'ai presque crue. Maintenant, parlons affaires.",
"D'accord. Que veux-tu?",
"Je recherche un dénommé ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Peux-tu me dire si une frégate noire du nom de 'Mefisto' est entrée dans la baie?",
"Rien. Parlons d'autre chose.",
"Ah, ces cinglés?! Oui, ils sont passés par ici, mais je les laisserais tranquilles à ta place\nUn pauvre bougre s'est querellé avec eux ici, et ils l'ont éventré sans sourciller.",
"Merci pour la mise en garde, mais il faut que je les trouve.",
"Ne t'en fais pas : je sais me débrouiller. Peux-tu me dire où les trouver?",
"Désolée, petit, mais je ne peux pas t'aider. Ils sont partis à bord de leur navire, et j'ignore où.",
"Est-ce qu'ils ont parlé à quelqu'un avant de partir?",
"Pas que je sache. Tu peux te renseigner aux alentours. Quelqu'un d'autre pourra peut-être t'aider.",
"Merci. C'est ce que je vais faire.",
"Qu'est-ce qui te fait croire que je peux t'aider? Pourquoi une vieille aubergiste saurait-elle où se trouvent ces ordures?",
"J'ai demandé autour de moi. On m'a dit que l'homme que je recherchais avait séjourné dans ton auberge.",
"J'ai entendu des rumeurs disant qu'il était au port. Je me suis dit que l'aubergiste aurait des chances d'être mieux renseignée.",
"Peu importe ce que disent les rumeurs! Je ne sais rien!",
"Quelque chose me dit que tu me caches quelque chose.",
"Écoute... Je ne veux pas qu'un type bien ait encore plus d'ennuis qu'il n'en a!",
"Je te promets que je ne vais pas lui mettre plus de problèmes sur le dos.",
"Je ne vais pas lui causer d'ennuis. J'ai juste une affaire urgente à traiter avec lui.",
"Écoute, je t'ai dit que je ne savais rien. Ça veut dire que je ne sais rien! Maintenant, dehors!",
"D'accord, d'accord. Tu ne sais rien. Je vais demander à quelqu'un d'autre.",
"Si tu n'étais pas entourée de vauriens qui croient que tu as décroché la lune, je te ferais parler avec mon épée...",
"Qu'est-ce que tu veux dire?",
"Rien de particulier. C'est juste que j'ai pour mission de trouver cet homme et de le ramener à Redmond.",
"À Redmond, hein? Tu dis peut-être vrai, après tout. ",
"Raoul Rheims",
" m'a dit un jour qu'il avait voulu aller à Redmond, mais qu'il avait rencontré des difficultés en y allant. Tu peux peut-être l'aider.",
"Ce sont exactement mes ordres : le ramener à Redmond en vie et bien portant.",
"D'accord. Alors écoute : comme je te l'ai dit, il était parti vers cette destination pour une affaire urgente, mais quelqu'un a tiré un coup de semonce devant sa proue et l'a obligé à changer de cap.",
"Et quel cap a-t-il pris?",
"Il a parlé de Conceicao. Il a un ami là-bas, Camilo Machado, le chef des contrebandiers du coin.",
"Merci pour le renseignement. Tu m'as bien rendu service.",
"Crois-tu tout ce que les gens disent? Je ne sais rien. Ne viens plus me déranger!",
"D'accord, je crois que je vais être obligé de demander à quelqu'un d'autre.",
"Oh, on se croit important, hein? Quelles sont donc ces affaires dont tu me parles?",
"J'ai besoin de... de lui remettre une lettre de la part d'un ami.",
"D'accord, petit. Je vais te dire où il est.",
"Alors où?",
"Une lettre, hein? Je peux la voir? Ou peut-être que tu mens?",
"Je ne peux pas te la montrer. C'est... du plus haut secret.",
"Menteur! Sors d'ici avant que les gars ne te jettent dehors!",
"D'accord, je m'en vais, mais tu le regretteras.",
"Il est un peu tard pour ça. Reviens dans la matinée et cet endroit sera rempli de membres d'équipage potentiels. Ou mieux encore : passe la nuit ici.",
"As-tu une chambre libre?",
"Peut-être plus tard. Laisse-moi te poser une autre question.",
"J'ai une chambre. Pour combien de temps en as-tu besoin?",
"Jusqu'au matin.",
"Seulement jusqu'à la tombée de la nuit.",
"Parfait. Ça te coûtera 5 pièces d'or.",
"D'accord. Voici ton argent.",
"Tant que ça? Je crois bien que ma bourse et moi allons passer la nuit sous une table ici, dans la taverne.",
"Si tel est ton prix, non merci. Je peux toujours dormir dans la salle commune.",
"Je vais y réfléchir.",
"Ça te coûtera 5 pièces d'or.",
"D'accord. Voici ton argent.",
"Tant que ça? Je crois bien que ma bourse et moi allons passer la nuit sous une table ici, dans la taverne.",
"Si tel est ton prix, non merci. Je peux toujours dormir dans la salle commune.",
"D'accord. Je vais y réfléchir.",
"Arrête tout de suite ou je te fais jeter dehors!",
"D'accord, d'accord. Je m'en vais.",

};