string DLG_TEXT[34] = {
"Je ne sais pas qui tu es, mais si tu pars sur-le-champ, je n'aurai pas besoin de te jeter aux requins!",
"...",
"Pourquoi cherches-tu ",
"Raoul Rheims",
"?",
"Ça ne te regarde pas.",
"Silehard m'a dit que tu viendrais. Il m'a dit de lui envoyer ta tête.",
"Eh bien, là voilà, sur mes épaules. Tu peux toujours essayer de la prendre!",
"Ah! C'est le vaillant ",
", ami et héros des masses opprimées! Qu'est-ce qui amène un noble personnage comme toi chez un abominable pirate comme moi?",
"Ah! C'est toi, ",
". Ta réputation impitoyable et sanguinaire menace de surpasser la mienne! Qu'est-ce qui t'amène?",
"Je suis venu pour te remettre cette lettre.",
"Tu ressembles plus à un bouffon que je ne m'y attendais. Prends cette lettre que je t'ai apportée pour que je puisse m'en retourner.",
"J'ai l'impression que je devrais te traiter de manière familière, petit... mais je te jure que je ne sais pas pourquoi. Qui es-tu?",
"Je m'appelle ",
" et je suis ici pour affaires. Je t'ai apporté une lettre.",
"Une lettre, tu dis? J'aimerais savoir qui me l'envoie.",
"Pourquoi veux-tu savoir qui te l'a envoyée? Pourquoi ne pas la lire, tout simplement? Veux-tu que je la lise pour toi?",
"Prends garde à ce que tu dis, gamin, ou je ferai un trophée de ta tête!",
"Eh bien, voilà qui répond à ma question... D'accord, si tu veux vraiment le savoir, la lettre provient du gouverneur anglais, ",
"Robert Christopher Silehard",
".",
"Robert Christopher Silehard",
"? Alors le vieux renard a encore besoin de mon aide? Très intéressant. Qu'est-ce que tu fais encore planté là? Tu m'as remis la lettre, alors va!",
"...",
"Laisse-moi t'expliquer ton erreur, petit. Cette ville est à moi. Cette île est à moi. Et tout ce qui se passe ici suit mes moindres volontés.",
"Alors qui es-tu? Un chef de pirates?",
"Je préfère me considérer comme le gouverneur d'une colonie indépendante, mais j'attends toujours ta réponse.",
"Quel genre de civilisation avez-vous ici, pour qu'une pauvre fille à la recherche de son amant provoque des troubles!",
"Amant? Haha, vraiment?! Les miracles arrivent encore dans ce monde! Pourquoi est-il parti?",
"Dis-moi : il est passé ici? Quand? Où est-il parti?",
"Il était ici... il a effectué des réparations après une tempête. Mais je ne sais pas où il est parti. Il n'a rien dit. Bon, tu peux partir maintenant.",
"...",

};
