string DLG_TEXT[133] = {
", ",
", qu'est-ce qui me vaut l'honneur de cette visite?",
"Puis-je t'aider, ",
"?",
"C'est la première fois que tu visites notre ville, ",
"? Je ne t'ai jamais vu ici.",
"Je suis ",
", capitaine et propriétaire du navire '",
".' J'ai une ou deux questions à te poser.",
"Je m'appelle ",
", et j'ai besoin de réponses.",
"Tu peux m'appeler capitaine ",
". Je voudrais des renseignements.",
"Bonjour, capitaine ",
". Qu'est-ce qui t'amène dans cette partie du monde?",
"Ah, capitaine ",
". ",
"C'est encore toi! Comment est la mer? D'huile, j'espère?",
"Bonjour, ",
", puis-je t'aider?",
"Quels sont les derniers potins?",
"Qu'est-ce qui se passe ici, ces temps-ci?",
"De quoi parlent les clients qui viennent boire un verre, ces derniers temps?",
"Je voudrais connaître les dernières nouvelles, rumeurs, médisances... tout ce que tu as.",
"J'étais en mer. Tout ce que je ne sais pas encore m'intéresse.",
"Sers-moi quelques rumeurs ; je peux peut-être transformer certaines nouvelles en or.",
"J'ai besoin que tu m'indiques mon chemin.",
"Je ne connais pas bien la ville. J'aurais besoin que tu m'indiques mon chemin.",
"J'ai besoin de me rendre quelque part et j'aimerais que tu me dises comment y aller.",
"Tu m'as l'air d'être du coin. Pourrais-tu m'expliquer comment aller à...",
"J'aurais besoin que tu m'indiques mon chemin.",
"Pas le temps de discuter. Explique-moi juste comment trouver...",
"Je voudrais te poser des questions sur quelqu'un que tu connais peut-être.",
"J'ai besoin de renseignements sur quelqu'un du coin.",
"Peux-tu me parler de l'un des habitants?",
"Je voudrais que tu me dises ce que tu sais sur un type...",
"L'un des habitants m'intéresse. Pourrais-tu me renseigner?",
"Je parie que tu connais tous ceux qui vivent ici, non?  J'ai quelques questions.",
"Désolé. Je t'ai confondu avec quelqu'un.",
"Je ne fais que passer. Ce serait plus facile si tu t'écartais.",
"Que veux-tu savoir, ",
"?",
"Puis-je t'aider, capitaine?",
"Que puis-je faire pour toi?",
"Je suis sûr que ce coin ne manque pas de rumeurs. Raconte-moi les plus croustillantes.",
"Il s'est passé quelque chose d'intéressant, ces derniers temps?",
"Je veux juste savoir ce qui se passe dans le voisinage - meurtres, escroqueries... tout ce qui présente un intérêt.",
"Comment aller à...",
"Peux-tu m'aider à me repérer dans cette ville?",
"Je ne trouve toujours pas...",
"Peux-tu me renseigner sur une personne en particulier?",
"Je voudrais te poser des questions sur quelqu'un que tu connais peut-être.",
"J'ai besoin de renseignements sur l'un des habitants.",
"Rien! Je ne fais que passer.",
"Merci. Une dernière chose...",
"Ça m'a fait plaisir de discuter avec toi. À plus tard!",
"Autre chose, capitaine ",
"?",
"Dis-moi ce que tu veux, ",
".",
"Je t'écoute, ",
".",
"Quels sont les derniers potins?",
"Qu'est-ce qui se passe en ce moment, ici?",
"Je voudrais connaître les dernières nouvelles, rumeurs, médisances... tout ce que tu as.",
"J'ai besoin que tu m'indiques mon chemin.",
"Je ne connais pas bien la ville. J'aurais besoin que tu m'indiques mon chemin.",
"J'ai besoin de me rendre quelque part et j'aimerais que tu me dises comment y aller.",
"Je voudrais te poser des questions sur quelqu'un que tu connais peut-être.",
"J'ai besoin de renseignements sur quelqu'un du coin.",
"Peux-tu me parler de l'un des habitants?",
"La prochaine fois, peut-être. Au revoir.",
"Qui, ",
"?",
"Quelqu'un en particulier?",
"De qui veux-tu parler, exactement?",
"Je veux parler du gentilhomme gouverneur.",
"Je m'intéresse au tavernier...",
"Je me pose des questions sur le propriétaire du chantier naval.",
"Je m'intéresse au marchand.",
"On reviendra là-dessus plus tard.",
"Notre gouverneur est relativement jeune. On dit que c'est un homme très capable, fils cadet d'un comte espagnol. Ça ne fait pas longtemps qu'il est ici, ce qui explique pourquoi il n'y a pas grand-chose à dire sur lui pour l'instant.",
"Je vois. J'ai une autre question pour toi.",
"Merci. Au revoir.",
"Que dire? C'est juste un homme. Il possède une taverne, ce qui signifie qu'il est au courant de tout ce qui se passe sur l'île.",
"Je vois. J'ai une autre question à te poser.",
"Merci. Au revoir.",
"Il est assez désagréable, ce vieux. Il grogne toujours quand quelqu'un veut acheter un nouveau navire et ressasse sans cesse le passé.",
"Je vois. J'ai une autre question à te poser.",
"Merci. Au revoir.",
"Ce gros homme est connu dans la ville pour son honnêteté et la qualité de ses produits.",
"Je vois. J'ai une autre question à te poser.",
"Merci. Au revoir.",
"Où vas-tu, ",
"?",
"Pas de problème, capitaine. Où veux-tu aller, aujourd'hui?",
"Tu peux compter sur mon aide, ",
". Où veux-tu aller, exactement?",
"Où est la taverne?",
"Où puis-je trouver le chantier naval?",
"J'ai besoin de trouver quelqu'un qui me donnera un bon prix pour mes marchandises.",
"La taverne est sur la place principale, presque en face de la résidence du gouverneur - et chose très pratique, à deux pas de l'église! Tu ne peux pas la manquer.",
"J'ai compris. Merci.",
"Où est le chantier naval?",
"Où puis-je vendre les marchandises de premier choix que j'ai apportées avec moi?",
"Le bureau du patron du chantier naval se trouve au centre de la ville, à gauche de la résidence du gouverneur quand tu la regardes de face.",
"Je vois. Et par où dois-je passer pour me rendre à la taverne?",
"J'ai besoin de trouver quelqu'un qui m'offrira un bon prix pour mes marchandises.",
"Merci pour ton aide. C'est tout ce dont j'ai besoin pour le moment.",
"Si tu viens du centre de la ville, il faut que tu te diriges vers les portes, sur ta droite. Tu verras un bâtiment avec une pancarte dessus; c'est le magasin.",
"Où puis-je trouver le chantier naval?",
"Par où dois-je passer pour aller à la taverne?",
"Merci pour ton aide. C'est tout ce dont j'ai besoin pour le moment.",
"Eh bien d'accord, ",
" - mais je ne comprends pas ce que tu trouves d'intéressant à ce coin.",
"Bien sûr, je t'en parlerai avec plaisir, capitaine.",
"C'est toujours une joie! J'adore discuter! Alors, installe-toi et écoute, ",
".",
"L'histoire de cette colonie m'intéresse...",
"Est-ce qu'il y a autre chose, en dehors de la ville, sur cette île?",
"Changeons de sujet.",
"L'histoire de Redmond? Eh bien, la colonie a été fondée il y a tout juste 25 ans, \nmais comme l'île est très riche et fertile, elle s'est très vite développée\nAujourd'hui, c'est la plus grande et la plus florissante colonie de notre archipel.",
"Continue.",
"Oui, c'est ce qu'ils disent tous. Laisse-moi te poser une autre question.",
"Évidemment, ils ont envoyé un gouverneur du continent et construit un fort solide \npour protéger la colonie. Je crois que c'est préférable, dans le fond. J'aime vivre en paix.",
"J'ai compris. Laisse-moi te poser une autre question.",
"Non, il n'y a rien d'autre sur ce petit rocher hormis des plages désertes, des montagnes et \nla jungle... La jungle commence juste à la sortie de la ville, en fait. Plusieurs chemins y mènent, mais seul un fou s'y aventurerait \nsans une bonne raison. Outre les animaux sauvages, il y a aussi les hommes sauvages : les bandits qui y ont élu domicile.",
"Ça a l'air dangereux. Que peux-tu me dire d'autre?",
"Eh bien, de manière générale, l'île est toujours sauvage et inexploitée. Le défrichage de la jungle qui entoure la ville \nest une tâche qui en décourage plus d'un, mais la terre est très fertile et les quelques plantations implantées ici produisent \nde riches récoltes. Petit à petit, les plantations remplaceront la jungle et \nl'île sera recouverte de fermes, de champs et de routes. Pour le moment, il n'y a qu'une ville portuaire.",
"Je vois. Autre chose?",
"Eh bien, il y a une superbe chaîne de montagnes... une luxuriante jungle sauvage... des kilomètres de plages désertes... et pas grand-chose d'autre. Toute l'action se déroule en ville.",
"Continue.",
"Je vois. Abordons un autre sujet, tu veux bien?",

};
