string DLG_TEXT[28] = {       
"Tu ne vois pas que je suis de service? Ne viens pas me déranger!",
"D'accord, d'accord.",
"Tu as un crime à signaler?",
"Non, évidemment : je suis capitaine! Je vois que tu ne m'écoutes pas.",
"Souviens-toi : les bagarres de rue ne sont pas autorisées! Tu ne peux te battre que si quelqu'un t'attaque.",
"D'accord. Je m'en souviendrai.",
"Dire que je suis coincé ici par ce temps! Tu ne me croiras pas, mais ma seule distraction est de me battre avec les mouches qui essaient de se poser sur ma tête.",
"Désolé, mais je ne peux pas t'aider. C'est ton travail, après tout.",
"Si tu veux discuter, trouve quelqu'un d'autre. J'ai une tâche à accomplir et je ne peux pas te parler.",
"Je me demandais juste si tu étais vivant. Tu es planté là comme une statue.",
"Tu crois que c'est facile de protéger notre ville? Loin de là! C'est une tâche dangereuse et de très haute importance. Je me souviens qu'une fois...",
"Tu me raconteras ça une autre fois. Je dois partir.",
"Circule et arrête de m'importuner.",
"Comme tu voudras, soldat.",
"Eh! Tu ne voudrais pas me rapporter un godet de rhum de la taverne?",
"Si je fais ça, ils me pendront pour avoir enivré un soldat! Non... Attends la fin de ton service et tu pourras boire autant que tu le voudras.",
"Pourquoi est-ce que des marins insolents de ton espèce essaient de me parler?! Il n'y a pas de jolies filles dans cette ville?",
"Tu appelles ça être au service de la ville? Tu ne sais même pas reconnaître un dangereux criminel... comme moi! Ha ha!",
"Tu as l'air en bonne santé. Pourquoi ne pas t'engager dans l'armée? Nous avons beaucoup de place dans nos casernes, de la bonne nourriture, du rhum gratuit...",
"Intéressant, mais j'ai peur de devoir refuser. Je ne suis pas assez discipliné pour l'armée.",
"Cette chaleur... Je donnerais n'importe quoi pour retrouver mon Espagne chérie.",
"Oui, ce climat n'a pas l'air de te réussir.",
"Toi... *hic!*... Toi, vil rustre! Tu as blessé mon... *hic!*... mon ami!",
"Quel ami? Tu es tout seul ici, ",
".",
"Quoi? Il était... là, il y a une minute. Je vais le chercher. Toi... *hic!*... Toi, tu attends ici que je te donne ta raclée!",
"Comment oses-tu me contredire! Je vais t'étrangler!",


};
