string DLG_TEXT[37] = {
"On m'a dit que tu t'etais donne du mal pour obtenir une audience. Je m'appelle ",
". Et maintenant, si tu veux bien m'expliquer l'objet de ta visite, ",
".",
"Je m'appelle ",
".",
"Ah, c'est encore toi. Qu'est-ce qui t'amene, cette fois-ci? ",
"Je voudrais te parler d'une petite affaire.",
"Desole, mais je suis occupe.",
"Alors, pourquoi viens-tu me deranger en plein milieu d'importantes affaires d'Etat?",
"Je voudrais te parler d'une petite affaire.",
"Je viens juste te presenter mes respects. Rien de plus.",
"Dans ce cas, je te prie de quitter mon bureau et de me laisser retourner a des affaires plus importantes.",
"Oui, bien sur. Desole de t'avoir derange.",
"Je t'ecoute, ",
".",
"Je suis ici pour recevoir ma recompense pour la mort de Garry le salingue.",
"Desole, mais je n'ai rien a te dire pour le moment.",
"Oh, j'ai entendu parler de ce que tu avais fait. Au nom de toute la colonie, je te prie d'accepter toute notre gratitude.",
"Bien. Je voudrais ma recompense.",
"Tu aimes la plaisanterie. Ha ha. Voici ton argent.",
"Merci, je suis ton humble serviteur.",
"Alors, et le pari que tu as place... apres avoir recu l'accord de nos services fiscaux, je vois que nous avons... voyons... 6 000.",
"Quoi?! On avait dit 10 000!",
"Je ne peux pas t'aider. A l'avenir, essaie d'etre plus calme.",
"Comme tu voudras. Bande de scelerats...",
", as-tu conscience que tu es accuse de meurtre? On t'a vu pres du corps de la victime. Qu'as-tu a dire pour ta defense?",
"Je n'ai rien a voir dans cette affaire. L'homme etait deja mort quand je suis entre dans la piece! On m'a dit qu'il etait juste blesse et qu'il avait peut-etre des informations importantes a me transmettre.",
", Je viens d'apprendre qu'un homme avait ete arrete alors qu'il tentait de quitter la ville avec un couteau couvert de sang en sa possession. Il a avoue le meurtre dont tu etais accuse. Tu peux partir.",
"Merci. Je savais que je pouvais faire confiance a la justice de Conceicao.",
"Sir Silehard m'envoie. Il m'a dit qu'une lettre de cachet et un cadeau diplomatique attendaient ici un messager de confiance.",
"Alors Silehard ne t'a pas menti. L'Europe a decide d'exporter jusque dans nos eaux ses calculs, ses peurs et ses ambitions.",
"Voici la lettre de cachet attendue, et voici le cadeau diplomatique qui doit l'accompagner. L'un sans l'autre perdrait une part de sa force.",
"Je les remettrai en main propre et sans halte inutile.",
"Fais-le. Il se murmure deja que certaines forces malfaisantes s'agitent entre ces iles. Si elles jettent les Caraibes dans le feu, il n'y aura bientot plus rien a vendre ni a prendre.",
"Je vous ai deja tout remis. Porte maintenant ces objets a Redmond sans perdre de temps.",
"Je ne trainerai pas."
};
