string DLG_TEXT[29] = {       
"On m'a dit que tu t'étais donné du mal pour obtenir une audience. Je m'appelle ",
". Et maintenant, si tu veux bien m'expliquer l'objet de ta visite, ",
".",
"Je m'appelle ",
".",
"Ah, c'est encore toi. Qu'est-ce qui t'amène, cette fois-ci? ",
"Je voudrais te parler d'une petite affaire.",
"Désolé, mais je suis occupé.",
"Alors, pourquoi viens-tu me déranger en plein milieu d'importantes affaires d'État?",
"Je voudrais te parler d'une petite affaire.",
"Je viens juste te présenter mes respects. Rien de plus.",
"Dans ce cas, je te prie de quitter mon bureau et de me laisser retourner à des affaires plus importantes.",
"Oui, bien sûr. Désolé de t'avoir dérangé.",
"Je t'écoute, ",
".",
"Je suis ici pour recevoir ma récompense pour la mort de Garry le salingue.",
"Désolé, mais je n'ai rien à te dire pour le moment.",
"Oh, j'ai entendu parler de ce que tu avais fait. Au nom de toute la colonie, je te prie d'accepter toute notre gratitude.",
"Bien. Je voudrais ma récompense.",
"Tu aimes la plaisanterie. Ha ha. Voici ton argent.", 
"Merci, je suis ton humble serviteur.",
"Alors, et le pari que tu as placé... après avoir reçu l'accord de nos services fiscaux, je vois que nous avons... voyons... 6 000.",
"Quoi?! On avait dit 10 000!",
"Je ne peux pas t'aider. À l'avenir, essaie d'être plus calme.",
"Comme tu voudras. Bande de scélérats...",
", as-tu conscience que tu es accusé de meurtre? On t'a vu près du corps de la victime. Qu'as-tu à dire pour ta défense?",
"Je n'ai rien à voir dans cette affaire. L'homme était déjà mort quand je suis entré dans la pièce! On m'a dit qu'il était juste blessé et qu'il avait peut-être des informations importantes à me transmettre.",
", Je viens d'apprendre qu'un homme avait été arrêté alors qu'il tentait de quitter la ville avec un couteau couvert de sang en sa possession. Il a avoué le meurtre dont tu étais accusé. Tu peux partir.",
"Merci. Je savais que je pouvais faire confiance à la justice de Conceicao.",

};