string DLG_TEXT[50] = {
"Capitaine, compte tenu de ta mauvaise réputation, je n'ai pas l'intention de faire affaire avec toi.",
"Comme tu voudras, mais c'est toi qui y perds.",
"Permets-moi de me présenter. Je suis ",
"Joaquin Da Saldanha",
"Joaquin Da Saldanha",
", amiral de la flotte d'Espagne. Ravi de te rencontrer, capitaine ; le gouverneur m'a dit que tu pouvais remédier à tous les problèmes.",
"Le gouverneur est trop indulgent avec moi. Certes, j'ai une certaine expérience des problèmes...",
"Capitaine, tu as changé d'avis? Tu acceptes de m'aider à retrouver mon fils?",
"Oui, je crois pouvoir t'aider maintenant. Mais j'ai besoin d'indices. As-tu une idée de l'endroit où je dois commencer mes recherches?",
"Désolé, amiral, mais je ne peux pas t'aider pour le moment.",
"Capitaine! Tu as trouvé mon fils?",
"Pas encore, amiral. Mais ne t'inquiète pas. J'y arriverai.",
"Ah, capitaine! Pile au bon moment!",
"J'ai des nouvelles de ton fils, amiral...",
"Capitaine, tu es toujours là? Qu'est-ce que tu attends?!",
"Du calme. Je vais le retrouver, ton fils.",
"Capitaine, tu m'as été d'une aide inestimable! Je ne l'oublierai jamais.",
"Je suis ravi que tout se soit bien terminé.",
"Parfait. J'ai du travail pour toi, capitaine. Voilà : mon fils, ",
"Lucas Da Saldanha",
", a disparu voilà quelques mois, quelques jours seulement avant son mariage. Comme tu peux l'imaginer, cette situation me met dans l'embarras.",
"Oui, bien sûr.",
"Lorsque j'ai appris que Lucas était parti pour le Nouveau Monde, j'ai demandé à être nommé amiral de la flotte des Indes occidentales pour venir ici et le retrouver.",
"Mais en vain?",
"Hélas. Chaque fois que je crois avoir retrouvé la trace de ",
"Lucas Da Saldanha",
", je la perds. J'aimerais que tu le retrouves. Je te propose 10 000 pièces d'or. Cela te convient?",
"Tout à fait. Mais je vais avoir besoin d'informations...",
"Désolé de te décevoir, amiral, mais je crains de ne pas pouvoir accepter cette mission pour le moment.",
"Je sais seulement que ",
"Lucas Da Saldanha",
" a été vu pour la dernière fois à la taverne de Redmond. Tu peux commencer par là. Je compte sur toi, capitaine.",
"Je vais faire mon possible. Au revoir.",
"Ça va être difficile de le trouver, je le sais. Mais je garde espoir. Si tu as des nouvelles, tu me trouveras ici.",
"Au revoir, amiral.",
"Excuse-moi de t'interrompre, mais le temps presse. Voici 3 000 pièces d'or pour tes frais. Maintenant, écoute bien : j'ai appris que ",
"Lucas Da Saldanha",
" avait été capturé par des pirates et que ces derniers réclamaient une rançon de 20 000 pièces d'or.",
"Je vois. Qu'est-ce que tu comptes faire? ",
"Payer la rançon, bien sûr! ",
"Lucas Da Saldanha",
" vaut plus à mes yeux que cet or. C'est mon fils! Je t'en prie, va remettre cet argent aux pirates et ramène-moi mon fils sain et sauf. Je te donnerai alors les 10 000 pièces d'or promises.",
"Je m'en occupe. Où dois-je apporter la rançon?",
"Désolé, mais la mission devient trop dangereuse pour moi. Au revoir, amiral.",
"À Falaise de Fleur. L'un des pirates t'attendra à la taverne. Je te montrerai le signe spécial qui m'a été indiqué pour qu'il te reconnaisse. Et n'oublie pas : à défaut de recevoir la rançon d'ici un mois, ils tueront ",
"Lucas Da Saldanha",
".",
"Ne t'inquiète pas, amiral. Ton fils sera bientôt ici.",
"Je suis ravi de te remettre ces 10 000 pièces d'or, capitaine. Tu les as bien méritées. Bonne chance!",
"Merci. Au revoir.",

};
