string DLG_TEXT[43] = { 
"Ravi de te rencontrer, ",
". Je m'appelle ",
", et je suis à ton service.",
"Je suis le capitaine ",
".",
"Ravi de te revoir, ",
".",
"C'est toi! J'espérais ne plus jamais te revoir ici.",
"Bonjour à toi, aussi, ",
".",
"J'imagine que ce n'est pas ton jour de chance, ",
"Tu veux voir ce que j'ai en stock?",
"Volontiers. Jetons un coup d'oeil.",
"Plus tard. Pour le moment, je dois parler.",
"Une autre fois.",
"Allons-nous conclure un marché ou veux-tu seulement acheter quelques marchandises?",
"J'aimerais me défaire de certaines marchandises.",
"J'aimerais t'acheter du matériel.",
"Rien, merci. Au revoir!",
"De quoi veux-tu parler?",
"J'écoute.",
"On m'a demandé de te livrer une cargaison.",
"Tu as besoin d'un capitaine? J'ai un excellent navire et je peux livrer toutes sortes de cargaisons n'importe où.",
"Je n'ai pas le temps de parler pour le moment.",
"Non, je n'ai pas besoin de tes services. Pas tant que tu couleras des navires français.",
"Dans ce cas, au revoir.",
"Désolé, je n'ai rien à te confier pour le moment.",
"Bon, je reviendrai plus tard.",
"Désolé, mais ton navire n'est pas assez grand pour la mission à laquelle je pense.",
"Bon, je reviendrai plus tard.",
"Oh! Je voulais juste te demander un service. En fait, je dois faire livrer une cargaison à ",
" au plus vite. Si tu parviens à le faire en un mois, tu recevras ",
" pièces d'or à ton arrivée. Ça te va?",
"Ah ça, oui.",
"Je ne peux pas accepter.",
"Je t'ai déjà dit que je n'avais rien pour toi.",
"Oh, désolé.",
"Tu t'es souvenu de ta mission un peu tard, tu ne trouves pas? J'ai déjà reçu ce dont j'avais besoin. Au revoir.",
"Au revoir.",
"Oh! J'attends cela depuis si longtemps. Tiens, voilà ta récompense, jeune homme.",
"Parfait.",
"Hélas, je n'ai pas besoin de tes services pour le moment.",
"Désolé d'entendre ça. Parlons d'autre chose, alors.",

};
