string DLG_TEXT[14] = {
"Oui?",
"...",
"Tu as des nouvelles du Professeur? Il a dit qu'il enverrait ses hommes.",
"Oui, c'est moi qu'il envoie. Mais ne le dis pas à toute la ville!",
"Désolé. Je tiendrai ma langue. Où est ton médaillon?",
"Tu n'as pas oublié le médaillon, hein? Le voilà.",
"Ah! Je savais que c'était toi! Je vais aller le dire aux autres. Quand met-on les voiles?",
"Tu ne le sais pas? Je parie que tu ne sais même pas où nous allons, hein?",
"Non. Le professeur ne nous l'a pas dit.",
"Bien, bien. C'est mieux ainsi. Motus et bouche cousue, comme on dit. Et où est le professeur? On ne peut pas partir sans lui.",
"Il est allé à Oxbay pour quelques jours. Maintenant que j'y pense, il devait rentrer hier, mais il n'est toujours pas là.",
"Étrange. Je suppose donc que notre départ va être retardé.",
"Quoi? Pourquoi?",
"Tu ne penses quand même pas qu'on va partir sans lui, hein? Il faut que je le trouve ou du moins je sache ce qui lui est arrivé. Ensuite, on pourra prendre la mer.",
};
