string DLG_TEXT[84] = {
"Qui es-tu, ",
"?",
"Je suis ",
", le capitaine du '",
"'.",
"Je m'appelle ",
", et je suis, bien sûr, le gouverneur de cette colonie.",
"Ravi de faire ta connaissance.",
"Oh, j'ai beaucoup entendu parler de toi, ",
". On dit que tu es un bon capitaine et que tu es très apprécié.",
"Ravi de l'entendre.",
"Bon, qu'est-ce que je peux faire pour toi, ",
"?",
"Je cherche du travail. Alors, si tu as besoin de mes services...",
"Je crains fort de devoir décliner la mission que tu m'as proposée. Je ne peux pas rivaliser avec ce navire de guerre anglais.",
"Je suis venu discuter un peu.",
"Discuter? Tu me prends pour qui, ",
"? Je suis officier de l'État. Je n'ai pas de temps de discuter, moi!",
"Je te demande pardon. Je m'en vais.",
"Au cas où tu ne le saurais pas, mon pays est en guerre contre l'Angleterre. Je ne vois pas ce que tu peux faire pour moi, ",
".",
"C'est dommage.",
"Oui, je crois pouvoir te confier une mission.",
"Parfait! Et de quoi s'agit-il?",
"Il paraît que tu as vaincu le navire de guerre anglais. Bravo, ",
". Quelle victoire!",
"Je suis ravi de vous servir, toi et la France.",
"On ne peut pas dire que je sois ravi de te voir, mais je n'ai pas le choix. Tu as des amis influents.",
"Merci.",
"Comme ça, l'un des hommes les plus recherchés de l'archipel se présente à moi? Gardes!!!",
"Rappelle tes hommes ou une certaine ",
"Virginie d'Espivant",
" mourra. Je ne crois pas que son père serait ravi d'apprendre que tu n'as rien fait pour empêcher ça.",
"Je suis tout ouïe. Qu'est-ce que tu veux?",
"J'ai à bord une dame du nom de ",
"Virginie d'Espivant",
"...",
"Tu l'as trouvée?! Dieu merci! Mais, dis-moi capitaine, est-elle prisonnière sur ton navire?",
"Exactement. Même si je l'ai trouvée par pur hasard.",
"Bien sûr que non! Au contraire, c'est une hôte de marque.",
"Je suis ravi de l'apprendre. Comment l'as-tu trouvée?",
"C'est une longue histoire. Je suis sûr que ",
"Virginie d'Espivant",
" te la racontera elle-même, si elle le juge nécessaire.",
"Oui, bien sûr, je ne vais pas te retarder davantage. Prends cet argent et accepte mes remerciements. Je vais veiller à ce que cette dame soit sous bonne escorte une fois à terre.",
"Certainement.",
"Alors tu la retiens prisonnière et tu veux une rançon?",
"Oui. Mais je tiens à ajouter qu'elle est ici par pur hasard.",
"C'est noté. Bon, que veux-tu en échange de sa liberté?",
"De l'argent et la possibilité de rejoindre sans encombre mon navire, bien sûr.",
"Combien?",
" Je pense que 7 000 pièces d'or devraient faire l'affaire.",
"Quoi? Tu as perdu la tête?!",
"Tu crois vraiment que l'heure est aux marchandages?",
"Très bien. Voilà l'argent et je te promets que tu pourras rejoindre sans encombre ton navire. Libère la fille.",
"Tu me le promets? Tu passes pour être un homme d'honneur, mais je ne veux pas prendre de risques. Tu récupéreras la fille quand j'aurai mis les voiles.",
"Très bien. Mais pas d'entourloupe sinon j'ordonnerai à tous les navires de me rapporter ta tête!",
"D'accord.",
"Je vois. Eh bien, je me vois contraint de dire que j'ai dû passer l'éponge sur tous les crimes que tu as commis contre mon pays...",
"Quel honneur!",
"Épargne-moi tes sarcasmes! Si j'avais le choix, je te ferais pendre haut et court. Tu retiens cette jeune femme : c'est la seule justification de ma générosité.",
"Je te suis infiniment reconnaissant!",
"Je n'en doute pas. En plus, j'ai reçu l'ordre de te récompenser. Voilà. Mais maintenant, fais-moi une faveur : déguerpis.",
"Avec plaisir.",
"Un navire de guerre anglais bloque les routes commerciales dans nos eaux et notre flotte mène une importante opération ailleurs.",
"Tu attends de moi que je coule ce navire?",
"Je crois savoir ce que tu vas me demander, mais c'est non.",
"C'est ça, ",
". Je te paierai 5 000 pièces d'or pour couler ce navire.",
"D'accord. J'accepte cette mission.",
"Non. C'est loin d'être suffisant pour me convaincre d'affronter un navire de guerre anglais. Je décline donc ton offre, à moins que tu ne la revoies à la hausse.",
"Parfait. Je te souhaite bonne chance, ",
".",
"Sois tranquille. Je me charge de cette mission.",
"Je ne suis pas prêt à marchander! J'appartiens à la noblesse. Accepte cette mission ou file!",
"Très bien. Je vais couler ce navire.",
"Tu vas avoir du mal à trouver un capitaine qui accepte ce sale boulot pour une telle misère!",
"Tiens, prends ta récompense et reste dans le coin. Je risque d'avoir d'autres missions pour toi.",
"Pas de problème. Je te laisse travailler. Au revoir.",
"Franchement, ta lâcheté me déçoit beaucoup.",
"Pense ce que tu veux, mais j'attache plus d'importance à la vie qu'à l'argent.",
"Retire ça! Je vais m'en charger, mais ne t'avise plus de m'insulter!",
"Tu me dégoûtes. Sors immédiatement de mon bureau!",
"Comme tu voudras.",

};
