string DLG_TEXT[45] = {
", cher visiteur! Je suis ",
", le propriétaire du chantier naval local.",
"Et moi ",
", le capitaine du navire '",
".'",
", ",
". Tu as besoin des services de mon chantier naval ",
"?",
"En effet, j'aimerais faire aveugler plusieurs impacts d'obus et raccommoder quelques voiles.",
"Pour l'instant, je souhaiterais juste te parler.",
"Non, je ne fais que passer.",
"Eh bien, je suis ravi de faire ta connaissance. Si tu es capitaine, sache que mon chantier naval est à ton service.",
"Parfait, ",
". Attelons-nous à ces réparations.",
"Merci. Mais d'abord, parlons.",
"La prochaine fois, peut-être. Je dois partir.",
"Qu'est-ce que tu veux exactement, ",
"?",
"Non, je ne crois pas.",
"Je vois. Tu as besoin d'autre chose, ",
"?",
"J'aimerais faire quelques réparations sur la vieille coque de noix qui m'a amené ici!",
"C'est tout, merci et au revoir!",
"Qu'est-ce que tu veux exactement?",
"J'aimerais faire réparer mon navire, mais je pourrais aussi m'en débarrasser pour en acheter un autre.",
"J'aimerais faire installer de nouveaux canons sur mon navire.",
"Rien, merci.",
"Que puis-je pour toi, capitaine?",
".",
"Il faut que je parle à Florens Clauss.",
"Que puis-je pour toi?",
"Il faut que je parle à Florens Clauss.",
"Clauss? Il me doit 5 000 pièces d'or. Si tu acceptes de rembourser sa dette, tu pourras lui parler autant que tu voudras.",
"Très bien. Je rembourse sa dette.",
"Désolé, mais je n'ai pas une telle somme.",
"Tu arrives trop tard. La dette de Clauss a été remboursée par l'un des pirates. Je te déconseille d'aller les voir ; ils n'aiment pas les étrangers.",
"Alors, comme ça, ce sont les pirates qui tiennent Clauss. Je vois...",
"Tu as besoin des services de mon chantier naval?",
"Ravi de faire ta connaissance.",
"Tu as besoin des services de mon chantier naval?",
"Parfait, ",
". Attelons-nous à ces réparations.",
"Merci. Mais d'abord, parlons.",
"J'ai changé d'avis. Je vais te donner 5 000 pièces d'or pour éponger la dette de Clauss.",
"La prochaine fois, peut-être. Il faut que j'y aille.",

};
