string DLG_TEXT[56] = {
"Bienvenue, ",
". Je crois qu'on ne s'est jamais rencontrés. Je suis Laurence Wellman, le capitaine du port.",
"Bonjour, Laurence. Moi, c'est ",
", le capitaine du ",
".",
"Bienvenue, ",
". Tu es là pour affaire?",
"Bonjour, ",
". J'ai vu ton navire entrer dans le port et j'étais sûr que tu viendrais me voir.",
"Ah, capitaine ",
". Qu'est-ce qui t'amène?",
"Bonjour, Laurence. J'aimerais te parler.",
"Je suis à ton service, ",
".",
"Où est-ce que je peux réparer et équiper mon navire à Redmond?",
"Il y a du travail ici?",
"Sur le port, j'ai rencontré un marin qui avait été débarqué de son navire.",
"Derrière les portes de la ville, tu trouveras le bureau du patron du chantier naval. La boutique du coin se trouve \nsur la place, devant la maison du gouverneur.",
"Je vois. Et où est la taverne?",
"Il y a du travail ici?",
"Merci. Au revoir.",
"La taverne du jeune Windem se trouve en face de la maison du gouverneur, \nde l'autre côté de la rue par rapport à la boutique de Thomas O'Reily.",
"Merci. Au revoir.",
"Il y a du travail ici?",
"Eh bien, parfois des marchands affrètent des navires pour transporter leurs marchandises, mais je n'ai pas eu de demandes dernièrement\nTu",
" pourrais aller voir le gouverneur ; il a peut-être du travail pour toi\nSinon, va à la taverne et adresse-toi aux marchands... Il y en a quelques-uns généralement.",
"Comme je te l'ai déjà dit, les marchands affrètent parfois des navires pour transporter leurs marchandises, mais je n'ai pas eu de demandes dernièrement.",
" Va voir le gouverneur Silehard ; il saura te conseiller\nEt parle aux clients de la taverne... On y trouve toutes sortes de gens.",
"Où est-ce que je peux réparer et équiper mon navire à Redmond?",
"Je vois. Merci.",
"Sur le quai, j'ai rencontré un marin qui avait été débarqué de son navire.",
"Adresse-toi à l'aubergiste, Windem, et discute avec O'Reily, le marchand local.",
"Où est-ce que je peux réparer et équiper mon navire à Redmond?",
" Sur le quai, j'ai rencontré un marin qui avait été débarqué de son navire.",
"Merci du conseil. Au revoir.",
"Ah, ça devait être Blum. Il a été débarqué pour avoir frappé un officier. Il a eu de la chance de ne pas être pendu.",
"Qu'est-ce qui s'est passé?",
"Eh bien, Blum semble désolé de tout ça...",
"Je vois. J'ai encore quelques questions à te poser.",
"C'est une histoire compliquée. À vrai dire, Blum n'est pas responsable\nTu vois il a pris la défense d'une serveuse de la taverne qu'un navigateur ivre harcelait\nC'est tout à son honneur, bien sûr, mais Blum a un caractère emporté et lorsque le navigateur l'a insulté, \nil l'a flanqué par terre.",
"Je vois. Eh bien, Blum semble désolé de tout ça...",
"C'est triste. Merci de m'avoir raconté toute l'histoire. Au revoir.",
"Il est trop tard pour être désolé. Il n'est pas prêt de rembarquer.",
"Il y a sûrement un moyen de lever sa sentence, pas vrai?",
"C'est triste. Visiblement, c'est un type bien. Bon, à plus tard, Laurence.",
"Tu sais, ",
", il y a peut-être une solution. Je serais prêt à changer d'avis si \nquelqu'un de respectable se portait garant de Blum.",
"Tu me considères comme quelqu'un de respectable?",
"Il est peu probable que ce pauvre bougre trouve quelqu'un pour lui rendre ce service.",
"Ah ça, oui. Tu es prêt à te porter garant de lui? Alors, je reviens sur ma décision\nPuisque tu acceptes de soutenir Blum, je te conseille de l'embaucher pour l'avoir à l'œil\nS'il venait à recommencer, ta réputation en pâtirait.",
"Je veillerai sur lui. Merci et au revoir!",
"Je peux te demander autre chose?",
"Tu me fais bonne impression, mais franchement, je ne te connais pas assez \npour accepter que tu te portes garant du jeune Blum. Ne le prends pas mal, ",
", mais il va \ndevoir trouver quelqu'un d'autre.",
"Eh bien, au revoir, Laurence.",
"Je peux te demander autre chose?",

};
