string DLG_TEXT[112] = {      
"Tu ferais mieux d'arrêter de parler et de te mettre au travail, l'ami. Les gardes nous surveillent avec leurs fouets.",
"Tu as raison. Je dois m'économiser pour mon évasion.",
"Quoi?",
"Rien. Ça n'a pas d'importance.",
"Eh! Tu es réveillé? Alors, au travail! Ces esclavagistes n'aiment pas qu'on lambine.",
"Comment suis-je arrivé ici?",
"Tu n'as pas mis longtemps à te faire une place au soleil? Il y a peu, tu étais encore ouvrier comme moi. Maintenant, tu es un maître.",
"Je ne veux pas me battre. J'ai juste besoin de réponses.",
"Te revoilà déjà? Tu as réussi à me faire libérer?",
"Oui, tu es libre. Mais avant de partir, j'aimerais que tu répondes à quelques questions.",
"Qu'est-ce que tu veux savoir? Je t'ai déjà tout dit.",
"Je t'avais promis de te laisser partir si tu répondais à toutes mes questions. Tu es libre maintenant.",
"Tu as réussi à me faire libérer?",
"Pas encore, mais je m'en occupe.",
"Non, désolé. Ils ont été trop gourmands. J'imagine que je vais devoir trouver un autre moyen de te faire parler.",
"Bonjour, capitaine. Tu as décidé de m'embaucher?",
"C'est pour ça que je suis dans ce marigot. Je suis ravi que tu n'aies pas encore trouvé de travail.",
"Non. J'ai d'autres affaires à régler.",
"Je t'ai entendu parler avec un officier. Tu es vraiment capitaine?",
"Ça ne te regarde pas.",
"Il est temps de partir. Tiens, prends ton épée et que Dieu nous protège!",
"On se retrouve à l'entrée.",
"On a réussi! Maintenant, il faut qu'on quitte l'île.",
"Ne restons pas ici. Montons à bord avant qu'ils ne donnent l'alerte!",
"Désolé, mais je pars seul. Je n'ai plus besoin de toi.",
"Qui es-tu et pourquoi me déranges-tu dans mon travail? Fais attention, ces esclavagistes n'aiment pas ça.",
"J'aimerais te poser une question sur des tablettes en argile découvertes dans ces mines.",
"Tu veux en savoir plus sur le type qui étudie les tablettes, c'est ça?",
"Oui, exactement.",
"Qui es-tu?",
"Tu peux me dire où se trouvent les tablettes indiennes?",
"Ce type a recopié les symboles des tablettes sur un parchemin. Puis il a pris la mer\nIl parlait de se rendre à Isla Muelle \npour mieux étudier ces symboles et les traduire.",
"Merci du renseignement.",
"Pourquoi je devrais répondre à tes questions?",
"Si tu réponds bien à mes questions, je te ferai sortir d'ici.",
"Parce que si tu refuses, je demanderai aux soldats de s'occuper de toi. Alors, qu'est-ce que tu préfères, parler ou encaisser les coups?",
"Ah, ordure!",
"Tu veux te battre, hein? Avec plaisir!",
"Alors, tu veux sortir d'ici, oui ou non?",
"Quoi? Tu peux me faire sortir?",
"C'est une mine, pas une prison. Le problème n'est pas de partir d'ici mais de quitter l'île.",
"Eh bien, mon navire mouille au large de l'île, alors ce n'est pas un problème.",
"Parfait! Tu sais te battre?",
"Quel capitaine ne sait pas se battre?",
"C'est vrai. Alors, voilà le plan : récemment, un glissement de terrain a enseveli un grand nombre d'ouvriers et quatre soldats.",
"Tu as réussi à récupérer leurs armes?",
"Oui. Maintenant, écoute : je peux envoyer des messages depuis la prison. Ton navire devra nous attendre près du phare.",
"D'accord. Remets cette lettre à mes officiers. Ils veilleront à ce que le navire soit là.",
"On a quelques heures devant nous avant notre évasion. Va te reposer.",
"Attends! Tu as déjà entendu parler de tablettes en terre avec d'étranges symboles? Elles devraient être cachées quelque part par ici.",
"C'est pour ça que tu es venu ici? Visiblement, tout le monde s'y intéresse...",
"Comment ça 'tout le monde'?",
"Il y a quelques mois, quelqu'un est venu en faire une copie. Et quelques jours plus tard, une dame est venue poser des questions à ce sujet.",
"Intéressant... Mais tu n'as pas répondu à ma question. Elles sont toujours ici?",
"Ce qu'il en reste, oui. Elles ont beaucoup souffert du glissement de terrain.",
"Oh, pas de chance! Et l'homme qui en a fait des copies? Tu sais où il est allé?",
"Il a parlé d'une colonie espagnole. C'est tout ce que je sais.",
"Très bien. Repose-toi et tiens-toi prêt à partir quand le moment viendra.",
"Qu'est-ce que tu veux savoir?",
"Ne me parle pas sur ce ton. Ce n'est pas ma faute si tu es dans ces mines.",
"Non, c'est de la faute d'un autre pirate. Une ordure du nom de ",
"Ethilrede Claar",
"Ethilrede Claar",
", qui a coulé mon navire et m'a vendu comme esclave.",
"Tu étais capitaine?",
"Eh bien, tu n'es plus capitaine, mais un mineur esclave, et ce que j'attends de toi, ce sont des réponses.",
"Oui, j'étais capitaine. Je commandais un navire marchand appelé 'Arethuse' avant d'arriver ici.",
"Écoute, je te propose un marché : tu réponds à mes questions et je te fais sortir d'ici.",
"Fascinant. Bon, maintenant que tu as dit ce que tu avais sur le cœeur, réponds à mes questions.",
"J'ai une meilleure idée. Tu me fais sortir d'ici et je répondrai à tes questions.",
"Marché conclu. Attends-moi ici.",
"Quoi? Tu sembles oublier qui est l'esclave ici. C'est moi qui mène la danse. De deux choses l'une : tu réponds à mes questions ou tu restes dans la mine.",
"Tu es un dur à cuire, hein?", 
"Ah, là on discute.",
"Alors, qu'est-ce qui t'intéresse?",
"Il paraît que tu as aidé un type qui était venu étudier des tablettes en argile découvertes dans les mines.",
"En effet. Un jeune homme. Il est venu ici et a recopié les tablettes sur un parchemin avant de repartir.",
"J'imagine que tu ne sais pas où il est allé.",
"Eh bien, il a parlé d'une colonie espagnole.",
"Parfait. J'ai peut-être une chance de le trouver.",
"Ça reste à voir.",
"Qu'est-ce que ça veut dire?",
"Eh bien, il y a quelques jours, une jeune femme a voulu en savoir plus sur ce type. Je lui ai tout dit et elle était plus jolie que toi! Alors, elle l'aura peut-être trouvé avant toi.",
"On verra bien.",
"Attends! Maintenant que je suis libre, j'aimerais te poser une question, pour changer.",
"Je t'écoute.",
"Je t'ai dit que j'étais capitaine sur un navire marchand, hein?",
"Laisse-moi deviner : tu veux rejoindre mon équipage?",
"C'est à peu près ça.",
"Ce n'est pas une mauvaise idée. Je suis à la recherche de marins qui ont la tête sur les épaules.",
"Je ne pense pas que ce soit une bonne idée.",
"Parfait! Je serais fier de naviguer sous tes ordres.",
"Pas de précipitation. Parlons d'abord de ton salaire.",
"Je crois que 1500 pièces d'or feront l'affaire.",
"C'est raisonnable pour un ancien capitaine de la marine marchande. Marché conclu.",
"Je ne pense pas pouvoir accepter ces conditions.",
"Bien, capitaine! Donne-moi le nom de ton navire et je t'y retrouverai.",
"Eh bien, je commande le '",
"'.",
"Dommage. Eh bien, si tu changes d'avis, sache que je vais aller chercher du travail à Falaise de Fleur.",
"D'accord. Je m'en souviendrai.",
"Il paraît que les esclavagistes t'ont amené ici. Ils se sont vantés de t'avoir roué de coups.",
"Et mes hommes?",
"Visiblement, ils ont réussi à s'enfuir.",
"Parfait. Ils vont bientôt venir me libérer.",
"Je ne compterais pas trop là-dessus.",
"Tu as peut-être raison. Je vais essayer de trouver un moyen de sortir d'ici.",
"Tu ne connais pas mes hommes. Ils sont prêts à tout pour moi!",
"Très bien, remets-toi au travail! Un garde arrive!",
"Et alors? Où veux-tu en venir?",
"...",
"...",
};
