string DLG_TEXT[33] = {
"Tu veux vendre des marchandises ou acheter du matériel? ",
"J'aimerais vendre quelques marchandises.",
"J'aimerais acheter du matériel.",
"Ni l'un ni l'autre. Au revoir!",
"Bonjour, ",
". Ma boutique est à ton service.",
"Merci. Je m'appelle ",
".",
", ",
". Ravi de te rencontrer. Tu es prêt à faire affaire, ",
"?",
"Eh bien, quel type de marchandises as-tu apporté à Redmond cette fois, capitaine ",
"? Mais tu n'es peut-être pas venu pour affaires.",
"Oh, capitaine! Ravi de te voir.",
"Voyons ce que tu as à vendre.",
"Pour le moment, j'aimerais discuter.",
"Au revoir.",
"Ravi de faire ta connaissance. Je suis ",
". J'espère qu'on fera affaire.",
"Eh bien, ",
", voyons ce que tu as à vendre.",
"J'aimerais te parler, ",
".",
"Au revoir.",
"Me parler? Bien sûr, c'est toujours un plaisir pour moi, capitaine.",
"En fait, je ne suis pas d'humeur à parler. Désolé.",
"Comme tu voudras, ",
".",
"Je peux jeter un coup d'oeil à tes marchandises.",
"Je dois partir. À bientôt.",
"Hélas, ",
", les Français m'ont confisqué mes meilleures marchandises et munitions et m'ont interdit de vendre le reste avant la fin de la guerre.",
"Eh bien, ce n'est pas de chance pour nous...",

};

