string DLG_TEXT[21] = {
"Je te serai éternellement redevable!",
"Pas du tout. J'ai été généreusement payé pour te sauver.",
"Mais qui es-tu? Pourquoi m'avoir sauvé?",
"Peu importe.",
"Je t'en prie, dis-moi qui tu es et pourquoi tu m'as sauvé?",
"On parlera plus tard. Pour le moment, fichons le camp. Je n'ai pas envie de bavarder avec un garde français.",
"Mais quand même, qui es-tu?",
"Je suis le capitaine ",
". Ta disparition a beaucoup affecté ton père et il m'a envoyé te chercher.",
"Je vois. J'allais le voir quand je me suis heurté aux problèmes que tu connais. Tu m'as sauvé la vie.",
"Ne me remercie pas. Je ne l'ai pas fait gratuitement.",
"Qu'importe, tu m'as sauvé la vie et je t'en suis reconnaissant. Et si on allait voir mon père?",
"Oui. On a assez perdu de temps.",
"Capitaine, je te suis infiniment reconnaissant. Tu accepterais peut-être que je rejoigne ton équipage? Je manie assez bien les armes et je connais les navires.",
"Les bons marins sont toujours les bienvenus, surtout s'ils sont loyaux. Bienvenue à bord.",
"J'apprécie ton offre, mais je ne peux pas l'accepter pour le moment.",
"Je comprends. Mais encore merci, capitaine. Je suis souvent chez le gouverneur. Viens me voir si tu changes d'avis.",
"Je m'en souviendrai. Bonne chance!",
"Capitaine, je suis ravi de te voir! Au cas où tu aurais changé d'avis, sache que je suis toujours prêt à rejoindre ton équipage.",
"C'est le cas. J'ai besoin d'un bon marin.",
"Je m'en souviendrai. Bonne chance!",

};
