string DLG_TEXT[40] = {       
"Hic...",
"Eh, ",
", l'ivrogne! Debout! Il faut qu'on parle!",
"Comment peut-on se saouler à ce point? Tu bois comme un trou!",
"...hic... ronflement...",
", debout, j'ai dit! C'est Geronimo qui m'envoie!",
"Geronimo? Tu aurais pu le dire au lieu de me donner des coups de pied!",
"Ouais, ouais. Pourquoi ne pas prendre un autre verre? Ça te fera peut-être oublier mes coups de pied. Allez, debout, il faut qu'on parle.",
"Qu'on parle de quoi? Je n'étais pas censé retrouver Geronimo avant demain. C'était le marché. ",
"Oh là là, tu es ivre mort, pas vrai? Tu te souviens de ton nom?",
"Écoute, je me souviens de tout. On doit se retrouver demain. Il nous donnera le reste de l'argent en échange des statuettes qu'on a volées à l'entrepôt du marchand.",
"Impressionnant, à un détail près. Les plans ont changé et c'est aujourd'hui le grand jour.",
"Écoute, ",
". Tu viens de tout avouer. Maintenant, essayons de trouver un terrain d'entente...",
"S'il veut qu'on se retrouve aujourd'hui, pourquoi n'est-il pas venu me le dire lui-même?",
"Tu ne comprends rien, pauvre ivrogne? En ville, tout le monde parle du vol et Geronimo préfère ne pas se faire remarquer.",
"Il a peur, c'est ça? J'ai tout de suite su que c'était un lâche!",
"Je n'ai que faire de ce que tu penses de lui, pas plus que lui d'ailleurs. Maintenant, debout, on y va.",
"Où ça?",
"Où ça, d'après toi? À l'endroit où tu as caché les statuettes, tiens! J'ose espérer que tu n'es pas assez fou pour les avoir gardées ici.",
"Euh... En fait... Eh bien... Elles sont ici.",
"Bravo. Bon, au moins on n'a pas à aller les chercher je ne sais où.",
"Écoute, ",
". Tu viens de tout avouer. Maintenant, essayons de trouver un terrain d'entente...",
"Attends une minute! Et Geronimo?",
"Pour être honnête, je ne connais pas de Geronimo. Donne-moi immédiatement ces statuettes.",
"Tu veux te battre, c'est ça? Très bien.",
"Qu'est-ce que tu veux dire?",
"Donne-moi les statuettes ou je te traîne jusqu'au premier garde que je trouverai et je lui révèle tout ce que tu viens de me dire. Et là, tu devras les restituer à la personne à qui tu les as volées. Dans les deux cas, tu perds les statuettes, mais avec moi, tu échappes à la prison.",
"Je pourrais te tuer et récupérer moi-même ces statuettes.",
"Ah, ordure!",
"Comment préfères-tu mourir?!",
"Tu promets que je serai libre? ",
"Je t'en donne ma parole.",
"Très bien. Je vais te faire confiance et tout te dire.",
"D'accord.",
"Ta parole?! Tu viens de me mentir! Tu me fais du chantage! Et tu crois que ta parole va me suffire?",
"Eh bien, je pourrais très bien de tailler en rondelles.",
"Geronimo a fait appel à moi pour voler ces statuettes moyennant 5 000 pièces d'or. J'étais supposé le retrouver demain en dehors de la ville.",
"Parfait! Maintenant, si tu veux bien m'excuser, je vais chercher un garde pour tout lui révéler. Si tu tiens à la vie, tiens-toi tranquille pendant que je te ligote.",

};
