string DLG_TEXT[78] = {
"Bonjour, ",
".",
"Content de te rencontrer. Mon nom est ",
".",
"Content de te voir, ",
". Mon nom est ",
"Marc Blacque",
"Marc Blacque",
".",
"Marc Blacque",
"? Je connais une famille qui porte ce nom ; elle habite à Falaise de Fleur.",
"J'ai déjà entendu ton nom quelque part, mais je ne sais plus où. Malheureusement, je n'ai pas le temps de chercher. Une autre fois, peut-être.",
"Tu les connais? Ils vont bien?",
"Tu es donc de la même famille. C'est bien ce que je pensais. C'est toi, le garçon qui a disparu il y a quelques années?",
"Oui, c'est moi. Mais je t'en prie, ",
", dis-moi comment ils vont.",
"Je n'ai pas de bonnes nouvelles, malheureusement. Ta soeur est morte, et ton père est devenu fou de chagrin après ta disparition.",
"Je n'ai pas de bonnes nouvelles, malheureusement. Ton père est devenu fou de chagrin après ta disparition.",
"Rachel Blacque",
"?! Non! Qu'est-ce qui s'est passé? Dis-moi la vérité, je t'en prie!",
"Ta soeur a été tuée par un ouvrier du port. Quant à ton père, il est toujours en vie, mais à peine.",
"Comment est-ce possible? Ma famille a besoin de moi, et je ne peux rien faire.",
"Pourquoi ne peux-tu rien faire? Pourquoi leur avoir fait croire que tu avais disparu, pendant tout ce temps?",
"C'est une longue histoire, ",
".",
"Je n'ai pas le temps, alors. À plus tard, peut-être.",
"J'ai tout mon temps, raconte.",
"Il y a cinq ans, j'avais mon propre navire marchand. Ce n'était qu'un petit sloop, mais je me faisais pas mal d'argent en livrant des marchandises dans tout l'archipel\nC'est là que les ennuis ont commencé ; mon bateau est tombé entre les mains des pirates, et ils m'ont vendu comme esclave. Quand j'ai enfin réussi à m'échapper, cela faisait près de cinq ans que je travaillais dans les plantations... Mais ils m'ont rattrapé. Ils allaient me fouetter à mort, en exemple, quand Thomas O'Reily m'a racheté\nBien entendu, quand j'étais esclave, je n'avais pas la possibilité d'envoyer des nouvelles à ma famille. Et depuis qu'O'Reily m'a libéré, c'est la guerre entre l'Angleterre et la France\nC'est pour ça que je n'ai pas pu tenir ma famille au courant...",
"Je peux leur remettre ta lettre.",
"Tu peux faire mieux qu'envoyer une lettre. Je peux te mener jusqu'à eux.",
"Tes histoires sont un peu trop longues, il faut que j'y aille.",
"Merci beaucoup! Prends-la, je l'ai écrite au moment où Thomas m'a acheté, et j'espérais la confier à quelqu'un.",
"Très bien, je donnerai cette lettre à ta famille dès que je serai de retour à Falaise de Fleur.",
"Eh, une seconde ; qu'est-ce que j'en retire, moi?",
"Dis à mon père que je vais bien, que je paierai ma rançon très bientôt et que je retournerai le voir.",
"Adieu.",
"Je sors de plusieurs années d'esclavage, je n'ai pas d'argent!",
"C'est dommage. Au revoir.",
"Bien sûr que non. Allez, donne-moi ta lettre, je vais le faire gratuitement.",
"C'est très aimable, ",
", mais je ne pourrai rentrer qu'une fois que j'aurai remboursé ma rançon de 3 000 pièces d'or à Thomas\nPour l'instant, je n'en ai que 500.",
"Si je pouvais, je t'aiderais. La prochaine fois, peut-être.",
"Ce n'est pas un problème. Je vais payer le reste et te ramener chez toi.",
"Oh, merci beaucoup!",
"Tu me remercieras quand tu seras chez toi en un seul morceau. Dis-moi où je peux trouver Thomas, à présent.",
"Facile, c'est le propriétaire du magasin.",
"Bien. Donne-moi tes 500 pièces et attends-moi ici.",
", ",
". Tu as parlé à Thomas?",
"Pas encore. Je reviendrai quand je lui aurai parlé.",
", ",
". Tu as parlé à Thomas?",
"Oui, mais il a refusé de te laisser partir. Adieu...",
", ",
". Tu as parlé à Thomas?",
"Oui, tu es libre. Mon bateau est au port, ",
". Je t'y attendrai.",
".",
"J'ai donné la lettre à ton père, et sa lucidité est miraculeusement revenue.",
".",
"Pas maintenant, je suis occupé.",
"Je peux porter ta lettre, si tu veux.",
"Je peux t'aider à retrouver ta famille.",
"Merci de ton aide, ",
"!",
"Merci beaucoup de ton aide, ",
"! Tu es très généreux.",
"Je te remercie, ",
", de ce que tu as fait pour moi.",
"Je t'en prie. Content d'avoir pu t'aider.",
"Attends! Et mon argent, il est où?",
"Ah oui, ton argent. Tiens.",
"Quel argent?",
"Je te suis reconnaissant de m'avoir soulagé de ce poids.",
"Je t'en prie. Adieu.",
"Je peux t'aider à retrouver ta famille.",
"Tu as perdu la mémoire? Je t'avais donné 500 pièces d'or!",
"Tu dois me confondre avec quelqu'un d'autre. Au revoir!",

};