string DLG_TEXT[33] = {
"Bienvenue dans ma taverne, étranger. Mon nom est ",
", et je dirais que tu n'es pas là pour boire un verre.",
"Mon nom est ",
", et tu as vu juste. Je suis là pour affaires.",
"Mon nom est ",
", et en effet, je ne suis pas là pour boire. J'ai besoin de réponses.",
"En quoi puis-je t'aider?",
"J'ai besoin d'informations.",
"Je cherche des marins pour mon équipage.",
"J'ai besoin de gars qui cherchent du travail et ne posent pas trop de questions.",
"As-tu une chambre libre? Je voudrais séjourner ici quelque temps.",
"J'ai besoin d'une chambre propre, avec un lit propre. Rien de luxueux.",
"Je n'ai besoin de rien, pour le moment. Au revoir.",
"J'ai une chambre libre, oui. Combien de temps comptes-tu rester?",
"Jusqu'à demain matin.",
"Jusqu'à la tombée de la nuit.",
"Cela te coûtera 5 pièces d'or.",
"Très bien, tiens.",
"Malheureusement, je crois que je n'ai pas les moyens de m'offrir le luxe d'un lit. À ce prix-là, je passerai la nuit ici, dans la taverne.",
"Non merci. A ce prix-là, je préfère dormir ici.",
"Je vais y réfléchir.",
"Cela te coûtera 5 pièces d'or.",
"Très bien, tiens.",
"Malheureusement, je crois que je n'ai pas les moyens de m'offrir le luxe d'un lit. À ce prix-là, je passerai la nuit ici, dans la taverne.",
"Non merci. À ce prix-là, je préfère dormir ici.",
"Je vais y réfléchir.",
"Je ne suis pas étonné que tu sois venu là. Dans ce travail, on recueille beaucoup d'informations. Qu'est-ce que tu veux savoir?",
"Je n'ai pas de questions, pour le moment. Parlons d'autre chose.",
"À cette heure? Tous les marins sont chez eux, ou saouls\nSi tu veux embaucher du monde, attends demain matin. J'ai des chambres libres, si ça t'intéresse.",
"As-tu une chambre libre?",
"Peut-être plus tard. J'ai une autre question.",
"Messieurs, du calme! Cessez sur-le-champ, ou j'appelle les gardes!",
"Inutile, j'allais partir.",

};