string DLG_TEXT[43] = {
"Content de te voir, ",
". Mon nom est ",
", et je suis à ton service.",
"Et je suis le capitaine ",
".",
"Content de te revoir, ",
".",
"C'est toi! J'espérais ne plus jamais te revoir.",
"Bonne journée à toi aussi, ",
".",
"La vie est parfois injuste, ",
"Veux-tu voir ce que j'ai en stock?",
"Oui, montre-moi ça.",
"Plus tard. Pour le moment, j'aimerais discuter avec toi.",
"Une autre fois.",
"Tu veux me refiler des marchandises ou tu veux juste acheter quelque chose?",
"Je voudrais vendre une partie des marchandises que j'ai apportées.",
"Je suis là pour acheter.",
"Ni l'un, ni l'autre. Au revoir!",
"Très bien, de quoi veux-tu parler?",
"Je t'écoute.",
"On m'a demandé de te faire une livraison.",
"Tu n'aurais pas besoin d'un capitaine, par hasard? J'ai un excellent bateau et je peux livrer n'importe quelle marchandise à n'importe quel endroit.",
"Je n'ai pas le temps de discuter.",
"Non, je n'ai pas besoin de tes services. Pas tant que tu t'attaqueras aux bateaux français, en tout cas.",
"Au revoir, dans ce cas.",
"Désolé, je n'ai rien pour toi pour le moment.",
"Je reviendrai plus tard.",
"Désolé, il n'y a pas assez de place sur ton bateau pour ce que j'ai en tête.",
"Je reviendrai plus tard.",
"Oh! J'allais justement te demander un service. J'ai une cargaison à livrer à ",
", aussi vite que possible. Si tu réussis à le faire en un mois, je te donnerai ",
" pièces d'or à ton arrivée. Qu'en dis-tu?",
"Ça me plaît bien.",
"Je ne peux pas accepter ça.",
"Je t'ai déjà dit que je n'avais rien pour toi.",
"Oh, désolé.",
"Tu arrives un peu tard, non? J'ai trouvé tout ce dont j'avais besoin. Au revoir.",
"Adieu.",
"Oh! Ça fait longtemps que j'attends ça. Voici ta récompense, jeune homme.",
"C'est un plaisir.",
"Désolé, je n'ai pas besoin de tes services pour le moment.",
"Dommage. Je voudrais te poser une autre question.",

};