string DLG_TEXT[118] = {
"Capitaine, tant que ta cible est toujours en vie, nous n'avons rien à nous dire.",
"D'accord, señor. D'accord. Je reviendrai quand j'aurai terminé le travail.",
"Bien joué, capitaine! Voici tes 3 000 pièces d'or, comme convenu.",
"Merci. Tu as d'autres tâches pour moi?",
"Merci et au revoir. J'en ai assez de ce racket.",
"Ah, capitaine! Beau travail! Tu as certainement mérité tes 4 500 pièces d'or. Tout s'est bien passé?",
"Oui. C'était presque agréable, même! C'est pas souvent que l'on rencontre un type aussi grossier que ce ",
"Geffrey Bampfylde",
"! Que dirais-tu d'un autre travail?",
"C'était facile. Trop facile, en fait. Quelque chose me dit que je devrais arrêter ce travail avant que les choses ne tournent mal.",
"Capitaine, tu n'arrêtes pas de me surprendre! En toute honnêteté, je ne pensais pas que tu viendrais à bout de ",
"Pepin Bertillon",
". Toutes mes excuses pour avoir douté de toi. Et voici tes 7 000 pièces d'or, comme convenu.",
"Tu as raison de t'excuser. La seule chose que cet homme pouvait faire, c'était de parler. Si l'argent se gagnait toujours comme ça, je serais riche.",
"Merci et au revoir. J'en ai assez de ce racket.",
"Capitaine, des mercenaires comme toi, il n'y en a pas deux! Voici tes 10 000 pièces d'or. Mais dis-moi, comment as-tu fait pour réussir à battre ",
"Amerigo Vieira",
"? Il a échappé à mes hommes pendant des années!",
"Du talent et un peu de chance, c'est tout ce qu'il a fallu.",
"Peu importe, c'est fait! Et j'en ai assez de ce genre de travail.",
"Capitaine, tu m'as rendu un grand service en me débarrassant de l'Italien! Malheureusement, tu as aussi gagné trop d'argent. Tu vas donc être enterré un peu plus tôt que prévu. Je suis vraiment désolé, capitaine.",
"Ainsi donc, ",
"Vito Leone",
" avait raison à propos de ta perfidie! J'aurais dû le croire. En garde, chien de traître!",
"Capitaine, que fais-tu ici?!",
"Don ",
"Vito Leone",
" m'a raconté des choses intéressantes sur la manière dont tu conduis tes affaires. Il m'a notamment dit que tes partenaires avaient tendance à mourir jeunes...",
"Ah, Capitaine ",
"! Je me demandais quand tu nous daignerais nous honorer de ta présence. Tu n'étais pas pressé de terminer le travail, hein?",
"Et tu n'as pas l'air terrifié pour quelqu'un dont la tête vaut tant d'or.",
"Tant d'or? Depuis quand 1 500 pièces d'or reflètent-elles la valeur de ma tête? Regarde autour de toi, capitaine! Qu'est-ce qe tu vois?",
"Je n'ai jamais excellé aux devinettes. Je dois chercher quoi, au juste?",
"Tu as dû remarquer les trois hommes armés qui sont prêts à te couper en rondelles si tu fais le moindre geste! Je suis sûr que ma tête vaut beaucoup plus que 1 500 pièces d'or. Et la tienne?",
"Je crois que je vois ce que tu veux dire.",
"Ah, ce sont des hommes? Et moi qui pensais que c'était des sangliers apprivoisés!",
"Ce que je veux dire est très simple. Tu ne pourras pas accomplir la mission que cet idiot de ",
"Ambroz Bricenos",
" t'a confiée.",
"En effet, il est difficile de te contredire. Il ne me reste donc qu'à m'excuser de t'avoir dérangé et à prendre congé. J'espère que je n'aurai pas à me battre pour sortir.",
"Ah, tu crois? Ce sont les arrogants crétins comme toi que j'aime bien remettre à leur place! Tu veux danser?",
"Inutile, capitaine, je ne suis pas fâché. Je suis habitué à ce genre de choses, dans ma profession. En fait, si tu veux, je pourrais te faire une proposition intéressante...",
"J'écoute.",
"Merci pour la proposition, mais cette rencontre n'a pas vraiment contribué à éveiller mon intérêt pour ce genre de travail.",
"Les conditions sont très simples. Primo : tu as un mois pour terminer le travail, pas un jour de plus. Si tu réussis, tu pourras venir chercher la récompense quand tu voudras.",
"...",
"Secundo : je ne veux aucun témoin. Je ne tolèrerai aucune exception.",
"...",
"Tertio : immédiatement après avoir reçu ta récompense, tu devras accepter une nouvelle mission. Tu peux refuser, mais tu n'auras pas beaucoup de temps pour réfléchir.",
"...",
"Voilà donc les conditions. Si tu désobéis à une seule, ou si tu refuses une mission, nous ne travaillerons plus ensemble. En fait, tu n'auras pas intérêt à m'adresser la parole.",
"J'accepte ces conditions. Quelle sera ma première mission?",
"Je vois. Merci pour la proposition, mais je ne suis pas prêt à devenir mercenaire à plein temps.",
"Je suis sûr que tu as déjà deviné. Débarrasse-moi de cet ",
"Ambroz Bricenos",
" ",
"Ambroz Bricenos",
". Cela prouvera ta loyauté envers moi et tu gagneras 3 000 pièces d'or.",
"J'aime le risque quand il en vaut la chandelle. J'accepte.",
"Désolé, mais je ne peux pas me retourner contre mon ancien employeur, même s'il m'a joué un mauvais tour.",
"Parfait. N'oublie pas: tu as exactement un mois pour le faire.",
"Je n'oublierai pas.",
"Je ne te retiendrai donc pas plus longtemps, capitaine. Et si tu décides d'aller voir ",
"Ambroz Bricenos",
", ne te dérange pas. Tu ne le trouveras probablement pas en vie.",
"Compris. Au revoir.",
"Dommage! Ce fut un plaisir de travailler avec toi. Adieu, capitaine!",
"Au revoir.",
"Tu n'aurais pas dû dire ça, capitaine. Je n'aime pas les insolents. Prépare-toi à mourir!",
"Je ne suis pas prêt à le faire, mais toi, on dirait que si!",
"Bien sûr. La cible est un marchand du nom de ",
"Geffrey Bampfylde",
"Geffrey Bampfylde",
". Sa maison se trouve à Greenford, de l'autre côté de la rue, à gauche de la taverne. La récompense est de 4 500 pièces d'or.",
"Prépare l'or. Cette tâche ne me prendra pas beaucoup de temps.",
"Ça a l'air trop compliqué. Je me retire.",
"Tu commences à aimer ce travail, capitaine? Mais ne te mets pas à trop l'aimer : c'est le meilleur moyen d'échouer. Écoute bien: cette tâche n'est pas facile.",
"J'aime les défis quand ils en valent la peine. Explique.",
"Ça a l'air trop compliqué. Je me retire.",
"La cible est un contrebandier du nom de ",
"Pepin Bertillon",
"Pepin Bertillon",
". Il est difficile à trouver. Tout ce que nous savons, c'est que son navire se rend souvent à Quebradas Costillas.",
"Une île de pirates, hein? Très commode. Aucun soldat...",
"Ça a l'air trop compliqué. Je me retire.",
"Aucun soldat, c'est vrai. Mais beaucoup d'assassins. Ils sont stupides mais armés et dangereux. Donc ",
"Pepin Bertillon",
" ne risque pas de se montrer sans gardes du corps. Compte tenu du danger, la récompense est fixée à 7 000 pièces d'or.",
"Pour une somme pareille, tu peux considérer la mission comme accomplie.",
"Ça a l'air trop compliqué. Je me retire.",
"Compte tenu de ton habileté, je suis sûr que tu réussiras. Mais la prochaine mission ne sera pas aussi facile.",
"Je peux le faire.",
"Dans ce cas, je me retire.",
"J'espère que tu pourras, parce que cet ennemi est mon ennemi le plus mortel. Son nom est ",
"Amerigo Vieira",
"Amerigo Vieira",
". Il habite Conceicao, dans une maison située à droite de la résidence du Gouverneur, en haut.",
"Et combien vaut cette dangereuse mission?",
"Ça a l'air trop compliqué. Je me retire.",
"10 000 pièces d'or. Mais n'oublie pas: il manie l'épée mieux que quiconque dans l'archipel. Je compte sur toi, capitaine. ",
"Amerigo Vieira",
" m'a trahi et je ne connaîtrai pas de repos tant qu'il sera en vie.",
"Il est déjà mort, mais il ne le sait pas encore.",
"Ça a l'air trop compliqué. Je me retire.",
"Ton habileté est unique et j'ai une mission que toi seul peut accomplir.",
"J'écoute.",
"J'en ai assez de tes missions. Je m'en vais.",
"Il y a peu de temps, un messager du continent est arrivé dans l'archipel. Il doit mourir, et le plus tôt possible! La nouvelle qu'il apporte est trop dangereuse.",
"Le messager, donc. Et la récompense?",
"J'en ai assez de tes missions. Je m'en vais.",
"Une somme royale : 20 000 pièces d'or. Cette tâche est très importante pour moi.",
"Marché conclu. Où pourrai-je le trouver?",
"Ça m'a l'air trop dangereux. Je m'en vais.",
"Là est le problème! Nous ne connaissons même pas son nom. Tout ce que nous savons, c'est que c'est un vieil Italien et qu'il est quelque part à Conceicao. Tu devras donc le trouver tout seul.",
"Tout ça ne m'avance pas à grand chose. Mais je le retrouverai.",
"Ça a l'air trop compliqué. Je me retire.",
"J'aurais dû me douter que tu ne ferais que bavarder avec ce vieux renard au lieu de le tuer! J'aurais dû faire le travail moi-même. Il ne perd rien pour attendre. Quant à toi, tu n'as plus rien à attendre!",
"Tu divagues, mais je vais te remettre les idées en place. En garde!",

};
