string DLG_TEXT[22] = {
"Dis-moi, ",
"? Ce n'est pas le 'Cleopatra' là-bas, à quai?",
"Non. C'est le '",
"', mon navire.",
"As-tu déjà vu le 'Cleopatra' au cours de tes voyages?",
"Non, j'ai peur de n'avoir jamais croisé un navire de ce nom.",
"Dommage. Si tu le vois un jour, je voudrais que tu dises à son capitaine, mon fils, que je l'attends.",
"Si j'en ai l'occasion, je n'y manquerai pas. Au revoir, capitaine.",
"Excuse-moi, ",
". As-tu vu le 'Cleopatra' au cours de tes voyages?",
"Non. Je ne l'ai jamais croisé. Mais j'ai une lettre de ton fils à te remettre.",
"Non seulement j'ai rencontré ton fils, mais en plus je l'ai ramené ici avec moi.",
"Ton fils? Cet imbécile qui n'est même pas capable de se prendre en charge? Je l'ai amené avec moi. Il sera là dans une minute, s'il ne se perd pas.",
"Non, je n'ai pas rencontré ton fils.",
"Tu m'as maintes fois posé cette question, vieil homme... et la réponse est toujours non.",
"Une lettre?! De Marc? Tu ne mentirais pas à un vieux marin, n'est-ce pas?",
"Peut-être, mais pas cette fois-ci. Voici la lettre. J'espère que tu verras ton fils très bientôt.",
"Marc? Est-ce possible?! Le ciel a entendu mes prières et t'a ramené à moi!",
"D'accord. Je ne vais pas t'ennuyer plus longtemps. Au revoir!",
"Tes parents peuvent être fiers de toi après ce que tu as fait, ",
".",
"Merci. Mais je dois partir maintenant. J'ai beaucoup de choses à faire.",

};