string DLG_TEXT[55] = {
"Qu'est-ce que tu fais ici, ",
"?",
"Rien. Je jette juste un coup d'œil aux alentours.",
"J'aimerais te parler de l'un de tes ouvriers.",
"Je veux acheter la liberté de ton ouvrier, ",
"Leborio Drago",
"Leborio Drago",
".",
"Qui est-ce?",
"Tu veux dire... moi?",
"Que veux-tu? Tu ne vois pas que je suis occupé? J'ai une gigantesque pile de paperasse à traiter.",
"Je ne te dérangerai pas longtemps. Laisse-moi juste te poser une question.",
"Mon affaire est plus urgente que ta paperasse. Si tu veux retourner à ton travail, réponds juste à ma question.",
"D'accord. Je vois qu'il ne va pas être facile de se débarrasser de toi. Que veux-tu savoir?",
"J'ai besoin de savoir si les tablettes en argile sont encore ici. Celles sur lesquelles sont gravés les étranges caractères et qui ont été trouvées dans les mines, il y a quelque temps.",
"Je pourrai peut-être t'aider. On dit que tu te prétends capitaine?",
"Bien sûr que je suis capitaine! Je m'appelle ",
" et je suis au service de la couronne anglaise.",
"Oui... Il me semble avoir déjà entendu ton nom.",
"C'est possible. Je suis venu ici récemment pour affaires. J'ai dû sortir un prisonnier de prison et le livrer au gouverneur de Redmond.",
"Oui, c'est ça. Le commandant de la prison m'a parlé de toi.",
"Tu y es. Tu peux me libérer maintenant, alors?",
"Ce n'est pas si simple. On a payé pour toi.",
"Je vois. Et combien dois-je payer pour sortir d'ici?",
"Tu vaux 10 pièces d'or. Mais tu sais, j'aurai des explications à fournir quand ils apprendront que tes solides épaules ont disparu. Alors je pense que 1 000 pièces d'or seraient une somme plus appropriée.",
"D'accord. Envoie un homme à mon navire qui mouille au port et mes hommes te donneront l'argent.",
"Tu es fou? Je sais que je vaux plus de 10 pièces d'or, mais où crois-tu que je vais en trouver 1 000?",
"Je m'en occupe. Sois patient.",
"Attends! Je suis ici pour affaires. On dit que des tablettes en argile couvertes de symboles étranges ont été trouvées ici.",
"C'est vrai, on les a trouvées ici. Mais j'ai peur que tu sois venu pour rien.",
"Pourquoi ça? Quelqu'un les a emportées?",
"Non! Qui voudrait de cette camelote? \nNon, un récent glissement de terrain a détruit toutes ces tablettes sauf une ; et même celle qui reste est en morceaux.",
"C'est vraiment dommage. Le gouverneur ",
"Robert Christopher Silehard",
" sera mécontent.",
"Oh! Tu représentes Son Excellence? Alors je devrais sans doute préciser qu'avant l'éboulement, un jeune homme est venu ici et a fait des copies de ces tablettes sur parchemin.",
"Où puis-je le trouver?",
"J'ai peur de ne pas pouvoir t'aider sur ce sujet, mais je sais que l'un des esclaves ici a été désigné pour s'occuper du jeune homme pendant qu'il examinait les tablettes. Si tu le trouves et si tu lui parles, il pourra peut-être t'aider.",
"D'accord, merci.",
"Alors je ne peux pas t'aider. Maintenant, laisse-moi tranquille!",
"...",
"Qui, exactement?",
"Un dénommé ",
"Leborio Drago",
"Leborio Drago",
" m'intéresse. Je voudrais acheter sa liberté, le sortir des mines.",
"Ça ne me dit rien. Je ne connais pas les prisonniers par leur nom.",
"Alors, je le trouverai moi-même. Je veux juste savoir si on peut passer un marché.",
"Je n'ai pas de raison de te le refuser. On reçoit régulièrement de nouveaux bras... euh... ouvriers, alors ce n'est pas la perte de l'un d'eux qui risque de provoquer la fermeture des mines.",
"D'accord. Dis-moi ton prix.",
"Eh bien, si tu es si pressé de le libérer, je peux te le céder pour 1 000 pièces d'or.",
"Tu es fou? C'est une fortune!",
"Un bon ouvrier coûte cher, de nos jours.",
"D'accord. Marché conclu. Prends ton argent.",
"Personne au monde, esclave ou pas, ne vaut une telle fortune!",

};