string DLG_TEXT[46] = {
"Hé, il y a de l'ambiance dans cette bonne vieille ville aujourd'hui, on dirait?!",
"Euh, ouais.",
"Qu'est-ce que tu veux? Si tu ne veux pas te joindre à la fête, ne la gâche pas.",
"Tu crois qu'on s'amuse, toi, sale brute?",
"La fête? On dirait que vous êtes prêts à brûler quelqu'un.",
"Alors, tu as décidé de ne pas t'en mêler? Sage décision. Et maintenant, file!",
"Tu cherches les ennuis?",
"Je t'ai dit de filer, à moins que tu ne veuilles rejoindre le vieux!",
"Écoute, quelqu'un t'a vu me frapper le premier.",
"Et alors? Tu crois que quelqu'un va accourir à ton secours? Je vois beaucoup de mes camarades ici - je ne vois aucun des tiens, étranger.",
"Je n'aurai pas besoin de camarades quand les soldats arriveront.",
"Ouais? Où sont-ils en ce moment? Qu'est-ce qui te fait croire qu'ils t'aideront?",
"Le plus important, c'est qu'ils ne nous dérangent pas.",
"Bien sûr, viens avec nous! Tu ne verras nulle part un aussi beau spectacle!",
"Spectacle? Tu appelles ça un spectacle, de voir un homme en flammes?",
"Eh, c'est mieux que de travailler au port!",
"Oui, je devine que vous vous ennuyez ferme.",
"Tu sais, c'est à cause de types comme toi que cette colonie est considérée comme l'île la plus barbare de tout l'archipel. Le gouverneur ",
"Robert Christopher Silehard",
" en personne s'en est plaint à moi plusieurs fois.",
"D'accord. Vous êtes une bande de brutes sans cervelle qui ne sait pas quoi inventer pour se distraire.",
"Je pourrais peut-être t'offrir quelque chose de plus excitant?",
"Vous ne préfèreriez pas plutôt boire un verre... ou six? C'est ma tournée.",
"Aucun homme digne de ce nom ne resterait là à regarder un vieil homme se faire brûler vif.",
"Le gouverneur en personne? Tu rigoles!",
"J'ai l'air de rigoler? Il m'a envoyé ici pour vérifier si les choses avaient empiré. Il ne va pas aimer mon rapport.",
"Tu mens. À ton avis, qu'est-ce qu'on fait des fanfarons de ton espèce par ici? Va au diable.",
"À ton avis, qu'est-ce que je fais de ceux qui me parlent sur ce ton, scélérat?",
"D'accord, d'accord! Je ne veux pas de problèmes.",
"Un rapport? Tu veux rire! L'archipel tout entier trempe dans la piraterie!",
"Peut-être, mais on ne fait pas brûler des vieux dans toutes les colonies. As-tu informé l'Église de ton intention de brûler cet homme?",
"Aucun besoin. Je pense que l'Église approuvera nos actions.",
"Bon, bon. Tu t'appelles comment, déjà?",
"Tu gâches tout, tu sais? Prends le vieux et file!",
"Voilà qui est parler.",
"Tu sais ce qu'on est capable d'engloutir, mes camarades et moi? Qu'est-ce qui te fait croire que tu peux payer pour nous tous?",
"J'ai 2 000 pièces d'or qui me font croire que je le peux. Vous pouvez boire jusqu'à l'inconscience avec une telle somme.",
"Non, je n'ai pas une telle somme, maintenant que tu en parles. Mais peux-tu vraiment considérer cette exécution comme un petit divertissement?",
"Ça me paraît bien! Mais on devrait peut-être commencer par brûler le vieux...",
"Laisse-le moi. Je m'en occupe.",
"Qui as-tu traité de brute?!",
"Alors non seulement tu es idiot, mais en plus tu es sourd? C'est toi que j'ai traité de brute. Seul un animal peut prendre plaisir à un tel spectacle.",
"Qu'est-ce que tu fais ici? Tu cherches les ennuis? Eh bien, on peut arranger ça tout de suite!",
"Quoi? Tu te cacherais derrière tes camarades, hein? Je ne devrais pas en attendre plus d'un lâche de ton espèce, prêt à brûler un vieux pour amuser la galerie.",
"Tu crois me faire peur? Je serai content de rectifier cette erreur!",
"Montre-moi ce que tu sais faire, animal!",

};