string DLG_TEXT[60] = {
"Que veux-tu?",
"Tu vois que ce type ne résiste pas. Je ne te laisserai pas tuer un homme désarmé. Jette ton épée.",
"Tout va bien. Continue.",
"Tu as vu ce que j'ai fait? Avec un seul coup...",
"Oui, impressionnant.",
"Tu as vu de quelle manière j'ai puni Artois? L'ordure m'a dit qu'il était bon navigateur,\nmais ça ne l'a pas empêché de couler mon navire et de ruiner toute ma cargaison. Il ne se vantera plus, hein?\nJe suis un bon capitaine ; aurais-tu une place pour moi sur ton navire?\nDemande à tout le monde par ici ; ils te diront tous que Blythe est le meilleur pirate qu'ils connaissent!",
"Désolé. Ça ne m'intéresse pas.",
"Une chose est sûre : tu sais te vanter... mais on va voir comment tu t'en sors dans les faits. Si tu es ne serait-ce qu'à moitié aussi doué que tu le dis, on devrait bien s'entendre.",
"Tu ne le regretteras pas! Il ne reste plus qu'à parler de mon salaire. Je ne travaille pas pour rien, tu sais.",
"Combien veux-tu?",
"3000 pièces d'or et mon âme t'appartient.",
"Marché conclu. Bienvenue dans l'équipage.",
"Hum. Tu as une haute opinion de toi-même. Je vais y réfléchir... plus tard.",
"Puis-je me joindre aux membres de ton équipage? Je ne demande que 300 pièces d'or.",
"Désolé. Mon équipage est au complet.",
"D'accord. Voici tes 300 pièces d'or.",
"Quels sont tes ordres, capitaine?",
"Je t'écoute.",
"Je ne fais que jeter un coup d'œil aux alentours.",
"Rien.",
"Capitaine, c'est toi?! Content de te voir! Je viens de passer un marché qui va faire de nous des hommes riches!",
"Quel marché?",
"Bonjour, capitaine.",
"Quoi? Pourquoi as-tu quitté le navire?!",
"Eh bien, j'ai parié 10 000 pièces d'or avec les gens du coin qu'on réussirait à couler Dirty Harry, Harry le salingue.",
"Qu'est-ce que tu racontes? Tu recommences?!",
"Qu'est-ce que tu veux dire, capitaine? D'accord, le contrat sur le chocolat a été difficile à digérer, mais il est question de 10 000 pièces d'or, cette fois!",
"C'en est trop. J'en ai ras-le-bol de tes combines tordues! Tu es viré!",
"Va annuler ce pari stupide. Sur-le-champ! J'en ai plus que marre de tes 'initiatives'!",
"Parle-moi de ce Harry.",
"Pas de grandes difficultés, capitaine. On a un mois pour couler cette ordure. Il ne doit pas être bien loin d'ici.",
"J'ai dit : parle-moi DE CE HARRY!",
"Oh, allons, capitaine, ne t'énerve pas comme ça. Bon, ce Harry n'a qu'un minable petit bateau... une corvette ou une frégate, je ne sais pas trop.\nEt le gouverneur local a mis sa tête à prix pour 3 000 pièces d'or. On en obtiendra 10 000 de plus si on le coule avant un mois.",
"Une frégate ou une corvette?! Nigel, tu as complètement perdu la tête?! Au diable ce pari!",
"Mmh. C'est risqué... mais la récompense en vaut la peine. On peut s'occuper de ce Harry.",
"Je savais que tu serais d'accord, capitaine! Tu vas voir! Toi et moi, on va faire de grandes choses!",
"Oh là là... La dernière partie de ce que tu viens de dire est particulièrement rassurante...",
"Oh, c'est facile. On livre cette cargaison de chocolat à Isla Muelle et on se fait payer 2 000 piastres!",
"Quoi?! Qui t'a autorisé à passer des contrats à ma place?",
"Calme-toi. C'est une affaire en or. J'ai été capitaine moi aussi, pendant quelque temps, alors je sais comment négocier.",
"C'est ton dernier exploit. Tu es viré.",
"D'accord, tu as une demi-heure pour annuler le contrat et revenir au navire. C'est CLAIR?!",
"Tu as de la chance que je ne veuille pas risquer ma réputation en annulant ce contrat. Si tu recommences, tu auras de sérieux ennuis.",
"Calme-toi, capitaine. Ne me regarde pas comme ça. Je vais tout t'expliquer.",
"Tu as plutôt intérêt.",
"Tu comprends, ce sale chien dont j'ai coulé le bateau m'a joué un sacré tour, il y a quelques mois.\nJe ne pouvais pas le laisser filer après ça, ça non! Après tout, ce rat m'a vendu des marchandises avariées!",
"Oh, bon sang, Nigel, combien de catastrophes vas-tu encore attirer?! C'est fini, tu es viré!",
"Eh bien, je crois que tu as bien fait.",
"On a réussi, cap'taine! Ça leur apprend...",
"La ferme, Nigel! Tu es viré!",
"Oui, oui, mais souviens-toi : c'était ta dernière entourloupe! Compris? Si tu recommences, je te fais passer par-dessus bord!",
"Comme tu voudras, capitaine.",
"D'accord, remonte à bord.",
"On n'a rien à se dire.",
"...",
"Tu ne devrais pas dire ça, capitaine. Tout ce que je veux, c'est protéger tes intérêts...",
"La ferme! Combien de tonnes de chocolat est-ce qu'on doit livrer?",
"Seulement 200 tonnes, capitaine.",
"Hum. D'accord, on a assez de place pour ça. Maintenant, monte à bord!",
"Tu es fou! Où est-ce que je vais les mettre, dans ma cabine?! Tu as une demi-heure pour annuler ce contrat!",

};