string DLG_TEXT[135] = {
"Bonjour, ",
". Je t'ai entendu parler à ce vieux fou. ",
"Milon Blacque",
".",
"Cette conversation ne te regarde pas, et de toute façon, je n'ai pas le temps de l'expliquer.",
"Pourquoi dis-tu qu'il est fou? Il m'a l'air plutôt sensé.",
"Pourrais-tu me dire, ",
", quel rafiot se balance là-bas, près de la côte?",
"C'est le navire '",
"', n'est-ce pas?",
"Oui, c'est exact.",
"Montre un peu plus de respect quand tu parles de mon navire!",
"Oh, désolé. Je ne savais pas que c'était ton rafiot!",
"Fais attention à ce que tu dis!",
"Désolé, ",
". Je ne fais que t'asticoter un peu. Je m'appelle ",
". Je travaille au port.",
"Moi, c'est ",
", et je suis le capitaine du '",
".'",
"Oui, je l'avais deviné, ",
".",
"Eh bien, puisque tu es si perspicace, tu peux peut-être répondre à une ou deux questions.",
"Avec plaisir : je manque de liquide en ce moment.",
"Quoi? Je ne vais pas te payer pour rester là à discuter avec moi.",
"Tu veux de l'argent, c'est ça? D'accord, voici une pièce d'or pour ton temps.",
"Désolé, ",
". Je viens de me souvenir que j'ai une affaire urgente à régler.",
"Au revoir.",
"Attends! Voici une pièce d'or.",
"Que veux-tu savoir, ",
"?",
"Pour commencer, raconte-moi les dernières nouvelles. Ensuite, on verra...",
"Une importante cargaison de marchandises prohibées est arrivée au port, il n'y a pas longtemps\nL'inspecteur du port ",
"Turpin Cabanel",
"Turpin Cabanel",
" s'est évertué à trouver les contrebandiers qui l'avaient introduite en ville.",
"Rien de bien original à ça. Je commence à me demander si ta conversation vaut l'argent que je t'ai donné.",
"Vraiment? Où puis-je le trouver?",
"Ne te sauve pas ; j'ai deux autres rumeurs toutes fraîches pour toi.",
"Écoutons-les. J'espère qu'elles seront plus intéressantes que l'autre.",
"Non, merci, ",
". Je crois que j'en ai assez entendu.",
"Eh bien, des pirates sont arrivés en ville récemment. Ils boivent et font du grabuge partout en ville...",
"Des pirates qui boivent?! C'est encore moins intéressant que ton histoire de contrebande.",
"Des pirates, tu dis? Où puis-je les trouver?",
"Je suis sûr que la plupart d'entre eux sont encore à la taverne, mais on m'a dit qu'ils avaient l'intention de quitter bientôt la ville.",
"Merci. Il faut que j'y aille : le temps, c'est de l'argent.",
"D'accord. Tu as autre chose pour moi?",
"Dans cette maison, près des quais.",
"Merci pour le renseignement.",
"Peux-tu me raconter quelque chose susceptible de m'intéresser?",
"Il y aurait bien une chose, ",
". Il semblerait que ",
"Milon Blacque",
" soit venu au port tous les jours pour rencontrer son fils...",
"Qu'y a-t-il d'étrange à ça?",
"Tout le monde sait que son fils et son navire ont disparu il y a de nombreuses années.",
"Un vieil homme que le chagrin aurait rendu fou? Je ne vois pas en quoi ça peut m'intéresser.",
"Pourquoi est-il encore là et pas dans un asile?",
"Un asile, ici? Tu plaisantes, capitaine. De toute façon, quelqu'un s'occupe de lui.",
"S'occupe de lui?",
"Oui. Il a une fille adoptive, ",
"Rachel Blacque",
", qui s'occupe de lui\nC'est une vraie poupée, mais aussi froide que la mer du Nord. En tout cas, je sais qu'un jour, je réussirai à la conquérir.",
"Épargne-moi tes rêvasseries sur la fille du coin. Ça ne m'intéresse pas.",
"Je vois que tu es bien informé sur tout ce qui se passe ici. Ça ne t'ennuierait pas de répondre à quelques questions?",
"Bonjour, ",
". Je t'ai entendu parler à ce vieux fou. ",
"Milon Blacque",
".",
"Cette conversation ne te regarde pas, et de toute façon, je n'ai pas le temps de l'expliquer.",
"Pourquoi dis-tu qu'il est fou? Il m'a l'air plutôt sensé.",
"Bon vent à toi, ",
".",
"Oh, c'est toi! Quoi de neuf?",
"On m'a dit que tu harcelais ",
"Rachel Balcque",
" et son père.",
"Bonjour, ",
". Ça fait une éternité que je ne t'ai pas vu.",
"Tu te souviens de ce que tu m'as dit sur les contrebandiers?",
"Tu m'as dit quelque chose sur les contrebandiers récemment. Tu te souviens des détails?",
"Nous parlerons plus tard. J'ai des affaires urgentes à traiter.",
"Bien sûr, ",
". Tout le monde en parle en ville.",
"Je vois. Est-ce que tu pourrais m'en dire plus?",
"Alors, dis-m'en plus. Je devine, en te regardant, que tu es mêlé à cette histoire.",
"Qu'est-ce que tu racontes? Je travaille au port, c'est tout.",
"Tu veux dire que tu ne sais rien sur ce qui se passe en ville? Dans le port où tu travailles tous les jours?",
"C'est pour ça que je suis persuadé que tu en sais plus que tu veux bien l'admettre.",
"Comment le saurais-je?!",
"Je sais comment sont les ouvriers qui travaillent dans les ports. Ils adorent se raconter tous les détails sur ce que livrent les bateaux, le type de marchandises transportées et les gens qu'ils voient!",
"Arrête de jouer. Même si tu n'as pas participé personnellement au déchargement de la cargaison de contrebande, tu sais certainement qui s'en est chargé.",
"D'accord. Je me trompe sûrement. Désolé.",
"Désolé. Je me trompe sûrement sur ton compte. Je ne suis pas moi-même depuis quelque temps.",
"D'accord, Je vois qu'on ne peut pas te faire entendre raison. Au revoir.",
"Je vois où tu veux en venir. Combien va me coûter le réveil de ta mémoire?",
"Eh bien, évidemment, c'est à toi de voir. Tu n'es pas obligé de me parler. Tu peux toujours parler à mon épée, si tu préfères.",
"Je crois que 500 pièces d'or feraient une somme juste, ",
".",
"Marché conclu. Prends l'argent et parle. ",
"Ne sois pas ridicule. Je n'ai pas une telle somme.",
"Alors je ne peux pas t'aider, ",
".",
"Je te conseille vivement de reconsidérer ta décision. Ou tu regretteras de ne pas l'avoir fait.",
"C'est ",
"Raoul Calmes",
"Raoul Calmes",
" qui est derrière tout ça. C'est tout ce que je sais. Maintenant, laisse-moi retourner à mon travail.",
"Merci pour ton aide.",
"Tu me fais rire! Si tu tentes quoi que ce soit ici, les soldats t'arrêteront.",
"Le temps que les soldats arrivent ici, j'aurai dégainé et tiré. Et tu ne seras plus là pour les voir m'arrêter. Enfin, c'est à toi de voir.",
"Tu ne ferais pas ça ; c'est de la folie!",
"Ne me force pas la main.",
"Diable! D'accord, très bien : je vais tout te dire.",
"Voilà un garçon intelligent. J'écoute.",
"Bon, je m'en vais.",
"Qu'est-ce que tu racontes, ",
"? Je suis un homme respectable!",
"Peu importe ton petit jeu. C'est très simple : laisse-les tranquilles ou je te ferai regretter de ne pas avoir suivi mon conseil.",
"Ne prends pas la peine de me mentir. Je lis la vérité sur ton visage.",
"Au diable cette fille! Quand j'en aurai fini avec elle, elle ne pourra plus se plaindre à qui que ce soit!",
"Tu es sourd? Si tu la touches encore... si tu t'avises même de la regarder de travers... Je ferai des jarretières de tes boyaux.",
"Je ne te mens pas, ",
"!",
"Bien sûr que si. J'ai affaire à de meilleurs menteurs que toi tous les jours. Mets-toi bien ça en tête : si tu la touches encore, tu le regretteras pour le restant de ta courte vie. Compris?",
"Calme-toi. Je veux juste savoir combien de temps tu comptes la laisser te mener en bateau.",
"Qu'est-ce que tu veux dire?",
"Je veux dire qu'il est temps que tu remettes cette ",
"Rachel Blacque",
" à sa place. Montre que tu es un homme!",
"Évidemment, ",
". Je, euh... C'est ce que je vais faire. Oui.",
"Exact. il est temps de montrer à cette jeune fille ce qu'elle vaut vraiment.",

};