string DLG_TEXT[73] = {
", cher client! Je suis ",
", propriétaire du chantier naval.",
"Je suis ",
", capitaine du '",
"'.",
", ",
". As-tu besoin des services de mon chantier naval, ",
"?",
"Oui, mon vaisseau a besoin d'être réparé.",
"Non, je veux juste parler.",
"Non, je suis juste de passage.",
"Eh bien, c'est un plaisir de faire ta connaissance. Si tu es capitaine, mon chantier naval est à ton service.",
"Parfait, ",
". Commençons par ces réparations.",
"Merci. Mais parlons un peu d'abord.",
"La prochaine fois peut-être. Je dois partir.",
"Qu'est-ce qui t'intéresse exactement, ",
"?",
"Rien du tout.",
"À propos de ce coffre que tu m'as demandé d'apporter à Redmond...",
"Est-ce que je peux faire quelque chose pour toi, ",
"?",
"Oui, j'ai besoin des services de ton chantier naval.",
"Merci. C'est tout. Au revoir!",
"De quoi as-tu besoin exactement?",
"J'ai besoin de réparer mon navire, mais j'envisagerai peut-être de m'en séparer et d'en acheter un autre.",
"J'ai besoin d'installer des canons neufs sur mon navire.",
"Rien, merci.",
"Tu es fou, ",
"? Tu crois vraiment que les Français vont te laisser réparer ton navire sous leur propre nez? Ils ont posté des gardes près de tous les navires de mon chantier naval!",
"C'est dommage.",
"Que s'est-il passé? Quelque chose ne va pas?",
"On a besoin de se cacher. Les soldats français sont à notre poursuite!",
"Pourquoi?",
"Je ne sais pas. Écoute, on parlera plus tard. Les soldats seront ici d'une minute à l'autre!",
"D'accord, j'accepte de vous cacher. Et pas d'inquiétude : je les éloignerai s'ils se présentent ici.",
"Merci.",
"J'ai montré la porte aux soldats. Maintenant, tu pourrais peut-être me raconter ce qui s'est passé?",
"Il semblerait que les Français soupçonnent ",
"Counterspy",
".",
"Et ils ont décidé de l'attraper d'abord et de poser les questions ensuite?",
"C'est à peu près ça, oui. Merci pour ton aide.",
"Ce n'est rien. Tu pourrais peut-être me rendre un service en retour. J'ai besoin d'envoyer quelque chose à Redmond, mais je risque d'éveiller les soupçons si je l'apporte moi-même.",
"C'est quelque chose que tu ne peux pas expédier de la manière habituelle?",
"Exact. Le contenu de ce coffre est extrêmement important. Je ne veux pas le confier à des inconnus, mais je peux te faire confiance.",
"\nC'est pour cette raison que je te demande de le livrer à Redmond, si tu le veux bien.",
"Après ce que tu as fait pour moi, comment pourrais-je refuser?",
"Merci. Je te prie d'apporter ce coffre à ",
"Charles Windem",
" ",
"Charles Windem",
". C'est le propriétaire de la taverne de Redmond. Dis-lui que je suis l'expéditeur et il comprendra. Bon vent à toi, ",
".",
"Et à toi. Au revoir.",
"Oui? L'as-tu livré?",
"J'ai bien peur que non. Quelqu'un s'est mis en travers de mon chemin. Ou quelque... chose.",
"Quelque chose?!",
"Deux hommes impossibles à tuer avec une épée.",
"Bon dieu! Alors c'est vrai...",
"Qu'est-ce qui est vrai? Tu as peut-être envie de m'expliquer?",
"Oh, non... non, ce n'est rien. C'est juste dommage que tu aies été attaqué...",
"Lâche le morceau ou ton sang va couler. À toi de choisir.",
"Attends! Je vais te dire ce que je sais. Il y a une histoire qui parle d'un terrible pirate. Il pillait et coulait les navires, il ne connaissait pas la pitié... Et un jour, il a fait quelque chose de si terrible que Dieu l'a abandonné à jamais\nCe pirate est devenu quelque chose d'indicible... un mort qui marche! On dit que son équipage et lui continuent de pourchasser et de piller les navires, mais aujourd'hui, plus personne ne peut espérer leur résister puisqu'il est impossible de les tuer! On dit qu'il cherche quelque chose... des pièces anciennes ou un trésor perdu ici, dans l'archipel.",
"C'est n'importe quoi! Une histoire pour effrayer les enfants.",
"Vraiment? Tu as vu ces pirates des ténèbres de tes propres yeux! J'ai envoyé ce coffre à mon vieil ennemi, ",
"Charles Windem",
", pensant qu'il contenait le trésor qu'ils recherchent. J'espérais qu'ils le trouveraient et le tueraient. Tu dois me croire : jamais je n'ai pensé qu'ils t'attraperaient le premier!",
"Où as-tu trouvé ce coffre?",
"Un homme me l'a vendu. Il m'a demandé très peu en échange et m'a promis qu'il me suffirait de l'envoyer à mon vieux rival pour me débarrasser de lui.",
"Où puis-je trouver cet homme?",
"Il habite sur Falaise de Fleur, près du port! C'est à lui que tu dois parler : il en sait beaucoup plus long que moi à propos de ce coffre!",
"Si je n'étais pas un homme d'honneur, je te ferais payer pour m'avoir mis dans un tel danger!",

};