string DLG_TEXT[172] = {
"Je te souhaite la bienvenue, ",
". Mon nom est ",
". Comment t'appelles-tu?",
"Bonjour, ",
"! Je suis ",
". Puis-je connaître ton nom?",
"Oui, ",
". Que veux-tu? Au fait, je m'appelle ",
". Et toi?",
"Je suis ",
", capitaine et propriétaire du navire appelé '",
"'.",
"Mon nom est ",
".",
"Tu peux m'appeler capitaine ",
".",
"Bonjour. Un officier a quitté mon bord. Son nom est ",
"Nigel Blythe",
"Nigel Blythe",
". Ta ville n'est pas très grande. Tu as peut-être entendu quelque chose à son sujet?",
", le capitaine du '",
"'.",
"Oh, c'est le capitaine ",
" en personne! Que cherches-tu, cette fois?",
"Hello, ",
". Cherches-tu quelque chose?",
"Quelles histoires à dormir debout as-tu entendues à la taverne ces derniers temps?",
"Qu'y a-t-il de neuf dans ce coin du monde?",
"Que se passe-t-il par ici?",
"Pourrais-tu, s'il te plaît, m'indiquer commet aller quelque part?",
"Je dois aller quelque part et je ne trouve pas mon chemin...",
"Pourrais-tu m'indiquer mon chemin?",
"J'aimerais savoir ce que l'on dit d'une personne.",
"Peux-tu me dire ce que l'on raconte sur une certaine personne?",
"J'aimerais avoir quelques informations sur les habitants.",
"Parle-moi de ta colonie.",
"Que sais-tu d'Oxbay?",
"J'aimerais obtenir quelques informations sur Oxbay.",
"Bonjour. Un officier a quitté mon bord. Il s'appelle ",
"Nigel Blythe",
"Nigel Blythe",
". Ta ville n'est pas très grande. Tu as peut-être entendu quelque chose à son sujet?",
"Eh bien, je n'ai besoin de rien pour l'instant. Adieu!",
"Oui, je crois avoir entendu dire que ton ami était à notre taverne",
"Merci.",
"J'ai plaisir à te rencontrer, capitaine ",
".",
"J'ai plaisir à te rencontrer, ",
".",
"Te rencontrer me ravit, capitaine ",
". Je suppose qu'il n'y a pas que mon nom qui t'intéresse...",
"J'ai plaisir à te rencontrer, capitaine ",
".",
"J'ai plaisir à te rencontrer, ",
".",
"Te rencontrer me ravit, capitaine ",
". Je suppose que ta curiosité ne se limite pas à mon nom...",
"Quel genre d'histoires de loups de mer as-tu entendu à la taverne, ces derniers temps?",
"Qu'y a-t-il de nouveau dans cette partie du monde?",
"Que se passe-t-il par ici?",
"Peux-tu m'indiquer comment me rendre à un certain endroit?",
"Je dois aller quelque part et je ne trouve pas mon chemin...",
"Pourrais-tu m'indiquer mon chemin?",
"Sais-tu ce que les gens disent de cette personne?",
"Pourrais-tu me dire quelque chose sur quelqu'un?",
"J'aimerais obtenir quelques informations sur les habitants.",
"Parle-moi de ta colonie.",
"Que sais-tu d'Oxbay?",
"J'aimerais avoir quelques informations sur Oxbay.",
"Je profite simplement de la ville. À une autre fois.",
"Je vois... Il y a encore une chose...",
"Merci du renseignement. Adieu.",
"Il est toujours agréable d'être en plaisante compagnie, ",
". Dis-moi.",
"Oui, ",
"?",
"Tu as envie de bavarder, n'est-ce pas, capitaine? Eh bien, moi aussi...",
"Il est toujours agréable d'être en plaisante compagnie, ",
". Je t'écoute.",
"Oui, ",
"?",
"Tu as envie de bavarder, n'est-ce pas, capitaine? Eh bien, moi aussi...",
"Quel genre d'histoires de loups de mer as-tu entendu à la taverne, ces derniers temps?",
"Qu'y a-t-il de nouveau dans cette partie du monde?",
"Que se passe-t-il par ici?",
"Peux-tu m'indiquer comment me rendre à un certain endroit?",
"Je dois aller quelque part et je ne trouve pas mon chemin...",
"Pourrais-tu m'indiquer mon chemin?",
"Sais-tu ce que les gens disent de cette personne?",
"J'aimerais savoir ce que les gens disent de quelqu'un.",
"J'aimerais obtenir quelques informations sur les habitants.",
"Parle-moi de ta colonie.",
"Que sais-tu d'Oxbay?",
"J'aimerais avoir quelques informations sur Oxbay.",
"Laisse tomber... J'ai changé d'avis. Au revoir.",
"Qui a attiré ton attention, ",
"?",
"Qui t'intéresse, capitaine?",
"Il y a beaucoup de monde à Oxbay. Sur qui veux-tu des informations?",
"Je veux en savoir plus sur le gouverneur de la colonie.",
"Je m'intéresse au tavernier ",
"Everard Gordon",
"Everard Gordon",
".",
"Parle-moi du propriétaire du chantier naval, ",
"Oweyn McDorey",
"Oweyn McDorey",
".",
"Je veux en apprendre davantage sur le marchand nommé ",
"Alan Milds",
"Alan Milds",
".",
"J'ai changé d'avis. Oublie tout ça.",
"Oxbay n'a pas de gouverneur : l'île dépend du gouverneur de Redmond.",
"Je vois. J'ai une question.",
"Merci. Au revoir.",
"On dit qu'on peut compter sur lui. D'un autre côté, j'ai entendu dire qu'il n'aime pas prendre de risques inutiles et tâche toujours d'être prudent en affaires. Je ne l'imagine pas tremper dans des affaires louches.",
"Je vois. J'ai une question.",
"Merci. Au revoir.",
"C'est quelqu'un de bien. Toujours prêt à aider. Je dois dire que c'est un sacré architecte naval pour un trou comme celui-ci.",
"Je vois. J'ai une question.",
"Merci. Au revoir.",
"Il n'a guère de succès. Pour commercer, il commerce, mais il semble de plus en plus pauvre. Il est souvent en rupture de stock et il est criblé de dettes.",
"Je vois. J'ai une question.",
"Merci. Au revoir.",
"Où veux-tu te rendre, ",
"?",
" Je connais cette ville sur le bout des doigts, capitaine. Il te suffit de me dire où tu veux aller.",
"Tu peux compter sur moi, ",
".",
"Comment puis-je me rendre à la taverne?",
"Où est le chantier naval?",
"Où vais-je pouvoir vendre les excellentes marchandises que j'ai apportées?",
"Notre taverne se trouve sur la place de la ville. C'est un bâtiment en bois à un étage doté de fondations en pierre.\nJ'espère que tu sais lire notre langue. Il y a une enseigne, là-bas.",
"Je vois. Merci et au revoir.",
"Et où est le chantier naval?",
"Où vais-je pouvoir vendre les excellentes marchandises que j'ai apportées?",
"Si tu viens du port, entre dans la ville, tourne à gauche et tu verras un petit bâtiment en pierre. C'est le bureau du patron du chantier naval.",
"Je vois. Et pour aller à la taverne?",
"Où puis-je vendre les marchandises que j'ai apportées?",
"Merci de ton aide. Je sais tout ce que je voulais savoir.",
"Oh, c'est facile, ",
"! Si tu tournes le dos à la mer, le magasin se trouve sur la droite.",
"Où est le chantier naval, dans cette ville?",
"Comment aller à la taverne?",
"Je vois. Je n'ai besoin de rien d'autre.",
"Pour être honnête, je ne sais pas grand-chose. Mais je te dirai ce que je sais.",
"Que veux-tu savoir au sujet de notre colonie?",
"Volontiers. Que veux-tu savoir, au juste?",
"J'aimerais connaître l'histoire de cette colonie...",
"Qu'y a-t-il sur cette île en dehors de la ville?",
"Tu sais quelque chose à propos du fort qui protège la ville?",
"Parlons d'autre chose.",
"Notre colonie a été fondée il y a une quarantaine d'années. L'île est assez petite, mais son sol est très fertile et elle abrite plusieurs baies fort commodes.\nOn aménage actuellement de nouvelles parties de l'île et le commerce s'est accru. Notre ville a constitué la première installation coloniale, puis Greenford fut fondée.",
"Continue...",
"J'en sais assez. Parlons d'autre chose ",
"Ensuite, les boucaniers ont pris la sale habitude de venir nous rendre visite. C'est la raison pour laquelle on a bâti le fort.",
"Je vois. Restons-en là pour ce point et changeons de sujet.",
"La majorité de l'île est déjà aménagée. Il est difficile de se développer davantage en raison de la difficulté que représente le défrichage de la jungle et du manque de main d'œuvre...",
"Très bien. Dis-moi autre chose.",
"Il n'y a rien de spécial à dire sur cette île. Elles se ressemblent toutes, dans cet archipel.",
"Je vois. Continue...",
"Nous avons des rochers, de la jungle et des plages désertes... C'est à peu près tout, je crois. Oh, il y a aussi Greenford, bien entendu.",
"Je vois. Continue...",
"Je vois. Restons-en là pour ce point et changeons de sujet.",
"Je ne sais rien.",
"C'est dommage. Dis-m'en plus sur la colonie.",
"Le fort n'a rien de particulier. Il a des murs épais, des canons à longue portée et sa garnison compte un millier d'hommes.",
"Je vois. Continue...",
"Pourquoi me demandes-tu ça, capitaine? Ce ne serait pas très malin de ma part de parler du fort avec le premier étranger venu. Comment puis-je être certain de tes bonnes intentions?",
"Eh bien, si le fort représente un sujet aussi sensible à tes yeux, oublions-le. Parle-moi de la colonie.",
"Je vois. J'en sais assez sur ce point. Changeons de sujet.",

};