string DLG_TEXT[28] = {       
"Tu ne vois pas que je suis de garde? Laisse-moi en paix!",
"Très bien, très bien.",
"Tu veux signaler une infraction?",
"Non, bien sûr que non. Je suis capitaine, après tout... Mais je vois que tu ne m'écoutes pas.",
"Rappelle-toi : les bagarres de rue ne sont pas tolérées. Ceci dit, si on t'attaque, tu gardes le droit de te défendre.",
"Très bien, je me souviendrai de cette indication.",
"Quel temps pénible... et je dois resté planté là. Crois-moi si tu veux, mais mon seul passe-temps consiste à chasser les mouches de mon visage...",
"C'est bien regrettable, mais je n'y peux rien. Cela fait partie du devoir...",
"Si tu veux tailler une bavette, va voir quelqu'un d'autre. Je suis en service, et cela ne consiste pas à te parler.",
"Je me demandais simplement si tu étais vivant. Tu es aussi immobile qu'une statue.",
"Tu crois qu'il est facile de protéger cette ville? Tu te trompes! C'est une tâche importante. Et dangereuse. Je me souviens, une fois...",
"Tu me raconteras ça une autre fois. Je dois y aller.",
"File, laisse-moi tranquille.",
"Comme tu veux, soldat.",
"Eh! Tu veux bien me rapporter un godet de rhum de la taverne?",
"C'est ça, pour qu'on me pende parce que j'aurai aidé un garde à se saouler? Non, attends la relève et tu pourras boire à ta soif.",
"Pourquoi est-ce que c'est un lourdaud de marin dans ton genre qui vient me parler? Mais où sont les jolies filles, dans cette ville?",
"Et tu appelles ça faire ton devoir? Écoute, tu ne voudrais pas laisser passer l'occasion d'arrêter un dangereux criminel comme moi, pas vrai? Ha-ha!",
"Tu m'as l'air costaud. Ça ne te dirait pas de t'engager dans nos forces? La caserne est spacieuse, la pitance correcte et le rhum gratuit.",
"C'est tentant, mais je dois refuser. La discipline militaire n'est pas mon fort.",
"Quelle chaleur... Je donnerais n'importe quoi pour rentrer en Angleterre.",
"Oui, le climat n'a pas l'air de te convenir.",
"Qu'est-ce que tu veux?",
"Toi... hic... sale chien! Tu as fait mal à mon... hic... mon ami!",
"Quel ami? Tu es tout seul, ici, ",
".",
"Quoi? Il était là... il y a une minute. Je m'en vais le chercher. Quant à toi... hic... tu restes là gentiment à attendre ta raclée...",
"Comment oses-tu me contredire! Je vais t'étrangler!",


};
