string DLG_TEXT[118] = {
"Bonjour, mon fils? Quelle est la raison qui t'amène au sein de l'Église? Viens-tu te confesser? Ou peut-être faire un don?",
"Je dois te parler, mon père.",
"J'aimerais faire un don, mon père.",
"Je jette juste un coup d'œil. D'ailleurs, il faut que j'y aille.",
"Je t'écoute, mon fils.",
"Je dois consulter la bibliothèque de l'église, mon père.",
"Je détiens les documents qui t'ont été volés.",
"Les papiers que tu m'as demandé de récupérer reposent au fond de l'eau. Ainsi que celui qui les a dérobés.",
"On m'a demandé de te remettre cette lettre.",
"On m'a demandé de te remettre cette lettre.",
"Je n'ai hélas pas été en mesure de remplir ta mission. Lorsque j'ai rejoint l'île, le 'Montanez' était déjà aux prises avec deux bateaux pirates qui l'ont coulé.",
"J'ai mené à bien ta mission. Le navire que tu m'as demandé d'escorter est amarré au port.",
"Je n'ai rien à faire avec toi pour l'instant.",
"Tu t'es bien débrouillé, mon fils! La traversée fut-elle bonne?",
"Pas vraiment. Lorsque j'ai rejoint ce bateau, il était attaqué par deux bateaux pirates qui tenaient à l'envoyer par le fond.",
"Je vois. Autre chose?",
"Oui, il y a une autre chose. Le capitaine du navire a débarqué un passager à Oxbay...",
"Oui, je suis au courant. En réalité, c'était l'objectif de toute cette aventure. L'arrivée de cet homme dans l'archipel revêt une grande importance aux yeux de l'Église. Je pense que tu feras un jour sa rencontre.",
"Je vois.",
"Dans ce cas, permets-moi de te remettre ta récompense. Et de te proposer une nouvelle mission.",
"Merci, mon père. Et en quoi consiste cette mission?",
"Seigneur! Voilà une terrible nouvelle. Quelqu'un connait visiblement nos plans et s'emploie activement à les réduire à néant.",
"Je regrette, mon père.",
"Ne t'en fais pas, mon fils. Tu as fait tout ce qui était en ton pouvoir et je crois qu'il serait injuste de ne pas récompenser ta tentative de venir en aide à la Sainte Église.",
"Merci.",
"Maintenant, accepterais-tu de te charger d'une autre mission pour moi?",
"De quoi s'agirait-il, cette fois?",
"Rien d'extraordinaire. Porte simplement cette lettre au Father Bernard, à Redmond. Et veille à ce que personne d'autre que lui ne la lise!",
"Entendu. Je vais y aller, maintenant, si tu m'y autorises.",
"Oui, et que Dieu soit avec toi, mon fils.",
"Amen, mon père.",
"Laisse-moi voir ça. Oui... oui, c'est bien ce que je pensais! Tu t'es bien débrouillé, mais permets-moi de te poser quelques questions.",
"Bien entendu. Que veux-tu savoir?",
"Laisse-moi voir ça. Oui... oui, c'est bien ce que je pensais. Mais qui a ouvert cette lettre?",
"Personne ne l'a ouverte, mon père! Tu crois que j'aurais fait une chose pareille?",
"Tu l'as remarqué, hein? Je savais que ça finirait mal.",
"Alors, qui l'a ouverte?",
"Ils m'attendaient dans la baie où j'ai débarqué. Je n'ai eu d'autre choix que de les laisser lire la lettre. Des hommes en robe noire... On aurait dit qu'ils savaient que j'allais débarquer à cet endroit!",
"Je vois. Je peux facilement te le pardonner, mon fils, en particulier parce que nous nous y attendions et l'avions rédigée en code\nTu nous as en réalité aidés à tromper l'ennemi. Je suis heureux de te remettre la somme promise.",
"Merci.",
"Il est clair que tu n'éprouves aucun remords pour ce que tu as fait. Libre à toi, bien entendu. Mais je dois te demander de quitter cette église!",
"Comme tu veux.",
"Non, attends! Je regrette, mon père. J'ai eu tort.",
"As-tu rencontré des difficultés en route?",
"Eh bien, ",
"Father Bernard",
", m'a demandé de débarquer dans une baie retirée pour éviter les ennuis, mais on m'y attendait...",
"Parle sans crainte dans la maison de Dieu, mon fils. Tu laisses entendre que...",
"Je ne laisse rien entendre. Je ne veux accuser personne. Je me suis simplement dit que je devais t'en informer. Dans cette baie, trois hommes en robe noire m'attendaient, et cette lettre les intéressait au plus haut point. À tel point, en fait, que j'ai été contraint de les tuer.",
"Je constate que ",
"Father Bernard",
" a fait preuve de sagesse en te confiant cette mission.",
"Il y a autre chose, mon père. En fouillant les cadavres de mes agresseurs, j'ai trouvé un étrange médaillon au cou de chacun d'eux.",
"Puis-je voir ces médaillons? Oui... intéressant... Mais revenons à nos affaires. Voici ta récompense.",
"Merci.",
"J'ai une autre mission à te confier, si cela t'intéresse\nEt la récompense sera nettement plus élevée, cette fois.",
"Qu'attends-tu de moi?",
"Un navire arrivera bientôt d'Europe avec à son bord des gens d'une importance cruciale pour notre cause. J'ai toutes les raisons de penser que ce navire sera attaqué ; ta tâche consistera à le retrouver près d'Oxbay et à l'escorter jusqu'à notre port.",
"Donne-moi le nom de ce navire et je ferai tout mon possible.",
"Il porte le nom de 'Montanez' et a pour capitaine ",
"Mergildo Hurtado",
", un officier espagnol.",
"Très bien. Je devrais maintenant avoir toutes les informations dont j'ai besoin. Je vais prendre la mer au plus tôt : plus vite je serai parti, plus j'aurai de chances de réussir.",
"J'en suis désolé. Ces documents étaient très importants pour l'église.",
"Tu devrais t'estimer heureux que tes ennemis ne puissent pas les utiliser contre toi, mon père.",
"C'est vrai. Mais leur perte reste regrettable.",
"Je suis désolé. Cela signifie-t-il que je ne peux pas consulter la bibliothèque?",
"Peut-être devrait-il en être ainsi. Mais tu m'as tout l'air de quelqu'un qui parviendrait quand même à ses fins.",
"Alors, je peux y aller?",
"Oui, tu peux. Tu as toute la journée pour la consulter. Mais c'est étrange... Tu es la deuxième personne à réclamer d'y avoir accès avec autant d'insistance.",
"Merci, mon père.",
"Parfait! S'il te plaît, remets-les moi sur-le-champ.",
"Les voici.",
"Pas si vite, padre!",
"Que veux-tu dire, mon fils?",
"J'ai découvert la nature de ces documents. Ce qui a fait augmenter leur prix.",
"Serais-tu en train de me faire chanter?",
"Tu croyais que ta soutane te mettrait à l'abri d'une honnête petite extorsion? Si tu ne veux pas que ces documents tombent en de mauvaises mains, il va falloir me laisser accéder à la bibliothèque et allonger 5 000 pièces d'or séance tenante.",
"Tu ne crains donc pas Dieu? Où vais-je trouver une telle somme?",
"Eh bien, examinons ensemble ces notes, si tu veux. Oui, c'est là : '... 17 000 pièces d'or ont été remises pour armer le navire et recruter des marins...' Ce que je demande n'est qu'une petite partie de cette somme.",
"Silence! On pourrait nous entendre. Voilà ton argent. Maintenant, donne-moi ces papiers!",
"Ils sont tout à toi. Et maintenant, pour la bibliothèque?",
"Tu as fait du bon travail au service de Dieu, mon fils. Tu vas être récompensé.",
"Et pour la bibliothèque? Je peux y entrer?",
"Oh, oui. J'avais oublié. Bien sûr, tu peux y accéder. Mais c'est curieux tu es la deuxième personne à demander de la consulter avec autant d'insistance.",
"Merci, mon père.",
"Je crains que ce ne soit pas possible. La bibliothèque est fermée aux profanes.",
"Peut-être peux-tu faire une exception pour moi? Écoute : j'ai un navire et un équipage. Peut-être que si tu m'aides à résoudre mon problème, je pourrai t'aider à résoudre les tiens.",
"Tu es capitaine? Alors, peut-être peux-tu effectivement m'aider, ainsi que l'Église d'Espagne.",
"Parfait! Que veux-tu que je fasse?",
"Des documents très importants ont été volés à l'église il y a quelques jours. Je soupçonne ",
"Ferro Cerezo",
"Ferro Cerezo",
" de les avoir dérobés. Malheureusement, je n'ai aucune preuve tangible contre lui.",
"Alors, tu veux que je vérifie si c'est bien lui qui les a, et que je les rapporte si c'est bien le cas?",
"Oui. Ce sont des documents très importants. Fais tout ton possible pour les retrouver.",
"Où puis-je trouver cet homme?",
"J'ai réussi à découvrir qu'il possédait son propre navire. C'est un sloop, si je ne me trompe. Et on le voit souvent à Conceicao : il donne probablement dans la contrebande.",
"Je le trouverai. Me laisseras-tu consulter la bibliothèque si je te rapporte ces papiers?",
"Certainement. Tu pourras y passer une journée entière, même si je ne vois pas ce qu'un marin peut bien y chercher.",
"Bénis-moi, mon père, et je me mets en route.",
"Bien sûr, mon fils. Combien envisages-tu de donner?",
"Je regrette, mon père, mais je ne peux faire aucun don pour l'instant.",
"Je crains de ne pouvoir donner plus que 100 pièces d'or en ce moment.",
"Je pense que le Seigneur regardera avec bienveillance 1 000 pièces d'or.",
"Je me débrouille bien, ces temps-ci. Je vais donner 5 000 pièces d'or.",
"Comme tu veux, mon fils. Il n'est jamais trop tard pour changer. Et rappelle-toi qu'il en sera tenu compte au jour de ta mort.",
"Ma mort n'est pas pour demain, si Dieu en veut ainsi! Parlons d'autre chose.",
"Désolé, mon père. Je dois partir.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Il faut que je te parle, mon père.",
"Je regrette, mon père, mais je dois partir.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Il faut que je te parle, mon père.",
"Je regrette, mon père, mais je dois partir.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Il faut que je te parle, mon père.",
"Je regrette, mon père, mais je dois partir.",

};