string DLG_TEXT[63] = {
"Bienvenue à l'église, mon fils.",
"Tu n'es pas mon père. Ne t'adresse plus jamais à moi de la sorte.",
"Bonjour, mon père.",
"Insolent mécréant! Hors d'ici! Ta présence est une insulte à la maison de Dieu!",
"De toute manière, je n'avais pas l'intention de m'éterniser.",
"Que Dieu te bénisse. Es-tu venu me voir pour une raison spéciale?",
"J'aimerais faire un don.",
"Je suis ici pour me confesser.",
"Je regrette, je dois filer.",
"Pas vraiment. Comment se porte la paroisse?",
"Je crois que la femme dont nous avons parlé reviendra bientôt à l'église.",
"La femme dont nous avons parlé... Je ne suis pas parvenu à la faire changer d'avis. Je regrette, mon père.",
"Oh! Excellent, mon fils. Je suis heureux de connaître un jeune marin qui ne sombre pas dans le péché comme ses congénères.",
"Je regrette, mon père, mais il se trouve que je n'ai pas d'argent.",
"Voici 100 pièces d'or pour tes services.",
"Je pense que le Seigneur regardera favorablement 1 000 pièces d'or.",
"Je me débrouille bien, ces temps-ci. Je vais donner 5 000 pièces d'or.",
"Comme tu l'entends, mon fils. Il n'est jamais trop tard pour changer. Et rappelle-toi qu'il en sera tenu compte au jour de ta mort.",
"Ma mort n'est pas pour demain, si Dieu en veut ainsi. Parlons d'autre chose.",
"Je regrette, mon père, je dois partir.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Il faut que je te parle, mon père.",
"Je regrette, mon père, mais je dois partir.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Il faut que je te parle, mon père.",
"Je regrette, mon père, mais je dois partir.",
"Je te remercie de ce don au nom de la Sainte Église, mon fils.",
"Il faut que je te parle, mon père.",
"Je regrette, mon père, mais je dois partir.",
"Bien entendu, mon fils. Je t'écoute.",
"J'ai changé d'avis. Peut-être une autre fois.",
"J'ai péché, mon père...",
"Il est dans la nature de l'homme de pécher, mon fils. Mais demander le pardon est de nature divine.",
"Oui, Mais je... J'ai pillé des navires et envoyé certains autres par le fond. J'ai tiré mon épée sous le coup de la colère et pris des vies...",
"Mais il n'y avait aucun Français parmi eux, n'est-ce pas?",
"Bien sûr que non, mon père.",
"Si, mon père. Des Français aussi.",
"Alors que Dieu pardonne tes péchés, mon fils.",
"Merci, mon père. Je vais partir, maintenant.",
"Quoi? Dieu ne pardonnera jamais un tel péché! Sors de cette église sur-le-champ!",
"Au revoir, mon père.",
"Tout va bien, mon fils.",
"Merci, mon père. Je vais te quitter, maintenant.",
"Que dis-tu? Tout le monde vient à l'église?",
"Tout va bien, mon fils.",
"Dans ce cas, mon père, je vais te laisser.",
"Hélas, il y a une brebis égarée : une femme qui mène une vie solitaire et qu'il est impossible de persuader de venir à l'église.",
"C'est une honte, mon père. Je suis certain que tu la feras changer d'avis tôt ou tard.",
"Peut-être est-il possible de parler à cette femme et de la convaincre de regagner le troupeau?",
"J'ai essayé maintes fois, mon fils, mais en vain.",
"Eh bien, si tu ne parviens pas à la convaincre, j'imagine que personne ne le pourra. Adieu.",
"Je pourrais essayer, si tu le souhaites. Parfois, les gens se confient à des étrangers alors qu'ils ne le feraient pas avec leur prêtre.",
"Je te serais infiniment reconnaissant d'essayer. Cette femme vit près des portes qui mènent au centre de la ville. Elle s'appelle ",
"Elzire Ayarai",
"Elzire Ayarai",
".",
"Je ferai de mon mieux, mon père.",
"Non, mon fils. Je doute que tu puisses y changer quoi que ce soit.",
"Très bien. Dans ce cas, au revoir, mon père.",
"Dommange, mon fils. Pour être franc, j'espérais vraiment que tu puisses nous aider.",
"Adieu.",
"Oh, elle est déjà venue. Elle s'est même confessée et a demandé à être pardonnée. Et elle a dit grand bien de toi.",
"Je suis heureux que tout ait si bien marché, mon père. Adieu.",

};