string DLG_TEXT[118] = {
"Pardon, je ne t'avais pas vu.",
"Ne t'en fais pas, cela arrive. Comment vont les affaires?",
"Quoi? Les affaires? Oh... bien...",
"Ça va?",
"Je vois que tu es très occupé. Je te laisse travailler.",
"Pardon? Tu as dit quelque chose?",
"Qu'est-ce qui ne va pas?",
"Rien d'important. Au revoir.",
"Oui... oui, ",
", je vais bien.",
"C'est toi que certaines personnes du coin qualifient de fou, pas vrai?",
"Dans ce cas, je m'en vais.",
"Attends! Je ne connais même pas ton nom...",
"Je m'appelle ",
".",
"Heureux de faire ta connaissance. Mon nom est ",
".",
"Qu'est-ce qui te préoccupe, ",
"?",
"Heureux de faire ta connaissance, mais je dois y aller. Peut-être à plus tard.",
"Ce n'est rien, ",
". Je ne suis qu'un homme sans importance et mes soucis sont à l'avenant. Ils ne méritent pas que tu t'y intéresses.",
"Si tu me laissais décider moi-même de ce à quoi je dois m'intéresser ou non?",
"Tu sais, ça fait longtemps que je n'ai pas entendu quelque chose qui soit frappé d'autant de bon sens. Tu as raison, j'ai bien assez de mes propres problèmes ; les tiens ne me regardent pas.",
"Eh bien, je ne sais pas....",
"Qu'y a-t-il de mal à m'en parler? Et, qui sait, peut-être que je pourrai t'aider...",
"C'est vrai que la décision t'en revient. Je te laisse tranquille.",
"D'accord, je vais te le dire. Il y a quelque temps, un homme \nse faisant appeler ",
"Teodoro Fernandez",
"Teodoro Fernandez",
" est venu me trouver. Il m'a demandé d'acheter à sa place des statuettes indiennes \nqui avaient fait leur apparition depuis peu dans l'archipel. Mais je n'avais pas assez d'argent. C'est que l'or massif coûte cher, de nos jours...",
"Ces statuettes étaient en or?",
"Oui. Je crois savoir qu'elles appartenaient à un collectionneur qui les avait trouvées dans la jungle et qui comptait les ramener en Europe.",
"Mais il n'y est pas arrivé?",
"Il me semble que nous nous écartons du sujet, là. Si tu me racontais la fin de ton histoire?.",
"Non. Son bateau est tombé entre les mains des pirates.",
"Je vois. Et quel est le problème, au juste?",
"Oh, oui. Eh bien, ",
"Teodoro Fernandez",
" m'a proposé de me verser d'avance l'argent nécessaire pour acheté ces statuettes, et j'ai accepté.",
"Il a payé d'avance? Et ça ne t'a pas paru louche?",
"Si, mais cela me permettait de gagner 10 000 pièces d'or! Comment aurais-je pu refuser?",
"Je ne te suis pas, là. ",
"Teodoro Fernandez",
" t'a piégé, c'est ça?",
"À t'entendre, j'ai l'impression que c'est la cupidité qui t'a perdu, ",
". Débrouille-toi tout seul.",
"Eh bien, pour être honnête, je ne sais pas.",
"Comment ça, tu ne sais pas? Tu as un problème, oui ou non?",
"Le problème, c'est que les statuettes ont été volées la nuit dernière et que  ",
"Teodoro Fernandez",
" sera là dans deux jours. Il faudra que je lui rende son argent.",
"Eh bien, rends-le lui. Où est le problème?",
"Tu ne comprends pas? C'est lui qui les a volées, ces statuettes! Comme ça, elles ne lui auront rien coûté!",
"Pardon, ",
", mais c'est toi qui m'a demandé de...",
"Détends-toi. Je vais retrouvé ce type qui t'a volé.",
"Je ne t'ai pas demandé de me raconter ta vie!",
"Oh, merci de rendre espoir à un homme désespéré!",
"C'est bon à savoir. Et maintenant, parlons de la récompense que tu es disposé à m'offrir.",
"Tu as sans doute raison et je suis assez enclin à le croire, mais rien ne le prouve.",
"Si les preuves existent, nous les trouverons. La seule chose restant à déterminer, c'est combien cela va me rapporter.",
"Il ne me reste pas beaucoup d'argent. 3 000 pièces d'or, ça irait?",
"Tu viens juste de me dire que tu as touché 10 000 pièces d'or d'avance et tu as le culot de ne m'en proposer que 3 000? Je veux au moins la moitié pour mon aide.",
"Je suis sûr que tu pourrais m'offrir davantage, mais c'est d'accord.",
"Si tu ne m'aides pas, c'est vrai que je ne garderai rien, alors, c'est honnête, j'imagine...",
"Dans ce cas, marché conclu. Au fait, à quoi ressemble ce ",
"Teodoro Fernandez",
"?",
"Non, je ne peux pas accepter.",
"Pourquoi? Sans moi, tu perdras tout.",
"Je ne suis pas certain d'avoir besoin de toi. J'ai parlé à un garde, tout à l'heure, et il a accepté de m'aider.",
"Dans ce cas, pas de marché entre nous. Bonne chance à toi.",
"Très bien, va pour 3 000.",
"J'attends de tes nouvelles, ",
".",
"Attends, à quoi ressemble cet homme?",
"C'est un Espagnol de grande taille, balafré et aux longs cheveux noirs.",
"Très bien. À plus tard.",
"Bonjour, ",
".",
"Bonjour.",
"Bonjour, ",
", comment ça se passe?",
"Je n'ai pas encore obtenu de résultats, mais j'y travaille.",
"Je viens juste d'apercevoir ",
"Teodoro Fernandez",
"! Il est entré dans la maison située à gauche de l'église!",
"Parfait. Reste ici, je vais lui rendre une petite visite...",
"Il fait beau, aujourd'hui, n'est-ce pas?",
"Comme toujours. Montre-moi ce que tu as à vendre.",
"Peut-être. Je suis trop occupé pour y faire attention. Si tu veux bien m'excuser, il faut que je file.",
"Merci, mais il faut que j'y aille.",
"Peux-tu me parler de la ville?",
"Oh, merci, ",
"! Il y a quelques minutes à peine, un garde est venu me dire que, grâce à toi, Teodoro avait été capturé et les statuettes retrouvées.",
"Cela a été un plaisir de pouvoir me rendre utile.",
"Alors, comment ça se passe? Teodoro sera bientôt là!",
"Je regrette, mais je n'ai rien pu faire pour toi.",
"J'ai retrouvé les statuettes... et le voleur. ",
"Dans ce cas, je crois bien qu'il va me falloir fermer boutique. Je comptais vraiment sur toi, capitaine.",
"Au revoir.",
"Alors, est-ce que ",
"Teodoro Fernandez",
" était bien notre voleur, finalement?",
"Non, mais c'est lui qui les avait engagés. Encore que ces derniers ne soient plus là pour en parler, désormais.",
"Tu fais un formidable allié, capitaine! Merci de ton aide. Tiens, prends cet argent à titre de remerciement.",
"Au revoir.",
"Tu n'as qu'à te retourner, la taverne se trouve juste derrière toi, ",
".",
"Merci. J'aurais encore quelques questions à te poser.",
"Merci, c'est tout ce que je voulais savoir.",
"Pour trouver la boutique, il te suffit de franchir les portes situées à droite de mon étal.",
"Merci. J'aurais encore quelques questions à te poser.",
"Merci, c'est tout ce que je voulais savoir.",
"Dans ce cas, il te faut aller au bureau du chantier naval, qui se trouve à côté des portes, juste à gauche de mon étal. Tu vois ce bâtiment à un étage? Il te suffit de monter l'escalier.",
"Merci. J'aurais encore quelques questions à te poser.",
"Merci, c'est tout ce que je voulais savoir.",

};