string DLG_TEXT[31] = {
"Ravi de te rencontrer, ",
". Je m'appelle ",
" et je suis à ton service.",
"Merci. Je suis le capitaine ",
".",
"Ravi de revoir, ",
".",
"Toi! J'espérais ne jamais te revoir sur le pas de ma porte.",
"Bonjour, ",
".",
"Désolé, ",
"Tu veux voir mes marchandises?",
"Bien sûr. Montre-moi ce que tu as en stock.",
"Pas tout de suite. Parlons.",
"Non, merci. Peut-être la prochaine fois.",
"Tu veux acheter ou vendre?",
"J'ai des marchandises à vendre.",
"Je voudrais acheter du matériel.",
"Ni l'un, ni l'autre, merci. Au revoir.",
"Je suis tout ouïe. Qu'y a-t-il?",
"Je cherche du travail pour mon navire et son équipage.",
"Je m'intéresse à l'un de tes employés, Clauss. Je voudrais rembourser sa dette.",
"Tu veux payer pour lui? Bien sûr, vas-y. Il a déjà remboursé une partie de sa dette en travaillant...",
"Ça suffit. Dis-moi juste combien je te dois.",
"Attends, je vérifie dans mes papiers... Aha... oui... Oui, voilà. Clauss me doit 2 632 pièces d'or.",
"Mmh, quel dépensier! Voilà ton argent. Maintenant, dis-moi, où est Clauss?",
"Je crois que je vais retarder un peu le paiement.",
"Je l'ai envoyé me chercher un tonnelet de bière à la taverne. Tu le trouveras là-bas.",
"Merci.",
"Je n'ai pas besoin de tes services pour le moment.",
"Dommage. Parlons d'autre chose.",

};