string DLG_TEXT[25] = {
"Ne reste pas là! Entre, allez!",
"...",
"Où vas-tu, moussaillon? Vire de bord et éloigne-toi. Il n'y pas de place pour les gens comme toi ici!",
"Je dois parler à ",
"Alistair Garcilaso",
"Alistair Garcilaso",
".",
"Attends un peu! Tu ne serais pas ",
", celui dont le simple nom fait trembler les marchands?",
"Je suppose que c'est moi. Qu'est-ce qu'il y a?",
"Attends! Aucun membre de ta confrérie n'aurait besoin d'un nouvel équipage, par hasard?",
"Pour le moment, il n'y a que le vieux ",
"Anacleto Rui Sa Pinto",
" qui recherche du monde. Mais il ne trouve personne. Le moins qu'on puisse dire, c'est qu'il a la guigne. Tu peux essayer, mais je t'aurai prévenu.",
"Et où puis-je trouver cet ",
"Anacleto Rui Sa Pinto",
"?",
"À la taverne, tiens. Où veux-tu qu'il soit?",
"Merci. Je vais aller le voir.",
"Désolé! Je me tais. Fais comme chez toi.",
"J'en ai bien l'intention.",
"Je doute qu'il ait envie de te parler. Va-t'en!",
"Et si j'allais lui demander moi-même s'il accepte de me parler?",
"Et si je t'en empêchais?",
"C'est ce qu'on va voir!",

};