string DLG_TEXT[28] = {
"Ah, capitaine ! Te voilà enfin. J'allais croire que la mer t'avait gardé pour elle toute seule. Viens donc boire un coup, qu'on parle de nos vieilles affaires.",
"Hé, l'ami ! Par tous les tonneaux de rhum des Caraïbes, ça fait plaisir de revoir ta trogne. Assieds-toi, j'ai deux ou trois souvenirs qui grattent encore la gorge.",
"Tiens donc, voilà mon vieux compagnon de traversée ! Approche, capitaine. Les hommes polis serrent les mains, nous autres on vide les verres et on raconte les tempêtes.",
"Ah ! J'aimerais parler de nos aventures mais nous sommes à terre, dis-m'en plus, mon cher Malcolm.",
"Ouvre grand tes oreilles, monbon Malcolm. Fouine dans les rues et les tavernes, et tu entendras des histoires qui font frémir le sang. Mais aussi de quoi se remplir les câles de trésor.",
"J'ai entendu dire qu'il y a des gaillards en ville qui cherchent un bateau pour aller déterrer un trésor. A mon avis, capitaine, il n'y aura qu'à se baisser pour ramasser l'or... enfin, si personne ne nous plante avant.",
"Dans les rues, on croise parfois de jeunes âmes amoureuses, mais plus fauchées qu'un mousse après trois jours de taverne. Les aider, ce n'est pas mauvais pour la conscience... et parfois ça rapporte plus qu'on ne croit.",
"La justice, dans ces îles, elle dort souvent plus profond qu'un ivrogne sous une table. Alors certains habitants finissent par chercher des hommes capables d'engager des tueurs à gages pour régler leurs vilaines affaires.",
"Mmmh ! Tu me titilles Malcolm. Dis-en moi sur cette histoire, il me faut bien gouverner ma barque.",
"Pour le trésor, je te conseille de ne pas battre le fer avec ces gaillards. Ce sont de redoutables bretteurs, et pas du genre à tomber au premier coup de vent. Et puis... j'ai le nez des vieux marins, capitaine : quelque chose de plus gros semble se profiler à l'horizon.",
"Pour les amoureux fauchés, il faudra avoir bonne réputation. Les jeunes coeurs tremblent vite quand un capitaine sent trop la poudre et les mauvaises affaires. Mais entre nous, quelque chose me dit qu'à la fin de cette histoire, il pourrait bien y avoir un coffre au trésor.",
"Pour les contrats de sang, ouvre grand tes oreilles et écoute les gens de la ville. Certains profitent du désordre pour faire porter un meurtre à d'autres. Dans ces îles, capitaine, un couteau ment moins souvent qu'un homme. Sois vigilant.",
"Et où je trouverai ces personnes ? Il vous pas sortir de terre !",
"Il traine dans les rues des villes. Facile à voir avec leur épée.",
"Ce sont généralement de beaux jeunes hommes, ils restent plantés là des heures.",
"En sortie de ville le soir.",
"Merci, mon bon Malcolm. Fidèle au poste, comme toujours.",
"J'ai une affaire pour Silehard. Tu as un conseil ?",
"Commence par reunir les seize objets indiens courants. Un seul exemplaire de chaque, puis retourne a Redmond quand la serie sera complete.",
"Tu as deja tout ce qu'il voulait. Ne traine pas : retourne voir Silehard a Redmond avant que cette affaire refroidisse.",
"A Isla Muelle, file a la Cote eloignee et parle a l'Anglais. Pas a l'Espagnol. Si tu te trompes, tu perdras du temps pour rien.",
"A Conceicao, meme methode : cherche l'Anglais a Havre radieux et garde-toi du Portugais. Silehard ne paie pas pour les erreurs evitables.",
"Pour Douwesen, va a la plage aux palmiers. Les Hollandais sont du decor, mais ton homme reste l'Anglais du reseau.",
"Le morceau suivant n'est plus sur un homme, mais dans la jungle de Douwesen. Cherche un signe ancien, puis suis ce qu'il t'indique.",
"Tu as l'indice. Il ne reste qu'a fouiller l'endroit marque dans la jungle de Douwesen pour recuperer la tete.",
"Si la statue est complete, inutile de trainer dans les buissons : retourne voir Silehard avec la piece entiere.",
"Je n'ai rien de plus pour cette affaire. Garde les yeux ouverts et la langue courte.",
"Je vois. Ca suffit pour l'instant.",

};