string DLG_TEXT[300] = {
"Par les sept enfers, voilà la carcasse la plus coriace des Caraïbes !",
"Et toi, vieux fripon, toujours pas noyé malgré ton haleine de rhum ?",
"Capitaine ! J'croyais que les requins t'avaient enfin digéré !",
"Pas encore, j'leur laisse ton nom pour la prochaine fois.",
"Hé ! Si c'est pas la terreur des comptoirs et le fléau des tavernes !",
"Moi ? Et toi alors, marchand de poisse et roi des dettes ?",
"Par ma barbe, j'te reconnaîtrais même sous un tas de boulets !",
"Et moi, à ton odeur de tabac mouillé, sans hésiter.",
"T'as encore survécu ? C'est une insulte à la logique navale !",
"J'compte sur toi pour équilibrer les comptes un jour.",
"Voilà la canaille qui m'a laissé ramer trois jours après San Juan !",
"Tu t'en es sorti, non ? Preuve que j'avais raison de filer !",
"Dis donc, t'as pas grossi ? On dirait presque un capitaine respectable.",
"Toi par contre, toujours aussi mal taillé pour les chemises.",
"Ah ! Le maître des fuites héroïques !",
"Et toi, prince des coups foireux !",
"Je jurais t'avoir enterré à La Havane...",
"Mauvaise fosse, mon vieux. Je dors mieux en hamac.",
"Voilà le seul bougre à qui je confierais un canon... peut-être.",
"Et moi, le seul gueux que je laisserais saborder ma soirée.",
"Par Bacchus ! T'es toujours plus laid que le dernier naufrage !",
"Et toi, plus bruyant qu'une bordée de mousquets.",
"Regarde-moi ça ! Le héros des tavernes, ressuscité encore une fois !",
"Pas plus que toi, prophète des dettes impayées.",
"Eh ben, voilà l'ami qui m'a déjà vendu trois fois aux Espagnols !",
"Et qui t'a racheté deux fois, faut pas l'oublier.",
"Le diable me tire la barbe si c'est pas mon frère de misère !",
"Et mon complice de tous les naufrages ratés !",
"J'ai vu des fantômes, mais toi, t'es plus têtu qu'eux pour revenir.",
"Et toi, plus ivre qu'eux pour disparaître.",
"Capitaine ! Tes dettes me manquaient, presque autant que ton sourire.",
"Ton haleine de rhum me manquait aussi, mais je m'en passerai.",
"Hé, fripouille ! Toujours vivant ? J'avais parié contre toi.",
"Dommage pour toi, tu perds encore une mise.",
"Voilà le boucanier qui sait pas dire non à un tonnelet.",
"Et toi, le pirate qui sait pas dire non à une embrouille.",
"Je croyais que t'étais parti au diable avec ta carcasse.",
"Il m'a renvoyé, il supportait pas mon chant.",
"Ah ! L'éternel compagnon de mes pires idées !",
"Et l'éternel fossoyeur de mes meilleurs plans.",
"Alors, vieux frère, veux-tu que je te raconte ce que mes oreilles ont entendu comme rumeurs ?",
"J'prends volontiers tes conseils, j'sens que la mer cache un piège.",
"Raconte donc l'un de nos coups fumants, ça m'fera passer l'temps.",
"Pas d'bavardage, j'ai soif, direction la taverne !",
"Capitaine, t'as besoin de mes lumières ou juste de mon ombre ?",
"Tes lumières, aye, j'peux pas naviguer à l'aveugle.",
"Éclaire-moi plutôt d'un souvenir... parle de nos vieilles frasques.",
"Ton ombre fera l'affaire, allons vider un godet !",
"Alors, dis-moi, veux-tu des tuyaux, des souvenirs, ou un tonnelet ?",
"Balance les tuyaux, vieux loup, j'les note dans ma caboche.",
"Chante-moi un bout d'nos exploits, ça r'chauffera mon cœur.",
"Ni l'un ni l'autre, mon gosier commande plus fort que toi !",
"Besoin de mes ragots, de nos légendes, ou d'la chopine ?",
"Les ragots m'iront bien, j'me fie à ton flair.",
"Les légendes, aye, rappelle-moi quand on était plus fous qu'sages.",
"Ni ragots ni légendes, mais une chopine de suite !",
"Alors mon vieux, conseil, souvenir... ou taverne ?",
"Conseil ! J'ai besoin de ta tête, pas d'ton verre.",
"Souvenir ! Ça fait trop longtemps qu'on n'a pas ri de nos bêtises.",
"Taverne ! La parole dessèche, seul le rhum abreuve.",
"Tu t'rappelles d'la mutinerie sur la Santa Estrella ? On avait tout prévu : les couteaux sous les gilets, les hommes prêts à rugir. Et puis, toi, avec ton air de rien, t'as juste éternué au mauvais moment.",
"Ouais, et tout l'équipage a cru que c'était le signal d'attaque... quelle bande de sourds.",
"En moins d'une minute, le capitaine était ficelé comme un jambon, et toi debout sur une caisse sans rien comprendre. Quand les gars ont crié À bas l'ancien, vive le nouveau !, j'ai cru que t'allais t'évanouir.",
"C'est bien simple, j'voulais juste renifler tranquille, pas hériter d'un navire pourri avec vingt bouches à nourrir.",
"Le plus drôle, c'est qu'ils t'ont demandé ton premier ordre, et toi... tu t'souviens ? Tu leur as dit : Servez-moi un verre d'eau, et ils ont pris ça pour une stratégie divine !",
"Ouais... et l'pire, c'est qu'ils m'ont obéi comme si j'étais un prophète. Alors qu'en vrai, je voulais juste rincer ma gorge, pas gouverner une foutue mutinerie.",
"Tu t'souviens de ce coffre énorme qu'on a déterré après trois jours d'fouilles sous le soleil ? Les hommes tremblaient déjà en s'imaginant nager dans l'or.",
"Et quand on l'a ouvert, c'était pas l'or qui chantait, mais une centaine de perroquets furieux !",
"Des volatiles qui juraient en espagnol, et plutôt salement ! On aurait dit une garnison entière. L'équipage a cru à une malédiction, certains se sont jetés à l'eau.",
"Ouais, alors qu'en vrai c'était juste un marchand d'oiseaux qui avait planqué sa cargaison.",
"Tu t'souviens du rouge qui criait sans arrêt : “Traidor, traidor !” ? Pendant un mois, l'équipage m'a pris pour un espion espagnol à cause de cette satanée bête !",
"Hé bien moi, j'me rappelle surtout qu'on a fini par les vendre plus cher que de l'or. Comme quoi, parfois les perroquets font meilleure fortune qu'les doublons.",
"Ah, cette foutue tempête au large d'Hispaniola... On croyait que le ciel entier voulait nous avaler ! Les mâts grinçaient, les voiles se déchiraient, c'était la fin assurée.",
"Et toi, tu hurlas : Enlevez vos chemises, on fera des voiles neuves !",
"Et par miracle, ça a tenu ! Des caleçons en guise de pavillon, j'avais jamais vu ça. On ressemblait plus à une lessive flottante qu'à un navire de guerre.",
"Mais on est sortis de l'enfer, et ça, c'était pas rien.",
"Tu t'rappelles la tête des pêcheurs qui nous ont vus débarquer, demi-nus, en haillons multicolores ? Ils nous ont pris pour une secte sortie de la mer.",
"Bah ! On avait l'air de fous, mais c'est bien la preuve qu'on survit toujours, même dans les pires bourrasques. Et rien que pour ça, j'me dis qu'on est peut-être maudits... mais invincibles.",
"Souviens-toi de cette île, toute couverte de brumes, avec ces silhouettes étranges la nuit. J'étais persuadé qu'on affrontait des esprits vengeurs.",
"Des esprits ? Tu parles ! C'était juste une procession avec des cierges !",
"Ouais, mais dans la brume, leurs chants lugubres sonnaient comme des incantations. Moi j'me voyais déjà sacrifié sur un autel.",
"Alors qu'eux priaient juste pour de la pluie !",
"J'avoue, j'ai peut-être crié un peu fort quand j'ai dégainé mon sabre... Mais t'aurais fait pareil, non ?",
"J'ai surtout vu la tronche des pauvres moines, qui ont cru qu'on était des démons sortis de l'océan. Au final, ils ont fui plus vite que nous, et c'est nous qui avons gardé l'île !",
"Tu t'souviens du vieux canon rouillé, celui qu'on utilisait à contre-cœur ? En plein combat, il a éclaté comme un tambour trop tendu !",
"Et sa roue a traversé l'air pour couler la chaloupe ennemie !",
"Je crois qu'on n'a jamais vu l'équipage aussi abasourdi. Les Espagnols, eux, ont pris ça pour de la sorcellerie !",
"En vérité, c'était juste un coup de malchance... qui nous a bien servi.",
"Depuis ce jour, certains m'appellent le maître du canon fantôme. J'te jure, j'y suis pour rien !",
"Moi j'dis que tant qu'ils y croient, c'est une gloire qu'on garde. Même si notre fameux canon, au final, était bon qu'à faire des planches.",
"J'te jure sur ma barbe, cette nuit-là une sirène m'a lancé un sourire ! Des yeux comme des perles, des cheveux ruisselants... c'était l'amour marin.",
"L'amour marin ? C'était surtout un contrebandier barbu avec une perruque, oui !",
"Bah, dans la pénombre, l'erreur est permise ! Il chantait drôlement bien, quand même. Et puis il avait une grâce... enfin, une démarche... enfin, il boitait, quoi.",
"Oui, la grâce d'un marin qui a glissé sur sa propre caisse de rhum.",
"Enfin, ça m'aura coûté une bourse et ma dignité. Mais avoue que c'était une belle illusion, non ?",
"Illusion, peut-être... mais ça reste la seule sirène que j'ai vue avec des poils de barbe. Crois-moi, celle-là, je la chante pas dans mes histoires.",
"Ah, cette plage scintillante, tu t'en rappelles ? On croyait marcher sur des millions de doublons ! Le soleil faisait briller chaque grain, c'était un trésor sans fin !",
"Un trésor, ouais... de pyrite. Du faux or, même les crabes en riaient.",
"Mais quelle allure ! Toute l'équipage à genoux, remplissant leurs poches comme des enfants. Certains ont même essayé de le croquer pour tester sa valeur !",
"Résultat : trois dents cassées, et un moral à zéro.",
"Bon... on n'est pas repartis riches. Mais au moins, on brillait comme des statues en rentrant au port !",
"Exact. Des statues dorées de ridicule, couvertes de faux éclat... mais statues quand même. J'te jure, parfois la gloire c'est juste de briller pour de mauvaises raisons.",
"Tu t'rappelles la fuite vers Tortuga, quand tout l'équipage paniquait à la barre ? C'est pas un homme qui nous a sauvés... mais ce satané singe de cuisine !",
"Et il a tenu la barre mieux que toi, ce fichu macaque.",
"Il tournait le gouvernail comme un vieux loup de mer, je t'jure ! Même les vagues semblaient lui obéir.",
"Ouais, jusqu'à ce qu'il lâche tout pour piquer une banane.",
"Bah, c'était quand même notre meilleur barreur de la semaine ! Certains marins voulaient l'élire maître d'équipage.",
"Et moi, j'ai dit que tant qu'il naviguait mieux que toi, il avait ma voix. Mais qu'on garde quand même un tonnelet de bananes, au cas où.",
"Ah, cet abordage près de Trinidad... on avait tout prêt : sabres, pistolets, fusils. Et pas une arme n'a tiré ! Toute la poudre était foutue !",
"Alors t'as balancé des hamacs mouillés à la tête des Espagnols... ridicule mais efficace.",
"Ridicule, peut-être, mais tu les as vus trébucher comme des crabes ivres ? En deux minutes, ils étaient par terre à s'débattre dans les cordages.",
"Et toi, tu criais “Victoire !”, comme si c'était un stratagème prévu.",
"Bah, fallait bien sauver les apparences ! J'ai même failli croire que c'était une idée de génie.",
"Ouais, de génie peut-être... mais sûrement pas préméditée. Reste que ce jour-là, nos hamacs ont gagné plus de batailles que nos canons.",
"Tu t'souviens quand j'ai infiltré les Espagnols en me faisant passer pour un noble ? J'avais la cape, la moustache cirée, et même un accent travaillé.",
"Ouais... sauf que t'avais oublié ton bandeau de pirate et ta cicatrice.",
"Bah, j'pensais que ça me donnait un air de vétéran distingué ! J'ai même réussi à leur faire croire que j'étais un grand duelliste.",
"Jusqu'à ce qu'ils demandent une démonstration, et que tu manques d'trancher ton propre chapeau.",
"Bon... on a dû fuir avant le dessert. Mais j'te jure, j'avais presque gagné leur confiance !",
"Presque, oui... à part que tu t'étais présenté comme Don Malcolm de la Taverna. Crois-moi, ça sonnait pas très aristocrate.",
"Trois semaines à suivre une carte... tu t'en rappelles ? On pensait être à deux doigts du trésor du siècle !",
"Jusqu'à ce que je réalise que tu lisais la carte... à l'envers.",
"Hé, les symboles étaient pas clairs ! Un palmier à gauche ou à droite, ça change tout. Et puis l'étoile du nord, elle brille pareil que celle du sud après trois bouteilles.",
"Ouais... résultat, on a traversé une île entière pour finir au point de départ.",
"Au moins, on connaît chaque buisson et chaque caillou par cœur maintenant ! Une vraie carte vivante, grâce à moi.",
"Ouais... mais la prochaine fois, laisse la lecture aux gens qui savent différencier haut et bas. Sinon on finira par enterrer nos propres bottes.",
"Ah, ce duel dans la cour de San Juan... L'officier espagnol, redouté de tous. Il m'avait défié devant une foule entière.",
"Et toi, tu l'as assommé d'un coup... de chaise !",
"Bah quoi ? Une chaise, c'est plus solide qu'un sabre quand on y pense. Et j'peux t'assurer que la foule a applaudi comme jamais.",
"En même temps, personne s'y attendait... surtout pas lui.",
"Depuis, certains m'appellent El Sillazo, le maître de la chaise. J'te cache pas que j'en suis presque fier.",
"Faut dire, battre un héros espagnol avec du mobilier, c'est pas donné à tout l'monde. Mais évite d'me demander d'porter ta chaise en trophée, hein.",
"Ah, ton déguisement de moine... j'en ris encore ! Tu marchais la tête basse, les mains jointes, l'air pieux.",
"Et alors ? Ça passait, non ?",
"Jusqu'à ce que le soldat espagnol te demande une prière en latin. Et toi, tu t'es mis à réciter une recette de bouillon !",
"Hé, ça sonnait assez latin pour eux ! Ils ont même fait le signe de croix.",
"Ouais... et ils t'ont obligé à bénir tout le port. Trois heures de procession, et toi qui transpirais sous la robe.",
"Si tu savais comme j'ai maudit chaque amen ce jour-là. Mais au moins, personne n'a fouillé sous la bure... et ça nous a sauvés.",
"Tu t'souviens de ce navire fantôme qu'on a poursuivi toute une nuit ? Brillant comme une chandelle en mer, on croyait à un miracle... ou une malédiction.",
"Et au matin, on a découvert que c'était juste des milliers de méduses phosphorescentes collées à la coque.",
"Mais avoue que ça foutait la frousse, ces lumières vertes partout ! Même nos marins les plus durs refusaient d'approcher.",
"Jusqu'à ce que l'un d'eux essaie d'en attraper une et finisse couvert de cloques.",
"Bon, j'avoue, c'était pas un navire maudit... Mais quand j'dis à la taverne qu'on a affronté une flotte de spectres, ça impressionne davantage.",
"Ouais... surtout si tu oublies de préciser qu'on a perdu la moitié d'notre savon pour calmer les brûlures. Mais après tout, c'est ça, la légende : du vrai, du faux, et beaucoup de méduses.",
"Trois jours à plonger pour des perles, j'crois qu'on avait jamais autant espéré ! Et quand enfin on en trouve une grosse comme mon poing...",
"Une tortue géante l'a avalée sous notre nez !",
"T'as sauté à l'eau pour la poursuivre, mais cette foutue bête nageait plus vite qu'un galion. Moi, j'criais qu'il fallait harponner la bestiole, mais personne n'osait.",
"Normal ! On avait déjà perdu trois harpons dans ses écailles.",
"Résultat : la perle, envolée pour de bon. Et une tortue qui doit se pavaner au fond de la mer avec un bijou dans l'estomac.",
"J'me console en me disant qu'elle est la plus élégante des Caraïbes. Et qu'un jour, peut-être, un pêcheur chanceux deviendra riche à notre place.",
"Ah, cette bagarre à la taverne de Port Royal... tout a commencé par une simple gifle. Et ça s'est fini avec le toit qui s'effondre sur tout l'monde !",
"Parce que t'as voulu escalader le comptoir pour frapper plus haut... et t'as fait tomber la poutre maîtresse.",
"Bon, j'avoue, ça tenait pas bien depuis des années. Mais quand même, voir une taverne entière s'écrouler sur un seul coup, c'était pas banal.",
"Pas banal, et surtout pas discret. Les soldats nous cherchaient déjà.",
"Au moins, on est sortis sans une égratignure ! Et les autres se sont fait enterrer sous les gravats.",
"Ouais, chance du diable, comme toujours. Mais rappelle-moi de jamais t'laisser grimper sur un comptoir encore debout.",
"Tu t'souviens de ce coffre infernal ? Trois jours à forcer ce fichu cadenas ! On suait sang et eau, l'équipage perdait patience.",
"Et quand on l'a enfin ouvert... juste une cocotte en papier avec marqué merci pour la patience.",
"J'ai cru qu'on allait tuer le serrurier qui nous avait vendu la carte. Mais certains riaient tellement qu'ils en sont tombés par terre.",
"Ouais, entre la rage et le fou rire, on savait plus de quel côté basculer.",
"Au moins, ça nous a fait une histoire à raconter. Et j'te jure qu'à Tortuga, les gars paient cher pour entendre ce genre de mésaventure.",
"Alors on n'aura pas gagné d'or, mais au moins une tournée gratuite. Et ça, c'est un trésor qu'on sait apprécier.",
"Tu t'souviens de cette cargaison de rhum, perdue corps et biens au large ? Un coup de houle et hop, tout à la flotte !",
"Et pourtant, le lendemain, quelques tonneaux flottaient à la surface comme par miracle.",
"L'équipage criait au don des dieux, chacun s'accrochant à son tonneau comme à une bouée sacrée. On aurait dit un pèlerinage sur mer.",
"Ouais, sauf qu'au lieu de prier, ils tapaient les bondes pour boire direct dedans.",
"Enfin, ça nous a sauvés : sans ces tonneaux, on rentrait bredouilles. Moi j'dis qu'le destin nous aime bien, même s'il se marre à nos dépens.",
"Peut-être... mais j'aurais préféré qu'il nous garde la cargaison entière. Là, on a survécu, mais les Espagnols ont dû trinquer à notre santé avec le reste.",
"Ah, ce rapt glorieux ! On croyait avoir enlevé un ambassadeur espagnol de haut rang ! Toute la mer aurait tremblé à l'annonce...",
"Jusqu'à ce qu'on découvre qu'on avait juste kidnappé le cuisinier du banquet.",
"Avec son tablier taché et sa louche en guise d'épée, il criait plus fort qu'un général. J'étais persuadé que c'était une couverture de génie.",
"Une couverture... de graisse, surtout !",
"Bon, au final, on a dû le libérer, et on n'a pas gagné grand-chose. Sauf peut-être sa recette de ragoût, qu'il nous a donnée pour la route.",
"Et c'est ça, la vérité : on est peut-être pas devenus riches... Mais on est les seuls pirates à avoir gagné une soupe en otage.",
"Te rappelles-tu de ce sablier étrange, trouvé dans les affaires d'un vieux mage ? J'étais persuadé qu'il ralentissait le temps lui-même !",
"Jusqu'à ce qu'on découvre que tu l'avais simplement coincé en le secouant trop fort.",
"Mais quand même, on jurait que les minutes passaient plus lentement ! C'était peut-être mon imagination... ou le rhum du mage.",
"Non, c'était juste un sablier fêlé qui coulait de travers.",
"Enfin, ça impressionne toujours de dire qu'on a manipulé le temps. Même si c'est faux, ça claque bien dans une histoire.",
"Ouais, sauf que moi, je sais qu'tu t'es battu avec un objet de cuisine. Et ça, vieux frère, c'est une histoire que je garde précieusement.",
"Sur quoi veux-tu que je te donne de l'aide, vieux frère ?",
"Les chasseurs de trésors, tu connais ? Ces gars qui écument les îles en quête de cartes anciennes et de légendes oubliées.",
"En ville, on dit qu'il y a des tourtereaux les poches vides.",
"S3",
"S4",
"S5",
"S6",
"Le titre de ''Pirates des Caraïbes'', c'est pas un peu ronflant ?",
"Qui est cette Carmen dont j'ai entendu parler ? Elle est discrète mais fait beaucoup de dégâts.",
"M3",
"M4",
"M5",
"M6",
"B1",
"B2",
"B3",
"B4",
"Tu les croiseras en ville tôt le matin jusqu'à midi environ, toujours à chercher un navire qu'ils n'ont pas. File-leur un coup d'main, mais garde ton sabre au fourreau même si la somme qu'ils te proposent à la fin n'est pas à ton goût. Je te conseille d'augmenter ton niveau de commandement et de chance l'ami. ",
"À Redmond, tu les trouveras près de la maison du gouverneur.",
"À Falaise de Fleur, cherche sur la plage, là où un bateau est en construction.",
"À Isla Muelle, passe par la porte entrouverte derrière la taverne, dans la petite cour.",
"À Conceição, tu les verras traîner en pleine ville.",
"À Douwesen aussi, c'est en ville qu'ils chassent leur fortune.",
"À Greenford, tu les trouveras en ville, l'œil à l'affût.",
"À Oxbay, les chasseurs rodent dans les rues de la ville.",
"Merci, vieux frère. J'verrai si leurs cartes mènent à l'or... ou à un autre de leurs tonneaux vides.",
"Y'a toujours un jeunot sans un sou qui soupire d'amour dans les rues. Suis ces histoires de cœur, ça pourrait finir en pièces sonnantes et trébuchantes. ",
"À Redmond, tu l'trouveras dans la partie ouest de la ville, pas loin de la prison.",
"À Falaise de Fleur, cherche-le juste après la porte principale qui mène au port.",
"À Isla Muelle, il traîne dans la partie ouest, près de la porte qui s'ouvre vers la jungle.",
"À Conceição, c'est en ville que tu croiseras l'un de ces amoureux transis.",
"À Douwesen aussi, ouvre l'œil dans les rues de la ville.",
"À Greenford, même rengaine, tu les verras en pleine ville.",
"Et à Oxbay, c'est pareil, c'est en ville que les cœurs s'égarent.",
"Alors l'amour mène à l'or ? Voilà une chanson que j'veux bien fredonner...",

};