string DLG_TEXT[22] = {
"Bonjour mon ami, je suis un trou du cul !",
"Euh... Oui ! Salut à toi. Je suis ",
", le capitaine du ",
", et on peut dire que c'est le plus fort des navires !",
"De quoi as tu besoin ?",
"D'argent (50000)",
"De points d'expérience (50000)",
"De notoriété",
"VOILA !!!",
"De quelle réputation as-tu besoin ?",
"Bonne réputation",
"Neutre",
"Mauvaise réputation",
"Laquelle ?",
"Horreur des hautes mers",
"Maudit bâtard",
"Escroc cynique",
"Fieffé coquin",
"Bon gars",
"Amis solide",
"Généreux",
"Héros",

};