string DLG_TEXT[20] = {
"Bonjour capitaine. Vous semblez savoir écouter sans vous moquer des gens simples.",
"Je peux au moins essayer. Qui êtes-vous ?",
"Je m'appelle Llewellyn Brooker. Je viens des rues de Redmond, et aujourd'hui elles me paraissent bien étroites.",
"Que vous arrive-t-il donc ?",
"Je suis épris de Magdalen Spooner. Elle vaut mieux que toutes les vitrines de joailliers de Redmond, et c'est bien mon problème.",
"Je ne suis pas certain de pouvoir me fier à vous. Redmond a la langue trop légère pour confier pareil secret au premier capitaine venu.",
"Je comprends. Je vous laisse donc à votre silence.",
"Je crois que votre réputation parle pour vous mieux que bien des sermons.",
"Alors dites-moi ce qui vous tourmente.",
"Magdalen ne veut pas d'une promesse vide. Elle veut un anneau en or serti d'émeraudes, digne d'une demande faite sans mendier à ma famille.",
"Redmond n'est pourtant pas avare en familles riches. Pourquoi ne pas attendre ?",
"Parce qu'il ne me reste qu'une semaine. Le fils d'un maître tonnelier a mis de côté de quoi lui offrir un anneau, et sa mère le pousse déjà vers elle.",
"Vous voulez donc gagner cette course avant son retour.",
"Oui. Si vous m'aidez, je ne pourrai vous offrir que ma gratitude, mais elle sera sincère.",
"Très bien. Je veux bien porter cette affaire jusqu'au bout.",
"Désolé, mais cette comédie mondaine se jouera sans moi.",
"Merci, capitaine ",
". Remettez cet anneau à Magdalen Spooner, et dites-lui que pour une fois Redmond a vu juste sur un homme.",
"Je vais m'en charger.",
"Avez-vous des nouvelles de Magdalen ? Le temps file plus vite que les ragots de Redmond."
};
