string DLG_TEXT[18] = {
"Monsieur, à Falaise de Fleur on ne s'approche pas d'une demoiselle sans raison. La vôtre ?",
"Je viens de la part de ",
" et j'espère ne pas vous offenser.",
"Vous n'y parviendrez pas si vous évitez les banalités.",
"Fabrisse de Lucien m'envoie. Il veut vous prouver qu'il sait enfin décider sans sa famille.",
"Ce serait en effet une nouveauté. J'en ai assez des jeunes hommes qui demandent à leur nom de penser pour eux.",
"Il veut vous montrer autre chose que son nom.",
"Alors tout dépend du présent. L'avez-vous apporté ?",
"Non. Sans cela, cette conversation n'a aucun intérêt pour moi.",
"Dans ce cas, regardez ceci.",
"Voici la bague en or sertie de saphirs qu'il vous offre pour vous demander votre main.",
"Oh... ",
" ... Il a donc compris ce qui compte vraiment : choisir et assumer ce choix.",
"Je crois qu'il a fait un vrai pas vers vous.",
"Merci, capitaine ",
". Dites à Fabrisse qu'il sera jugé sur son courage, et qu'aujourd'hui il n'a pas été ridicule.",
"Je n'y manquerai pas.",
"Merci, capitaine. Vous avez épargné à Falaise de Fleur une scène bien plus vulgaire."
};
