string DLG_TEXT[25] = {
"Toi... capitaine. J'ai une affaire a te proposer.",
"Parle.",
"Je n'ai rien a faire avec toi.",
"Une personne de cette ile me gene. Je veux qu'elle disparaisse.",
"Pourquoi moi ?",
"Parce que tu as l'air de savoir te taire. Et parce que je paie.",
"Qui est la cible ?",
"Je te donnerai le nom des que tu auras accepte. Interroge qui tu veux ensuite, cela m'est egal.",
"Je veux en savoir plus.",
"Alors ecoute bien.",
"Des rumeurs, des dettes, des morts... assez pour qu'un homme prudent prefere payer quelqu'un d'autre.",
"Je prends le contrat.",
"Non. Trouve un autre sabre.",
"Parfait. Le nom t'attend deja. Ne tarde pas trop.",
"Je saurai la retrouver.",
"Tu es revenu les mains vides. La cible respire encore.",
"Je poursuis mon enquete.",
"La cible est morte.",
"Bien. Voila ton paiement. J'espere que tu dors bien.",
"L'affaire est close.",
"Tu as laisse partir ma cible ?",
"Je ne tue pas sans certitude.",
"Alors tu me laisses un seul choix.",
"Tire donc l'acier.",
"Nous en avons fini."
};
