string DLG_TEXT[17] = {
"Monsieur, a Falaise de Fleur on ne s'approche pas d'une demoiselle sans raison. La votre ?",
"Je viens de la part de ",
" et j'espere ne pas vous offenser.",
"Vous n'y parviendrez pas si vous evitez les banalites.",
"Fabrisse De Lucien m'envoie. Il veut vous prouver qu'il sait enfin decider sans sa famille.",
"Ce serait en effet une nouveaute. J'en ai assez des jeunes hommes qui demandent a leur nom de penser pour eux.",
"Il veut vous montrer autre chose que son nom.",
"Alors tout depend du present. L'avez-vous apporte ?",
"Non. Sans cela, cette conversation n'a aucun interet pour moi.",
"Dans ce cas, regardez ceci.",
"Voici la bague en or sertie de saphirs qu'il vous offre pour vous demander votre main.",
"Oh... ",
" ... Il a donc compris ce qui compte vraiment: choisir et assumer ce choix.",
"Je crois qu'il a fait un vrai pas vers vous.",
"Merci, capitaine ",
". Dites a Fabrisse qu'il sera juge sur son courage, et qu'aujourd'hui il n'a pas ete ridicule.",
"Je n'y manquerai pas.",
"Merci capitaine. Vous avez epargne a Falaise de Fleur une scene bien plus vulgaire."
};
