string DLG_TEXT[20] = {
"Capitaine, attendez. Je vous prie de m'accorder une minute avant que tout Falaise de Fleur n'invente le reste.",
"Je vous écoute. A qui ai-je l'honneur ?",
"Je suis Fabrisse de Lucien. Mon nom ouvre encore des portes, mais il ne m'aide guère à gagner le coeur de Donatienne de La Fayette.",
"C'est donc une affaire de mariage ?",
"Oui, et dans cette ville on jauge l'amour comme un bal bien tenu. Donatienne veut une bague en or sertie de saphirs, preuve que je peux choisir par moi-même.",
"Pardonnez-moi, mais je ne puis me confier à quelqu'un dont la réputation ferait jaser tout le port.",
"Alors je ne vous retiens pas davantage.",
"Votre nom, lui, ne me fait pas honte. Peut-être avez-vous l'honneur qu'il me faut emprunter.",
"Expliquez-moi cela plus clairement.",
"Mon père tient à me marier utilement. Donatienne aussi est courtisée, et une famille mieux née doit présenter son prétendant dans une semaine.",
"Vous cherchez à frapper vite avant que la noblesse ne tranche pour elle.",
"Exactement. Si Donatienne reçoit ce bijou de ma part, elle saura que je ne courbe plus l'échine devant mon nom.",
"Et vous voulez que je devienne le discret messager de cette rébellion galante.",
"Oui. Je n'ai pas d'or à vous promettre, seulement le souvenir d'avoir servi une belle cause.",
"Soit. Je porterai votre bague à Donatienne.",
"Non. Les salons de Falaise de Fleur se passeront de moi.",
"Merci, capitaine ",
". Dites à Donatienne qu'une bague en or sertie de saphirs l'attend, et qu'elle vient d'un homme qui a enfin choisi son propre camp.",
"Je lui remettrai le message.",
"Capitaine, avez-vous vu Donatienne ? Dans cette ville, une semaine suffit pour perdre une vie entière."
};
