string DLG_TEXT[54] = {
"Salutations pirate ! [Kof !]",
"Salutations ! A qui ai-je l'honneur ?",
" ! Capitaine du ",
". Je suis certain que tu me connais [Kof ! Kof !], Je suis François l'Olonnais.",
"LE FLÉAU DES ESPAGNOLS ! Tout le monde dit qu'il est mort depuis bien longtemps, mangé par des indiens friant de chair humaine...",
"J'ai bien faillit y passer avec ces indiens. [Kof !] Mais j'ai eu une chance inouïe de trouver un radeau dérivant non loin de la plage de ces maudits mangeurs d'homme.",
"Quelle chance, oui ! Mais pourquoi n'a-t-on plus entendu parler de vous ?",
"C'était un coup de semonce pour moi. Mes dernières prises ont été très bonnes. J'ai donc pris ma retraite. [Kof ! Kof !]",
"Je vois, cocktails sous les cocotiers, les doigts de pied en éventail !",
"Pas vraiment. Je m'étais mis à dos toutes les nations qui voguent dans ces eaux. J'étais LE 'pirate des Caraïbes'. Même après ma mort officielle, chaque pays traquait les butins que je leur ai arrachés.",
"Une vie recluse ?",
"C'est un peu près ça. Mais maintenant, c'est la fin. [Kof ! Kof ! Kof !] J'ai attrapé la phtisie. Les médecins ne me donne que quelque mois à vivre et je ne peux pas aller en ville me soigner, les autorités me tomberaient dessus. Mais toi, capitaine ",
", je veux te léguer mon trésor.",
"Moi ? Pourquoi ? Je sens qu'il y a quelque chose derrière ça !",
"[Kof ! Kof !] Oui, je veux te transmettre aussi mon titre de 'Pirate des Caraïbes'.",
"Euh... Oui... Comment ?",
"Comme moi, tu dois faire preuve d'audace.",
"Salutations François l'Olonnais.",
"Je te léguerai tous mes biens lorsque tu auras pris tous les forts des Caraïbes ! [Kof ! Kof !]",
"Rien que ça !?!",
"[Kof ! Kof !] Evidemment, je laisserai le bruit courrir que je suis vivant. Tu auras donc toutes les nations à tes trousses. Les forts vont être défendus par des navires de guerre.",
"Mais encore ?",
"C'est sans moi !",
"[Kof !] Tu pourras faire des réparations de tes navires gratuitement dans chaque port pris ! Mais reviens à Quebradas Costillas pour faire des achats et pour renflouer ton équipage, il te faudra de l'argent. Mais il te sera impossible de le faire dans les autres îles.",
"C'est dangereux mais intéressant, continue.",
"Oui mais non, l'ami.",
"Une fois, tous les forts pris, je me débrouillerai pour me rendre aux autorités, tes relations avec les nations redeviendront les mêmes qu'avant.",
"Tant mieux.",
"Si tu acceptes, tu auras aussi une trève avec les pirates jusqu'à ce que tu es mon titre.",
"Chouette !",
"Mais attention, la convoitise des pirates va grandir, je ne peux pas te promètre que cela durera. [Kof !]",
"Toujours les mêmes ceux-là.",
"Veux-tu combattre et devenir le nouveau 'Pirate des Caraïbes' ?",
"je trépigne d'impatience",
"Je ne suis pas encore prêt. Je reviens vers toi quand je serai mieux armé.",
"Une demande.",
"Oui ?",
"[Kof !] Je viens avec toi, je veux le voir de mes yeux.",
"J'imagine, que ce n'est pas négociable. Que la fête commence !",
"J'attends de te voir à l'œuvre capitaine ",
"Félicitation capitaine pour la prise de Redmond. C'était une belle bataille. Ces rosbif l'ont bien mérités.",
"Bravo gamin ! Tu m'as bien vengé de ces mangeurs de grenouilles.",
"Conceicao n'est plus ce qu'elle était. Une petite bataille et elle rend les armes.",
"Félicitation capitaine ! Isla Muelle est tombée. L'armada n'est pas invinsible.",
"Bravo ! Douwesen est à toi ! Petite victoire, mais victoire tout de même.",
"Greenford ! Les anglais doivent se demander ce qu'ils ont fait pour ne jamais arriver à garder cette place forte !",
"Ces anglais d'Oxbay sont très arrogants mais je trouve que leur cadavres flottants dans la mes reflète mieux l'image que j'ai d'eux.",
" ! Capitaine du ",
"Je ne pensais pas te revoir avant ma mort. Ils vont me pendre demain. Je ne savais pas que justice pouvais être rendue si vite.",
"Il semblerait que des personnes veulent te voir mort.",
"Il en sera mieux ainsi.",
"C'est étrange quelque chose ne semble pas aller dans toute cette histoire et ...",
"C'est terminé. Je m'en vais. Retourne voir Chui A-poo. Il te donnera ta récompence. ADIEU !",
"Adieu, Fléau des espagnols. [mais tu me cache quelque chose]",

};