string DLG_TEXT[26] = {
"Toi... capitaine. J'ai une affaire à te proposer.",
"Parle.",
"Je n'ai rien à faire avec toi.",
"Une personne de cette île me gêne. Je veux qu'elle disparaisse.",
"Pourquoi moi ?",
"Parce que tu as l'air de savoir te taire. Et parce que je paie.",
"Qui est la cible ?",
"Je te donnerai le nom dès que tu auras accepté.",
"Je veux en savoir plus.",
"Alors écoute bien.",
"Des rumeurs, des dettes, des morts... assez pour qu'un homme prudent préfère payer quelqu'un d'autre.",
"Je prends le contrat.",
"Non. Trouve un autre sabre.",
"Parfait. Le nom est ",
"Je saurai la retrouver.",
"Tu es revenu les mains vides. La cible respire encore.",
"Je poursuis mon enquête.",
"La cible est morte.",
"Bien. Voilà ton paiement. J'espère que tu dors bien.",
"L'affaire est close.",
"Tu as laissé partir ma cible ?",
"Je ne tue pas sans certitude.",
"Alors tu me laisses un seul choix.",
"Tire donc l'acier.",
"Nous en avons fini.",
". Ne tarde pas trop."
};