string DLG_TEXT[67] = {
"Capitaine, je suis Sir Henry Huncks, officier au service du gouverneur Silehard. On m'a confié de consigner chaque indice et de rédiger les mandats. Avec moi, tout sera en règle.",
"Fort bien, Sir Henry. Vous semblez savoir tenir vos registres.",
"A chaque fois que vous obtenez un indice, venez me le transmettre. Je compilerai les informations et dresserai une liste de suspects. S'il ne reste qu'un seul nom, je vous remettrai un mandat d'arrêt en bonne et due forme.",
"Voilà qui est clair.",
"Voici ce que nous savons déjà : ",
". Dites-moi maintenant quel type d'indice vous souhaitez préciser.",
"Je vais réfléchir à ce que j'ai appris.",
"Sa chevelure.",
"Ses yeux.",
"Son accoutrement.",
"Un accessoire distinctif.",
"Une passion.",
"Une compétence.",
"Un signe distinctif.",
"La langue parlée.",
"Son port d'origine.",
"Il est du genre hominidé mâle.",
"Nous avons affaire à une voleuse. Diantre !",
"Ses cheveux ?",
"Noirs.",
"Roux.",
"Blonds.",
"Ses yeux ?",
"Marron.",
"Verts.",
"Bleus.",
"Son habits ?",
"Habits sobres et fonctionnels.",
"Vêtement élégant de belle facture.",
"Habits voyants aux couleurs criardes.",
"Un accessoire ?",
"Un compas marin.",
"Un anneau en or.",
"Une longue-vue.",
"Une passion ?",
"Collectionneur.",
"Poète.",
"Passionné pour les oiseaux.",
"Une compétence ?",
"Grimpeur.",
"Manie la langue avec ruse.",
"Déguisement parfait.",
"Un signe distinctif ?",
"Une cicatrice.",
"Un tatouage.",
"Boiterie.",
"La langue parlée ?",
"Espagnol.",
"Français.",
"Anglais.",
"Port d'origine ?",
"Séville.",
"La Rochelle.",
"Plymouth.",
"Je ne suis plus sûr.",
"Très bien, j'ai noté que c'est un homme.",
"Bien.",
"Très bien, j'ai noté que c'est une femme.",
"Bien.",
"J'ai croisé les informations. Voici la liste des suspects qui correspondent à vos dires : ",
"Bien !",
"Hmm… aucun suspect ne correspond à ces descriptions. Quelque chose cloche dans vos témoignages. Peut-être avez-vous mal compris.",
"Je reverrai mes informations. Mieux vaut repartir en chasse.",
"Il ne reste qu'un nom possible. Je rédige aussitôt le mandat d'arrêt à son encontre.",
"Très bien. Avec ce mandat, le pirate ne m'échappera pas.",
"Noté.",
"Effaces ce que j'ai dit à propos de ça."

};