string DLG_TEXT[19] = {
"Encore un regard de travers... Que me voulez-vous ?",
"Quelques questions. Rien de plus, pour l'instant.",
"On m'a parlé de vous. Certains vous disent dangereux.",
"Dans une ville portuaire ? Alors on m'accuse de respirer au mauvais endroit.",
"Je peux encore poursuivre mon enquête.",
"Faites donc. J'en ai assez des langues sales et des hommes payés pour les écouter.",
"Je pense que vous êtes innocent. Partez, vite.",
"Vous me donneriez cette chance ?",
"Oui. Partez avant que quelqu'un nous voie ensemble.",
"Je ne peux pas vous faire confiance. Tirez votre lame.",
"Alors c'était donc vrai. Vous n'êtes qu'un sabre à louer.",
"Une dernière parole avant que tout s'achève ?",
"Je ne suis pas venu pour bavarder.",
"Je vous ai déjà dit ce que je pouvais.",
"Je n'ai plus rien à ajouter.",
"Je vous dois peut-être la vie. Je ne l'oublierai pas.",
"Partez. Maintenant.",
"Si vous venez pour achever ce que vous avez commencé, je n'ai rien à dire.",
"Adieu."
};