string DLG_TEXT[20] = {
"Capitaine, un mot si vous voulez bien. Conceicao aime les chansons, mais moi je n'ai plus le coeur a chanter.",
"Parlez donc. Qui etes-vous ?",
"Je suis Florencio Baiano. Je travaille, j'epargne, j'espere, et pourtant cela ne suffit pas a convaincre Violamte Pinto.",
"Elle vous demande une preuve plus eclatante ?",
"Une broche en or. Ici, meme les amours les plus sinceres doivent briller un peu si elles veulent etre prises au serieux.",
"Je ne peux pas confier cela a quelqu'un dont le nom ferait peur a la moitie du quai.",
"Je vois. Je n'insiste pas.",
"En revanche, votre reputation me rassure. C'est peut-etre le signe que le ciel n'a pas tout oublie.",
"Qu'est-ce qui presse a ce point ?",
"Un autre pretendant revient d'Europe dans une semaine, charge d'argent et de promesses. Moi, je n'ai que mes mains et mon entetement.",
"Vous voulez passer devant lui avant qu'il ne pose pied a terre.",
"Oui. Si Violamte recoit cette broche en or, elle saura que je n'ai pas laisse la chance me filer entre les doigts.",
"Et vous attendez de moi que je porte cette chance jusque chez elle.",
"C'est cela. Je ne peux vous offrir qu'un merci, mais il viendra du fond du coeur.",
"Tres bien. Je vais vous aider.",
"Non, cette histoire devra se terminer sans moi.",
"Merci, capitaine ",
". Dites a Violamte qu'une broche en or l'attend, et qu'elle vient d'un homme qui refuse d'etre pauvre jusque dans ses sentiments.",
"Je n'oublierai pas.",
"Avez-vous parle a Violamte ? Le temps court plus vite ici que les nouvelles venues d'Europe."
};
