string DLG_TEXT[18] = {
"Qui êtes-vous, monsieur ? Oxbay n'envoie pas ses inconnus pour rien.",
"Je viens de la part de ",
" et je préfère aller droit au but.",
"C'est une bonne manière de commencer.",
"Rys Scorer m'envoie. Il espère que ce qu'il n'osait pas porter lui-même parlera enfin pour lui.",
"Rys a de l'audace quand il s'agit de rêver, moins quand il faut tenir tête aux belles familles du port.",
"Il essaie aujourd'hui de corriger cela.",
"Avez-vous apporté le présent qu'il m'a promis ?",
"Non. Sans preuve, je n'ai rien à entendre.",
"Alors regardez ce qu'il a osé choisir.",
"Voici le collier en pierres précieuses qu'il vous offre pour vous demander votre main.",
"Oh... ",
" ... Cette fois, il ne s'est pas contenté de parler plus fort que les autres. Il a choisi.",
"Je pense que c'est ce qu'il voulait vous faire savoir.",
"Merci, capitaine ",
". Dites à Rys qu'il vient peut-être de cesser d'être un rêveur pour devenir un homme.",
"Je le lui dirai.",
"Merci capitaine. Même Oxbay peut parfois voir naître quelque chose de sincère."
};
