string DLG_TEXT[18] = {
"Bonjour monsieur. J'espère que ce n'est pas encore un marchand venu se faire valoir.",
"Rien de cela. Je viens de la part de ",
" et il m'a chargé de vous parler franchement.",
"Alors j'apprécierai cette franchise.",
"Rawlin Feaver m'envoie. Il dit qu'un homme vaut peu s'il attend toujours que le monde lui fasse signe.",
"C'est une phrase plus courageuse que d'habitude. J'avais besoin de voir s'il pouvait agir sans se cacher derrière les circonstances.",
"Il a essayé de vous le montrer.",
"Avez-vous apporté ce qu'il m'a promis ?",
"Non. Sans cela, Greenford restera Greenford: beaucoup de bruit, peu de preuves.",
"Alors regardez plutôt ceci.",
"Voici le pendentif en émeraude qu'il vous offre pour vous demander votre main.",
"Oh... ",
" ... Il a donc enfin compris qu'une promesse doit peser quelque chose pour être entendue.",
"Je crois qu'il espère surtout que vous le jugerez sur cet effort.",
"Merci, capitaine ",
". Dites à Rawlin que je l'attendrai, mais pas indéfiniment: il vient de gagner du temps, pas une certitude.",
"Je transmettrai mot pour mot.",
"Merci capitaine. Vous avez peut-être empêché une belle sottise."
};
