string DLG_TEXT[20] = {
"Capitaine, puis-je vous retenir un instant ? Le vent de Douwesen me semble aujourd'hui bien froid.",
"Je vous ecoute. Qui etes-vous ?",
"Ghijsbrecht Van Der Hagen. Je voudrais epouser Tjaatje Meilink-Roelofsz, mais les bonnes intentions ne valent rien sans preuve.",
"Quelle preuve attend-elle ?",
"Une bague en argent sertie de saphirs. Ici, meme les coeurs sobres aiment voir un engagement tailler dans quelque chose de durable.",
"Je ne peux pas vous parler plus avant si votre reputation mettrait Tjaatje mal a l'aise.",
"Alors restons-en la.",
"Votre reputation me rassure au contraire. Elle me dit que je peux parler sans attirer le malheur sur nous.",
"Quel est donc le danger ?",
"Un marchand bien ne revient d'Europe que dans une semaine. Sa famille le pousse deja vers elle comme s'il etait une affaire conclue.",
"Vous voulez rompre cette affaire avant qu'elle ne se signe.",
"Oui. Si Tjaatje recoit cette bague en argent sertie de saphirs, elle saura que ma parole n'est pas en retard sur mon courage.",
"Et vous me demandez d'etre le porteur de cette parole.",
"C'est exactement cela. Je n'ai pas d'autre paiement a vous promettre qu'une reconnaissance durable.",
"Tres bien. Je vais vous aider.",
"Non. Je ne me mele pas de cela.",
"Merci, capitaine ",
". Remettez cette bague a Tjaatje et dites-lui qu'elle vient d'un homme qui prefere l'honnetete aux beaux comptes.",
"Je transmettrai.",
"Capitaine, avez-vous vu Tjaatje ? Le temps ne fait pas de cadeau, meme a Douwesen."
};
