string DLG_TEXT[56] = {
"On m'a dit que tu t'étais donné du mal pour obtenir une audience. Je m'appelle ",
". Et maintenant, si tu veux bien m'expliquer l'objet de ta visite, ",
".",
"Je m'appelle ",
".",
"Ah, c'est encore toi. Qu'est-ce qui t'amène, cette fois-ci? ",
"Je voudrais te parler d'une petite affaire.",
"Désolé, mais je suis occupé.",
"Alors, pourquoi viens-tu me déranger en plein milieu d'importantes affaires d'État?",
"Je voudrais te parler d'une petite affaire.",
"Je viens juste te présenter mes respects. Rien de plus.",
"Dans ce cas, je te prie de quitter mon bureau et de me laisser retourner à des affaires plus importantes.",
"Oui, bien sûr. Désolé de t'avoir dérangé.",
"Je t'écoute, ",
".",
"Je suis ici pour recevoir ma récompense pour la mort de Garry le salingue.",
"Désolé, mais je n'ai rien à te dire pour le moment.",
"Oh, j'ai entendu parler de ce que tu avais fait. Au nom de toute la colonie, je te prie d'accepter toute notre gratitude.",
"Bien. Je voudrais ma récompense.",
"Tu aimes la plaisanterie. Ha ha. Voici ton argent.",
"Merci, je suis ton humble serviteur.",
"Alors, et le pari que tu as placé... après avoir reçu l'accord de nos services fiscaux, je vois que nous avons... voyons... 6 000.",
"Quoi?! On avait dit 10 000!",
"Je ne peux pas t'aider. À l'avenir, essaie d'être plus calme.",
"Comme tu voudras. Bande de scélérats...",
", as-tu conscience que tu es accusé de meurtre? On t'a vu près du corps de la victime. Qu'as-tu à dire pour ta défense?",
"Je n'ai rien à voir dans cette affaire. L'homme était déjà mort quand je suis entré dans la pièce! On m'a dit qu'il était juste blessé et qu'il avait peut-être des informations importantes à me transmettre.",
", je viens d'apprendre qu'un homme avait été arrêté alors qu'il tentait de quitter la ville avec un couteau couvert de sang en sa possession. Il a avoué le meurtre dont tu étais accusé. Tu peux partir.",
"Merci. Je savais que je pouvais faire confiance à la justice de Conceicao.",
"Sir Silehard m'envoie. Il m'a dit qu'une lettre de cachet et un cadeau diplomatique attendaient ici un messager de confiance.",
"Alors Silehard ne t'a pas menti. L'Europe a décidé d'exporter jusque dans nos eaux ses calculs, ses peurs et ses ambitions.",
"Voici la lettre de cachet attendue, et voici le cadeau diplomatique qui doit l'accompagner. L'un sans l'autre perdrait une part de sa force.",
"Je les remettrai en main propre et sans halte inutile.",
"Fais-le. Il se murmure déjà que certaines forces malfaisantes s'agitent entre ces îles. Si elles jettent les Caraïbes dans le feu, il n'y aura bientôt plus rien à vendre ni à prendre.",
"Je vous ai déjà tout remis. Portez maintenant ces objets à Redmond sans perdre de temps.",
"Je ne traînerai pas.",
"On m'a volé la lettre de cachet et le cadeau avant Redmond.",
"Je vous ai déjà rapporté ce vol.",
"Quoi ? Des objets diplomatiques subtilisés si près de Redmond ? C'est une humiliation pour tous ceux qui ont fait circuler cet accord.",
"Les hommes portaient l'uniforme anglais, mais pas la langue qui allait avec.",
"Alors prévenez Silehard sans délai. Lui seul peut mesurer le choc politique de cette perte. Et si vous avez encore un peu d'honneur, retrouvez-moi ces voleurs.",
"Je repars aussitôt pour Redmond.",
"Ne traînez plus. Chaque heure rend cette lettre plus dangereuse hors de nos mains.",
"Je vous ferai tenir la suite.",
"Je vous ai déjà ordonné de prévenir Silehard et de reprendre la piste. Je n'ai rien à ajouter.",
"Très bien.",
"J'aurais besoin de votre jugement sur une personne de cette ville.",
"Vous m'avez déjà donné votre jugement sur cette affaire.",
"Je pèse mes mots, capitaine. L'administration entend bien des plaintes, et toutes ne méritent pas la corde. Mais au sujet de ",
", plusieurs signaux concordent. Si vous cherchez mon jugement, cette personne n'est pas blanche comme neige.",
"Je pèse mes mots, capitaine. Rien, dans les rapports ni dans les plaintes sérieuses, ne me permet d'accabler ",
". Je vous conseille la prudence avant de verser le sang.",
"Votre avis m'éclaire.",
"Je vous ai déjà livré l'appréciation que je pouvais formuler. Je n'ai rien à y retrancher.",
"Très bien."
};
