string DLG_TEXT[80] = {
"Fiche le camp, laisse-moi tranquille.",
"...",
"Oh, allez, capitaine. Je sais ce qui t'intéresse.",
"Excuse-moi, capitaine, mais j'ai des informations qui pourraient t'intéresser. Des choses qui pourraient t'être utiles.",
"De quoi pourrait-il s'agir?",
"Et qu'est-ce que tu pourrais bien avoir d'intéressant pour moi?",
"Ah! hé hé. Pas si vite, capitaine. Discutons d'abord de paiement. Je te promets que tu n'arriveras pas à découvrir quoi que ce soit sans moi.",
"Tu veux conclure un accord, capitaine? Une poignée de pièces contre des informations sur M. Rheims?",
"Vas-y. Combien veux-tu?",
"Es-tu ",
"?",
"Peut-être. Est-ce que tu sais quelque chose sur les bibelots indiens?",
"En effet. Et même un peu plus que ça, si tu vois ce que je veux dire.",
"Je peux te guider jusqu'à M. Rheims, mais circuler sur ces chemins dangereux te coûtera un peu d'argent. Si tu préfères y aller seul, je t'indiquerai le chemin et tu pourras te débrouiller.",
"Tu ferais mieux de venir avec moi et de me montrer le chemin.",
"Indique-moi le chemin ; j'irai tout seul.",
"Ne t'inquiète pas, capitaine, nous y serons bientôt.",
"Ce serait préférable...",
"Tu es à la traîne, capitaine. Marche à la même allure que moi.",
"C'est ridicule. Je crois que tu ferais mieux de me dire où nous sommes.",
"Oh, n'essaie pas de me cacher quoi que ce soit. Je sais ce que tu mijotes. Je vais peut-être juste te prendre tout ton argent.",
"Quoi?",
"Pas si vite, ",
", ça te coûtera 100 pièces d'or.",
"D'accord. Voilà ton argent.",
"C'est beaucoup trop! Indique-moi le chemin et je me débrouillerai.",
"Ah! Tu es pingre, stupide, ou peut-être même les deux. Très bien, écoute-moi alors. Enfonce-toi dans la jungle et va jusqu'au croisement.\nL'un des chemins va vers la gauche et l'autre tout droit. Prends celui qui va tout droit.\nTu verras ensuite un autre croisement et tu devras continuer toujours tout droit.\nUne fois que tu auras atteint le troisième croisement, tourne à gauche et tu auras atteint ton but.",
"Ca fait beaucoup de choses à se rappeler. J'espère que je ne me perdrai pas.",
"Parfait, allons-y.",
"Montre-moi le chemin, mais pas de blague. J'aurai toujours un oeil sur toi. ",
"Oui. Partons, il y a beaucoup de monde qui aimerait entendre notre conversation.",
"Et où proposes-tu que nous allions? Je ne...",
"Calme-toi, je ne veux pas te faire de mal. On va juste marcher un peu.",
"D'accord, mais n'oublie pas que je suis parfaitement capable de me défendre.",
"Bien sûr, calme-toi, je sais que tu as du talent. Viens maintenant, on a assez parlé, partons.",
"Passe devant.",
"Nous y voici. J'ai d'autres choses à faire, je te laisse.",
"Au revoir.",
"Je vais être clair. Donne-moi ton argent!",
"Je t'avais prévenu, je suis parfaitement capable de me défendre. Et tu vas bientôt avoir un aperçu de ces capacités.",
"Je sais qui tu cherches et je peux t'aider.",
"Je sais qui tu cherches et je peux t'aider.",
"Que sais-tu?",
"Dis-moi ce que tu sais.",
"Eh, discutons d'abord du paiement. Tu penses vraiment que je vais te donner ces informations gratuitement?",
"Mmh... Je pense que mes services méritent une récompense.",
"Combien veux-tu?",
"Eh bien, de combien as-tu besoin?",
"Donne-moi 1 500 pièces d'or et je te dirai tout ce que je sais.",
"Pas grand chose... juste 1 500 pièces d'or.",
"Prends ton argent.",
"Voilà, prends-les. Maintenant, dis-moi ce que tu sais sur ce gars.",
"C'est une assez grosse somme. Et tes informations ne valent peut-être pas autant...",
"Tu penses que c'est un peu trop?",
"Tu es doué pour extorquer de l'argent. Mais as-tu pensé à ce qui se passerait si je ne voulais pas payer autant d'or?",
"Pas d'argent - pas d'informations. Reviens me voir quand tu pourras me payer.",
"Si ça a de l'importance pour toi, tu devras me payer tôt ou tard.",
"Prends ton argent.",
"Voilà, prends-les. Maintenant, dis-moi tout ce que tu sais sur ce gars.",
"Eh bien, je reviendrai si j'ai encore besoin de ces informations.",
"Pourquoi devrais-je croire que tu es le seul vantard à pouvoir me dire ce que je souhaite savoir?",
"C'est une assez grosse somme. Et tes informations ne valent peut-être pas autant...",
"J'ai échangé quelques mots avec un marin de l'équipage de ce gars et il m'a dit qu'ils se dirigeaient vers Conceicao.\nIls doivent y conclure des affaires avec le chef des contrebandiers, un gars qui s'appelle Camilo Machado.",
"Parfait! Laisse-moi passer maintenant, je suis pressé.",
"Je vais vérifier cette information. Si elle se révèle infondée, je reviendrai et je serai moins poli. C'est bien clair?",
"Qu'est-ce que tu veux dire?",
"Je vais être clair. Tu veux vivre? Tu me comprends maintenant?",
"Je n'ai pas autant d'argent!",
"D'accord, alors donne-moi tout ce que tu as et dis-moi ce que tu sais.",
"Je n'y crois pas, tu, tu... tu ME menaces?",
"Ca me semble la meilleure chose à faire. Maintenant, donne-moi ton argent et dis-moi tout ce que tu sais.",
"Je n'y crois pas. Ils avaient raison de dire que tu n'as pas de coeur. Voilà, prends-le. C'est tout ce que j'ai.",
"Eh bien, ce n'est pas grand-chose. J'espère que ton information sur l'endroit où se rendait a plus de valeur. ",
"Raoul Rheims",
"D'accord, d'accord, calme-toi. Je vais tout te dire tout de suite.",
"Dépêche-toi!",
"Ah, espèce de salaud! Tu vas me lécher les bottes!",
"Tu ne penses pas que ça va un peu trop loin?",
"...",
"...",

};