string DLG_TEXT[50] = {
"Laisse-nous.",
"",
"Pas si vite, ",
"! Tu n'espères pas nous éviter, quand même?",
"Je n'ai pas vraiment envie de te parler.",
"Alors, ne traîne pas. Je suis pressé.",
"Je crois que tu ne vas pas bouger d'ici. Maintenant, donne-nous la lettre que tu portes.",
"On pourrait peut-être juste boire une chope de bière et s'en aller? Non?",
"Qu'est-ce que tu veux de moi?!",
"Dis-moi où est ta planque et ta mort sera rapide.",
"Qu'est-ce que tu veux de moi, espèce de salaud?",
"Nous sommes là pour te libérer.",
"Qu'est-ce que tu veux de moi, espèce de salaud?",
"Nous sommes là pour te libérer.",
"Nous nous rapprochons de la colonie. Pour le moment, rien ne prouve que tu es digne de foi. Voyons si tu te tiens bien.",
"Comme tu veux.",
"Tu disais donc vrai. Tu connais vraiment bien notre confrérie. Je ne sais toujours pas quand et comment tu nous as rejoints, mais pour le moment ça n'a aucune importance. Le rituel va bientôt commencer. On doit aller à la grotte. Je suis sûr que tu accepteras de nous escorter, moi et plusieurs indigènes, jusqu'au temple.",
"Bien sûr, dis-moi juste où vous allez.",
"Dans une petite île, près d'ici. C'est là que se trouve le temple.",
"C'est tout ce que je voulais savoir. L'heure est venue pour toi de mourir.",
"Quoi?! Alors, tu es...",
"... Pas la personne à qui tu penses! En garde, frère.",
"Dans ce cas, une fois que nous aurons débarqué, j'espère te voir à la taverne.",
"Bien.",
"C'est trop gentil. Et qu'est-ce qui me vaut un tel honneur?",
"Je n'ai pas le temps de t'expliquer. Ils risquent de découvrir à tout moment que tes papiers sont des faux.",
"Et alors? Eh bien, je t'autorise à m'escorter jusqu'à la colonie espagnole. Nous déciderons ensuite de ton sort.",
"Comme tu veux.",
"Tu n'arriveras pas à m'intimider! Je n'ai pas peur de mourir!",
"Mmh... En effet...",
"Qu'est-ce que la mort pour moi! Elle me libérera et me permettra d'aller m'asseoir auprès de mon maître!",
"D'accord, tu n'as donc pas peur de la mort. Et qu'est-ce que tu dirais de devoir vivre dans cette cellule?",
"...",
"Cette cellule est peut-être trop confortable pour toi. Tu préférerais peut-être quelque chose de plus humide et de plus sombre.",
"...",
"On pourrait peut-être recouvrir le sol d'eau froide et tu ne pourrais alors pas te reposer...",
"C'est bon! Je vais tout te dire. Que veux-tu savoir?",
"Où est ta planque.",
"Près de la colonie espagnole. Sur... kof... kof... no-o-o-on.",
"Quoi? No-o-on!",
"Arrête de faire l'imbécile! Je vais compter jusqu'à trois. Donne-nous la lettre, sinon! Un...",
"Trois!",
"Tu détiens une lettre qui nous intéresse! Nous avons besoin de la lire\nNe t'inquiète pas, nous avons une copie du cachet avec lequel elle a été scellée. Je te promets que le client n'y verra que du feu\nRends-nous ce service et nous te paierons 1 000 pièces d'or. Qu'en dis-tu?",
"Qu'est-ce que j'en dis? Hmm, comment te le dire...? NON! Et va te mettre ton cachet là où je pense!",
"Mmh... 1 000 pièces d'or... C'est tentant. C'est entendu. Voilà la lettre.",
"Tu es un homme avisé, ",
". Voilà ton argent. Voyons maintenant la lettre\nMmh-mmh, oui... C'est bien ce que je pensais... Bon, ils ont tort de ce côté-là... J'ai appris tout ce que je voulais savoir. Maintenant... scellons la lettre... Tu vois, le cachet est identique. Tu peux y aller.",
"D'accord.",
"Alors, nous serons obligés de te tuer.",
"Essaie un peu!",

};