string DLG_TEXT[27] = {
"Tu devrais le savoir, ça fait longtemps que je n'ai pas fait ce genre de chose.",
"J'espère que ça n'affecte pas ta capacité à te battre.",
"Ce serait plutôt l'inverse. J'attends ça avec impatience.",
"Eh bien, ne sois pas trop impatient de sortir ta lame, c'est déjà assez risqué comme ça.",
"C'est beaucoup trop calme ici. Des ennuis nous attendent.",
"Pour l'ennemi peut-être... pour nous, le silence est un allié.",
"Et si nous sommes capturés, capitaine?",
"Ils nous pendront je suppose. Ou nous décapiteront. Ou nous feront brûler...",
"Pitié.... Et qu'allons-nous faire maintenant, capitaine?",
"Tu vois le bâtiment de guerre français qui est amarré là?",
"Oui, je l'ai vu. Un bateau redoutable.",
"Nous allons le capturer.",
"Tu plaisantes, ",
"? Et comment proposes-tu de t'y prendre? On ne pourra même pas l'approcher : une seule salve de ces canons et nous sommes morts.",
"Ah, mais l'équipage du bateau a obtenu un congé et il est maintenant à terre, occupé à manger et à boire. Les seuls membres d'équipage restés à bord sont les hommes de quart.",
"Je vois! Nous pouvons nous glisser à bord, prendre le bateau et rejoindre la flotte anglaise. Oh, nous aurons certainement droit à une récompense et aux honneurs. Tu seras un héros, mon petit gars.",
"Eh bien, ce n'est pas exactement le plan que j'avais prévu. À mon avis, on a peu de chances de pouvoir prendre la mer avec lui. Nous sommes trop peu nombreux pour manœuvrer un bateau de cette taille.",
"Alors, qu'est-ce qu'on va faire?",
"La cale du bateau est chargée de poudre. On va le faire sauter!",
"Oh, mon Dieu! Et si on saute avec lui? Et même si ce n'est pas le cas, une explosion à bord de cette bête réveillera toute la ville!",
"Si tu as peur, tu peux rester ici.",
"Oh non, je viens avec toi! Je ne suis pas un lâche!",
"Allons-y, alors.",
"À ta disposition, capitaine.",
"Alors, on est prêt à y aller?",
"Oui, nous t'accompagnerons.",
"Bien, allons-y, alors.",

}; 