string DLG_TEXT[36] = {
"C'est toi qui cherches ",
"Camilo Machado",
"?",
"Oui. Je voudrais lui parler.",
"Vraiment? Tu devrais savoir que ",
"Camilo Machado",
" n'est pas un gars à qui on peut facilement parler.",
"Merci du conseil, mais à moins que ce ne soit toi qui prennes ses rendez-vous, je m'en vais.",
"Disons que je suis un associé de ",
"Camilo Machado",
" et si tu veux un rendez-vous avec lui, tu vas devoir me parler.",
"Eh bien, la conversation que je veux avoir avec lui ne t'est pas destinée. Conduis-moi à ton patron ou écarte-toi de mon chemin. Je n'ai pas besoin de ton aide pour le trouver.",
"Dans ce cas, j'ai une idée - conduis-moi à ton patron ou je te troue la panse.",
"Je peux te conduire à lui, mais tu dois me donner ton épée et ton pistolet.",
"Tu crois que t'es un dur? Un simple claquement de doigts et il ne restera rien de toi!",
"J'irai avec mes armes ou je n'irai pas du tout, et je trouverai ",
"Camilo Machado",
" sans ton aide.",
"Une fois que je t'aurai tiré dans le foie, tu n'en auras plus que pour quelques heures à peine et tu mourras dans d'atroces souffrances.",
"Tu veux parler à ",
"Camilo Machado",
" ou pas? Donne-moi tes armes ou nous devrons en venir aux mains!",
"Si tu me tires dessus, tu mourras aussi... Je pense que tu bluffes.",
"J'ai dit tout ce que j'avais à dire. Conduis-moi à ",
"Camilo Machado",
", ou je le trouverai moi-même.",
"Alors, conduis-moi à ",
"Camilo Machado",
", ou tu auras affaire à mon épée.",
"Allons-y, mais je te préviens que ",
"Camilo Machado",
" n'aimera pas ça.",
"Calme-toi, je vais te conduire à ",
"Camilo Machado",
", et tu te débrouilleras.",
"À la bonne heure. Passe devant.",

};
