string DLG_TEXT[29] = {
"Je peux me joindre à toi?",
"Es-tu ",
"?",
"... Oui. Qu'est-ce que je peux faire pour toi?",
"Counterspy",
" ne pourra pas venir à la taverne.",
"Quoi? Pourquoi? Qui es-tu?",
"Je m'appelle ",
". J'ai un message de ",
"Counterspy",
".",
" Ça ne faisait pas partie du plan. Il a changé l'accord? Je vais ordonner immédiatement son arrestation!",
"Non, attends, nous avons eu des problèmes. Nous avons dû changer le lieu de rendez-vous.",
"C'est épouvantable. Ça pourrait être un piège! Pourquoi me suis-je trouvé mêlé à ses affaires?",
"On dirait que tu perds ton sang-froid.",
"Non! Oh, non! S'il te plaît, donne-moi le message que ",
"Counterspy",
" t'a laissé pour moi?",
"Il est prêt et t'attend derrière la taverne, près du mur de la ville.",
"Pourquoi n'est-il pas venu jusqu'ici?",
"Il y a des soldats français partout.",
"Je vois... Donc, je suppose que tu veux m'aider à sortir de la ville.",
"Oui. Le plus tôt sera le mieux.",
"Eh bien, qu'est-ce qu'on attend? Allons-y.",
"Allons-y, allons-y.",
"Cours jusqu'au bateau! Dépêche-toi!",
"On est mal partis!",
"Allons au bateau et prenons la mer aussi vite que possible. Si le vent est avec nous, personne ne devrait pouvoir nous rattraper!",
"Si seulement j'avais autant d'assurance que toi.",

};