string DLG_TEXT[93] = {
"Bonjour, ",
", désolée mais je suis pressée. Je ne peux pas te parler.",
"Excuse-moi, ce ne sera pas long. Tu n'aurais pas un frère qui s'appelle Marc?",
"Mais... attends! J'ai des nouvelles de ton frère.",
"Bonjour, ",
", je voulais que tu saches qu'",
"Orable Caron",
"Orable Caron",
" ne t'ennuiera plus.",
"D'accord, tu peux y aller. Je ne vais pas te retarder plus longtemps.",
"Qu'y a-t-il de si urgent?",
"Attends! Je veux t'aider. D'après ce que j'ai compris, tu as un problème.",
"Je n'ai pas beaucoup de temps. Mon père, ",
"Milon Blacque",
"Milon Blacque",
", est souffrant. Je ne peux pas le laisser seul longtemps.",
"Ah, c'est le vieil homme qui vit près de l'embarcadère?",
"De quoi souffre-t-il?",
"J'espère qu'il se rétablira. Au revoir.",
"Désolée, ",
", mais il faut vraiment que j'y aille.",
"Sacrée tête de mule! Très bien, file!",
"Oui, c'est mon père.",
"On m'a dit qu'il n'avait pas toute sa tête. C'est vrai?",
"Je suis désolé pour ton père. On dit qu'il est fou et j'ai tendance à le croire.",
"Il ne m'a pas paru malade.",
"Si mon père t'intéresse autant, demande à ceux qui répandent les ragots.",
"Désolé. Je ne voulais pas te vexer.",
"Au revoir, ",
". Comme je te l'ai dit, je suis pressée et il faut que je m'en aille.",
"Alors, vas-y. Vas-y avant qu'il ne mette le feu à la maison ou qu'il ne se mette à manger du sable! Les fous sont incapables s'occuper d'eux-mêmes!",
"Tu entendras sûrement parler de cette histoire un jour ou l'autre. Maintenant, excuse-moi, il faut que j'y aille.",
"Et je ne voudrais pas te retarder.",
"Qui n'en a pas, des problèmes, ",
"?",
"Enfin, tu vois ce que je veux dire.",
"Tu as raison. Tout le monde a des problèmes, je suppose. ",
"Turpin Cabanel",
" s'est trompé sur ton compte.",
"Ne m'oblige pas à t'en parler, ",
".",
"Je vois bien que tu n'as pas envie d'en parler. Au revoir.",
"Tout ce que je veux, c'est t'aider. Fais-moi confiance.",
"Non, je ne vois pas de quoi tu veux parler.",
"Alors, au revoir.",
"Turpin Cabanel",
"? Oh! C'est quelqu'un de bien.",
"Alors, il avait raison? Tu as des ennuis, oui ou non?",
"Je ne peux pas en parler, ",
".",
"Je vois bien que tu ne veux pas en parler. Au revoir.",
"Tout ce que je veux, c'est t'aider. Fais-moi confiance.",
"M'aider? Je ne vois pas pourquoi tu aiderais une pauvre fille qui n'a même pas de quoi pour s'acheter à manger...",
"Raconte-moi ce qui t'est arrivé.",
"Ah, c'est ça, ton problème? L'argent? Tiens, prends ça. Ça devrait t'aider pendant quelque temps.",
"Tout va bien, ",
".",
"Eh bien, si tu ne veux rien me dire... au revoir.",
"C'est un bleu que tu as sur le visage? Quelqu'un t'a battue?",
"Oh, laisse-moi tranquille, je dois déjà supporter ",
"Orable Caron",
"Orable Caron",
", alors si tu viens me tourmenter avec avec tes questions...",
"Bien, je ne dis plus rien.",
"Orable Caron",
"Orable Caron",
"? Je vais lui en toucher deux mots.",
"Oh, je t'en prie, laisse! Je ne veux faire de mal à personne.",
"Ne t'en fais pas, je ne ferai de mal à personne. Je lui dirai juste quelques mots.",
"Oh, ",
", merci de tout mon coeur! Comment te remercier?",
"Ne t'en fais pas pour ça. Ça me fait plaisir de te rendre service.",
"Merci, ",
".",
"De rien. Au revoir.",
"J'avais un frère. Il est mort, il y a 5 ans...",
"Hum... C'est bizarre... S'il est mort, comment a-t-il pu me remettre une lettre?",
"Une lettre? De Marc? Il est vivant? Où est-il?",
"Eh, eh, du calme. J'ai donné la lettre à ton père. Il a eu l'air très content d'apprendre que son fils était vivant et en bonne santé.",
"Où est-il? Pourquoi n'a-t-il pas écrit depuis tout ce temps? Pourquoi n'est-il pas venu jusqu'ici?",
"J'ai donné la lettre à ton fou de père et si tu veux savoir comment va ton frère, le mieux serait que tu rentres chez toi et que tu la lises.",
"C'est une longue histoire. Je croyais que tu étais pressée?",
"Non, ça peut attendre. Dis-moi comment va mon frère.",
"Quand il est parti il y a 5 ans, il a été enlevé par un pirate et il n'a réussi à s'échapper que récemment. Il vit à Redmond et économise pour pouvoir rentrer. Il pense à ton père et à toi. Tu t'en rendras compte par toi-même en lisant sa lettre, celle que j'ai donnée à ton père.",
"Merci, ",
", tu as raison. Je file à la maison. Tu ne peux pas t'imaginer à quel point je te suis reconnaissante. Tu as rendu l'espoir à mon père.",
"Au revoir.",
"Oui, je t'écoute, j'espère que ce n'est pas une plaisanterie.",
"Non. Ton frère discute tranquillement avec ton père au port en ce moment-même...",
"Quelque chose me dit que tu te moques de moi et que ce n'est qu'une blague cruelle!",
"Tu me prends vraiment pour un mufle! Tu devrais peut-être y aller et te rendre compte par toi-même avant de faire ce genre de remarque. Au revoir.",
"Oh, mon dieu! Marc est de retour après toutes ces années?!",
"Oui, il est de retour. Va t'en rendre compte par toi-même.",

};