string DLG_TEXT[158] = {
", ",
". Je m'appelle ",
". Comment t'appelles-tu?",
"Bonjour, ",
"! Je suis ",
". Puis-je te demander comment tu t'appelles?",
"Oui, oui, ",
". Alors, qu'est-ce que tu veux? Je suis ",
".",
"Je suis ",
", le capitaine du navire '",
"'.",
"Je m'appelle ",
".",
"Tu peux m'appeler capitaine ",
".",
"Rebonjour, capitaine ",
".",
"Ah, c'est encore toi, ",
". De quoi allons-nous parler?",
"Je n'en crois pas mes yeux! Le capitaine ",
" en personne!",
"Bienvenue, capitaine ",
".",
"Ah, c'est encore toi, ",
". De quoi allons-nous parler?",
"Je n'en crois pas mes yeux! Le capitaine ",
" en personne!",
"Quelles sont les dernières nouvelles?",
"Ce qui m'intéresse, ce sont les rumeurs du coin.",
"De quoi parlent les gens en ville?",
"Pourrais-tu m'aider à trouver un endroit, s'il te plaît?",
"Je suis un peu perdu dans les rues de cette ville...",
"Je cherche mon chemin...",
"Sais-tu où se trouve Nathaniel?",
"J'aimerais que tu me parles d'un homme en particulier...",
"Je m'intéresse à un citoyen en particulier. Pourrais-tu me renseigner?",
"Je suppose que tu connais tout le monde ici, non? J'aurais quelques questions à te poser.",
"Parle-moi de ta colonie.",
"Que sais-tu sur Greenford?",
"J'aimerais avoir des renseignements sur Greenford.",
"Eh bien, rien. Bonne chance!",
"Tu as besoin de moi, capitaine?",
"Ravi de te rencontrer, ",
".",
"C'est un plaisir de te rencontrer pour moi aussi, capitaine ",
". En quoi puis-je t'être utile?",
"Parle-moi des rumeurs ; je pourrai peut-être transformer certaines nouvelles en or.",
"Que s'est-il passé ici dernièrement?",
"Je voudrais connaître les dernières rumeurs.",
"J'ai besoin d'indications.",
"Je cherche mon chemin...",
"Je ne connais pas cette ville. J'aurais besoin d'indications.",
"Sais-tu où se trouve Nathaniel?",
"J'aimerais que tu me parles d'un homme en particulier...",
"Je m'intéresse à un citoyen en particulier. Pourrais-tu me renseigner?",
"Je suppose que tu connais tout le monde ici, non? J'aurais quelques questions à te poser.",
"Parle-moi de cette colonie.",
"Que sais-tu sur Greenford?",
"J'aimerais avoir des renseignements sur cet endroit.",
"Pardon de t'avoir dérangé. Au revoir.",
"Je vois... J'aurais une autre question.",
"Merci du renseignement. Adieu.",
"Je serai ravi de discuter à nouveau avec toi, ",
". Dis-le-moi.",
"Oui, ",
"?",
"J'écoute.",
"Je voudrais connaître les dernières rumeurs.",
"Que s'est-il passé ici dernièrement?",
"Je voudrais connaître les dernières rumeurs.",
"Je suis perdu. J'aurais besoin d'indications.",
"Je suis perdu. J'aurais besoin d'indications.",
"Je cherche mon chemin...",
"Je ne connais pas cette ville. J'aurais besoin d'indications.",
"J'aimerais que tu me parles d'un homme en particulier...",
"Je m'intéresse à un citoyen en particulier. Pourrais-tu me renseigner?",
"Parle-moi de cette colonie.",
"Que sais-tu sur Greenford?",
"J'aimerais avoir des renseignements sur cet endroit.",
"Pardon de t'avoir dérangé. Au revoir.",
"À qui pensais-tu, ",
"?",
"De qui veux-tu parler, capitaine?",
"Dis-moi de qui il s'agit, ",
", je connais peut-être cette personne.",
"Je voudrais en savoir plus sur le gouverneur.",
"Je m'intéresse à ",
"Simon Hanpool",
"Simon Hanpool",
"l'aubergiste.",
"J'aimerais en savoir plus sur le propriétaire du chantier naval, ",
"David Fairweather",
"David Fairweather",
".",
"Que sais-tu sur le marchand ",
"John  Filbert",
"John  Filbert",
"?",
"Désolé, j'ai changé d'avis, oublie tout ça.",
"Je vois. J'ai une question.",
"Merci, au revoir.",
"Je vois. J'ai une question.",
"Merci, au revoir.",
"Puis-je savoir où tu veux aller, ",
"?",
"Difficile de se perdre dans cette ville, capitaine. Où veux-tu aller?",
"Je serais ravi de t'aider, ",
".",
"Puis-je savoir où tu veux aller, ",
"?",
"Difficile de se perdre dans cette ville, capitaine. Où veux-tu aller?",
"Je serais ravi de t'aider, ",
".",
"Comment puis-je me rendre à la taverne?",
"Où est le chantier naval?",
"Où puis-je vendre ma cargaison?",
"En partant du port, passe la porte de la ville et tourne à droite. La taverne se trouve dans la ruelle. Tu ne peux pas la manquer. Il y a une grande et belle enseigne juste devant.",
"Merci.",
"Et où se trouve le chantier naval?",
"Où puis-je vendre mes excellentes marchandises?",
"En partant du port, passe la porte de la ville et tourne à gauche. Le bureau du chantier naval se trouve en bas de la ruelle.",
"Je vois. Et comment puis-je me rendre à la taverne?",
"Où puis-je vendre ma cargaison?",
"Merci de ton aide. C'est tout ce que je voulais savoir.",
"En partant du port, passe la porte de la ville et continue tout droit jusqu'à ce que tu voies l'enseigne du commerçant.",
"Où se trouve le chantier naval?",
"Comment puis-je me rendre à la taverne?",
"Merci. C'est tout ce que je voulais savoir.",
"Eh bien, je ne sais pas... De quoi veux-tu que je te parle?",
"Que veux-tu savoir, exactement, capitaine?",
"Que veux-tu savoir, ",
"?",
"Je voudrais connaître l'histoire de la colonie...",
"À part la ville, qu'y a-t-il sur cette île?",
"Que veux-tu savoir sur le fort?",
"Parlons d'autre chose.",
"Ah, ça t'intéresse? Tu es quelqu'un de bien. En général, les gens se moquent de ce genre de choses. Je ne suis pas un expert, mais je vais te dire ce que je sais. Cette colonie a été fondée il y a environ 40 ans. L'île est relativement petite, mais ses terres sont fertiles et elle abrite plusieurs baies idéales pour embarquer et pêcher.\nAvec l'apparition des nouvelles colonies, le commerce et notre ville se sont considérablement développés.",
"Continue...",
"Bien. Parlons d'autre chose.",
"Ah oui. Le fort. Eh bien, il n'y a pas si longtemps, la ville était souvent en proie aux saccages et aux pillages des flibustiers et des pirates. Le fort a été construit pour la protéger. Maintenant, nous sommes beaucoup plus en sécurité.",
"Je vois. Bon, et si on changeait de sujet...",
"L'île est assez prospère. Les marchandises et l'eau ne manquent pas et les récoltes sont excellentes. Ceci dit, l'épaisse jungle qui entoure la ville freine notre développement. Nous manquons de main-d'œuvre pour défricher...",
"Très bien, parle-moi d'autre chose.",
"Cette île n'a rien d'exceptionnel. Toutes les îles se ressemblent dans ces eaux.",
"Je vois. Continue...",
"Il y a la jungle, les rochers... quelques plages désertes ça et là. C'est tout. En revanche, l'intérieur donne des récoltes abondantes. Et on y trouve une grande variété de plantes.",
"Je vois. Continue...",
"Je vois. Bon, et si on changeait de sujet.",
"Ça ne m'intéresse pas vraiment.",
"Bon, dommage. Parle-moi d'autre chose.",
"Dans ces eaux, les forts sont un mal nécessaire. Bien que celui-ci soit assez petit, c'est une merveille ; il est très bien conçu et très résistant. Ses architectes doivent en être fiers. Il abrite une garnison de 800 soldats.",
"Je vois. Continue...",
"Je ne devrais pas parler autant. Le commandant métriperait s'il découvrait que je t'ai parlé du fort, à cause du secret militaire. Parlons d'autre chose.",
"D'accord...",
"Je vois. Bon, changeons de sujet.",
"Je ne sais rien sur lui, je regrette ",
"Eh bien, merci, ",

};