string DLG_TEXT[71] = {
"Dehors!",
"Je m'en vais, pas la peine de crier!",
"Qu'est-ce que tu fais chez moi?! Dehors!",
"Tu vas d'abord me répondre! Où est ",
"Teodoro Fernandez",
"?",
"On te tient! Ça faisait longtemps qu'on t'avait à l'oeil. On sait que tu espionnes pour le compte du capitaine du port! Tu ne sortiras pas d'ici vivant!",
"Si tu le dis!",
"Qu'est-ce que tu fais ici?",
"C'est quelqu'un de la taverne qui m'a envoyé ici.",
"Je ne connais pas de ",
"Teodoro Fernandez",
"! Sors d'ici! Sur-le-champ!",
"Eh, pourquoi est-ce que vous tremblez tous? Vous ne me cachez rien, n'est-ce pas?!",
"Dehors ou je...",
"Ou quoi? Laisse-moi deviner : tu appelles les gardes? Eh bien, désolé de te décevoir, mais eux aussi cherchent  ",
"Teodoro Fernandez",
".",
"Qu'est-ce que tu veux?",
"Je veux juste savoir ce qui est arrivé à l'homme qui est venu ici il y a dix minutes.",
"Il est sorti par la porte de derrière. Tu ne pourras sûrement pas le rattraper.",
"Alors tu peux peut-être me dire ce qu'il voulait?",
"Laisse-moi tranquille! Je t'ai dit ce que je savais!",
"Je vois. Voyons... Qu'est-ce qu'il y a sur ces papiers que tu caches derrière ton dos?",
"Ça ne te regarde pas! C'est juste une lettre de... euh, de ma nièce!",
"Montre-la-moi, je vais te la lire à voix haute!",
"Comment oses-tu! Mais pour qui te prends-tu?!",
"Je suis ",
", mon propre capitaine et je n'ai pas l'habitude de recevoir des ordres, et si tu ne me donnes pas cette lettre sur-le-champ, je vais te remuer les tripes avec ma lame.",
"Un pirate?!",
"Dans le mille! Alors, je compte jusqu'à trois. Un...",
"Prends-la, sale type, mais ne me fais pas de mal!",
"Ah, voyons... Une nièce, tu disais?",
"Fiche-moi la paix!",
"Pas si vite. Je vois que tu achètes des marchandises de contrebande ici. Tu es sur la pente glissante de la perdition.",
"Ce que je fais ne te regarde pas!",
"Ne t'énerve pas. Tu ne vas pas rester en liberté bien longtemps. Ces documents devraient sacrément intéresser les autorités.",
"Ah, ",
"Andre Juliao",
"!",
"C'est ça, c'était lui.",
"En fait, il ne s'est pas présenté.",
"Sors tout de suite!",
"Qu'est-ce qui ne va pas?",
"Tout de suite, j'ai dit! Avant que je n'appelle les gardes!",
"Comme tu voudras.",
"Essaie et tu le regretteras!",
"Jamais, hé-hé.... Bon, passons aux choses sérieuses.",
"On aurait dû, il y a un bon moment.",
"Alors, tu as besoin d'une marchandise spéciale, capitaine?",
"Oui.",
"Puis-je savoir pourquoi?",
"Eh bien... Je ne sais pas encore, mais l'acheter ne peut pas faire de mal, pas vrai?",
"On m'a demandé de l'acheter.",
"Qui ça?",
"Tu crois vraiment que je vais te donner le nom de mon employeur?",
"D'accord, je te crois. Mais, il va falloir payer... Argh... J'oublie toujours ces chiffres.",
"Hmph!",
"Oh, ne t'en fais pas, je l'ai là. Il faut juste que je jette un coup d'oeil à mes papiers.",
"Laisse-moi regarder aussi.",
"Eh! Qu'est-ce que tu fais?!",
"Mets ces papiers sur la table et écarte-toi, sinon...",
"Quoi?! Qui es-tu?!",
"Je suis ",
", capitaine d'un vaisseau pirate, rien que ça. Laisse-moi t'expliquer les choses simplement. Si tu ne me donnes pas ces papiers sur-le-champ, je vais devoir recourir à des méthodes moins civilisées.",
"Un pirate?! Oh non!",
"Exact, tu sais ce qu'on raconte, hein? Parfait. Alors, sois gentil et fais ce qu'on te dit.",
"Prends les papiers mais ne me fais pas de mal!",
"C'est mieux. Hum, je vois que tu as non seulement un problème avec les chiffres, mais qu'en plus, tu as tout écrit, y compris les noms...",
"Tu vas le regretter!",
"Je crois que c'est toi qui vas avoir quelque chose à regretter quand j'aurai montré ces papiers aux autorités.",

};