string DLG_TEXT[32] = {
"Excuse-moi, ",
".",
"Bien sûr.",
"Désolé, mais je suis occupé. Laissez-moi finir mon repas et tu pourras me poser tes questions.",
"...",
"Qu'est-ce que vous voulez, jeunes gens?",
"Es-tu ",
"?",
"Alors, de quoi allons-nous parler? Qui est-ce?!",
"Qui?! Où?!",
"Kof-kof... Cette ordure a fini par m'avoir.",
"Le gouverneur Silehard?",
"Et sa bande de brutes.",
"Je t'en prie, reste allongé, ne t'essouffle pas inutilement. Tes blessures sont trop graves... Je doute que tu arrives jusqu'au navire.",
"Je sais, jeune fille, je sais. Kof, kof... Sais-tu pourquoi ",
"Robert christopher Silehard",
" a voulu me tuer?",
"Oui, à cause du trésor inca.",
"Oui. Il le cherche depuis qu'il en a entendu parler. Je t'en supplie, emporte-le... sous son nez. Cela vengera ma mort... Kof.",
"Oui et je m'occuperai aussi du gouverneur. Tu peux en être sûr. Dès que j'ai appris l'existence du trésor, il a envoyé ses tueurs à mes trousses.",
"Non. Ne le tue pas, ma fille. Il est trop puissant et trop bien gardé. Et il est bien plus important que tu gardes le trésor.",
"Pourquoi?",
"Ce trésor est encore plus important qu'il n'y paraît. Les informations détenues par ",
"Robert Christopher Silehard",
" sont incomplètes. Je n'ai découvert cela que récemment, mais il y en a beaucoup d'autres.\nLors de ma quête initiale du trésor, j'ai découvert une légende expliquant comment trouver ces objets.\nHélas, c'était une transcription incomplète de la bibliothèque de l'église d'Isla Muelle.\nJe suis sûr que tu peux y trouver une version complète. Une dernière chose : \ncherche l'idole Khirucatceliti, car elle ouvre la porte...",
"Au revoir. Repose en paix.",
"Oui? Mais qui êtes-vous et que me voulez-vous?",
"Détends-toi, nous voulons juste te parler ",
"À voir vos têtes, la conversation ne s'annonce guère agréable, mais je suppose que je n'ai pas le choix.\nAllons parler chez moi, en dehors de la ville.",
"Inutile d'essayer de nous échapper!",
"Aucun risque.",
"D'accord, allons-y.",

};