string DLG_TEXT[47] = {       
"Tu ne vois pas que je suis en service! Ne me dérange pas.",
"D'accord, d'accord.",
"Tu voulais signaler un crime?",
"Non. Je suis capitaine... Mais je vois bien que tu ne m'écoutes pas.",
"Attention : il est interdit de se battre dans les rues. Sauf en cas de légitime défense, bien sûr.",
"D'accord, je prends bonne note de cette information.",
"Quel climat insupportable... Et il faut que je reste planté là! Tu ne vas pas me croire, mais mon seul passe-temps, c'est de chasser les mouches qui essaient de se poser sur mon visage.",
"Désolé pour toi, mais je n'y peux rien. C'est ton travail.",
"Si tu as envie de discuter, trouve quelqu'un d'autre. Moi, je suis en service et je n'ai pas le droit de te parler.",
"Je me demandais si tu étais mort ou vivant. Tu es aussi raide qu'une statue.",
"Si tu crois que c'est facile de protéger notre ville! Eh bien, pas du tout! C'est un travail très important et dangereux. Je me souviens d'une fois où...",
"Tu me raconteras ça une autre fois. Je dois m'en aller.",
"Va-t'en. Tu me déranges.",
"Comme tu voudras, soldat.",
"Eh! Tu ne voudrais pas aller me chercher un godet de rhum à la taverne?",
"Je ne sais pas. Je risque d'être pendu pour avoir fait boire un soldat pendant son service. Non, attends la relève et tu pourras boire autant que tu voudras.",
"Pourquoi faut-il que ce soit un marin comme toi qui vienne me parler?! N'y a-t-il donc pas de jolies femmes dans cette ville?",
"Et tu appelles ça être en service? Écoute, tu ne voudrais pas voir t'échapper de dangereux criminels comme moi, n'est-ce pas? Ha ha!",
"Tu as l'air bien portant. Tu devrais t'enrôler dans notre armée. À la caserne, on a de la place, on mange bien et le rhum est gratuit.",
"Intéressant, mais c'est impossible. La discipline militaire, ce n'est pas pour moi.",
"Cette chaleur... Je donnerais n'importe quoi pour rentrer chez moi, en Angleterre.",
"Oui, ce climat n'a pas l'air de te convenir.",
"Où vas-tu? Reviens!",
"Calme-toi, soldat. Je dois parler à notre gouverneur.",
"De quoi?",
"D'une affaire très importante. Je dois informer le gouverneur que les Français ont pris Oxbay! Puis-je passer maintenant?",
"Sacrée nouvelle! Mais tu vas devoir attendre son Excellence jusqu'à demain matin! Tu peux prendre une chambre à la taverne.",
"C'est très ennuyeux...",
"Sacrée nouvelle! Il fallait le dire plus tôt! Vas-y, entre.",
"C'est mieux!",
"Que veux-tu?",
"Toi... hic... sale chien! Tu as blessé mon... hic... mon ami!",
"Quel ami? Il n'y a que toi ici, ",
".",
"Quoi? Il était là... il y a une minute. Je vais le chercher. Toi... hic... attends-moi ici!",
"Comment oses-tu me contredire? Je vais t'étrangler!",
"Excuse-moi, mais les ordres sont formels : le gouverneur ne reçoit aucun visiteur.",
"Pourquoi?",
"Son Excellence nous a donné des ordres, ",
".",
"Mais tu vas devoir faire une exception. Je dois annoncer une nouvelle très importante au gouverneur. Voici la lettre qui explique tout.",
"Bien sûr. Tu peux entrer. Seul.",
"Mille diables! Bien sûr. Messieurs, attendez-moi à bord du navire. Je reviens tout de suite.",
"D'accord, voyons ça.... Eh bien, apparemment, tu as un sauf-conduit du gouverneur.",
"Alors, je peux entrer?",
"Oui. J'espère que tu es seul. Sinon, tes amis devront s'arrêter ici.",
"Ne t'en fais pas, je suis seul.",

};