string DLG_TEXT[52] = {
"Hum, quel est ton problème, ",
"? Qui veut ta peau?",
"Quoi?",
"Bonjour. Qui es-tu?",
"Je suis ",
". Et j'ai besoin de ton aide.",
"Désolé, je me suis trompé.",
"Alors, tu as encore besoin de mon aide?",
"C'est ça, la vie de pirate...",
"Dieu merci, non. Ce genre d'aide est bien trop cher.",
"Qui t'es-tu mis à dos, cette fois-ci?",
"L'Angleterre.",
"L'Espagne.",
"Le Portugal.",
"Les Pays-Bas.",
"La France.",
"J'ai changé d'avis.",
"Alors, avec qui dois-tu faire la paix, cette fois-ci? Les Espagnols? Les Français? Les Anglais?",
"J'ai peur de ne pas comprendre.",
"Oh, je croyais que tu étais l'un de mes clients. Mes services pourraient peut-être t'intéresser?",
"Je ne sais pas. Qu'est-ce que tu proposes? Je ne vois pas de marchandises.",
"Ce n'est pas de marchandises qu'il s'agit. J'aide les gens à résoudre leurs problèmes. Tu vois, la plupart de ceux qui vivent ici sont loin de mener une vie honnête et ils ont besoin d'aide de temps à autre.",
"Quel genre d'aide?",
"Eh bien... Imaginons qu'au cours de tes voyages, tu te sois emparé des marchandises de quelques bons gros navires marchands. Avant que tu aies le temps de dire ouf, toute la flotte espagnole est à tes trousses et la vie commence à se compliquer. Si tu viens me voir, je peux t'aider à renouer des relations avec les Espagnols.\nÉvidemment, ce service n'est pas facile à obtenir, et ce genre d'arrangement peut coûter très cher. Mais il te permet ensuite de te rendre dans les ports et villes espagnols et d'y reprendre tes activités.",
"Qu'est-ce qui me garantit que mes 'relations' seraient renouées?",
"Aucune garantie. Mais n'hésite pas à te renseigner auprès de ceux qui ont déjà fait appel à mes services. Je n'escroque pas mes clients.",
"D'accord, j'aimerais utiliser tes services.",
"Ça te coûtera ",
" pièces d'or.",
"Marché conclu.",
"C'est trop.",
"Ça te coûtera ",
" pièces d'or.",
"Marché conclu.",
"Trop cher pour moi. Au revoir!",
"D'accord. Ça te coûtera ",
" pièces d'or.",
"Marché conclu.",
"Trop cher.",
"Ça te coûtera ",
" pièces d'or.",
"Marché conclu.",
"Trop cher.",
"Ça te coûtera ",
" pièces d'or.",
"Marché conclu.",
"Trop cher.",
"Désolé, tu n'as pas assez d'or. Pas de marché.",
"Argh! Je reviendrai peut-être quand j'aurai davantage à t'offrir.",
"Tu peux faire voile sur-le-champ. Tout sera réglé au plus vite.",
"Merci. Fais attention à toi.",
"Ce n'est pas tout.",

};