string DLG_TEXT[125] = {
"J'ai bien peur d'être trop occupé pour pouvoir te parler en ce moment, l'ami. Je viens d'avoir une nouvelle idée et elle m'accapare totalement.",
"Voilà qui a l'air prometteur. Essaie juste de ne pas tous nous faire sauter.",
"À l'aide! À l'aide!",
"Tiens bon, j'essaye justement de t'aider!",
"À l'aide! À l'aide!",
"Non merci. Il est hors de question que je risque ma vie pour toi.",
"Oh, merci! Merci mille fois, ",
". Si tu n'étais pas intervenu, ces dégénérés m'auraient mis en pièces!",
"De rien.",
"Excuse-moi, l'ami, mais l'expérience sur laquelle je travaille requiert toute mon attention et je dois te quitter.\nNe le prends pas mal, surtout. Des gens très sympathiques m'ont rejoint chez moi et je suis sûr que tu prendras plaisir à discuter avec eux.",
"Bien. Cela m'intéresse de faire la connaissance de tes invités.",
"Heureux de te voir. Où est ",
"Danielle",
"?",
"Mmh... je croyais qu'elle était déjà arrivée...",
"Oh, non! Que t'est-il arrivé, ",
"? Tu n'es pas toi-même. Regarde tes vêtements... et ces bleus... et tu es trempé de partout!",
"Laisse-moi reprendre mon souffle et apporte-moi un peu de vin, je meurs de soif.",
"Voilà.",
"C'est ça? S'il s'agit d'un yacht, alors, moi, je suis le roi de France! Ce rafiot n'est qu'un bateau de pêche!",
"C'est tout ce que je peux faire pour toi, ",
". Et ne me crie pas dessus, s'il te plaît.",
"Pardon. Je suppose que je n'ai pas le choix, il va falloir que je parte à la recherche de ",
"Danielle",
" à bord de ce rafiot.",
"Voici ton vin. Et maintenant, dis-moi ce qui s'est passé...",
"C'est une longue histoire. Est-ce que ",
"Danielle",
" est là? Je ne vois pas son bateau.",
"Non, elle n'est pas encore arrivée.",
"Crénom! Cette fille a vraiment la bougeotte! Et moi qui ai perdu mon bateau. Tu parles d'une déveine!",
"Mmh... je possède un petit yacht. Cela pourrait peut-être t'aider?",
"Un yacht? Pourquoi ne pas l'avoir dit plus tôt, espèce de vieux renard?",
"Eh bien, il est plutôt petit, et...",
"Montre-le moi.",
"Non, elle n'est pas encore arrivée.",
"Crénom! Cette fille a vraiment la bougeotte! Il faut que je la retrouve.",
"De quoi parles-tu? Je te dois la vie, me diras-tu ton nom?",
"Je m'appelle ",
" et je suis capitaine.",
"Quelle chance! J'ai justement réalisé quelques inventions pouvant être installées sur un bateau.\nOh, mais pourquoi parlons-nous ici? Je te suis tellement reconnaissant de m'avoir sauvé que j'insiste pour que tu viennes chez moi. Je tiens absolument à te remercier. Allons, viens!",
"Très bien, allons chez toi. Mais je te préviens, on ne touche pas à mon bateau!",
"Il faut retourner au bateau. Je crains fort que la destruction du temple ne déclenche un tremblement de terre, ou pire. Les Incas étaient passés maîtres dans l'art de concevoir des pièges extrêmement complexes.",
"Un piège pouvant provoquer un tremblement de terre? Voilà qui me paraît très exagéré.",
"Oui, bon, d'accord. Admettons qu'il n'y aura pas de tremblement de terre, mais les inscriptions des murs du temple mentionnent une terrible vengeance qui fera disparaître les profanateurs de la surface de la terre.",
"Dans ce cas, filons!",
"Plus vite, capitaine! Aucun trésor, si fabuleux soit-il, ne mérite qu'on meure pour lui!",
"Du calme, nous allons lever l'ancre.",
"Oui, je crois que c'est une bonne idée...",
"Elle aurait au moins pu attendre d'avoir la réponse.",
"Suivons son exemple, ",
". Je prends à droite et tu vas tout droit, capitaine. Si ça te convient, bien sûr.",
"Ça revient au même, de toute façon. Essaie juste de ne pas te perdre.",
"J'en doute. Le texte dit que le piège se trouve à côté de l'entrée de la niche du Dieu Soleil. On dirait que c'est là que débute le labyrinthe.",
"Le labyrinthe?",
"Oui. Je ne t'en avais pas parlé? Il faut le traverser pour accéder au trésor. J'imagine qu'un seul de ces passages y conduit.",
"J'ai l'impression que le concepteur de ce temple avait un curieux humour...",
"Méfiance à l'intérieur du temple. Le texte révèle l'existence d'un piège à côté de l'entrée de la niche du Dieu Soleil.\nIl n'y a hélas aucune indication permettant de le désamorcer, mais les instructions nécessaires se trouvent apparemment à l'intérieur du temple.",
"Merci de l'avertissement. Tu as fini ta traduction?",
"Oui, mais les feuilles sont trempées et toutes froissées. Je n'ai pas réussi à tout déchiffrer. Il y avait un passage concernant la niche et un dieu endormi, mais je ne pense pas qu'il faille y prêter attention. Il doit s'agir d'une légende locale.",
"Malédiction! Où est le trésor?",
"J'imagine que l'entrée de la salle au trésor, ou plutôt du tombeau, se trouve dans la niche.",
"Alors, vas-y.",
"Attends! On ne peut entrer dans le temple que quand il est baigné par la lumière du soleil. C'est à cause d'un mécanisme complexe que je ne comprends pas trop...",
"Vraiment? Dans ce cas, attendons le soleil... et espérons que la saison des pluies n'a pas décidé de commencer en avance.",
"Si ma mémoire est bonne, nous allions au temple.",
"Ah, oui! C'est exact.",
"Oh, capitaine ",
"! Que fais-tu ici? Tu as été jeté en prison, toi aussi?",
"Non, mon ami. Je suis là pour te libérer.",
"Me libérer? Et comment? Je ne vois pas comment tu pourrais persuader le gardien de me laisser sortir sans ordre du gouverneur.",
"Je me suis déjà chargé de le convaincre, ",
".",
"C'est vrai? Dans ce cas, tu es vraiment quelqu'un d'extraordinaire, capitaine. Mais pourquoi avoir décidé de m'aider, d'un seul coup?",
"Pour être honnête, j'aurai une faveur à te demander en retour.",
"Mmh... cela ne me dérange pas, capitaine, mais peut-être pourrions-nous poursuivre cette conversation dans un endroit plus confortable?",
"Bien sûr. Allons au phare et je t'expliquerai tout en chemin.",
"... Stupide et téméraire! Je n'arrive pas à croire que les gens puissent faire ça...",
"Chacun a sa propre conception de l'amusement.",
"Alors, tu voudrais que je te traduise ce texte et tu t'intéresses tout particulièrement au passage expliquant comment pénétrer à l'intérieur du temple, c'est bien ça?",
"Oui. Tu dis connaître la langue indigène.",
"Oui, oui. J'ai passé beaucoup de temps à étudier ces peuples. Mais je te préviens, ",
", si tu pars à la recherche de ce temple, je t'accompagne!",
"Pour quelle raison?",
"Je sais pourquoi tu y vas, toi. Mais je te rassure tout de suite, cela ne m'intéresse pas. Je veux juste voir ce qu'il y a là-bas... et peut-être faire une découverte hors du commun!",
"Mmh... les voyages en mer sont souvent désagréables pour qui n'y est pas habitué...",
"C'est proprement ridicule! Écoute, ",
", si tu ne m'emmènes pas avec toi, je jure de ne pas traduire un mot de ce texte!",
"Dans ce cas, c'est réglé. Tu viens avec nous.",
"Excellent! Je t'en suis reconnaissant. Quant à la traduction, j'ai besoin de temps. Je pense qu'elle me demandera quelques jours, car le dialecte employé est assez inhabituel.",
"De notre côté, nous allons réparer le bateau et le préparer pour le voyage.",
"Ah, c'est toi, capitaine! La traduction est presque terminée. Plus qu'une semaine et c'est bon.",
"Nous ne pouvons pas nous permettre d'attendre si longtemps. Si tu poursuivais la traduction à bord du bateau?",
"C'est une bonne idée. Est-ce que le fait d'être à bord me donnera des migraines? Je ne pense pas... je ne crois pas non plus être sujet au mal de mer...  d'accord, faisons comme ça. Mais, dis-moi, pourquoi tant de précipitation?",
"J'imagine que tu n'es pas au courant de la bataille qui a eu lieu dans la rade, alors, je devrais peut-être t'expliquer...",
"Une bataille? Quelle bataille? Et dans quelle rade?",
"Le gouverneur Silehard n'a pas l'intention de nous faire cadeau de la colonie. Pire, je le soupçonne de vouloir nous pendre haut et court à la première occasion.",
"Nous pendre? Je vois. Très bien, je continuerai mon travail pendant le voyage. Je dois d'ailleurs dire que nous avons de la chance de partir maintenant, car j'ai déjà appris que l'on ne peut s'engager que deux fois l'an dans la baie de Khael Roa.",
"Pourquoi est-il impossible d'approcher de l'île le reste de l'année?",
"Selon le texte, cela est dû à un phénomène naturel affectant les marées.",
"C'est probablement pour cela que ",
"Raoul Rheims",
" n'a pas réussi à accéder au temple.",
"Peut-être. Mais d'autres périls sont également mentionnés, des dangers qui attendent quiconque chercherait à pénétrer au cœur du temple du Dieu Soleil.",
"Poursuis ta lecture. Tu as encore quelques jours pour terminer ta traduction. Allons au bateau.",
"Au fait, capitaine, j'aurai besoin d'une cabine privée, et j'aimerais qu'elle se trouve à l'arrière du bateau, afin de ne pas être dérangé par les cris de l'équipage.",
"Mmh... très bien, tu l'auras.",
"Pas d'impatience, mes amis. Nous nous trouvons au seuil de l'entrée secrète du tombeau. Elle doit être quelque part par ici...",
"Crois-tu qu'il serait bon de sonder les murs?",
"Inutile. Ces motifs muraux devraient nous dire comment trouver le tombeau et éviter les pièges éventuels.",
"Tous les dangers se trouvent-ils derrière nous, désormais?",
"J'en doute fort, car ceux qui ont construit ce temple ont tout fait pour le protéger et je suis persuadé que de nombreux périls nous attendent encore.\nBah, nous le verrons bien assez tôt. Laisse-moi réfléchir un petit instant...",
"S'il te plaît, oui.",
"Oh, non! N'y touche pas!",
"Pourquoi?",
"C'est un piège! Oh, non! Tu as déjà touché la pierre!",
"Oh, non! Dis-moi ce qui s'est passé?",
"Ce piège était le dernier conçu par les bâtisseurs du temple. Pourquoi n'as-tu pas attendu? J'aurais pu découvrir comment l'éviter en lisant les inscriptions, mais, non! Il faut toujours que tu touches à tout!",
"S'il s'agit d'un piège, pourquoi sommes-nous encore en vie?",
"Ce qui est sûr, c'est que ça ne durera pas si nous restons là! Ce piège ouvre un conduit permettant à l'eau du lac de s'engouffrer dans les cavernes situées sous le temple.\nLa chambre du volcan est toujours active. Tu imagines ce qui va se passer quand toute cette eau va entrer en contact avec la lave?",
"Mmh... est-ce que... tu penses qu'on pourrait avoir un peu chaud si on reste ici?",
"Un peu chaud? Le temple entier va exploser, oui! Il faut fuir!",
"Et le trésor?",
"Oublie-le! Ce qu'il faut, c'est filer d'ici!",
"N'y a-t-il pas moyen de...",

};