string DLG_TEXT[28] = {
"Halte! Que faites-vous ici?",
"Qu'est-ce qui se passe, ici?",
"Demande au lieutenant!",
"Je vois ça.",
"Quel lieutenant?",
"Ouvre les yeux! Le lieutenant est là-bas. Va lui parler!",
"Porc!",
"Bonjour. Vous ne pouvez pas vous imaginer comme je suis content de vous voir tous!",
"Qui es-tu?",
"Je suis ",
". Mais c'est sans importance. Je vous attendais, messieurs.",
"Pourquoi?",
"Le gouverneur a pensé que des visiteurs arriveraient au phare après la capture du vieil homme.\nAprès avoir passé bien trop de temps sur ce rocher, je suis fier que l'honneur d'attraper notre proie me revienne!",
"Qu'est-ce qui s'est passé avec ",
"Researcher",
" ",
"Researcher",
"?",
"Qui?",
"Le vieil homme. Celui qui vivait au phare.",
"Ah. Il a été emmené à la prison du coin. Une fois qu'on en aura fini avec lui ici, il sera envoyé à Redmond où le gouverneur l'interrogera plus avant.",
"Ordure!",
"Ne t'en fais pas. J'ai l'impression que tu pourras bientôt parler avec le vieil homme.",
"À combien évalues-tu ta vie?",
"Pourquoi me demandes-tu ça?",
"Parce qu'il faut vraiment qu'on y aille et si tu résistes...",
"Va brûler en enfer!",
"Tu manques de manières! Au revoir!",

};