string DLG_TEXT[49] = {
"On m'a dit que tu voulais me voir. Alors, de quoi veux-tu me parler?",
"J'aimerais te proposer mes services.",
"Tu es capitaine? Quel est ton nom?",
"Je m'appelle ",
", capitaine du '",
"'.",
"Bien, je me souviendrai de ton nom. Maintenant, dis-moi ce qui t'a amené à moi.",
"J'aimerais parler affaires avec toi.",
"Rien. Je vais m'en aller, si tu le permets.",
"Tu peux partir. Mais ne disparais pas... J'aurai peut-être des projets pour toi.",
"À ta guise, mijnheer.",
"Je suis tout ouïe. Qu'est-ce qui t'a amené à moi?",
"Des affaires, mijnheer.",
"Je m'en vais.",
"Alors parlons affaires.",
"Je suis ici au nom des femmes qui se tiennent devant ta porte.",
"Ta mission est une réussite. Les enfants perdus ont été rendus à leurs parents",
"Je veux parler d'un homme qui trouve grâce à tes yeux.",
"Tu as accompli ta mission, mijnheer.",
"Je n'ai rien à te dire pour le moment, mijnheer",
"Oui, je le sais déjà. Voici ta récompense. J'espère qu'à l'avenir, je pourrai refaire appel à tes services.",
"Quand tu voudras, mijnheer",
"Alors, de qui veux-tu parler.",
"D'un boucanier, ",
"Bernardo Gamboa",
", mijnheer.",
"Ah. Lui?! Et que veux-tu que j'en dise? D'après ce que je sais, sa réputation est irréprochable...",
"Tu as tort. J'ai entendu dire qu'il avait enlevé une fille dans ta ville.",
"Ah, ah, ah. Tu en es sûr? Je ne veux pas l'accuser à tort.",
"Si tu n'y vois pas d'inconvénient, je vais faire une enquête discrète. Personne ne saura que tu es impliqué. S'il n'a pas enlevé cette fille, ta relation avec lui restera intacte. Dans le cas contraire, tu pourras montrer à tout le monde à quel point tu es juste et puissant.",
"Hum... Ta proposition me paraît raisonnable. C'est vrai : je ne risque rien. Tu découvriras peut-être ce qui s'est passé. Si tu mènes à bien cette mission, je te récompenserai. Mais puisque tu agis en ton nom, ce ne sera qu'une modeste somme.",
"Merci, mijnheer.",
"Te souviens-tu de notre discussion?",
"Nous parlions d'une fille qui avait été enlevée.",
"Ah, oui, je m'en souviens. D'après ce que je sais, elle a bel et bien été enlevée.",
"Oui. L'ordure n'a pas voulu rendre la fille et a été massacré par ses propres hommes.",
"Eh bien, plus de pirate - plus de problème. Voilà ta récompense. Tu peux te retirer, maintenant...",
"Tes désirs sont des ordres.",
"Ah, c'est de cela que tu voulais me parler...",
"Je ne comprends pas pourquoi tu ne prends pas cette affaire plus au sérieux. C'est bien à toi d'assurer la sécurité des habitants de la colonie?",
"Capitaine, je fermerai les yeux sur cette critique. Mais ne recommence pas si tu veux jouir de mes bonnes grâces\nQuant à ces femmes... Je vois que tu es un homme intelligent, alors laisse-moi te dire quelque chose.",
"Je t'écoute.",
"Deux soldats ont été retrouvés morts aujourd'hui. L'un d'eux avait un morceau de tissu noir dans la main\nPlusieurs heures avant la découverte de leurs corps, une frégate a été vue s'éloignant de l'île toutes voiles dehors.",
"Et c'est là que s'arrête ton enquête?",
"Eh bien... Il est évident que les enfants enlevés ont été emmenés hors de l'île. Vu les circonstances, leur recherche ne vaut pas l'argent dépensé pour une telle expédition\nEn plus, ils peuvent être n'importe où. Tu devrais comprendre ça, capitaine. La mer offre bien des cachettes\nQuoi qu'il en soit, si la peine de ces femmes te touche tant, je te propose de relever le défi et de retrouver leurs enfants\nJe te promets que si tes recherches sont fructueuses, je saurai me montrer reconaissant.",
"D'accord, j'accepte, mais je voudrais d'abord savoir où trouver un témoin qui a vu la frégate.",
"Non, je n'ai pas de temps à perdre à de telles bêtises.",
"Tu acceptes? Parfait! Tu trouveras le témoin à la taverne. C'est le capitaine d'un navire marchand qui a aperçu ce bateau.",
"Merci. Puis-je prendre congé?",

};