string DLG_TEXT[93] = {
	"Aaah. Capitaine ",
	" servant sur le fameux ",
	". ",
	"Je suis très impressionné par tes dernières aventures. Le Black Pearl, les Incas, ce n'est pas rien.",
	"Merci gouverneur. Mais je suis venu te demander du travail.",
	"Capitaine, nous avons à travailler sur des affaires délicates.",
	"Je suis à ton service.",
	"J'ai besoin d'un capitaine fiable.",
	"Je n'ai rien pour toi pour le moment.",
	"Au revoir.",
	"Que cherchez-vous au juste ?",
	"Je viens faire le point sur les objets incas que vous m'avez demandés.",
	"J'ai réuni les seize objets incas que vous vouliez.",
	"Je viens reprendre vos instructions pour cette affaire.",
	"J'ai reconstitué la statue complète.",
	"Je voulais savoir si cette affaire était bien terminée.",
	"J'ai besoin d'un capitaine discret, capable de suivre des consignes simples sans attirer toute la mer dans son sillage.",
	"Cela ressemble à une proposition de travail.",
	"Mouais. Une autre fois, peut-être.",
	"Quelques antiquités incas circulent encore dans l'archipel. Je souhaite les réunir pour ma collection, et peut-être pour une exposition plus tard. Considérez cela comme un premier test de votre sérieux.",
	"Je vous écoute. Qu'attendez-vous précisément de moi ?",
	"Rapportez-moi un exemplaire de chacun des seize objets indiens courants, du premier au seizième. Rien de plus, rien de moins. Revenez quand la série sera complète et vous serez payé.",
	"Très bien. Je réunirai la série complète.",
	"Vous n'avez pas encore complété la série. Il me faut toujours un exemplaire de chacun des seize objets indiens courants. Ne vous pressez pas inutilement, mais ne revenez qu'une fois la collection complète.",
	"Je poursuis mes recherches.",
	"Voilà enfin une série complète. Ces pièces comptent davantage que leur apparence ne le laisse croire.",
	"Vous semblez leur accorder beaucoup d'importance pour de simples curiosités.",
	"Elles auraient appartenu autrefois à une tradition fort ancienne. Une secte inca, ou quelque chose d'approchant. Les Fils de l'Ombre d'Inty.",
	"Vous en parlez pourtant comme un homme qui a déjà suivi cette piste.",
	"Peut-être ai-je seulement mieux lu que d'autres. Prenez votre récompense. À présent, l'affaire devient plus délicate : votre premier contact vous attend sur la Côte éloignée d'Isla Muelle, et vous ne devez parler qu'aux Anglais.",
	"Je retiens la destination, et surtout la consigne.",
	"Enfin... oui, enfin. Vous ignorez à quel point cette statue est remarquable.",
	"Vous la connaissez donc mieux que vous ne le laissiez entendre.",
	"Disons plutôt que j'en ai lu davantage que la plupart des hommes de gouvernement. L'érudition prend parfois des formes que les marins jugent excessives.",
	"Vous paraissiez pourtant presque ému en la voyant.",
	"N'y voyez rien de plus. Vous m'avez bien servi, capitaine. Je saurai me souvenir de votre efficacité, et des affaires plus importantes pourraient bientôt requérir un homme de votre trempe.",
	"Je suppose que ce ne sera pas votre dernière demande.",
	"Notre affaire est close pour l'heure. Si j'ai de nouveau besoin d'un capitaine discret, vous serez parmi les premiers avertis.",
	"Je saurai me tenir prêt.",
	"La Côte éloignée d'Isla Muelle. Votre homme y est anglais, et lui seul doit vous intéresser.",
	"Havre radieux, à Conceicao. Même principe : cherchez l'Anglais et ne vous égarez pas auprès du Portugais.",
	"À Douwesen, la plage aux palmiers vous attend. Cette fois, les Hollandais ne devraient pas compliquer les choses autant que les Ibériques.",
	"Le dernier morceau a quitté le circuit de mes contacts. Cherchez dans la jungle de Douwesen un signe ancien qui devrait vous guider.",
	"Vous avez l'indice. Il ne vous reste qu'à fouiller l'endroit indiqué dans la jungle de Douwesen pour récupérer la tête.",
	"Je poursuis.",
	"Je vous ai déjà dit qu'il n'y avait rien pour vous ici, capitaine. La plage est calme, et je tiens à ce qu'elle le reste.",
	"Je vois que j'ai assez attiré l'attention pour aujourd'hui.",
	"Vous semblez chercher quelqu'un, capitaine. Cette plage n'accueille pas souvent d'étrangers de votre genre.",
	"Je me renseignais, rien de plus.",
	"Alors renseignez-vous ailleurs. Les rencontres ici sont déjà assez étranges sans que vous y ajoutiez votre curiosité.",
	"Message reçu.",
	"Pas ici. Certainement pas sous les yeux de cet Espagnol. Si vous venez bien de Redmond, nous parlerons comme des hommes prudents.",
	"Je croyais pourtant que vous étiez entre amis.",
	"Naturellement. Une affaire de relations diplomatiques. Mais certaines relations gagnent à rester très discrètes.",
	"Je reviendrai donc quand vous jugerez le sable plus sûr.",
	"Mieux. Voici ce que vous êtes venu chercher : les pieds seulement. Le reste a pris d'autres chemins, et je ne suis payé ni pour poser des questions ni pour garder une statue entière.",
	"Tout cela pour un vieux morceau de pierre ?",
	"On m'a appris à ne pas discuter ce que mon supérieur juge précieux. Portez cela à Conceicao. À Havre radieux, cherchez encore un Anglais, surtout pas le Portugais.",
	"Je commence à comprendre votre manie.",
	"Vous regardez encore beaucoup autour de vous, capitaine. Si vous attendiez quelqu'un, il a sûrement préféré remettre cela à plus tard.",
	"Vous avez peut-être raison.",
	"Vous regardez beaucoup autour de vous, capitaine. Vous attendez quelqu'un ?",
	"À vrai dire, je cherchais surtout un peu de calme.",
	"Alors vous avez choisi une bien mauvaise plage. Ici, le calme a tendance à changer de propriétaire quand les étrangers posent trop de questions.",
	"Je vais vous laisser votre tranquillité.",
	"Ne me dites pas un mot ici. Le Portugais croit servir un échange de courtoisie entre gens civilisés, et je préférerais ne pas troubler cette illusion.",
	"Et ce n'est pas le cas ?",
	"Disons que la courtoisie change parfois de forme selon les besoins de la Couronne. Revenez me voir sans attirer davantage d'oreilles.",
	"Je saurai être plus discret.",
	"Bien. Prenez ceci. Le corps de la statue. J'en suis volontiers délivré, car cette pierre attire trop d'intérêts pour une simple antiquité.",
	"Vous avez tous le même talent pour parler beaucoup sans rien expliquer.",
	"C'est ce qui nous garde en vie. Les bras vous attendent à Douwesen, à la plage aux palmiers. Cette fois, les Hollandais seront moins nerveux que nous.",
	"Alors cap sur Douwesen.",
	"Ah. Vous êtes celui de Redmond. Oui, je vois très bien. Ici, nous faisons moins semblant qu'à Isla Muelle ou Conceicao.",
	"Pour une fois, quelqu'un parle clairement.",
	"N'allez pas vous emballer. L'Anglais vous attend et tient toujours à ses petites précautions. Inutile de jouer au plus malin, allez donc le voir directement.",
	"J'y vais.",
	"Voici les bras. Pour la tête, c'est une autre histoire. Elle n'est plus entre les mains du réseau.",
	"Ne me dites pas qu'elle a disparu.",
	"Pas disparue. Cachée, ou enterrée. Un signe ancien dans la jungle de Douwesen devrait vous mener au bon endroit. À partir d'ici, vous n'aurez plus besoin de nous.",
	"C'est bien ce qui m'inquiète le plus.",
	"Nous n'avons rien à nous dire.",
	"Très bien.",
	"Vous avez encore un homme à voir sur la Côte éloignée d'Isla Muelle. Cherchez l'Anglais, lui seul, et gardez-vous de vous faire remarquer par l'Espagnol.",
	"Je n'oublie ni le lieu ni la consigne.",
	"Votre prochain contact se trouve à Havre radieux, à Conceicao. Même méthode : cherchez l'Anglais et ne vous égarez pas auprès du Portugais.",
	"Conceicao, l'Anglais, pas le Portugais. C'est noté.",
	"Les bras doivent vous attendre à Douwesen, sur la plage aux palmiers. Les Hollandais ne sont pas l'obstacle cette fois ; trouvez simplement l'Anglais.",
	"Cap sur Douwesen, et droit vers le bon homme.",
	"La tête n'est plus entre les mains de mes contacts. Cherchez dans la jungle de Douwesen un signe ancien ; il doit vous mener à l'endroit.",
	"Je vais fouiller la jungle jusqu'à trouver cette marque.",
	"Alors vous avez trouvé l'indice. Ne perdez plus de temps : fouillez l'endroit qu'il désigne et rapportez-moi la tête.",
	"Je vais terminer cela."
};