string DLG_TEXT[306] = {
"Présente-toi, s'il te plaît. Je ne crois pas te connaître.",
"Je m'appelle ",
", et je suis le capitaine du ",
".",
"Capitaine ",
". J'espère que tu vas bien. Et que me vaut l'honneur de ta visite?",
"Bonjour, ",
", bonjour. Quel est l'objet de ta visite?",
"J'écoute, capitaine ",
". C'est à quel sujet?",
"Je dois parler affaires.",
"J'espérais que tu aurais du travail pour un capitaine compétent.",
"Je ne faisais que passer. Au revoir ",
"Eh bien, capitaine ",
", je vois à ton air que tu as quelque chose à me dire.",
"Je suis au regret d'annoncer que la colonie d'Oxbay a été attaquée.",
"As-tu ramené le prisonnier? Où est-il? Je veux le voir.",
"Désolé, j'ai une mauvaise nouvelle. Le prisonnier s'est échappé avant que j'arrive à Oxbay.",
"Mmh... Tu as toute mon attention, capitaine.",
"On en parlera plus tard.",
"J'arrive à l'instant d'Oxbay.",
"Tu as mené ta mission à bien.",
"Hélas, je n'ai rien pour toi pour le moment. Mais n'hésite pas à revenir me voir plus tard.",
"Je dois discuter affaires.",
"Gouverneur, j'aimerais m'entretenir de quelque chose avec toi.",
"Très bien, capitaine ",
", mais avant de t'entretenir avec moi, réfléchis bien aux sujets que tu vas aborder.",
"As-tu du travail pour un capitaine compétent?",
"Je ne faisais que passer. Au revoir",
"Hahahaha, ne sois pas si modeste, capitaine. Tu veux peut-être dire que ce sont eux qui ont commencé!",
"Eh bien, en fait, c'est le cas.",
"Peu importe, je suis ravi de te remettre cette récompense pour avoir combattu les pirates.",
"Merci. Il faut qu'on parle de quelque chose.",
"Merci. Puis-je te demander si tu as du travail pour un capitaine compétent?",
"Je te suis reconnaissant ",
", pour cette récompense. Hélas, je dois partir. Au revoir.",
"Mmh, troublante nouvelle.... Mais comment peut-il y avoir des pirates dans ces eaux? \nLa flottille commandée par le capitaine Tomlison m'a assuré avoir capturé ou coulé tous ces scélérats!",
"C'est bien ça. Il n'y avait pas de pirates, mais des troupes et des navires français.",
"Quoi?! Je le savais. Son honneur, Carl, aurait dû donner un coup de semonce depuis bien longtemps\nDis-moi tout. Comment as-tu réussi à filer? Combien y avait-t-il de navires, de canons et d'hommes? D'où venaient-ils? \nTu es sûr que ces navires appartenaient à la flotte française?",
"Certain. J'ai immédiatement remarqué leurs pavillons français.",
"C'est terrible, terrible! Des soldats français sur le sol anglais et presque pas d'or dans les caisses pour mener une guerre ouverte. Comment allons-nous protéger nos foyers? \nJe crains, ",
", que cela ne t'affecte, toi et ton navire.",
"Moi? Comment ça?",
"On parlait de la flottille française.",
"Mmh. Je n'aime pas beaucoup ça. Je préfère partir.",
"Eh bien, capitaine, au terme de la campagne contre les pirates, il ne reste plus que deux navires de guerre, deux navires qu'on doit épargner. Aussi, je donne l'ordre de réquisitionner et d'armer des navires privés chaque fois que la défense de nos terres l'exige\nDésolé, capitaine, mais ton navire tombe sous le coup de cet ordre.",
"Quoi? Il est hors de question que l'on réquisitionne mon navire!",
"Ah, oui... oui.... Alors, quels navires ont été utilisés pour assiéger le fort? Quelles étaient leurs armes? Et combien y avait-il de soldats?",
"J'ai compté cinq navires... Un brick et une goélette avec respectivement 24 et 20 canons... Les autres navires étaient dissimulés par le brouillard.",
"Cher ",
", à mon grand regret, je ne peux pas te laisser partir. Je dois réquisitionner ton navire contre ces envahisseurs.",
"Excuse-moi, je n'ai pas bien compris ce que tu as dit...",
"Si tu refuses, capitaine, je vais devoir te confisquer ton navire\nEssaie de comprendre, je n'ai pas le choix.",
"Eh bien, j'ai autre chose à te proposer : mon navire et moi à ton service.",
"Tu vas me forcer? Vas-y, essaie un peu!",
"Cette information n'est pas d'une grande aide, capitaine. Dommage, car ta situation n'est guère enviable. Je vais quand même te dire quelque chose, ",
".",
"Me dire quelque chose? Intéressant... Je suis tout ouïe ",
"Excellente décision, capitaine ",
". Je suis ravi qu'on ait trouvé un terrain d'entente. Maintenant, au travail. Il me semble qu'au lieu de te fondre dans les rangs de l'armée, tu ferais mieux\nd'agir seul.",
"Qu'est-ce que tu veux dire?",
"Je passe sur ton impolitesse pour cette fois, capitaine. Mais sache qu'il y a une arme chargée sur mon bureau et de nombreux gardes dehors. Bon, continuons...",
" Dans ce cas, j'aimerais commander mon navire moi-même! Permets-moi de le faire pour toi!",
"Comme tu es nouveau dans ces eaux, j'espère que tu pourras obtenir des informations sur les forces françaises\nDepuis la colonie voisine de l'île, tu peux traverser la jungle et franchir l'enceinte de la ville pour interroger ses habitants.\nPeut-être surprendras-tu même des conversations émanant des forces françaises.",
"Tu veux que je me faufile dans la ville capturée pour découvrir le sort que les Français réservent à la colonie?",
"Et combien ça va me rapporter?",
"Oui... C'est audacieux. Si ça marche, on saura peut-être où s'attendre à une nouvelle attaque et, plus important, comment libérer notre colonie.",
"Je comprends. Bonne chance.",
"À propos, tu pourrais m'avancer un peu d'argent avant que mon départ?",
"Si tu as besoin d'argent, capitaine, voici 1 000 pièces d'or. Mais utilise-les afin de préparer le navire pour le départ. N'oublie pas que cette somme viendra en déduction de ta solde finale.",
"Merci.",
"Hélas, capitaine ",
", impossible de te faire une avance. Nos fonds sont réservés à la formation d'une flottille et à la préparation du fort en vue d'une possible campagne.",
"Eh bien!",
"Je te promets, capitaine, que tu seras indemnisé. Mais n'essaie pas de me duper. Si tu manques à ton devoir, \nje crierai haut et fort que tu es un pirate et la flottille du capitaine Tomilson te traquera jusqu'à la fin de tes jours.",
"À condition qu'il en reste quelque chose à l'issue de la bataille avec les Français!",
"Mmh.... Notre conversation a pris mauvaise tournure. N'oublie pas que tu dois en savoir plus sur les intentions des Français à Oxbay\nParle aux gens du coin, va à la taverne, elle doit être intacte et ouverte, car je suis sûr que les Français apprécient de s'y reposer après le combat.\nGlane des informations sur les plans du commandement français\nEt là, crois-moi, je saurai me montrer généreux. Bonne chance, Capitaine.",
"Au revoir.",
"Écoute, ",
", dis-toi que c'est un mal nécessaire. En fait, tu devrais être heureux\nTu as été accepté au service de la Couronne, un poste envié par beaucoup. De plus, je passe pour être généreux avec mes capitaines!",
"J'espère donc pouvoir rapidement profiter de ta générosité.",
"Mmh... Tu es de retour, capitaine, bravo. Au rapport, s'il te plaît.",
"Les habitants d'Oxbay n'apprécient guère leurs nouveaux maîtres.",
"Et as-tu réussi à savoir ce que signifie cette invasion pour les plans à venir des Français?",
"Ils utilisent Oxbay comme tremplin pour attaquer Redmond. La flottille qui mouille près d'Oxbay attend des munitions qui doivent arriver de Falaise de Fleur à bord d'un navire marchand. Lorsque ce sera chose faite, elle prendra la mer pour attaquer Redmond.",
"Cette information est inestimable. Tu as fait du bon travail. Merci pour ce service, ",
". Voici 3 000 pièces d'or en guise de paiement.",
"Merci.",
"Bon, compte tenu de cette nouvelle, ta nouvelle mission consiste à veiller à ce que ces munitions n'arrivent pas à Oxbay. Si nous devons affronter les Français, moins ils auront de poudre, mieux cela vaudra.",
"Tu veux que je coule ce bateau?",
"Fais comme tu l'entends, capitaine. Aborde-le, coule-le... À toi de voir. Mais veille à ce que les Français ne mettent pas la main sur ces munitions.",
"Et son escorte? Mon navire risque de ne pas lui résister.",
"Oui. Il aura certainement une escorte.",
".",
"D'accord. Mais, ",
", on peut peut-être en tirer parti.\nPuisque tu peux te faufiler en territoire ennemi, va à Falaise de Fleur. Avec un peu d'esprit et de judicieuses questions, tu pourras peut-être te charger du navire d'escorte avant qu'il ne mette les voiles...",
"J'en doute... Mais je vais quand même essayer.",
"Bien, ",
", mais n'oublie pas de m'en rendre compte.",
"Nous autres flibustiers, on n'a pas l'habitude de telles formalités...",
"Alors souviens-toi que tant que tu me sers, tu sers la Couronne. Ne l'oublie pas, capitaine.",
"D'accord.",
"Si je comprends bien, tu as réussi à échapper à la flottille française?",
"Eh oui.",
"Après ton départ, j'ai envoyé un autre capitaine à Oxbay. Elle a découvert une vaste grotte sur l'île, près d'une plage déserte\nJ'envisage d'y débarquer un déploiement de soldats pour qu'ils s'y cachent. Après quoi, ils libéreront la ville pendant que nous combinerons une bataille navale et terrestre.",
"Tout à fait réalisable, mais je doute que mon navire puisse accueillir un détachement entier.",
"Ce ne sera pas utile, capitaine. Je me suis déjà occupé de leur acheminement. Ta mission consistera à protéger ce navire. Le sloop 'Albion', commandé par le capitaine ",
"Ewan Glover",
"Ewan Glover",
", est ancré au port. ",
"Ewan Glover",
" t'attendra aux portes de la ville.",
"Je vois. Bon, je suppose qu'il faut que j'y aille...",
"Attends, ce n'est pas tout. Tu dois escorter le sloop 'Albion' jusqu'au port de Greenford, à Oxbay\nUn fidèle de la Couronne te conduira alors à la grotte. Ensuite, tu devras une nouvelle fois infiltrer Oxbay et chercher l'un de nos agents caché en ville.",
"Ça fait beaucoup à retenir. Et qu'est-ce que je dois faire après avoir trouvé l'agent?",
"Il détient de précieuses informations. Tu dois donc veiller à ce qu'il ne lui arrive rien et qu'il puisse nous faire parvenir ces informations.",
"Et comment s'appelle cet agent?",
"Counterspy",
". Il est entré en contact avec des gens du coin. Si tu ne parviens pas à le localiser, demande discrètement autour de toi.",
"Comme tu voudras. Bon, et quand est-ce que je peux espérer être payé pour ma dernière mission?",
"Ne t'inquiète pas, ",
", voilà ton or.",
"Parfait.",
"Allez, tu peux partir, capitaine. J'attends ton prochain rapport avec impatience.",
"Au revoir.",
"Eh bien, capitaine ",
"... Je m'attendais à mieux. Mais ce qui est fait est fait. Au moins, tu as mené à bien une partie de la mission.",
"Mais...",
"Félicitations, capitaine. Tu ne peux pas t'imaginer à quel point je suis soulagé depuis que tu es à mon service.",
"Merci",
"Je n'ai que faire de tes explications, capitaine. J'ai eu vent de ton rapport par ",
"Counterspy",
" et il m'a expliqué ce qui s'était passé. Je trouve dommage que ton échec entraîne de nouvelles morts.",
"Je suis désolé, ",
", j'ai fait de mon mieux.",
"... Eh bien. Ce sont des choses qui arrivent. Je te remercie quand même, car grâce à toi, on a pu reconstituer notre flottille.",
"Et quelle est ma nouvelle mission?",
"Tu vas prendre part à l'assaut d'Oxbay au sein de notre flottille. Il va sans dire que tu dois t'y préparer\nJ'espère que cela te suffira. Au fait, j'ai déduit de cette somme l'équivalent de la perte du navire 'Albion'.",
"On part quand?",
"Bientôt. Pour l'instant, fais ce que tu veux en ville ; le moment venu, tu seras informé. Pense à te détendre et à te reposer. Tous les capitaines méritent une bonne soirée à la taverne après un voyage en mer.",
"On en est loin, mais il y a un fond de vérité dans ce que tu dis.",
"Ça n'a pas d'importance. Mon messager te trouvera. Bonne chance, capitaine.",
"Au revoir.",
"counterspy",
" vient de m'informer de tes exploits. Et ",
"Ewan Glover",
"Ewan Glover",
" a eu l'air très heureux de faire route avec toi.",
"Mmh.... Quels exploits?",
"Ha. Modeste, en plus. Eh bien, voici ta récompense. Je te conseille de faire réparer ton navire. Tu vas bientôt partir.",
"Et de quel type de mission s'agit-il cette fois?",
"Le siège d'Oxbay. Tu vas t'intégrer à la flottille qui s'apprête à libérer l'île.",
"Et quand la flottille doit-elle partir?",
"Bientôt. Pour l'instant, fais ce que tu veux en ville ; le moment venu, tu seras informé. Pense à te détendre et à te reposer. Tous les capitaines méritent une bonne soirée à la taverne après un voyage en mer. Un messager te préviendra.",
"Très bien. Il faut que je m'en aille maintenant.",
"Ah?! Quoi?! Qu'est-ce que tu fais ici?! ",
"? ",
"Danielle",
"?!!",
"Désolé de te réveiller, cher gouverneur, mais j'ai des questions à te poser.",
"Qu'est-ce que tu veux dire? Pars sur-le-champ et j'envisagerai de ne pas te tuer!",
"Visiblement, tu ne comprends pas bien ce qui t'arrives, gouverneur. ",
". Ce n'est plus toi qui donnes les ordres. Et tu vas devoir faire attention sinon, ",
"Danielle",
", tu vas devoir mettre en œuvre tes élégantes techniques d'escrime.",
"D'accord, d'accord, je t'en prie! Du calme. Bien sûr que je vais répondre à tes questions... Mais range ton épée, ",
"Danielle",
", s'il te plaît, raisonne-le! Son attitude me rend nerveux.",
"Tais-toi et écoute. On connait tous ton implication avec le trésor et tu vas devoir en répondre.",
"Je vous en prie, démons diables, ne me faites pas de mal!",
"C'est flatteur, mais pour le moment, dis-nous ce que tu sais sur l'idole qui ouvre la porte du palais.",
"Je ne vous dirai rien, scélérats! Gardes!",
"Oh non!",
"Danielle",
"! Aux navires!",
"En fuite?! Comment est-ce possible?",
"Ils n'ont pas donné d'explication, si ce n'est que la traque du fugitif se poursuit.",
"Bon sang! La situation devient incontrôlable!",
"Excuse-moi, mais j'ai une bonne nouvelle pour toi.",
"Alors, ",
", je n'ai pas toute la journée!",
"J'ai retrouvé la trace de.",
"Raoul Rheims",
"? C'est vrai. C'est plutôt bon signe.",
"Je suis prêt à l'arrêter, si tu le souhaites.",
"Bien sûr, vas-y, ",
". Et capitaine... Cette fois, tu dois le ramener. Et n'oublie pas qu'avant son arrivée, tu ne dois rien divulguer à quiconque. Compris?",
"Oui. Je ferai selon tes souhaits.",
"! Tu en as mis du temps, je commençais à m'inquiéter pour toi!",
"Je vais bien et j'ai accompli la mission que tu m'avais confiée.",
"Pour être honnête, je suis surpris car je ne pensais pas que cette expédition porterait ses fruits\nAlors, tu as réussi à récupérer tous ces objets pour moi, hein?",
"Oui, à l'exception d'une idole qui a été achetée par un inconnu.",
"Une idole? Voyons ce qu'il manque.",
"Tiens, regarde, je t'en prie.",
"C'est vrai, il manque une idole, quel dommage.",
"Tu veux que je la retrouve?",
"Non, ne t'inquiète pas, ",
". Mais j'apprécie ta proposition. En fait, j'ai une autre mission pour toi et je vais confier à quelqu'un d'autre le soin de retrouver l'idole\nOh oui, j'oubliais. Voilà l'argent promis.",
"Merci, et je suis curieux de savoir quelle nouvelle mission tu as pour moi.",
"Oui, eh bien... Quelques minutes avant ton arrivée, ",
", j'ai appris qu'un pirate avait été capturé à Greenford. À mon plus grand agacement, ce pirate a toujours réussi à m'échapper\nJe veux que tu me le ramènes.",
"Ça n'a pas l'air difficile. Je peux y aller?",
"Un moment, ",
". J'apprécie ton enthousiasme, mais ce n'est pas tout.",
"Désolé.",
"Lorsque tu arriveras à Greenford, parle au commandant de la prison,  ",
"Greenford Prison Commendant",
"Greenford Prison Commendant",
"\nMontre-lui cette lettre et il te remettra le prisonnier\nÀ ton retour, tu recevras 5 000 pièces d'or.",
"Compris.",
"J'espère que ton retour signifie que tu as mené à bien ta mission et remis la lettre à son destinataire.",
"Oui. Mais ça n'a pas été facile. Les manières des pirates laissent à désirer. Enfin, rassure-toi, il a eu la lettre.",
"Parfait. J'espère que tu te montreras également à la hauteur de ta nouvelle mission, ",
".",
"Et quelle est cette mission?",
"Du calme, pas de précipitation, ",
". Tout d'abord, laisse-moi te remettre ta récompense.",
"Merci. C'est un plaisir de travailler pour toi.",
"Et tes flatteries sont toujours les bienvenues, ",
". Bon, revenons-en aux choses sérieuses.",
"Je suis tout ouïe.",
"Ta prochaine mission, ",
", revêt un caractère plus personnel pour moi. Compte tenu de mes fonctions, je ne peux pas vraiment recourir aux forces impériales pour des affaires privées et c'est là que tu interviens.",
"Ça m'intrigue. Tant que tu n'attends pas de moi que j'attaque seul la flotte française.",
"Tu as beaucoup d'humour, ",
", mais ne nous écartons pas du sujet.",
"Je suis désolé.",
"Il y a quelques jours, un navire a été capturé par des pirates, '",
"pirate captain 06",
"', a mis le cap sur l'Europe depuis New Light. Alors qu'il croisait au large de notre colonie, les pirates ont frappé\nOutre les marchandises habituelles, il y avait quelques idoles en or à bord ; de rares trésors incas que j'avais commandés pour ma collection\nJ'ai réussi à savoir qui était le pirate responsable. Il s'appelle ",
"Alistair Garcilaso",
"Alistair Garcilaso",
"\nÀ ce qu'on dit, sa bande de bouchers et de voleurs et lui se cacheraient dans la jungle de Douwesen, mais je ne sais pas exactement où\nJ'aimerais, ",
", que tu les retrouves et que tu me rapportes ma collection\nJe sais que ça ne va pas être facile, c'est pourquoi je te propose 10 000 pièces d'or si tu y parviens\nComme je te l'ai dit, je n'aime pas recourir à l'armée pour régler des affaires personnelles. Et en débarquant des troupes à Douwesen... Eh bien, on s'exposerait à un conflit avec les Hollandais\nTu es mon seul espoir.",
"Trouver des hommes qui se cachent n'est pas chose aisée, mais je vais essayer et c'est, en effet, une somme généreuse.",
"Eh bien, si tu y parviens, cela vaudra effectivement la peine, ",
". Alors, sans plus attendre, prends ton argent et bonne chance.",
"Je reviendrai au plus vite.",
"Te revoilà, ",
", mais où est ",
"Raoul Rheims",
"? Je ne le vois pas avec toi.",
"J'ai échoué... J'ai perdu sa trace dans le repaire des contrebandiers.",
"Tu me déçois, ",
". Une mission aussi simple et tu ne l'as pas réussie?! J'avais une plus haute opinion de toi.",
"Je m'excuse sincèrement. Mais si je peux me permettre, j'ai réussi à trouver ce que ",
"Raoul Rheims",
" mijote. Il prépare une expédition.",
"Eh bien, je n'ai pas l'habitude de punir les échecs, notamment lorsque de gros efforts ont été mis en œuvre. Mais j'espère que tu vas te montrer à la hauteur, cette fois.",
"Merci de la confiance que tu me portes. Je vais tout faire pour ne pas te décevoir encore une fois.",
"Parfait, ",
". À propos, voilà les 5 000 pièces d'or promises, même si tu ne les as pas complètement méritées.",
"Merci. Ta générosité me surprend.",
"Assez, ",
". Inutile de me flatter. Parlons affaires, tu veux bien\nTu es donc allé au repaire des pirates\nAlors, maintenant que tu sais où aller, j'aimerais que tu portes cette lettre à leur chef. Il s'appelle ",
"Isenbrandt Jurcksen",
"Isenbrandt Jurcksen",
"\n Bon, avant que tu prennes peur, je suis sûr que tu serais curieux de connaître la nature de mes relations avec ce pauvre diable. Tu dois te rappeler que ce ",
"Raoul Rheims",
" en sait à présent trop pour que je le laisse partir\nSi tu ne parviens pas à l'attraper, ces pirates s'en chargeront. Bon, alors, quand comptes-tu entamer ce voyage?",
"Mon navire est prêt à prendre la mer.",
"Parfait. Alors, vas-y immédiatement. Après avoir accompli ta mission, reviens chercher ta récompense. C'est clair, ",
"?",
"Oui, je fais voile sur-le-champ.",
"Parfait, personne ne nous dérangera.",
"Continue.",
"Tout d'abord, une bonne nouvelle : Oxbay est libérée\nTu as contribué à cette victoire. Merci.",
"Il n'y a pas de quoi. Et tu as peut-être une autre mission à me confier?",
"Bien sûr. Je veux que tu m'amènes l'homme qui nous a trahis et qui a mis en péril notre colonie! Il s'appelle ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Si je peux me permettre, qu'a-t-il fait?",
"Une question! Cela me plaît\nNe te méprends pas. Rheims a vilement trahi la Couronne. De même qu'il a trahi son équipage. Il menait une mission cruciale lorsqu'il est passé à l'ennemi\nAvertis de sa trahison par l'un de ses hommes, nous avons de justesse évité le pire\nHélas, le pauvre était déjà à l'article de la mort et n'a pas pu m'en dire plus sur la destination de Rheims\nOn sait qu'ils se sont arrêtés au campement des pirates pour se ravitailler\n\nTu devrais t'y rendre et si ",
"Raoul Rheims",
", s'y trouve toujours, l'arrêter\nSinon, essaie de glaner le plus d'informations possible.",
"Compris. Mais c'est dangereux d'affronter les pirates et j'espère que le jeu en vaudra la chandelle.",
"Ah ça oui. Je suis prêt à te donner 5,000 pièces d'or maintenant et 5,000 autres lorsque tu auras ramené ce traître.",
"C'est raisonnable. Je m'en occupe.",
"Comment se fait-il que tu sois libre? Qu'est-ce qui s'est passé? Et les gardes?",
"Désolé, mais j'ai été injustement jeté en prison et je n'avais pas l'intention d'y croupir. Après avoir récupéré mon arme, j'ai tout fait pour m'enfuir.",
"Je suis désolé, ",
"! Il y a eu une terrible méprise\nMes soldats devaient arrêter un espion français\nDe toute évidence, ils t'ont pris pour cet espion.",
"Merci de t'excuser. Je ne savais pas si je finirais par retrouver ma liberté.",
"Tu t'es montré brillant, félicitations. Cela t'honore, mais le geôlier devrait être pendu pour t'avoir laissé t'échapper!",
"Je crains fort que ce soit trop tard. Je m'en suis déjà occupé.",
"Le geôlier, c'est ton affaire. Maintenant, j'aimerais que tu m'expliques pourquoi je me suis retrouvé en prison.",
"J'aimerais parler en son nom. Il dit avoir sacrément bien manié les armes. J'ai besoin d'un bon canonnier et, avec ta permission, j'aimerais l'employer.",
"Mmh. Je suppose que je peux me montrer indulgent, ",
", mais ce geôlier est au service de la colonie. Je ne peux pas le laisser partie.",
"Dis-moi ce que ça me coûterait de le remplacer.",
"1 000 pièces d'or devraient suffire.",
"Ça me semble raisonnable. J'accepte",
"Ah! C'est plus que je pensais. Que ce geôlier continue de te servir alors!",
"Disposes-en, mais tu risques de le regretter, il paraît que c'est un ivrogne.",
"J'en prends bonne note. Bon, tu vas peut-être me dire maintenant pourquoi j'ai été arrêté.",
"Tu es trop assoiffé de sang... Mais c'est peut-être nécessaire en ce bas monde... Tu te montres toujours impitoyable.",
"J'espère. Bon, maintenant, tu veux bien me donner les raisons de mon arrestation?",
"Une méprise. Une terrible méprise. Mes soldats devaient arrêter un espion français\nMes agents m'ont affirmé qu'il se trouvait à la taverne\nMais visiblement, il était déjà parti et c'est toi qu'ils ont arrêté.",
"Eh bien, le mystère est élucidé. Tu ne peux pas imaginer ma détresse lorsque je me suis retrouvé dans cette geôle obscure.",
"Une méprise. Une terrible méprise. Mes soldats devaient arrêter un espion\nMes agents m'ont affirmé qu'il se trouvait à la taverne\nMais visiblement, il était déjà parti et c'est toi qu'ils ont arrêté.",
"Eh bien, le mystère est élucidé.",
"Bon, maintenant que ce quiproquo est résolu, j'aimerais que tu me suives dans mon bureau.\n On doit discuter de choses importantes.",
"Bien sûr.",
"Encore une fois, je te prie d'accepter mes excuses pour les agissements de mes soldats\nJe crois que cet argent te prouvera combien je suis désolé pour ce qui s'est passé.",
"Merci. En ce qui me concerne, je te remercie pour ta gentillesse.",

};
