string DLG_TEXT[83] = {
	"Presente-toi, capitaine. Je veux etre certain d'avoir affaire au bon homme.",
	"Je suis ",
	", capitaine du ",
	".",
	"Tres bien. Parle.",
	"Qu'as-tu a me dire au sujet de cette affaire inca ?",
	"Je dois te parler de l'affaire inca.",
	"Je t'ecoute.",
	"Je n'ai rien pour toi pour le moment.",
	"Au revoir.",
	"Vous disiez avoir besoin d'un capitaine discret. De quoi s'agit-il ?",
	"Rappelez-moi ce que vous attendez de moi pour votre affaire inca.",
	"J'ai reuni les seize objets incas que vous vouliez.",
	"Ou en sommes-nous de votre affaire inca ?",
	"J'ai reconstitue la statue complete.",
	"Votre affaire inca est reglee.",
	"J'ai besoin d'un capitaine capable, discret, et moins sot que la moyenne. Quelques objets incas circulent encore dans l'archipel, et je souhaite les reunir.",
	"Voila une demande bien erudite pour un gouverneur.",
	"Je ne suis pas votre antiquaire. Une autre fois, peut-etre.",
	"Un homme d'Etat doit aussi savoir s'interesser a ce qui survivra a son temps. Pour commencer, rapportez-moi un exemplaire de chacun des objets indiens courants, du premier au seizieme.",
	"Un seul exemplaire de chaque objet, de indian1 a indian16. J'ai compris.",
	"Exactement. Revenez quand la serie sera complete. Si vous reussissez, vous verrez que je paie aussi serieusement que je collectionne.",
	"Je m'en charge.",
	"Je veux un exemplaire de chacun des seize objets indiens courants. Un seul de chaque me suffit. Revenez me voir quand la serie complete sera en votre possession.",
	"Tres bien.",
	"Excellent. Ces pieces etaient plus importantes que leur apparence ne le laissait croire.",
	"Vous semblez y tenir beaucoup pour une simple collection.",
	"Disons qu'elles appartenaient autrefois a une tradition fort ancienne. Une secte inca, ou quelque chose d'approchant. Les Fils de l'Ombre d'Inty.",
	"Vous en parlez comme si vous les connaissiez mieux qu'un amateur.",
	"Seulement par des papiers, des fragments et quelques rumeurs. Prenez votre recompense. Votre premier contact vous attend sur la Cote eloignee d'Isla Muelle. Souvenez-vous d'une seule chose : ne parlez qu'aux Anglais.",
	"Je retiendrai surtout la derniere consigne.",
	"La Cote eloignee d'Isla Muelle. Votre homme y est anglais, et lui seul doit vous interesser.",
	"Havre radieux, a Conceicao. Meme principe : cherchez l'Anglais et ne vous egarez pas aupres du Portugais.",
	"A Douwesen, la plage aux palmiers vous attend. Cette fois, les Hollandais ne devraient pas compliquer les choses autant que les Iberiques.",
	"Le dernier morceau a quitte le circuit de mes contacts. Cherchez dans la jungle de Douwesen un signe ancien qui devrait vous guider.",
	"Vous avez l'indice. Il ne vous reste qu'a fouiller l'endroit indique dans la jungle de Douwesen pour recuperer la tete.",
	"Je poursuis.",
	"Enfin... oui, enfin. Vous ignorez a quel point cette statue est remarquable.",
	"Vous la connaissez donc mieux que vous ne le disiez.",
	"Mieux ? Non. Disons que j'en ai lu davantage que la plupart des hommes de gouvernement. L'erudition prend parfois des formes que les marins jugent theatrales.",
	"Vous paraissiez pourtant presque emu.",
	"N'y voyez rien de plus. Vous m'avez bien servi, capitaine. Je saurai me souvenir de votre efficacite. Des affaires plus importantes pourraient bientot requerir un homme de votre trempe.",
	"Je suppose que ce ne sera pas votre derniere demande.",
	"Notre affaire inca est close pour l'heure. Si j'ai besoin de vous de nouveau, vous en serez informe.",
	"Je saurai attendre.",
	"Je vous ai deja dit qu'il n'y avait rien pour vous ici, capitaine. La plage est calme, et je tiens a ce qu'elle le reste.",
	"Je vois que j'ai assez attire l'attention pour aujourd'hui.",
	"Vous semblez chercher quelqu'un, capitaine. Cette plage n'accueille pas souvent d'etrangers de votre genre.",
	"Je me renseignais, rien de plus.",
	"Alors renseignez-vous ailleurs. Les rencontres ici sont deja assez etranges sans que vous y ajoutiez votre curiosite.",
	"Message recu.",
	"Pas ici. Certainement pas sous les yeux de cet Espagnol. Si vous venez bien de Redmond, nous parlerons comme des hommes prudents.",
	"Je croyais pourtant que vous etiez entre amis.",
	"Naturellement. Une affaire de relations diplomatiques. Mais certaines relations gagnent a rester tres discretes.",
	"Je reviendrai donc quand vous jugerez le sable plus sur.",
	"Mieux. Voici ce que vous etes venu chercher : les pieds seulement. Le reste a pris d'autres chemins, et je ne suis paye ni pour poser des questions ni pour garder une statue entiere.",
	"Tout cela pour un vieux morceau de pierre ?",
	"On m'a appris a ne pas discuter ce que mon superieur juge precieux. Portez cela a Conceicao. A Havre radieux, cherchez encore un Anglais, surtout pas le Portugais.",
	"Je commence a comprendre votre manie.",
	"Vous regardez encore beaucoup autour de vous, capitaine. Si vous attendiez quelqu'un, il a surement prefere remettre cela a plus tard.",
	"Vous avez peut-etre raison.",
	"Vous regardez beaucoup autour de vous, capitaine. Vous attendez quelqu'un ?",
	"A vrai dire, je cherchais surtout un peu de calme.",
	"Alors vous avez choisi une bien mauvaise plage. Ici, le calme a tendance a changer de proprietaire quand les etrangers posent trop de questions.",
	"Je vais vous laisser votre tranquillite.",
	"Ne me dites pas un mot ici. Le Portugais croit servir un echange de courtoisie entre gens civilises, et je prefererais ne pas troubler cette illusion.",
	"Et ce n'est pas le cas ?",
	"Disons que la courtoisie change parfois de forme selon les besoins de la Couronne. Revenez me voir sans attirer davantage d'oreilles.",
	"Je saurai etre plus discret.",
	"Bien. Prenez ceci. Le corps de la statue. J'en suis volontiers delivre, car cette pierre attire trop d'interets pour une simple antiquite.",
	"Vous avez tous le meme talent pour parler beaucoup sans rien expliquer.",
	"C'est ce qui nous garde en vie. Les bras vous attendent a Douwesen, a la plage aux palmiers. Cette fois, les Hollandais seront moins nerveux que nous.",
	"Alors cap sur Douwesen.",
	"Ah. Vous etes celui de Redmond. Oui, je vois tres bien. Ici, nous faisons moins semblant qu'a Isla Muelle ou Conceicao.",
	"Pour une fois, quelqu'un parle clairement.",
	"N'allez pas vous emballer. L'Anglais vous attend et tient toujours a ses petites precautions. Inutile de jouer au plus malin, allez donc le voir directement.",
	"J'y vais.",
	"Voici les bras. Pour la tete, c'est une autre histoire. Elle n'est plus entre les mains du reseau.",
	"Ne me dites pas qu'elle a disparu.",
	"Pas disparue. Cachee, ou enterree. Un signe ancien dans la jungle de Douwesen devrait vous mener au bon endroit. A partir d'ici, vous n'aurez plus besoin de nous.",
	"C'est bien ce qui m'inquiete le plus.",
	"Nous n'avons rien a nous dire.",
	"Tres bien."
};
