string DLG_TEXT[83] = {
	"Aaah. Capitaine ",
	" servant le fameux ",
	". ",
	"Je suis très impressionné par tes dernières aventures. Le Black Pearl, les Incas, ce n'est pas rien.",
	"Merci gouverneur. Mais je suis venu te demander du travail.",
	"Capitaine, nous avons à travailler sur des affaires délicates.",
	"Je suis à ton service.",
	"Je t'écoute.",
	"Je n'ai rien pour toi pour le moment.",
	"Au revoir.",
	"Vous disiez avoir besoin d'un capitaine discret. De quoi s'agit-il ?",
	"Rappelez-moi ce que vous attendez de moi pour votre affaire inca.",
	"J'ai réuni les seize objets incas que vous vouliez.",
	"Où en sommes-nous de votre affaire inca ?",
	"J'ai reconstitué la statue complète.",
	"Votre affaire inca est réglée.",
	"J'ai besoin d'un capitaine capable, discret, et moins sot que la moyenne. Quelques objets incas circulent encore dans l'archipel, et je souhaite les réunir.",
	"Voilà une demande bien érudite pour un gouverneur.",
	"Je ne suis pas votre antiquaire. Une autre fois, peut-être.",
	"Un homme d'État doit aussi savoir s'intéresser à ce qui survivra à son temps. Pour commencer, rapportez-moi un exemplaire de chacun des objets indiens courants, du premier au seizième.",
	"Un seul exemplaire de chaque objet, de indian1 à indian16. J'ai compris.",
	"Exactement. Revenez quand la série sera complète. Si vous réussissez, vous verrez que je paie aussi sérieusement que je collectionne.",
	"Je m'en charge.",
	"Je veux un exemplaire de chacun des seize objets indiens courants. Un seul de chaque me suffit. Revenez me voir quand la série complète sera en votre possession.",
	"Très bien.",
	"Excellent. Ces pièces étaient plus importantes que leur apparence ne le laissait croire.",
	"Vous semblez y tenir beaucoup pour une simple collection.",
	"Disons qu'elles appartenaient autrefois à une tradition fort ancienne. Une secte inca, ou quelque chose d'approchant. Les Fils de l'Ombre d'Inty.",
	"Vous en parlez comme si vous les connaissiez mieux qu'un amateur.",
	"Seulement par des papiers, des fragments et quelques rumeurs. Prenez votre récompense. Votre premier contact vous attend sur la Côte éloignée d'Isla Muelle. Souvenez-vous d'une seule chose : ne parlez qu'aux Anglais.",
	"Je retiendrai surtout la dernière consigne.",
	"La Côte éloignée d'Isla Muelle. Votre homme y est anglais, et lui seul doit vous intéresser.",
	"Havre radieux, à Conceicao. Même principe : cherchez l'Anglais et ne vous égarez pas auprès du Portugais.",
	"À Douwesen, la plage aux palmiers vous attend. Cette fois, les Hollandais ne devraient pas compliquer les choses autant que les Ibériques.",
	"Le dernier morceau a quitté le circuit de mes contacts. Cherchez dans la jungle de Douwesen un signe ancien qui devrait vous guider.",
	"Vous avez l'indice. Il ne vous reste qu'à fouiller l'endroit indiqué dans la jungle de Douwesen pour récupérer la tête.",
	"Je poursuis.",
	"Enfin... oui, enfin. Vous ignorez à quel point cette statue est remarquable.",
	"Vous la connaissez donc mieux que vous ne le disiez.",
	"Mieux ? Non. Disons que j'en ai lu davantage que la plupart des hommes de gouvernement. L'érudition prend parfois des formes que les marins jugent théâtrales.",
	"Vous paraissiez pourtant presque ému.",
	"N'y voyez rien de plus. Vous m'avez bien servi, capitaine. Je saurai me souvenir de votre efficacité. Des affaires plus importantes pourraient bientôt requérir un homme de votre trempe.",
	"Je suppose que ce ne sera pas votre dernière demande.",
	"Notre affaire inca est close pour l'heure. Si j'ai besoin de vous de nouveau, vous en serez informé.",
	"Je saurai attendre.",
	"Je vous ai déjà dit qu'il n'y avait rien pour vous ici, capitaine. La plage est calme, et je tiens à ce qu'elle le reste.",
	"Je vois que j'ai assez attiré l'attention pour aujourd'hui.",
	"Vous semblez chercher quelqu'un, capitaine. Cette plage n'accueille pas souvent d'étrangers de votre genre.",
	"Je me renseignais, rien de plus.",
	"Alors renseignez-vous ailleurs. Les rencontres ici sont déjà assez étranges sans que vous y ajoutiez votre curiosité.",
	"Message reçu.",
	"Pas ici. Certainement pas sous les yeux de cet Espagnol. Si vous venez bien de Redmond, nous parlerons comme des hommes prudents.",
	"Je croyais pourtant que vous étiez entre amis.",
	"Naturellement. Une affaire de relations diplomatiques. Mais certaines relations gagnent à rester très discrètes.",
	"Je reviendrai donc quand vous jugerez le sable plus sûr.",
	"Mieux. Voici ce que vous êtes venu chercher : les pieds seulement. Le reste a pris d'autres chemins, et je ne suis payé ni pour poser des questions ni pour garder une statue entière.",
	"Tout cela pour un vieux morceau de pierre ?",
	"On m'a appris à ne pas discuter ce que mon supérieur juge précieux. Portez cela à Conceicao. À Havre radieux, cherchez encore un Anglais, surtout pas le Portugais.",
	"Je commence à comprendre votre manie.",
	"Vous regardez encore beaucoup autour de vous, capitaine. Si vous attendiez quelqu'un, il a sûrement préféré remettre cela à plus tard.",
	"Vous avez peut-être raison.",
	"Vous regardez beaucoup autour de vous, capitaine. Vous attendez quelqu'un ?",
	"À vrai dire, je cherchais surtout un peu de calme.",
	"Alors vous avez choisi une bien mauvaise plage. Ici, le calme a tendance à changer de propriétaire quand les étrangers posent trop de questions.",
	"Je vais vous laisser votre tranquillité.",
	"Ne me dites pas un mot ici. Le Portugais croit servir un échange de courtoisie entre gens civilisés, et je préférerais ne pas troubler cette illusion.",
	"Et ce n'est pas le cas ?",
	"Disons que la courtoisie change parfois de forme selon les besoins de la Couronne. Revenez me voir sans attirer davantage d'oreilles.",
	"Je saurai être plus discret.",
	"Bien. Prenez ceci. Le corps de la statue. J'en suis volontiers délivré, car cette pierre attire trop d'intérêts pour une simple antiquité.",
	"Vous avez tous le même talent pour parler beaucoup sans rien expliquer.",
	"C'est ce qui nous garde en vie. Les bras vous attendent à Douwesen, à la plage aux palmiers. Cette fois, les Hollandais seront moins nerveux que nous.",
	"Alors cap sur Douwesen.",
	"Ah. Vous êtes celui de Redmond. Oui, je vois très bien. Ici, nous faisons moins semblant qu'à Isla Muelle ou Conceicao.",
	"Pour une fois, quelqu'un parle clairement.",
	"N'allez pas vous emballer. L'Anglais vous attend et tient toujours à ses petites précautions. Inutile de jouer au plus malin, allez donc le voir directement.",
	"J'y vais.",
	"Voici les bras. Pour la tête, c'est une autre histoire. Elle n'est plus entre les mains du réseau.",
	"Ne me dites pas qu'elle a disparu.",
	"Pas disparue. Cachée, ou enterrée. Un signe ancien dans la jungle de Douwesen devrait vous mener au bon endroit. À partir d'ici, vous n'aurez plus besoin de nous.",
	"C'est bien ce qui m'inquiète le plus.",
	"Nous n'avons rien à nous dire.",
	"Très bien."
};
