string DLG_TEXT[27] = {
", cher client, je suis ",
", propriétaire du chantier naval local.",
"Je suis ",
", capitaine du '",
"'.",
", ",
". Que puis-je faire pour toi aujourd'hui, ",
"?",
"Mon navire a besoin d'être réparé.",
"Je voulais juste parler.",
"Je dois partie.",
"Eh bien, c'est une joie de te rencontrer. Mon chantier naval est à ton service.",
"Parfait, ",
". Voyons ce que ton chantier naval a à offrir.",
"Je veux juste parler.",
"Je dois partir. Merci.",
"Et de quoi veux-tu parler exactement, ",
"?",
"Rien pour le moment.",
"Hum... As-tu besoin d'autre chose, ",
"?",
"Oui, je voudrais employer les services de ton chantier naval.",
"Merci. Adieu!",
"De quoi as-tu besoin exactement?",
"Voyons ce que ton chantier naval a à offrir.",
"Je voudrais installer des canons neufs sur mon navire.",
"Je dois partir. Merci.",

};