string DLG_TEXT[173] = {      
"Bonjour, ",
". Je n'avais malheureusement pas encore eu la chance de te rencontrer, mais je sais que tu es le capitaine du bateau qui se trouve au port.",
"Et alors? Je n'ai pas le temps de discuter avec les marins.",
"Je suis ",
". De quel bateau parles-tu, au juste?",
".' C'est bien le tien, n'est-ce pas, ",
"",
"?",
"Comment l'as-tu deviné?",
"C'est possible, mais cela ne te regarde pas. Disparais!",
"Ce n'était pas difficile, ",
", car je t'ai vu débarquer. Je m'appelle ",
".",
"Je vois. Heureux d'avoir discuté avec toi.",
"Tu n'as rien de mieux à faire que de regarder les bateaux aller et venir?",
"Malheureusement, j'ai perdu mon poste pour avoir enfreint le règlement du bateau sur lequel je me trouvais.",
"Quel dommage! Et tu ne peux rien y faire?",
"C'est regrettable, mais bonne journée quand même. Et bonne chance!",
"Eh bien... peut-être que si un capitaine respectable disait du bien de moi au capitaine du port. Ah, mais qui se préoccupe de moi, de toute façon",
"?",
"Mmh... je vais voir si je peux faire quelque chose à ce sujet.",
"Je peux aller voir le capitaine du port, mais ce ne sera pas gratuit.",
"Désolé, mais je ne peux rien pour toi.",
"C'est vrai, ",
"? Si tu m'aides, je te jure que je ne l'oublierai pas.",
"Ce n'est pas ce qui m'intéresse et tu le sais très bien.",
"À la réflexion, je n'ai pas le temps de t'aider.",
"Oh. Autrement dit, ta générosité s'achète, c'est ça, ",
"? Mais il se trouve que j'ai quelque chose à t'offrir.",
"Je t'écoute.",
"Ça m'étonnerait...",
"Eh, non, capitaine! Si tu m'aides, j'en ferai autant pour toi. Je suis comme ça, moi!",
"Je vais commencer par aller voir le capitaine du bord.",
"Au fait, où puis-je trouver le capitaine du port?",
"Eh bien, il est vrai que je n'ai pas grand-chose à faire à part observer les bateaux qui vont et viennent dans la rade. Au revoir, capitaine.",
"Au revoir.",
"Je connais un homme prêt à payer cher pour engager quelqu'un qui se chargera de certaines tâches à sa place\nSi tu m'aides, je te le présenterai. Il me fait confiance et je suis sûr que tu es le genre d'individu qu'il recherche.",
"Mmh... voilà qui a l'air intéressant... Très bien, je vais essayer de t'aider.",
"Au fait, où puis-je trouver le capitaine du port?",
"Peut-être dans le bâtiment faisant face aux portes de la ville ",
"Merci.",
"Oh, capitaine ",
"! Bonjour, ",
".",
"Bonjour, ",
". Je ne pensais pas te revoir un jour...",
"Oh, c'est encore toi, ",
". Heureux de voir que tu te portes bien.",
"Ainsi, personne n'a voulu t'aider, ",
"?",
"Bonjour et au revoir. Je suis très pressé.",
"Non, en effet, ",
". Il va me falloir dire adieu à la mer.",
"Très bien, je vais t'aider.",
"Qu'est-ce que j'y gagne?",
"Tu ne peux t'en prendre qu'à toi-même. Au revoir.",
"C'est vrai, ",
"? Eh bien, capitaine, si tu m'aides, je te promets que je ne l'oublierai pas.",
"Ce n'est pas ce qui m'intéresse et tu le sais très bien.",
"À la réflexion, je n'ai pas le temps de t'aider.",
"Oh. Autrement dit, ta générosité s'achète, c'est ça, ",
"? Mais il se trouve que j'ai quelque chose à t'offrir.",
"Je t'écoute.",
"Ça m'étonnerait...",
"Eh, non, capitaine! Si tu m'aides, j'en ferai autant pour toi. Je suis comme ça, moi!",
"Je vais commencer par aller voir le capitaine du port.",
"Au fait, où puis-je trouver le capitaine du port?",
"Eh bien, il est vrai que je n'ai pas grand-chose à faire à part observer les bateaux qui vont et viennent dans la rade. Au revoir, capitaine.",
"Au revoir.",
"Je connais un homme prêt à payer cher pour engager quelqu'un qui se chargera de certaines tâches à sa place\nSi tu m'aides, je te le présenterai. Il me fait confiance et je suis sûr que tu es le genre d'individu qu'il recherche.",
"Mmh... voilà qui a l'air intéressant... Très bien, je vais essayer de t'aider.",
"Au fait, où puis-je trouver le capitaine du port?",
"Eh, mais c'est le capitaine ", 
"! Bonjour, ",
".",
"Bonjour, ",
". Je ne pensais pas te revoir un jour...",
"Oh, c'est toi, ",
". Heureux de voir que tu te portes bien.",
"Est-ce que ça a marché?",
"Je vais de ce pas voir le capitaine du port.",
"Pas encore, je regrette. Nous parlerons plus tard.",
"Au fait, où puis-je trouver le capitaine du port?",
"Oh, pardon! Prends ton temps, bien sûr, ",
". C'est juste que j'en ai tellement marre de rester à terre...",
"Ça ne va pas durer, fais-moi confiance.",
"Écoute, j'aurais quelques questions à te poser. Tu es un marin expérimenté, n'est-ce pas?",
"J'aimerais que tu me parles de navigation...",
"Je l'espère, ",
". J'aimerais t'offrir un verre, mais je suis capitaine, et toi, tu n'es que marin...",
"Ha! Offre-le moi plutôt quand tu me permettras de reprendre la mer!",
"Mais un marin peut trinquer avec un capitaine!",
"Tu auras du mal à trouver de meilleurs marins que moi entre ici et la Jamaïque, ",
"!",
"Alors, fais-moi profiter de ton expérience.",
"Mmh... d'accord, à plus tard.",
"N'étant pas officier, je peux difficilement te conseiller sur l'art de la navigation ou de la manœuvre\n Pour le reste, je me ferai une joie de t'aider.",
"Parfait. Peux-tu me dire ce qu'un capitaine doit savoir?",
"Comment dois-je traiter mon équipage?",
"Si tu me donnais quelques conseils?",
"Mmh... je ne peux pas te parler de navigation ou de commerce, mais certaines choses sont vitales pour nous autres marins. C'est pour ça que nous devons les connaître si nous ne voulons pas nous faire avoir.",
"Que veux-tu dire par-là?",
"Pour commencer, il faut avoir quelques notions de défense. Si le capitaine ne sait pas disposer son équipage à bord du bateau, \n le moindre combat tournera au carnage\n Meilleure sera ta défense, moins tu subiras de pertes.",
"Continue, je t'écoute...",
"Je vois. Merci de me l'avoir dit.",
"Ne néglige jamais ton équipage, sauf si tu veux t'échouer ou te retrouver à la dérive. L'équipage est le cœur du bateau et aucun capitaine ne peut naviguer seul\n Et si tu n'as pas assez d'hommes à bord, ton navire sera aussi mobile qu'un cachalot.",
"Les marins sont aussi des hommes. Nul ne remet cela en doute.",
"Je crois que je vais te donner les conseils habituels à un jeune capitaine, ces derniers ayant tendance à se précipiter au combat, même face à un adversaire fortement supérieur en nombre.\nSi tu cherches à fuir, n'oublie pas qu'il vaut mieux perdre une cargaison que la tête.",
"Je vois. Autre chose?",
"Au revoir et merci de tes conseils.",
"Ensuite, tu dois apprendre à manier l'épée. On dit parfois que cela ne regarde que le capitaine, mais les marins s'y connaissent aussi un peu en la matière...",
"Génial! Ça me plaît!",
"Je crois que ça me suffira pour aujourd'hui. Au revoir.",
"Le moral de l'équipage est primordial. Si tes hommes sont mécontents, tu risques de te retrouver avec une mutinerie sur les bras.",
"Changeons de sujet.",
"Merci, nous en parlerons une autre fois. Au revoir.",
"Ah, au fait, ",
"! N'affronte jamais les gardes de la ville, car les combats loyaux ne les intéressent pas\n Ils attaquent tous ensemble et cherchent à ligoter leur adversaire. Il vaut mieux affronter trois pirates qu'un groupe de gardes.",
"Changeons de sujet.",
"Merci, nous en parlerons une autre fois. Au revoir.",
"Autre point important : l'abordage. Ton équipage doit apprendre à lancer les grappins\nsur le bateau que tu souhaites aborder, et il devra savoir le faire quelles que soient la vitesse et la distance.",
"C'est drôle : tes conseils n'en sont pas vraiment.",
"Merci, nous en parlerons une autre fois. Au revoir.",
"Pardon, ",
". Je me suis laissé emporter.",
"Très bien, changeons de sujet.",
"Merci du renseignement. Au revoir.",
"Ah, capitaine ",
"! Bonjour, ",
".",
"Bonjour, ",
". Je ne pensais pas te revoir un jour...",
"Ah, encore toi, ",
". Heureux de voir que tu te portes bien. ",
"Alors, des résultats?",
"Hélas, ",
", je n'ai rien pu faire.",
"Pas encore, je regrette. Nous en parlerons plus tard.",
"Quelle dommage! Mais merci quand même, ",
".",
"Ne le prends pas si mal, ",
". Je t'accepte à bord de mon bateau.",
"Écoute, j'aurais quelques questions à te poser. Tu es bien un marin expérimenté, non?",
"J'aimerais que tu me parles de la vie de marin.",
"Alors, comment ça se passe, capitaine?",
"Tu vas pouvoir m'offrir à boire, Rys.",
"Je n'ai pas encore résolu le problème.",
"C'est vraiment si terrible que ça, ",
"?",
"Je crois que non, au contraire. Tu vas pouvoir retrouver un emploi à bord d'un bateau...",
"Oh, merci, capitaine! À vrai dire, je n'y croyais plus...",
"Mmh... c'est que tu me sous-estimais.",
"Bonne chance, ",
"! À la revoyure!",
"Je dois bien reconnaître que oui. Bon, que puis-je pour toi, ",
"? Laisse-moi te prouver ma gratitude.",
"Merci, ",
", mais je n'ai besoin de rien. Au revoir.",
"Au fait, je me demandais... Cela te dirait d'intégrer mon équipage en tant qu'officier?",
"Une leçon de plus ne me fera pas de mal, j'imagine...",
"Ça me convient parfaitement.",
"! J'ai besoin d'argent pour régler mes affaires ici.",
"Combien te faut-il?",
"500 piastres. Je sais que ça fait beaucoup, mais...",
"D'accord. Voilà ton argent.",
"C'est une somme! Tiens, voilà ton argent. Allez, viens à bord.",
". C'est bon de voir que tu es toujours en vie, capitaine. C'est que tu fais un métier dangereux, par les temps qui courent...",
"Écoute, ",
", pourrais-tu me répéter ce qu'il faut pour être un bon capitaine?",
"Au fait, je me demandais... Cela te dirait d'intégrer mon équipage en tant qu'officier?",
"Je crois que je le sais déjà. Au revoir.",
"Quels sont les ordres, capitaine?",
"Je n'en ai pas pour toi.",

};