string DLG_TEXT[74] = {
"Bonjour, je m'appelle ",
", mais mes amis m'appellent ",
".",
"C'est un plaisir de faire ta connaissance, ",
", je m'appelle ",
". Désolée, mais j'ai du travail ; une autre fois, peut-être.",
"Salut, beauté, je m'appelle ",
", mais tu peux m'appeler ",
". A plus tard.",
"Bonjour! D'après ton nom, tu dois être la fille du propriétaire de cette échoppe, je me trompe?",
"Eh, beauté, ce n'est pas ton papa là, près du comptoir?",
"C'est un tel plaisir de te voir, ",
"!",
" Tout le monde en ville parle de toi et de tes exploits!",
"Oui, oui, mais je n'ai pas le temps.",
"Oui, c'est vrai, je suis comme ça, parfois. Je manque parfois de politesse, mais je connais mon boulot. J'ai des choses à faire pour l'instant, mais on se reverra un peu plus tard.",
"...",
"...",
"...",
"...",
"...",
"J'ai beaucoup entendu parler de toi, ",
". On dit que tu es la seule femme pirate...",
"On a tort : je ne suis pas pirate, je suis un honnête capitaine de vaisseau.",
"Je t'ai déjà demandé de me montrer un peu de respect. Je suis capitaine, ",
", alors ne m'appelle pas autrement. Compris?!",
"Tu n'as pas changé d'avis au moins? Je t'en prie, emmène-moi avec toi!",
"On a tort : je ne suis pas pirate, je suis un honnête capitaine de vaisseau.",
"Je t'ai déjà demandé de me montrer un peu de respect. Je suis capitaine, ",
", alors ne m'appelle pas autrement. Compris?!",
"Oh, pardon, ",
".",
"Tu veux me parler de quelque chose en particulier, ou tu ne fais que perdre mon temps?",
"Tu commences à m'agacer avec tes jacasseries. Tu veux parler affaires, oui ou non?",
"Je veux parler affaires. Tu es mon dernier espoir!",
"À en juger par le ton de ta voix, tu es en train de mijoter un coup tordu et tu veux mon aide.",
"Non, vraiment! Je suis ton 'dernier espoir'? Comme c'est intéressant! Vas-y, explique-moi un peu ce que tu as en tête.",
"Je regrette, mais j'ai pas le temps de m'occuper de tes problèmes.",
"C'est ridicule ; demande de l'aide à ton père et ne viens pas m'embêter.",
"Merci de bien vouloir m'écouter. Le problème, c'est que je ne peux plus rester avec mon père. C'est un brave homme, mais il veut me marier.",
"Et c'est si mal, pour une fille comme toi?",
"Et alors, il n'y a rien de mal à ça. Une fois que tu auras mis la main sur ton mari, tu pourras l'embobiner comme tu voudras.",
"Il veut te marier contre ton gré? Ce n'est pas bien, et je comprends ta colère contre lui, mais que veux-tu que j'y fasse?",
"Sans te demander ton avis? Tu parles d'un père! On devrait le pendre au grand mât! Mais je ne sais toujours pas ce que tu veux que je fasse.",
"Quoi? Je pensais que tu me comprendrais. Je ne veux pas me marier! Je veux être indépendante et libre!",
"Je trouve que tu as de bien étranges idées pour une jeune fille, mais en quoi cela me concerne-t-il?",
"Et alors? Quitte la maison de ton père. Je ne vois pas en quoi ça me regarde.",
"Emmène-moi avec toi, je t'en supplie! Je veux prendre la mer sur ton bateau et admirer l'océan et...",
"Oh, minute, fillette! Tu veux que je t'enlève?",
"Eh, oh, une seconde, là! Tu veux que je risque ma peau pour résoudre tes petits problèmes?",
"Non, pas question. Tu es jeune et immature. Tu regretteras ta décision bien vite.",
"Ah, comme si je n'avais rien d'autre à faire ; j'ai des problèmes moi aussi, tu sais.",
"En te voyant, je me suis dit que tu pourrais m'aider, mais si tu penses que ce sont de 'petits' problèmes...",
"Du calme. Tu veux vraiment prendre la mer et abandonner le confort d'un bon foyer?",
"Arrête de pleurnicher! Tu veux vraiment quitter ta maison et ta vie tranquille pour aller vivre sur l'océan?",
"Je te comprends très bien, mais je ne crois pas avoir le droit de me mêler de ta vie. Vis comme tout le monde, et sois heureuse.",
"Tu as raison, tes désirs ne sont que les petites envies d'une petite fille gâtée.",
"Oui, cela fait des années que je rêve de voyager. Je veux voir des nouveaux endroits, rencontrer de nouvelles personnes, ne plus avoir à me cacher derrière mon père et le laisser prendre toutes les décisions pour moi.",
"Très bien, je te prends avec moi, mais ne va pas croire que la vie de marin est de tout repos.",
"D'accord, d'accord. Mon bateau est au port et je dirai à mon équipage de te laisser monter à bord, mais à la moindre jérémiade, tu iras nourrir les requins.",
"Tu te trompes. En voyageant, on visite des endroits nouveaux et fascinants, mais on se retrouve aussi dans des situations dangereuses. Tu ferais mieux de rester chez toi.",
"Alors ne te cache pas derrière ton père. Vis ta vie, profites-en et fais ce que tu veux, quoi qu'en dise ton père! ",
"Oh, merci beaucoup, capitaine ",
", je vais aller tout de suite chercher mes affaires et je me rendrai sur ton bateau.",
"Très bien, mais ne traîne pas ; on lève l'ancre très bientôt.",
"Ne va pas prendre tous tes vêtements ; n'emporte que le nécessaire.",
"Tu as sans doute raison, merci.",
"Tant pis. Et maintenant, laisse-moi m'occuper de mes affaires.",
"Comme tu voudras, ",
". Je n'ose te retarder davantage.",
"Bien sûr que non. Ne monte pas sur tes grands chevaux, gamine.",
"Oui, j'aimerais que mon père soit capitaine... je pourrais parcourir les mers à ses côtés et me tenir sous les voiles blanches gonflées par la brise océane...",
"Joli rêve, mais on ne choisit pas ses parents. Allez, j'ai des choses à faire.",
"Idiote! Une femme, ça porte la poisse sur un navire, alors reste sur la terre ferme.",

};
