string DLG_TEXT[121] = {
"Il est agréable de voir quelqu'un qui sache s'habiller dans ce trou paumé. Je m'appelle ",
" et je suis le propriétaire de cet établissement.",
"Tu te permets de juger ma tenue alors que tu n'es pas fichu de garder ce bouge à peu près propre? Je vois le genre de tavernier que tu es...",
"Bien sûr, ",
". Que puis-je pour toi?",
"J'ai besoin d'engager des marins pour compléter mon équipage.",
"Mon équipage est épuisé après de nombreux combats et je cherche à engager des marins jeunes et peu expérimentés à la recherche de travail.",
"J'ai une proposition à te faire.",
"Est-ce que tu aurais une chambre? Je souhaiterais rester ici quelque temps.",
"Est-ce qu'il y aurait une chambre disponible dans ton bouge?",
"Je n'ai pas d'autres questions à te poser. Au revoir.",
"Je sais désormais tout ce que je voulais savoir. Au revoir.",
"Alors, parlons affaires. Que veux-tu?",
"Non merci. Je cherche le navigateur de Rheims.",
"Je suis à la recherche de quelqu'un, une jeune femme prénommée ",
"Danielle",
"Danielle",
". Tu sais quelque chose à son sujet?",
"Je voudrais me confesser, mais on dit que le prêtre local est le plus grand pécheur du coin. C'est vrai?",
"Tu sais, on dirait que tu t'es trompé au sujet du prêtre.",
"Ce Hollandais était fou et je n'ai eu d'autre choix que de le tuer. La servante t'a appris quelque chose?",
"Le Hollandais a refusé de me parler. Peut-être que tes employés t'ont appris quelque chose...",
"J'ai découvert que ces lettres étaient fausses. Qu'est-ce que tu sais à ce sujet?",
"J'aimerais en savoir davantage sur la mort d'un certain ",
"Giraldo Figuiera",
"Giraldo Figuiera",
".",
"J'aimerais savoir si une frégate noire est arrivée au port.",
"Dis-moi, as-tu vu un certain ",
"Blaze",
"Blaze",
", dernièrement? C'est un capitaine et il est dur de ne pas le remarquer.",
"Il faut que je quitte discrètement la ville. Tu pourrais m'aider à y arriver? Pour... disons, 1 pièce d'or.",
"J'aurais besoin de renseignements au sujet d'un homme vêtu d'une robe noire et qui se fait appeler le 'professeur'.",
"J'ai besoin de travail. Tu ne connaîtrais pas des gens riches qui ont peur de voyager seuls, sur cette île?",
"Rien pour le moment.",
"Si un tel homme existe, il ne doit pas aimer attirer l'attention avec tant de compagnie, comme tu dois t'en douter, j'imagine.", 
"C'est vrai, j'oubliais. Très bien, je reviendrai plus tard, quand j'aurai moins de bateaux. Ha, ha, ha!",
"Je ne t'aiderai pas. Tu as déjà fait assez de mal comme ça à mon pays.",
"Regardez-moi ce patriote! Dans ce cas, au revoir.", 
"Tu as les mains pleines de sang. Tu ne t'attends tout de même pas à ce que quelqu'un accepte de voyager avec toi, si?",
"Tu as raison, tout le monde a peur de moi. Ha, ha, ha!",
"Tu arrives juste à temps, un marchand cherche justement quelqu'un qui accepterait de l'accompagner. Tiens, le voilà qui entre dans la taverne.",
"Je n'y manquerai pas.",
"Non, personne pour le moment. La prochaine fois, peut-être.",
"Mmh... dans ce cas, j'attendrai.",
"Ah! Il va te falloir aller trouver le gardien de la prison! Celui que tu recherches a été arrêté voici quelques jours. Il incitait les habitants à se révolter.",
"Merci, tu m'as été d'une aide précieuse.",
"J'y pense, un navigateur habite non loin d'ici. C'est peut-être lui que tu cherches...",
"Merci. Je crois bien que je vais aller lui rendre visite...",
"Je ne crois pas, non. Par contre, pour 50 pièces d'or...",
"Marché conclu. Tiens, voici ton argent.",
"C'est du vol pur et simple!",
"Passons dans l'arrière-salle et je te donnerai d'autres habits afin que personne ne te reconnaisse.",
"Fantastique!",
"Pas récemment, non. Il passe de temps en temps, mais cela fait longtemps que je ne l'ai pas vu.\n On raconte que son bateau aurait coulé au cours de la tempête de la semaine dernière.",
"J'en ai entendu parler...",
"Une frégate noire? Attends que je réfléchisse... non, je suis à peu près sûr qu'elle n'est pas passée par notre port\nPar contre, je connais quelqu'un qui l'a déjà vue...",
"Où puis-je trouver cette personne?",
"Le voilà, à cette table. Si ma mémoire est bonne, il s'appelle ",
"Balltesar Figueiredo",
"Balltesar Figueiredo",
".",
"Bien, je vais aller lui parler.",
"Oui, cette femme a reconnu que personne ne lui avait envoyé ces lettres et qu'elle avait raconté tous ces mensonges sur ordre de l'assistant du prêtre.",
"Parfait! Cela signifie que je peux retourner à Redmond.",
"Tu te trompes! Cette personne est innocente et ces rumeurs sont infondées!",
"Ah, oui? Et que fais-tu de ces lettres, alors?",
"Je pense qu'il s'agit de faux. Il y a peu, j'ai vu l'assistant du prêtre parler avec un Hollandais du nom de ",
"Yedam Kinne",
"Yedam Kinne",
".\n Et tout le monde sait que cet homme est un faussaire accompli, entre autres.",
"Mmh... bien, je vais essayer d'en apprendre davantage. De ton côté, interroge la servante. Peut-être aura-t-elle des choses intéressantes à te révéler...",
"Oh! Tu as frappé à la bonne porte. Mes clients ont évoqué cet incident plusieurs soirs durant.",
"Que sais-tu au sujet de la personne qui l'a tué?",
"On raconte que c'est une folle qui a fait ça. Pourtant, il n'était ni son amant ni son souteneur\nOn dit qu'elle est très belle et très intelligente. Elle a même réussi à s'échapper de la prison, tu te rends compte? \nEt sais-tu pourquoi elle l'a tué? Une statuette en or a été retrouvée chez lui, et elle pèse dans les dix livres! \nIl serait intéressant de savoir à qui il l'avait volée, tu ne crois pas?",
"D'un côté, il a eu de la chance de se la procurer, mais de l'autre, il serait toujours en vie s'il n'avait pas eu cette statuette entre les mains. Où est-elle, à présent? Est-il possible de la voir?",
"Ha! As-tu l'intention de t'en emparer? \nTu n'y arriveras jamais! C'est le commandant de la garnison qui en a la garde et il ne la remettra à personne\nTrois types ont essayé de lui chercher des noises et leurs têtes se balancent toujours aux portes de la ville.",
"Ainsi, tu dis que l'idole se trouve chez le commandant de la garnison? Excellent!",
"Est-ce de ",
"Father Jerald",
"Father Jerald",
" que tu veux parler? Il ne faut pas écouter tous ces mensonges, ",
"! \nC'est vrai qu'il lui arrive parfois de boire un ou deux verres de vin, mais il est très pieux\nTu peux aller te confesser à lui sans la moindre crainte.",
"Merci d'avoir dissipé mes doutes à son sujet.",
"J'ai entendu parler d'elle, oui.",
"C'est vrai? Qu'est-ce que tu sais à son sujet? Quand est-elle venue ici pour la dernière fois?",
"Donne-moi une pièce d'or et je te dirai tout ce que je sais, ",
".",
"Tiens, la voilà.",
"Ha! Pour cette somme, moi aussi je peux te dire n'importe quoi.",
"Elle était là peu de temps avant la libération d'Oxbay, mais elle n'est pas restée. Je me souviens d'elle parce qu'un homme lui a fait des avances et qu'elle l'a aussitôt remis à sa place.",
"Tu ne sais pas grand-chose. À part ça, tu as entendu parler de tablettes d'argile retrouvées à l'intérieur de la mine?",
"Donne-moi une pièce d'or de plus et je te le dirai, ",
". ",
"Escroc! Tiens, la voilà.",
"Euh, non... je crois que je vais plutôt me renseigner par moi-même.",
"Des tablettes d'argile, dis-tu? Je suis au courant, oui. Il y a quelques années, j'ai eu un client qui s'y intéressait énormément. Il n'avait pas le droit de les emporter, alors, il allait les étudier sur place. Il ne cessait de répéter qu'elles le rendraient riche et célèbre.",
"Je vois. Et où est-il, maintenant?",
"Dieu seul le sait. Comme je te l'ai dit, il n'a pas eu le droit de sortir ces tablettes de la mine, mais j'ignore pour quelle raison. Un jour, il n'a plus eu de quoi payer sa chambre et il est parti. Depuis, je ne l'ai plus jamais revu.",
"Dans ce cas, j'imagine qu'il va me falloir me rendre à la mine. Où se trouve-t-elle?",
"Sors de la ville et tu tomberas dessus. Un phare se dresse juste derrière ; tu ne devrais pas avoir de mal à la trouver.",
"Bien.",
"En général, j'ai beaucoup d'apprentis marins, ici, mais il est un peu tard, aujourd'hui. Le plus souvent, ils arrivent dès le matin\nTu n'as qu'à prendre une chambre. Comme ça, tu pourras les attendre.",
"Très bien. Il t'en reste une?",
"Je n'en ai pas besoin pour le moment. Changeons de sujet.",
"J'ai des chambres disponibles, oui. Combien de temps comptes-tu rester?",
"Jusqu'à demain matin.",
"Jusqu'à la nuit.",
"Ça te coûtera 5 pièces d'or.",
"Voilà ton argent.",
"Hélas, on dirait que ma bourse ne me permet pas de dormir dans un lit. Je me contenterai donc de la salle commune.",
"C'est une suite que tu me proposes ou quoi? Non, merci. Compte tenu de tes tarifs, je préfère dormir dans la salle commune.",
"Je vais y réfléchir.",
"Ça te coûtera 5 pièces d'or.",
"Voilà ton argent.",
"Hélas, on dirait que ma bourse ne me permet pas de dormir dans un lit. Je me contenterai donc de la salle commune.",
"C'est une suite que tu me proposes ou quoi? Non, merci. Compte tenu de tes tarifs, je préfère dormir dans la salle commune.",
"Je vais y réfléchir.",
"Chers clients! Arrêtez de vous comporter de la sorte ou je vais devoir appeler les gardes!",
"C'est bon, je m'en vais...",

};