string DLG_TEXT[22] = {
"Qu'est-ce que tu veux, capitaine?",
"Je suis le capitaine ",
".",
"Je suis  ",
", propriétaire du '",
"'.",
"Qu'est-ce que tu me proposes, capitaine?",
"Quelques articles à vendre.",
"Rien du tout. Au revoir.",
"Je peux t'aider, capitaine?",
"J'ai quelque chose à vendre.",
"Impossible. Adieu.",
"Mmh... je crois que tu te trompes. Va à l'échoppe ; ils t'achèteront ta marchandise sans problème.",
"J'ai bien peur qu'une échoppe ne fasse pas l'affaire.",
"Merci du conseil. Au revoir.",
"Ah oui?",
"Ce que j'ai, aucun marchand n'en voudra.",
"Tu devrais peut-être finir une affaire avant d'en commencer une autre, non?",
"Tu as sans doute raison.",
"Mmh... je peux peut-être t'aider. Je vais te trouver un client. On t'attendra à un endroit appelé ",
".",
"Parfait. À plus tard.",

};
