string DLG_TEXT[53] = {
"Qu'est-ce que tu fais là?",
"Du calme, on a la marchandise!",
"A ton avis? J'ai la marchandise!",
"Allez, sors de là! Si tu fais capoter l'affaire, on te tue!",
"Tu me menaces?",
"Tu vas le regretter, vaurien!",
"Calme-toi. Je m'en vais. Au revoir.",
"Je suppose que tu la caches dans tes poches? Allez, dis-moi où sont ton bateau et la marchandise!",
"Je voulais d'abord m'assurer que tout allait bien.",
"Je ne voulais pas risquer mon navire. Je voulais d'abord m'assurer que tout allait bien.",
"Oublie notre accord!",
"On ne va pas te voler. Allez, amène ton bateau, et méfie-toi des patrouilles côtières.",
"D'accord. Attends-moi là.",
"Quoi? Tu rigoles ou quoi?",
"Je suis tout à fait sérieux.",
"Tu peux pas nous rouler comme ça! Tu vas le payer de ta vie!",
"Ça m'étonnerait!",
"Tu vas le regretter!",
"Allez aboyer ailleurs, espèces de chiens galeux!",
"Tu vas le regretter!",
"Allez aboyer ailleurs, espèces de chiens galeux!",
"Ah, très bien. Alors...",
". Ça te coûtera ",
". Alors ça fera ",
" en tout. Ça te va?",
"Ça me va.",
"Pas question. Je trouverai un autre acheteur.",
"Qu'est-ce que tu fais là? Tu n'as rien à vendre! Ce n'est pas ce qu'on cherche. On peut acheter tout ça en ville!",
"Non merci.",
"Ça fait plaisir à entendre. On continue? ",
". Ça te coûtera ",
". Alors ça fera ",
" en tout. Ça te va?",
"Ça me va.",
"Pas question. Je trouverai un autre acheteur.",
"Bon...",
". Ça te coûtera ",
". Alors ça fera ",
" en tout. Ça te va?",
"D'accord.",
"Non. Je crois que je préfère trouver un autre acheteur.",
"Et pour finir...",
". Ça te coûtera ",
". ",
" en tout. Ça te va?",
"Ouais.",
"Pas question. Je trouverai un autre acheteur.",
"Non merci? Tu veux qu'on se rencontre et puis tout ce que tu dis, c'est 'non merci'? Fiche-moi le camp. Tu ferais mieux d'honorer ta parole à l'avenir!",
"Tu croyais qu'il y avait de l'honneur entre voleurs? C'est original.",
"La somme totale est de ",
" pièces d'or. Ton argent, contre notre marchandise!",
"Marché conclu!",
"C'est trop cher! Pas question!",

};
