string DLG_TEXT[20] = {
"Bonjour! Tu es ",
", c'est bien ça? Je regrette, mais je n'ai pas le temps de discuter. J'ai tellement de clients aujourd'hui.",
"...",
"Bonsoir, ",
". Oh. Tu es si... beau garçon.",
"Qu'est-ce que tu veux dire?",
"Qu'est-ce que tu fais là?",
"Ah! C'était quelque chose! Reviens me voir vite!",
"Promis, si j'ai le temps.",
"Bon...",
"Il faut que j'y aille. A bientôt.",
"Eh bien, c'est ",
"Fabiao Dunga",
"Fabiao Dunga",
", qui m'a recommandé, ",
".",
"Ah, d'accord! Qu'est-ce que tu attends? Entre donc!",
"Dis-lui que je n'ai pas besoin de lettre de recommandation.",
"Quoi? Tu me jettes dehors?",
"Exactement.",

};
