string DLG_TEXT[23] = {
"Lâche ton arme, ",
", tu es en état d'arrestation!",
"En état d'arrestation? Pour quelle raison?",
"J'ai là un mandat d'arrêt concernant ",
" et tous ceux qui l'accompagnent.",
"Quoi? Qui a donné cet ordre?",
"Il vous faudra d'abord nous vaincre!",
"Qu'est-ce qui se passe?",
"Tu es en état d'arrestation, ",
". Suis-nous, s'il te plaît.",
"Je ne me laisserais pas faire si la balance ne penchait pas tant en votre faveur. Très bien, je vous suis, mais j'insiste pour que le gouverneur soit mis au courant de mon arrestation. Je travaille pour lui, après tout.",
"Dépose tout de suite les armes!",
"Tu ne t'en tireras pas comme ça!",
"Le gouverneur ",
"Robert Christopher Silehard",
". Tu as cinq secondes pour lâcher ton arme et te rendre.",
"C'est une terrible méprise. Allons voir le gouverneur pour régler cette affaire.",
"Crétin! C'est lui qui m'a ordonné de te mettre en prison. Tu ne sortiras d'ici que pour rejoindre la potence.",
"Espèce de chien : Tu vas tâter de mon épée!",
"Ça ne te regarde pas, chien! Ne contredis pas notre officier!",
"Ne me parle pas sur ce ton, paysan!",
"Tu n'es pas en mesure d'exiger quoi que ce soit. Suis-nous.",
"Diable.",

};