string DLG_TEXT[23] = {
"Attends, il faut qu'on parle.",
"De quoi?",
"Bonjour, ",
". Tu es ",
"?",
"C'est toi qui dois charger la marchandise à bord de mon bateau?",
"Oui. Qui es-tu? Le responsable de la cargaison? ",
"Oui, qu'est-ce que tu veux?",
"Tu es là pour charger la marchandise sur mon bateau?",
"Je vois que tes amis et toi êtes costauds, et on a besoin d'argent.",
"Je n'ai pas tout à fait compris ce que tu as dit.",
"Ne t'inquiète pas, tu comprendras plus tard.",
"Assez avec les devinettes!",
"Très bien. Tu vois, on a décidé de donner une leçon à cette canaille de ",
"Thomas O'Reily",
". Il a refusé nos services et tu vas bientôt savoir toi aussi ce qui arrive quand on n'est pas d'accord avec nous.",
"Qu'est-ce que tu veux dire?",
"Qu'est-ce que tu racontes?",
"Oui, c'est moi le patron de ces gars-là. Il est où, ton bateau? On peut pas charger sans le bateau.",
"Mon bateau est au port. J'ai simplement décidé de vérifier si les choses allaient bien avant de venir.",
"Pas de problème. Je vais retourner au port et dire à mon équipage de venir jusqu'ici, dans cette baie.",
"Peu importe. Allez, les gars! Attrapez-le!",
"Bon sang!",

};
