string DLG_TEXT[92] = {
"Qu'est-ce que tu fais chez moi, ",
"?",
"Oh, je suis navré, je suis juste passé pour voir qui habite ici, mais je m'en vais.",
"Mêle-toi de tes affaires, vieille peau. Un mot de plus et tu vas regretter d'avoir vu le jour. Encore que... je n'ai pas envie de me salir les mains.",
"Bonjour, ",
". ",
"Sabine Matton",
" m'a parlé de toi.",
"J'ai grand plaisir à faire ta connaissance. Si je comprends bien, tu es ",
" et ",
"Sabine Matton",
" est ta filleule?",
"Je sais ce que tu veux dire quand tu dis qu'elle t'a 'parlé'. C'est un vrai moulin à paroles. Tu es sa marraine?",
"Tu sais, je crois qu'il y a quelque chose qui ne va pas. Peut-être que ",
"Sabine Matton",
" t'a vraiment dit que je te mènerais à elle, mais son père m'a donné des instructions bien différentes.",
"Tais-toi, vieille sorcière. ",
"Sabine Matton",
" m'appartient, et c'est moi qui décide de ce que j'en ferai.",
"Qu'est-ce qui est arrivé à ma petite fille? Qu'est-ce que tu lui as fait, espèce de parasite?!",
"Tu t'inquiètes trop. Ta fille est sur mon bateau, et elle va très bien.",
"Tais-toi, vieille sorcière. Tu m'énerves à pleurnicher comme ça. La fille est en vie, mais ce que je fais d'elle ne regarde que moi.",
"Ah, espèce de brute! Que veux-tu pour la relâcher? De l'argent?!",
"Quelle perspicacité. J'ai l'intention de demander une rançon.",
"C'est tout à fait ça. Je ne connais pas de plus belle musique que le bruit des pièces d'or.",
"Oh, je suis vraiment navré! Heureusement que tu viens de me le rappeler! Ça fait longtemps que je voulais la laisser partir.",
"Cette ",
"Sabine Matton",
" et toi m'ennuyez avec vos jérémiades. Prends la fille, et bon débarras.",
"Je n'ai rien à te dire.",
"Tu n'es toujours pas calmée? Je vais garder la fille pour l'instant, et puis on verra.",
"Combien veux-tu, pirate, pour relâcher ma petite fille?!",
"Combien offres-tu, señorita?",
"Qu'est-ce que tu racontes? Dis-moi ton prix et on verra.",
"Je te donnerai tout ce que j'ai : 5 000 pièces d'or.",
"Marché conclu, ma chère. Donne-moi l'argent, et je relâcherai ma 'passagère'.",
"Ah, vieille sorcière, tu es redoutable en affaires! OK, donne-moi l'or et je relâche la fille.",
"Très bien, je vais prendre l'argent, mais ",
"Sabine Matton",
" reste avec moi.",
"Ha! Tout ce que j'ai à faire, c'est prendre ton argent et garder la fille!",
"Tiens, voilà ton or, et j'espère que tu t'étoufferas avec!",
"Mon Dieu, quelle grossièreté! Mais je dirai à mes hommes de libérer la fille. Au revoir.",
"Tu n'es pas la première à me dire ça. Donne-moi l'argent et attends tranquillement la gamine.",
"Non, tu ne peux pas nous faire ça! Je t'en supplie, ",
", pitié!",
"Ne t'inquiète pas tant, tu risques l'indigestion... Bon, d'accord. Donne-moi ton argent, et dis-moi au revoir.",
"Pourquoi pas? Tu ne peux rien faire pour m'arrêter. Et si tu penses à appeler les gardes, alors cette charmante demoiselle passera un sale quart d'heure.",
"Prends ton argent et file. Tu n'es pas un homme! Tu es un monstre!",
"Au revoir, señorita.",
"Oh, s'il te plaît, arrête de couiner.",
"Oh, tu es si gentil, ",
"! Je vois bien que tu as bon cœur, même si tu essaies de te faire passer pour un pirate cruel.",
"Tu as bien tort. J'en ai plus qu'assez de cette fille et de ses jérémiades. Combient de temps un homme peut-il tenir en mer, coincé avec la même fille?",
"Tu ne comprends rien du tout, vieille femme. Cette fille m'épuise avec ses jérémiades, et le modeste plaisir que j'éprouve en sa compagnie n'est rien comparé à l'irritation incessante qu'elle me cause.",
"Tu te trompes, j'en ai peur, señorita. Je suis un pirate...",
"Allez, je suis un vrai pirate. Pas la peine d'enjoliver les choses.",
"Je vois que j'ai été trop gentille avec toi. Tu es bien un pirate et un assassin!",
"Je suis ravi de voir que tu m'estimes enfin à ma juste valeur, mais d'autres affaires m'attendent et je vais devoir mettre un terme à cette conversation.",
"Ce n'est pas la première fois qu'on me le dit... mais si tu n'as pas envie que quelque chose arrive à la fille ou à toi, je te conseille de la fermer!",
"Je me fiche de ce que tu penses. Je suis une vieille femme, et je connais la vérité.",
"Comme tu voudras, señorita ; et à présent, je vais te dire adieu.",
"Je suis content que tu connaisses la vérité, vieille femme, mais il faut vraiment que j'y aille.",
"Pourquoi?",
"Ne t'inquiète pas. J'amènerai ta filleule en lieu sûr.",
"Du calme. C'est moi qui décide de ce que je ferai de cette fille, et crois-moi, je vais trouver quelque chose d'utile à lui faire faire.",
"Eh bien, ",
", il est probable que ",
"Sabine Matton",
" ne connaissait pas les intentions de son père. Je vois bien que tu es un homme honnête, et je donne la permission à ma filleule de prendre la mer avec toi.",
"Merci de ta confiance... Maintenant, il me faut partir.",
"En fait, j'étais censé t'amener ta filleule... alors la voilà. Sur ce, je m'en vais.",
"Bon voyage, ",
"!",
"Adieu.",
"Quoi?! Comment oses-tu dire des choses pareilles? Tu n'es qu'une canaille, ",
"!",
"Je n'ai pas l'intention d'écouter tes insultes. Je vais prendre la fille avec moi et filer. Si tu essaies de m'en empêcher ou de me mettre des bâtons dans les roues, je te jure que je te trancherai la gorge!",
"Non, pas ma petite fille, je t'en supplie, laisse-la partir!",
"Adieu, vieille femme.",
"Oui, tu as raison. Je te suis très reconnaissante pour ce que tu as fait pour nous.",
"Ce n'est rien. Au fait ",
"Arnaud Matton",
" m'a demandé de te donner cette lettre.",
"Merci, je te laisse décider. Je peux m'en passer, mais si tu as un peu pièce d'or à dépenser, je ne dis pas non.",
"Merci encore. Mais attends! Je vais écrire quelques lignes pour ",
"Arnaud Matton",
", et si ça ne te dérange pas trop, tu pourras lui remettre ce message.",
"Au revoir. J'espère que tout ira bien.",
"Adieu.",
"Bien sûr! Bien sûr! Voilà tout ce que j'ai : 800 pièces d'or. J'espère que cela couvrira tes frais.",
"Oh. Oui. Oui, certes. Et, au fait, j'ai un document pour toi.",

};
