string DLG_TEXT[34] = {
"Du vent.",
"Je m'en vais.",
"Si tu ne comptes pas donner plus d'argent, tu ferais mieux de partir. Ha ha ha ha!",
"Je te rappellerai ça.",
"On se reverra, capitaine.",
"J'ai l'impression qu'il y a une drôle d'odeur.",
"Allez, viens.",
"Pas maintenant. Peut-être une autre fois.",
"Avec plaisir. Tu vas m'offrir à boire?",
"Tu as payé ma dette! Merci!",
"De rien. Tiens, voilà ton reçu.",
"Tu ne m'as pas encore payé, pas vrai?",
"Non, attends encore un peu.",
"*Gasp!* Comment oses-tu me parler comme ça!",
"Je parlerai comme je veux. Pourquoi, tu veux m'apprendre les bonnes manières?",
"Tu as de la chance qu'il y ait des gardes dans le coin, sinon ma lame serait déjà sur ta gorge...",
"Tu serais mort avant d'avoir eu le temps de dégainer.",
"Capitaine, si je peux me permettre... tu veux bien me payer à boire? Mon ardoise est déjà très élevée, je le crains...",
"Combien dois-tu?",
"Oh, je regrette, il faut vraiment que j'y aille...",
"500 pièces d'or.",
"C'est une sacrée dette. Bonne chance pour ce qui est de la payer.",
"500 seulement? Ce n'est pas si grave. Je peux peut-être la payer pour toi.",
"Oh! Merci! Merci beaucoup!",
"Non, attends. Je n'ai pas cet argent sur moi.",
"C'est tout? Aucun problème, je vais payer pour toi.",
"Oh, capitaine, merci encore!",
"Je serai de retour en un rien de temps.",
"Ha! Quel imbécile! Tavernier! Apporte-moi du vin!",
"Attends... Tu as dit que tu n'avais pas d'argent.",
"Je crois bien que oui, non? Tu devrais mieux choisir ceux à qui tu fais confiance... Maintenant, dégage.",
"Sale... sale voleur! Rends-moi mon argent!",
"Ah, mais tu t'es fait escroquer selon les règles de l'art, mon ami! Maintenant, hors de ma vue... à moins que tu ne préfères que je te batte comme plâtre?",
"Pas aujourd'hui!",

};