string DLG_TEXT[197] = {
"Es-tu ici pour vendre ou es-tu intéressé par des objets personnels?",
"J'ai des marchandises à vendre.",
"Je recherche des objets personnels.",
"Je ne fais que passer. Au revoir.",
"Bonjour, ",
". Bienvenue dans ma boutique.",
"Merci, je suis ",
".",
", ",
". Cela fait plaisir de te voir. Es-tu prêt à marchander ",
"?",
"Eh bien, que nous as-tu apporté cette fois, capitaine ",
"? Ou peut-être es-tu ici pour d'autres raisons?",
"Capitaine. Content de te voir. Je suis à ton service!",
"Voyons ce que tu as.",
"Dans un moment, peut-être. Avant, je voudrais parler.",
"Adieu.",
"Content de te voir. Je suis ",
". J'espère que nos relations seront profitables.",
"Eh bien, ",
", voyons ce que tu as.",
"J'aimerais te parler, ",
".",
"Adieu.",
"Tu es là pour bavarder, capitaine? C'est toujours un plaisir.",
"Je cherche du travail.",
"Je cherche du travail.",
"Je t'écoute.",
"On m'a demandé de te livrer une cargaison.",
"Tu as sûrement quelques petites tâches que tu aimerais voir accomplies. Je serais ravi de t'offrir mes services... contre rémunération.",
"Arnaud Matton",
" a reçu ses parchandises, ",
".",
"Je suis ici de la part de ",
"Arnaud Matton",
"Arnaud Matton",
".",
"J'aimerais parler de l'un de tes employés.",
"J'aimerais une explication. À commencer par les hommes qui m'ont tendu une embuscade sur la plage et essayé de me tuer.",
"Dis-moi qui a essayé de me tuer sur la plage? Ils travaillaient pour toi!",
"J'ai mené à bien ta mission.",
"Ta cargaison a été acheminée comme prévu.",
"Le moment est mal choisi pour parler.",
"Tu tombes à pic, ",
", j'ai besoin d'un capitaine pour... hum... une affaire délicate.",
"Ce doit être mon jour de chance. Qu'est-ce que tu attends de moi?",
"Ça me va. De quel genre de travail s'agit-il?",
"Je cherche quelqu'un pour livrer en main propre une cargaison à Falaise de Fleur.",
"De quoi veux-tu parler? Tu veux que je transporte des marchandises de contrebande?",
"Une minute, ça me paraît louche. Tu veux que je livre des marchandises de contrebande?",
"Oui, ",
". J'aimerais que tu me rendes ce service. Je peux t'assurer que la récompense sera impressionnante.",
"Dis-moi ton prix et nous ferons peut-être affaire.",
"Combien?",
"Désolé, je ne donne pas dans la contrebande.",
"Non, c'est trop risqué pour moi.",
"Mon offre est de 6 000 pièces d'or. Dont la moitié d'avance.",
"Ça me paraît correct. Bon, venons-en aux détails.",
"Marché conclu. Maintenant, dis-moi ce qu'il faut faire.",
"Cela couvre à peine les risques que courront mon navire et son équipage.",
"Seulement 6 000? Pour une telle somme, je reste assis!",
"Bien. Maintenant, parlons affaires. Je veux que tu accostes sur la plage déserte située de l'autre côté de l'île. Et aujourd'hui même.",
"Très bien. Et ensuite?",
"Jusque-là, ça va. Ensuite?",
"Mes employés t'attendront et chargeront la marchandise à livrer à bord de ton bateau.",
"À qui dois-je la remettre, à Falaise de Fleur?",
"Et à qui est-elle destinée? Une fois dans la colonie française, il me faudra bien contacter quelqu'un.",
"Tu devras trouver ",
"Andre Juliao",
"Andre Juliao",
", il t'attendra à la taverne.",
"Bien. Maintenant que les détails sont réglés, je vais préparer mon navire pour le départ.",
"Dans ce cas, ne perdons pas de temps. Je vais aller préparer mon navire pendant que tu t'occupes du chargement. Je ne prévois aucun problème.",
"Je regrette, mais j'aurais dû indiquer qu'il risquait d'y avoir des... euh... complications avec ce type de mission.",
"Je suis prêt à tout, mais je n'aime pas qu'on essaie de me tuer. J'exige une explication.",
"Des complications? Voilà un terme bien civilisé pour de tels agissements. Et si je te trouais la carcasse pour voir si tu aimes ce type de traitement?",
"Allons, du calme. Je vais tout t'expliquer.",
"J'attends.",
"Tu ferais mieux d'expliquer vite.",
"Ceux qui t'ont attaqué appartiennent à la guilde des contrebandiers. J'avais fait appel à leurs services dans le passé\nMais ils se sont montrés très insolents ces derniers temps et ont demandé une commission telle que j'ai refusé de retravailler avec eux.",
"Alors, ils ont décidé de se venger et ont pensé que me tuer ruinerait tes chances de trouver un autre moyen de transporter ces marchandises. C'est bien ça?",
"Alors, ils ont décidé de te donner une leçon, c'est ça?",
"Exactement, ",
". En outre, ils m'ont ordonné de charger mes marchandises sur leur bateau sous peine de mort, puis ont fait voile vers Dieu sait où.",
"Dans ces conditions, notre accord est annulé, n'est-ce pas?",
"Attends une minute. Tu vas annuler notre accord?!",
"J'en ai peur. Je n'ai plus de marchandises et j'ai déjà investi une somme considérable dans cette opération.",
"Depuis combien de temps sont-ils partis? Je peux peut-être les rattraper et m'emparer du butin...",
"Depuis combien de temps sont-ils partis? Je peux peut-être les rattraper et m'emparer du butin...",
"Je ne peux vraiment pas t'aider.",
"Eh bien, je ne peux rien y faire. Adieu!",
"Ils sont partis il y a moins d'une heure. Si tu parviens à les rattraper et à accomplir la tâche prévue à l'origine, je te donnerai 2 000 pièces d'or de plus.",
"Alors, pas une minute à perdre! Tu peux être certain que tes marchandises seront bientôt à Falaise de Fleur.",
"Marché conclu. Je vais partir sur-le-champ. Prépare déjà ton argent!",
"Tout va bien?",
"Oui, mais il soupçonne quelque chose. Fais preuve de prudence.",
"Tout va bien, mais à ta place, je serais plus prudent. On dirait qu'il soupçonne quelque chose.",
"Merci de ton avertissement, mais réglons nos comptes. Voilà ta récompense. J'espère que nous retravaillerons ensemble à l'avenir.",
"Tu as peut-être raison.",
"Si tu paies toujours autant, je suis sûr que ce sera le cas.",
"Le maximum que je puisse offrir est ",
"commerce",
" pièces d'or.",
"Mmh, bon. D'accord.",
"Ce n'est pas ce que j'espérais, mais j'imagine que je n'obtiendrai pas plus de toi. Marché conclu.",
"Ça ne m'intéresse pas. Adieu.",
"C'est une véritable insulte. Qu'est-ce que tu as à offrir?",
"Comme tu veux, ",
".",
"Voyons ce que tu as.",
"Terminons là cette conversation. Adieu.",
"Mmh... Oui, je recherchais un capitaine pour m'aider à acheminer quelques marchandises. J'ai conclu un marché \npour livrer quelques articles au propriétaire d'une boutique de Falaise de Fleur, mais compte tenu de la situation actuelle entre \nla France et l'Angleterre, personne ne veut se lancer dans cette traversée.",
"Quel genre de marchandises?",
"Quel genre de marchandises?",
"Merci, ",
", mais cela ne m'intéresse pas. Adieu.",
"J'aurais normalement payé 1 000 pièces d'or, \nmais dans la situation actuelle, je suis prêt à monter à 1 500. J'espère que cela te convient.",
"1 500 pièces d'or? Tu peux peut-être offrir un peu plus?",
"Ça me va. Je peux faire ça pour toi.",
"Merci, ",
", mais cela ne m'intéresse pas. Adieu.",
"Des marchandises ordinaires... De la soie, du rhum, des épices... Pas de contrebande, ne t'en fais pas!",
"Je ne mets pas ton honnêteté en cause.",
"Merci, ",
", mais cela ne m'intéresse pas. Adieu.",
"2 000 pièces d'or?... Très bien, j'accepte. Sinon,\nje ne parviendrai pas à livrer ces marchandises.",
"Là, ça me convient. J'accepte.",
" ",
", j'ai changé d'avis. Je ne peux pas faire ça.",
"C'est trop! Je ne peux pas te payer autant. Il faut quand même\nque je fasse un peu de bénéfice, ",
". C'est mon gagne-pain.",
"Très bien. Paie-moi 1 500 pièces d'or et je livrerai ta cargaison.",
"Dans ces conditions, nous ne pouvons faire affaire, ",
".",
"Alléluia! Je vais enfin pouvoir expédier cette cargaison!\nN'oublie pas, ",
", à qui tu dois remettre les marchandises! Son nom est Arnoir Matton, à Falaise de Fleur!",
"Montre-moi ce que tu as à vendre.",
"Ne t'en fais pas. Nous nous reverrons bientôt, ",
".",
"Alléluia! Je vais enfin pouvoir expédier cette cargaison!\nN'oublie pas, ",
", à qui tu dois remettre les marchandises! Son nom est Arnoir Matton, à Falaise de Fleur!",
"Montre-moi ce que tu as à vendre.",
"Ne t'en fais pas. Nous nous reverrons bientôt, ",
".",
"Merci, ",
"! Veux-tu l'or que j'ai promis de te payer?",
"Bien sûr que je veux les ",
" pièces d'or que j'ai gagnées.",
"Pourquoi me demandes-tu ça, ",
"?",
"Voilà tes ",
" pièces d'or. N'oublie pas de venir me voir chaque fois que tu seras au port. J'aime bien faire des affaires avec toi, capitaine.",
"Merci, ",
". Il y a autre chose...",
"Au revoir, ",
". Bonne chance!",
"Eh bien, je pourrais placer cet argent à intérêt et, au fil du temps, \ntu toucherais davantage...",
"Non merci. J'ai besoin de cet argent maintenant.",
"Je suis toute ouïe.",
"Arnaud Matton",
"Arnaud Matton",
" m'a engagé pour te livrer du cacao.",
"Enfin! J'attendais une cargaison, mais la guerre a modifié tous mes projets.",
"Où dois-je décharger?",
"Ne t'inquiète de rien. Je vais envoyer quelqu'un à ton bord pour s'occuper du déchargement.",
"Parfait! Maintenant, voyons ce que tu as à vendre.",
"Bien.",
"Tu veux parler de Mark?",
"Oui, j'aimerais bien payer sa rançon.",
"Tu sais, je ne veux pas que quelqu'un paie sa rançon. J'espère qu'il parviendra bientôt à accumuler un peu d'argent afin de rentrer chez lui et je ne veux pas le priver de ce droit.",
"Mais c'est pour ça que je veux payer sa rançon.",
"Tu dis que tu veux faire ça pour le ramener chez lui?",
"Exactement.",
"Cela fait plaisir de voir qu'il reste encore des gens au cœur noble en ce bas monde.",
"Alors, tu es d'accord?",
"Oui, bien sûr, si tu me verses 3 000 pièces d'or.",
"Eh! Tu sais, c'est trop cher pour moi.",
"Voilà ton argent. Je peux emmener Mark tout de suite?",
"Oui, bien sûr. Dis-lui que je suis très content qu'il puisse enfin rentrer chez lui.",
"Je le ferai.",
"Non, je n'ai pas besoin de tes services. Du moins, pas tant que tu couleras des navires anglais.",
"Dans ce cas, au revoir.",
"Je regrette, mais je n'ai rien pour toi en ce moment.",
"Je reviendrai plus tard, alors.",
"Je regrette, mais la cale de ton bateau ne suffit pas pour ce que j'ai en tête.",
"Je reviendrai plus tard, alors.",
"Oh! J'allais te demander de me rendre un service. Voilà, il faut que je livre une cargaison à ",
", et le plus vite possible. Si tu y parviens en moins d'un mois, tu toucheras ",
" pièces d'or à l'arrivée. Que dis-tu de mon offre?",
"Elle me plaît beaucoup.",
"Je ne peux pas l'accepter.",
"Je t'ai déjà dit aujourd'hui que je n'avais rien pour toi.",
"Oh, désolé.",
"Tu t'es souvenu de ta mission un peu tard, non? J'ai déjà reçu tout ce dont j'avais besoin. Au revoir.",
"Adieu.",
"Oh! Cela fait longtemps que j'attends ça. Voilà ta récompense, jeune homme.",
"Cela fait toujours plaisir.",

};