string DLG_TEXT[38] = {
"Encore merci de ce que tu as fait pour moi, ",
".",
"De rien.",
"Oh, laisse-moi tranquille! Si tu cherches de la compagnie, adresse la parole à quelqu'un d'autre!",
"Comme tu veux.",
"C'est quoi, ton problème? Je ne t'ai rien fait!",
"Qu'est-ce que tu veux?",
"Rien.",
"Parlons de ta fille...",
"Oh, merci, merci! J'ai enfin vu ma fille! Je regrette tant de ne rien avoir à t'offrir... si, attends! Prends cette épée!",
"Elle est peu commune. D'où la tiens-tu?",
"Quand j'étais plus jeune, j'ai exploré de nombreuses îles, persuadé que je ferais fortune ainsi. Je n'ai presque jamais rien trouvé, bien sûr, sauf une planque, dont on disait qu'elle appartenait à un célèbre capitaine. C'est de là que vient l'épée.",
"Je vois. Merci du cadeau.",
"Vraiment? Espèce de chacal! Pilleur de sépulture!",
"Du calme. Tu ferais bien de t'asseoir un peu.",
"Qu'est-ce que tu veux dire par là?",
"Vous autres, les pirates, les corsaires et les contrebandiers. Vous êtes des démons, tous, jusqu'au dernier!",
"Qu'est-ce qui t'a amené à voir les choses ainsi?",
"Peut-être ai-je tort de te raconter tout ça, mais tu as l'air plus fréquentable que le reste de ces gredins...",
"Merci, je suis flatté. Continue, je te prie.",
"Ça ne te regarde pas! Regarde-toi! Tu es un être vil et indigne de confiance! Tu parcours les mêmes mers que ces reptiles!",
"Fais comme tu veux. Si tu ne veux rien me dire, ne me dis rien.",
"Ma fille, ",
"Tanneken Oremans",
", est douce et naturellement confiante...",
"Laisse-moi deviner... cela a quelque chose à voir avec les pirates...",
"Oui. L'un des pires, ",
"Bernardo Gamboa",
". Il a séduit ma fille! \nJe lui ai dit que je m'y opposais, mais elle a refusé de m'écouter et a disparu il y a trois jours! \nJe suis persuadé que ce maudit Espagnol l'a enlevée!",
"Pourquoi ne demandes-tu pas l'aide des autorités?",
"Les autorités? Tu es bien naïf! Le serpent qui s'est emparé de ma fille est ami du gouverneur.",
"Je vois. Dans ce cas, espérons que cette histoire se finira bien...",
"Je peux peut-être t'aider. Où peut-on trouver ce type?",
"Son bateau est à quai. Tu n'auras aucun mal à le trouver.",
"Je vais voir ce que je peux faire.",
"Va-t-en! Je t'ai déjà tout dit, alors, ne me tourmente pas avec tes questions!",
"Très bien, continue de te saouler et d'espérer que ta fille te reviendra.",
"Du calme, du calme. Dis-moi où je peux trouver l'homme qui a enlevé fille.",

};