string DLG_TEXT[95] = {
", du '",
"', si je ne me trompe?",
"En effet, mais comment le sais-tu?",
"C'est mon métier de tout savoir sur tout le monde. Au fait, je me nomme ",
".",
"C'est un plaisir de te rencontrer. J'aurais quelques questions à te poser.",
", ",
".",
"J'aurais quelques questions à te poser.",
"Je pense détenir des informations qui devraient t'intéresser. Je sais qui vend de la contrebande dans cette ville.",
"Je sais qui vend de la contrebande dans cette ville.",
"Je sais qui donne dans la contrebande dans ta ville, Mocie.",
"As-tu vérifié les informations que je t'ai communiquées?",
"Je suis le capitaine du vaisseau qui va escorter l'Oiseau jusqu'à Oxbay.",
"Je t'écoute.",
"J'aimerais obtenir des renseignements sur la ville.",
"J'ai entendu dire que les contrebandiers te causaient des soucis...",
"Je pense détenir des informations qui devraient t'intéresser. Je sais qui vend de la contrebande dans cette ville.",
"Je sais qui vend de la contrebande dans cette ville.",
"Je suis le capitaine du vaisseau qui a été chargé d'escorter l'Oiseau jusqu'à Oxbay.",
"Comment? Est-ce que tout le monde en parle déjà en ville? J'aimerais bien savoir d'où vient ce renseignement.",
"Personnellement, je le tiens des ouvriers du port.",
"Si tout le monde est au courant, inutile de nier. Oui, les contrebandiers me posent en effet des problèmes. Pourquoi cette question?",
"Simple curiosité de ma part. Parlons plutôt d'autre chose.",
"Eh bien, il se trouve que j'aimerais t'aider... mais ce ne serait pas gratuit, bien sûr.",
"Quel genre d'aide as-tu à proposer?",
"Je suis disposé à retrouver ces contrebandiers pour toi en échange de 5 000 pièces d'or.",
"Si tu sais où ils sont, qu'est-ce qui m'empêche d'appeler les gardes? De cette façon, tu me dirais tout ce que tu sais... et gratuitement...",
"Sauf que je ne détiens peut-être pas encore cette information et que tu ne peux pas avoir la certitude que la force te permettra d'obtenir ce que tu cherches.",
"Essaie et je pourrais vérifier très vite la couleur de ton sang, l'ami.",
"Mmh... Admettons que je te crois. Comment comptes-tu t'y prendre pour trouver les contrebandiers?",
"Ça, c'est mon problème, pas vrai?",
"Très bien. Tu auras tes 5 000 pièces d'or si tu trouves les contrebandiers. Mais je te préviens, s'il s'agit d'un piège...",
"Comment ça? Il n'y a aucun piège là-dessous! Je suis tout ce qu'il y a d'honnête avec toi.",
"As-tu des preuves de ce que tu avances?",
"Il se trouve que oui. Tiens, jette un œil à ces lettres.",
"As-tu des preuves de ce que tu avances?",
"Il se trouve que oui. Tiens, jette un œil à ces lettres.",
"Tu as raison. Ces documents font la lumière sur cette transaction douteuse. Que désires-tu comme rémunération pour tes services?",
"Je t'ai rendu ce service gratuitement et je n'attends rien en retour, si ce n'est ta gratitude.",
"J'imagine que 500 pièces d'or me conviendraient amplement...",
"Non, il n'en est pas question. Tiens, voici 1 500 pièces d'or, en plus de toute ma gratitude.",
"Je ne voudrais pas te retarder d'avantage.",
"Bien. Voici ton argent. Et maintenant, excuse-moi, mais j'ai à faire.",
"Je ne voudrais pas te retarder d'avantage.",
"Tu as raison. Ces documents font la lumière sur cette transaction douteuse. Tiens, voici ton argent. Et maintenant, excuse-moi, mais j'ai à faire.",
"Je ne voudrais pas te retarder d'avantage.",
"Vraiment? De qui s'agit-il?",
"Il s'agit de ",
"Raoul Calmes",
"Raoul Calmes",
".",
"Je ne peux pas le croire! ",
"Raoul Calmes",
" est un homme très respecté!",
"Dans ce cas, va t'en assurer par toi-même ; je t'attends ici.",
"Oui, c'est une bonne idée, ",
". Comme ça, si tu te trompes, tu ne pourras t'en prendre qu'à toi-même.",
"Je suis sûr de mon fait.",
"Parfait. Dans ce cas, je te demanderai de m'attendre à l'entrée de la résidence. Je vais vérifier cette information et, si elle est exacte, tu auras ton argent.",
"Bien, je vais suivre ton conseil.",
"Tu avais raison, c'est maintenant avéré. Tiens, voici ta récompense. Bon, pardonne-moi, mais je suis pressé ; le gouverneur a accepté de m'accorder une audience.",
"C'est toujours un plaisir que de me rendre utile.",
"Que veux-tu savoir? Je t'avertis tout de suite, ne me demande pas ton chemin. Je n'ai rien d'une commère de village.",
"Mmh... dans ce cas, je ne vais pas te retarder d'avantage.",
"J'aimerais connaître l'histoire de la famille de ",
"Rachel Blacque",
". À ce que j'ai cru comprendre, tu connais bien ces gens.",
"C'est exact. Je les connais, et c'est une bien triste histoire.",
"Oui. J'ai entendu dire que le vieux ",
"Milon Blacque",
" était abattu par le chagrin.",
"C'est la vérité vraie, hélas. La mort de son seul fils l'a bouleversé.",
"Que s'est-il passé?",
"C'est bien triste... mais il faut que j'y aille.",
"Pour son fils, tu veux dire? Il y a cinq ans, il est parti pour Redmond à bord de son bateau et, depuis, plus personne n'a entendu parler de lui.",
"C'est tragique, en effet, mais peut-être est-il encore en vie...",
"Je ne pense pas, non. Cinq années se sont écoulées. Si c'était le cas, il aurait donné des nouvelles.",
"Tu dois avoir raison. Mais j'ai entendu dire que le vieil homme n'était pas seul. Sa fille adoptive s'occupe de lui, c'est bien ça?",
"Rachel Blacque",
"? C'est une brave fille. Elle se sacrifie sans compter pour s'occuper de lui, et pourtant, elle a ses propres problèmes, elle aussi.",
"Merci de ton assistance.",
"C'est mon métier de tout savoir à propos de ceux qui entrent dans mon port. Au fait, je m'appelle ",
".",
"Heureux de faire ta connaissance. J'aurais quelques questions à te poser.",
"Ah, oui, on m'a prévenu. Es-tu déjà prêt à lever l'ancre? Au fait, t'es-tu entretenu avec Monsieur Bun?",
"Non, je n'ai pas encore fait sa connaissance.",
"Oui. Le chargement sera bientôt terminé.",
"Il doit être quelque part par là. Tu pourras lever l'ancre dès que vous vous serez mis d'accord, tous les deux.\nJe ne vais pas tout vérifier ; j'ai bien assez de sujets de préoccupation comme ça.",
"Le voilà. Tu le vois? C'est lui qui porte un gilet bleu. Tu pourras lever l'ancre dès que vous vous serez mis d'accord, tous les deux.\nJe ne vais pas tout vérifier ; j'ai bien assez de sujets de préoccupation comme ça.",
"Merci, ",
".",
"Bien. Remets-moi le document et tu pourras lever l'ancre dès que tu seras prêt.\nJe ne vais pas tout vérifier ; j'ai bien assez de sujets de préoccupation comme ça.",
"Merci de ta gentillesse, ",
".",

};