string DLG_TEXT[144] = {
"! Que puis-je pour toi?",
"C'est un plaisir de te voir ici, ",
"! As-tu besoin de mes services?",
"Bonjour, ",
". Je ne crois pas que nous ayons été présentés...",
"Je m'appelle ",
".",
"Le capitaine ",
" est à ton service.",
"Je suis ",
".",
"Heureux de te voir, capitaine ",
". Si tu as besoin de mes services, je me ferai un plaisir de t'aider.",
". Es-tu ici pour affaires?",
"Bonjour, ",
". Que puis-je pour toi? J'accepte toutes les transactions, dans toutes les monnaies.",
"Je souhaiterais emprunter de l'argent.",
"J'ai grand besoin d'argent.",
"Tu pourrais me faire crédit?",
"J'aimerais placer de l'argent à un taux intéressant.",
"Puis-je mettre mon butin en dépôt chez toi?",
"Puis-je mettre de l'argent en dépôt chez toi, au cas où?",
"Au revoir, ",
".",
",",
"! Tu viens payer tes dettes? Ah, oui! Tu me dois... ",
" pièces d'or.",
"Bonjour, capitaine. Tant de ponctualité fait plaisir à voir. Alors, es-tu prêt à me payer les ",
" pièces d'or que tu m'as empruntées?",
"Sois le bienvenu, ",
". J'espère que ton voyage s'est bien passé et que tu me ramènes l'argent que tu me dois, ainsi que les intérêts.",
" pièces d'or.",
"Je viens te rembourser.",
"Je peux rembourser ma dette.",
"L'heure est venu de rembourser ma dette.",
"Malheureusement, je ne peux pas, pour le moment.",
"La prochaine fois, ",
".",
"Hélas, non. Je reviendrai quand j'aurai l'argent.",
"...",
"Heureux de te voir, capitaine ",
". Si tu as besoin de mes services, je me ferai un plaisir de t'aider.",
". Es-tu ici pour affaires?",
"Bonjour, ",
". Que puis-je pour toi? J'accepte toutes les transactions, dans toutes les monnaies.",
"Je souhaiterais récupérer mon dépôt.",
"Je viens récupérer l'argent que tu gardes pour moi.",
"Je veux récupérer mon or, avec les intérêts.",
"Au revoir, ",
".",
"...",
"Heureux de faire ta connaissance. Je m'appelle ",
" et mon métier consiste à prêter de l'argent à intérêt.",
"Je me nomme ",
" et je suis prêteur. Si tu as besoin d'argent, je me ferai une joie de t'aider.",
"Tu sais déjà sans doute que je m'appelle ",
". Je suis connu, par ici. Mais venons-en au fait. As-tu besoin de mes services?",
"Je souhaiterais emprunter de l'argent.",
"J'ai grand besoin d'argent.",
"Tu pourrais me faire crédit?",
"J'aimerais placer de l'argent à un taux intéressant.",
"Puis-je mettre mon butin en dépôt chez toi?",
"Puis-je mettre de l'argent en dépôt chez toi, au cas où?",
"Au revoir, ",
".",
"Mais bien sûr! De combien as-tu besoin?",
"Pas de beaucoup.",
"D'une belle somme.",
"D'autant que possible.",
"Parfait! Il vaut toujours mieux commencer par une somme modeste, car cela est moins risqué. Je peux te prêter ",
" pièces d'or.",
"Marché conclu! À quel taux?",
"Hélas, ça ne me convient pas. Tu ne peux pas faire un petit effort?",
"Je préfère ne pas m'endetter. Au revoir.",
"Ce n'est pas un problème. J'espère que ",
" pièces d'or te permettront de résoudre tes tracas. C'est une somme rondelette, tu en conviendras.",
"Marché conclu! À quel taux?",
"Hélas, ça ne me convient pas. Tu ne peux pas faire un petit effort?",
"Je préfère ne pas m'endetter. Au revoir.",
"Hmm... oui, c'est risqué, mais... d'accord. Je peux te prêter un total de ",
" pièces d'or. Mais j'espère que tu as conscience de l'importance de cette somme, capitaine. Je tiens à ce que cela soit bien clair dans ton esprit.",
"Marché conclu! À quel taux?",
"Hélas, ça ne me convient pas. Tu ne peux pas faire un petit effort?",
"Je préfère ne pas m'endetter. Au revoir.",
" par mois. C'est le mieux que je puisse faire, compte tenu de ce que je sais à ton sujet.",
"Ça me va. Il ne nous reste plus qu'à nous mettre d'accord.",
"Je préfère ne pas m'endetter. Au revoir.",
"Compte tenu de ce que j'ai entendu à ton sujet, ",
", je vais te demander de me rembourser au plus tard dans ",
" mois. Si tu ne l'as pas fait d'ici-là, je devrai prendre les mesures qui s'imposent. Tu le comprends, j'espère.",
"J'accepte tes conditions et ton argent avec plaisir.",
"Hélas, ça ne me convient pas. Au revoir.",
"J'en suis heureux, mais je dois te prévenir : cela fait très longtemps que je suis dans le métier et je sais comment récupérer mon argent. Alors, si tu as l'intention de ne jamais me rembourser, oublie tout de suite.\nNe le prends pas mal, surtout, c'est juste une mise en garde amicale.",
"Je vois. Eh bien, au revoir.",
"Je te conseille de faire attention. Les intérêts s'accumulent et il ne te reste plus beaucoup de temps pour rembourser.",
"Ne t'inquiète pas, je reviendrai te voir.",
"Oh, c'est merveilleux! Si jamais tu as besoin d'argent, je suis à ton service.",
"Merci. C'est très agréable de faire affaire avec quelqu'un qui rembourse ses dettes à l'heure. Car on ne sait jamais, tout peut arriver...",
"J'avais raison d'avoir une si haute opinion de toi, ",
"! J'espère que ce n'est pas la dernière fois que tu fais appel à mes services!",
"Je souhaiterais emprunter de l'argent.",
"J'ai grand besoin d'argent.",
"Tu pourrais me faire crédit?",
"J'aimerais placer de l'argent à un taux intéressant.",
"Puis-je mettre mon butin en dépôt chez toi?",
"Puis-je mettre de l'argent en dépôt chez toi, au cas où?",
"Au revoir, ",
".",
"Ah, je vois que j'ai à faire à un homme intelligent! Quelle somme comptes-tu investir?",
"Très bien. Tu peux être sûr que ton argent sera en sécurité chez moi et qu'il te rapportera des intérêts. Au fait, combien comptes-tu me confier?",
"Je vois que tu sais comment les choses fonctionnent. Combien comptes-tu me confier?",
"Un quart de ma fortune, soit ",
" pièces d'or.",
"La moitié de ma fortune, soit ",
" pièces d'or.",
"Tout ce que je possède, soit ",
" pièces d'or.",
"Bien. Pour une telle somme, je peux te proposer un taux d'intérêt de, disons... ",
". Il s'agit bien évidemment du taux mensuel.",
"Ça me convient.",
"Dans ce cas, il vaut mieux que je modifie le montant.",
"Je préfère ne pas investir pour le moment. Au revoir.",
"Bien. Pour une telle somme, je peux te proposer un taux d'intérêt de, disons... ",
". Il s'agit bien évidemment du taux mensuel.",
"Ça me convient.",
"Dans ce cas, il vaut mieux que je modifie le montant.",
"Je préfère ne pas investir pour le moment. Au revoir.",
"Bien. Pour une telle somme, je peux te proposer un taux d'intérêt de, disons... ",
". Il s'agit bien évidemment du taux mensuel.",
"Ça me convient.",
"Dans ce cas, il vaut mieux que je modifie le montant.",
"Je préfère ne pas investir pour le moment. Au revoir.",
"Tu peux désormais être sûr que, quoi qu'il advienne, tu ne te retrouveras jamais sans argent. Et si tu as besoin d'en retirer, tu peux venir le faire à tout moment.",
"Parfait. Bonne chance.",
"Compte tenu du taux sur lequel nous nous sommes mis d'accord et du temps qui s'est écoulé depuis, je te dois ",
" pièces d'or. Veux-tu vraiment retirer ton argent aujourd'hui?",
"Parfaitement. Remets-le moi.",
"Tu sais, je crois que tu as raison. Je ne vais pas retirer mon argent aujourd'hui. Au revoir.",
"Oh, quel dommage... et moi qui commençais à m'habituer à avoir cet argent chez moi. Hé, hé... N'hésite pas à revenir, surtout.",
"En cas de besoin, je reviendrai, sois tranquille. Au revoir.",
"Tu es toujours en vie et tu viens me rembourser? Inutile de perdre ton temps. J'ai déjà tellement perdu à cause de toi que tu ne pourras jamais t'acquitter de tes dettes! Je ne m'estimerai satisfait que quand je te verrai mort devant moi!",
"D'autres sont morts pour moins que ça!",
"Hors de ma maison! Je ne veux plus jamais te revoir!",
"...",

};