string DLG_TEXT[49] = {
"Laisse-moi tranquille, je me sens bien ici!",
"Je voulais juste...",
"Tu n'as pas entendu? Je t'ai dit de me laisser tranquille. Laisse-moi ou je demande aux soldats de te clouer à la porte de la taverne!",
"Eh!",
"Qu'est-ce que tu veux?",
"Je m'appelle ",
".",
"Je n'ai que faire de ton nom. Tu me déranges. Tu as besoin de quelque chose? Sinon, fiche le camp.",
"Je... Je cherche du travail sur un bateau!",
"Est-ce que j'ai l'air d'un maître de timonerie?! Va voir les gars du port. Je ne m'occupe pas du menu fretin. Allez, file, moi, je suis très bien ici!",
"Non, attends! Ce n'est pas un poste de matelot que je cherche. C'est pour ça que je suis venu te voir, capitaine.",
"Je vois. Bon, et quel poste cherchez-tu?",
"Eh bien, je suis un excellent navigateur, selon beaucoup de gens.",
"Vraiment? Eh bien, fallait le dire plus tôt! Quelle chance! Mon navigateur est mort au combat à Oxbay et j'en cherche un nouveau\nAlors, offre-moi un verre et c'est dans la poche!",
"(Au tavernier)... Une autre tournée!",
"Un navigateur doit garder soigneusement trace de tous nos trajets...",
"Excuse-moi, mais pourrons-nous discuter des détails du poste plus tard? En attendant, fêtons ça et dis-m'en plus sur ton navire?",
"Excellente idée! A ton nouveau travail! Hic... Du rhum! Demain matin, va au port et demande le '",
"'.",
"Alors, quand est-ce qu'on prend la mer?",
"La mer? Ah... Quand le bateau chargé de... hic... munitions arrivera. Mais chut! Personne n'est censé être au courant de ce bateau!",
"Entendu!",
"Bien parlé! Un autre gobelet de rhum, s'il te plaît! Hic... Bon, faut que je retourne au bateau... Tu parles d'une ville... Pas le moindre bordel!",
"Monsieur! Prenons un autre verre et...",
"Et quoi?... À la tienne, navigateur! Aloooors, qu'est-ce que... hic... tu voulais dire?",
"Eh bien, que ma tante va me manquer. Elle vit près d'ici, pas loin des remparts...",
"Je vois. Tu... Tu veux lui dire au revoir... hic? Laisse tomber! Il faut que tu m'accompagnes jusqu'au bateau!",
"Ses filles vont beaucoup me manquer elles aussi. À mon retour, elles seront devenues de très jolies jeunes femmes.",
"Attends. Euh. Tu devrais peut-être leur rendre une petite visite... hic... Oui... hic... Allez, on y va!",
"C'est d'accord!",
"Hic! Faites place! Mon ami et... hic... moi allons rendre visite à ces dames!",
"...",
"Qu'est-ce que tu attends? Allez, en route!",
"J'arrive!",
"Attends! Où est-ce qu'on va? Je ne vois que la jungle ici!",
"Tu as raison. Arrêtons-nous ici.",
"Pourquoi?",
"Pour que tu puisses m'en dire plus sur ce bateau chargé de munitions.",
"Quoi? Tu n'es pas navigateur, hein? Tu es un espion anglais!",
"Tu comprends vite.",
"... Incroyable! Imposteur! Je t'en ai déjà trop dit et je vais veiller à ce que tu tiennes ta langue. Prépare-toi à te battre, lâche!",
"Du calme, capitaine. Tu tiens à peine debout, alors pour ce qui est de te battre...",
"... Écoute! Tu m'as saoulé exprès!",
"Dis-moi tout et tu auras la vie sauve. Si tu me mens, je trouverai bien le moyen de te faire parler.",
"... Oui, oui. Je vais tout te dire. Un bateau appelé l'Oiseau doit apporter de nouvelles armes, c'est pourquoi nous devons garantir la sécurité de toute l'île. J'ai entendu dire qu'il se trouvait au port de Falaise de Fleur.\nLe capitaine de l'Oiseau attend son escorte sur le quai.",
"Ce bateau va rester au port jusqu'à l'arrivée de l'escorte?",
"Oui. Je crois... Je n'en sais pas plus...",
"Tu m'as dit ce que je voulais savoir. Tu peux partir.",
"Merci pour ces informations, capitaine, mais je crois que je vais devoir te tuer.",

};
