string DLG_TEXT[74] = {
"Tu ne connais donc pas les bonnes manières? Tu ne vois pas que je suis en pleine discussion et que tu ne m'intéresses pas.",
"Oh, je ne voulais pas te déranger. Désolé.",
"Très bien, du calme, pour être honnête, tu ne m'intéresses pas non plus.",
"Pardon, tu ne serais pas ",
", le capitaine du Juno?",
"Attends, tu es ",
"? C'est toi qui commande le Juno?",
"Désolé, mais je vais bientôt faire voile et je n'ai pas le temps de discuter avec toi.",
"Dans ce cas, je ne veux pas te retarder. Bon voyage.",
"Alors, dépêche-toi avant que quelque chose... ne te tombe dessus.",
"Je suis ravi de te revoir. Il y a une chose dont j'aimerais te parler.",
"Je t'écoute, qu'as-tu à me dire?",
"Il paraît que tu cherches un bon capitaine pour escorter ton navire au cours de son voyage.",
"Il paraît que tu as besoin d'une escorte. Je peux m'en charger.",
"Oh, quel plaisir de te revoir! A vrai dire, je me suis senti en sécurité sous ta protection!",
"Quand penses-tu revenir?",
"Quand je pense revenir, imbécile? J'attends mon argent.",
"Bon, nous sommes de retour. Merci de ton aide, ",
".",
"Tu es satisfait de notre coopération?",
"C'est tout? Tu n'as pas besoin de moi pour le moment? Alors, donne-moi mon argent.",
"D'accord, d'accord, je me suis emballé. Je n'aurais pas dû te sauter dessus. Bon, je me présente, je suis ",
", le capitaine du navire marchand.",
"Et mon nom est ",
". Eh bien, il semble que nous soyons collègues : tous deux capitaines.",
"On m'appelle ",
", ",
", tu as certainement déjà entendu parler de moi.",
"Oh! Mais bien sûr! Tu es le capitaine qui a réussi à filer sous le nez des Français. Les Français qui ont attaqué Oxbay! Eh! Buvons un verre de rhum pour fêter ça!",
"Tu me flattes. Moi aussi, je suis content de te rencontrer.",
"Si je n'avais pas dû me rendre d'urgence à Redmond, je me serais volontiers battu contre ces Français!",
"Bon, je ne vais pas te déranger plus longtemps.",
".",
"Occupe-toi de tes affaires et non des miennes et tout ira bien.",
"Oui, et à qui ai-je l'honneur?",
"Je m'appelle ",
". Il paraît que tu cherches un bon capitaine pour escorter ton navire lors de ton voyage.",
"Il paraît que tu as besoin d'une escorte. Je peux m'en charger.",
"Je ne doute pas de ton courage, ",
", mais hélas, je dois partir.",
"Bon, alors je ne veux pas te retarder.",
"Pour l'amour du ciel, qui a dit que j'y étais opposé?",
"J'aimerais te demander un service. As-tu deux minutes à m'accorder?",
"Oui, bien sûr, de quoi s'agit-il?",
"Ça a été un peu agité par ici, récemment. Les pirates ont jeté leur dévolu sur ces eaux et je suis un peu inquiet, car mon navire est vieux et plus très rapide. En outre, ses canons ne suffisent pas à le défendre.",
"Alors, tu veux que mon navire te protège en cas d'attaque pirate?",
"Oui, j'ai vraiment besoin d'une escorte et je suis prêt à payer 2 500 pièces d'or. Pour cela, ton navire va devoir m'escorter jusqu'à Falaise de Fleur avant de revenir ici.",
"Marché conclu. On part quand?",
"Parfait. Quand doit-on prendre la mer?",
"Non. A ce tarif-là, je perds de l'argent.",
"Non, ce n'est pas assez pour que je risque mon navire face aux pirates.",
"Je ne peux pas accepter ton offre. J'ai trop à faire ces temps-ci.",
"Ça ne m'intéresse pas.",
"Le plus tôt sera le mieux. Je te paierai à notre retour de Falaise de Fleur.",
"Bien, laisse-moi le temps de régler quelques affaires personnelles et je suis à toi.",
"Marché conclu. Nous ferons voile dès que j'aurai réglé quelques affaires en ville.",
"Mon navire est prêt pour le retour. A propos, voilà la moitié de l'argent que je te dois.",
"Allons-y. Que la chance soit avec nous!",
"Qu'est-ce que tu attends? Allez! Je ne vais pas m'éterniser sur cette île.",
"Oh, oui! Encore merci. Voilà ta récompense. ",
"Zaid Murro",
" a démissionné de son poste au terme de ce voyage.",
"C'est la vie. Eh bien, si tu as besoin de quoi que ce soit, je suis à ton service.",
"Oui, oui. Bon, je file.",
"Bien, que penses-tu de ",
"ce marché",
"?",
"C'est toujours un plaisir de traiter avec toi. J'accepte.",
"Certainement, je m'en charge.",
"Je dois refuser. Mon équipage ne travaillera pas pour rien.",
"Je t'ai dit que je ne travaillerais pas pour toi, alors trouve quelqu'un d'autre.",
"Quel dommage! Je vais devoir courir le risque de voyager seul. Bonne chance.",
"Bonne chance à toi aussi.",
"Au revoir.",

};
