string DLG_TEXT[56] = {
"Oui?",
"Non, rien.",
"Bonjour. J'imagine que ",
"Danielle",
" t'a parlé de moi?",
"Oui, bien sûr, ",
". Je m'appelle ",
". On peut dire que je suis un vieil ami de ",
"Danielle",
".",
"Te voilà enfin.",
"Tu as trouvé ",
"Raoul Rheims",
"?",
"J'ai entendu dire que vous cherchiez tous les deux la même personne\nEt il se trouve que je sais où elle se trouve.",
"Tu sais où se trouve ",
"Raoul Rheims",
"? Comment ça?",
"Disons qu'on a été voisins à une certaine époque.",
"Tu peux nous conduire à lui?",
"Bien sûr. Tout de suite.",
"Parfait...",
"Tu vois cette table près de la porte? Voilà  ",
"Raoul Rheims",
". Il vaudrait mieux aller lui parler avant qu'il ne disparaisse... Bon, excuse-moi, mais j'ai d'autres affaires à régler.", 
"Quelque chose me dit qu'il vaut mieux que je n'en sache pas plus. Quoi qu'il en soit, merci pour ton aide. Vas-y, on parlera plus tard.",
"J'ai entendu parlé de votre relation.",
"Certaines choses doivent rester privées. Alors, dis-moi, comment tu as trouvé ",
"Raoul Rheims",
" et pourquoi tu as décidé de nous aider.",
"Eh bien, à vrai dire, je ne fais pas cela pour vous aider vous, mais seulement ",
"Danielle",
" en fait.",
"Je vois. Mais ça ne me dit pas comment tu as trouvé Rheims?",
"Comme tu dis, ",
".",
"S'il te plaît. Assez de familiarités. Je ne sais pas si tu es digne de confiance.",
"Danielle",
" avait raison à ton sujet... Tu es beaucoup trop méfiant.",
"Ce que ",
"Danielle",
" pense ou dit ne regarde qu'elle. Mais je dois savoir comment tu connais l'homme qu'on cherche et pourquoi tu as décidé d'aider ",
"Danielle",
", sinon ça va barder!",
"D'accord, d'accord, du calme. Je connais très bien ",
"Raoul Rheims",
" - disons que nous avons été voisins par le passé. Quant à ",
"Danielle",
", j'ai décidé de l'aider parce qu'elle-même m'a aidé alors que je me trouvais dans une mauvaise passe.",
"C'est convaincant. Je vais vérifier. Bon, où as-tu dit que ",
"Raoul Rheims",
" se cachait?",
"Je n'ai rien dit. Tu devrais d'abord t'adresser à ",
"Danielle",
", - elle ne veut peut-être pas que tu nous accompagnes.",
"Très bien, je vais aller lui parler.",

};
