string DLG_TEXT[45] = {
"Oui, ",
"? Tu vois pas que je suis occupé?",
"Désolé, je suis ",
". Je dois escorter ton navire jusqu'à Oxbay.",
"Ah, enfin quelqu'un! Je croyais que tu ne viendrais jamais.",
"Tu es prêt à prendre la mer?",
"Presque. Mes hommes chargent et assurent la cargaison\nMais avant de partir, il faut informer le capitaine du port, ",
"Turpin Cabanel",
"Turpin Cabanel",
" et nous procurer l'autorisation de larguer les amarres.",
"Où puis-je trouver le capitaine du port?",
"Je m'en suis déjà chargé.",
"Là-bas, dans la maison près du quai, celle sur pilotis. C'est le bureau du port. Bon, va chercher l'autorisation. Je t'attends ici.",
"Oui, à tout de suite.",
"Parfait. En route.",
"On peut faire voile.",
"Où est ton navire?",
"Mmh... Eh bien, il est caché dans une petite crique.",
"Bon sang, l'ami! Pourquoi n'est-il pas au port? Va chercher ton navire, et vite. Nous devons partir au plus tôt!",
"Parfait, je vais le chercher.",
"Excuse-moi, ",
"! Tu es capitaine, pas vrai?",
"Oui, j'ai un navire. Tu es ",
"Virgile Boon",
"Virgile Boon",
"?",
"Tu sais qui je suis?",
"Je ne suis autre que... ",
". Je dois escorter ton navire jusqu'à Oxbay.",
"Ah, enfin quelqu'un! Je désespérais de te voir arriver.",
"Tu es prêt à prendre la mer?",
" Presque. Mes hommes chargent et assurent la cargaison\nMais avant de partir, il faut informer le capitaine du port, ",
"Turpin Cabanel",
"Turpin Cabanel",
" et nous procurer l'autorisation de larguer les amarres.",
"Je m'en suis déjà chargé.",
"Tu as l'autorisation du capitaine du port?",
"Non, pas encore.",
"On est prêts.",
"Qu'est-ce que tu attends? Vite, va la chercher!",
"On ne me donne pas des ordres comme à un homme de pont, ",
"Virgile Boon",
". Chaque chose en son temps.",
"On est prêt à larguer les amarres. C'est bon pour moi.",
"Attention, capitaine. Tu pourrais regretter ton manque de manières.",

};
