string DLG_TEXT[47] = {
"Laisse-moi tranquille!",
"...",
"J'imagine que tu vas t'assurer de ma personne?",
"C'est exact. Maintenant, cesse de discuter! Je vais ordonner à mes hommes de t'escorter jusqu'à mon navire.",
"Non, tu as tort. Tu es libre.",
"Quand je pense que j'ai tout abandonné pour cette canaille! J'ai été stupide! Qu'est-ce que je vais faire maintenant?!",
"Le mieux, c'est de rentrer.",
"Je suppose que tu as raison. Tu veux bien m'accompagner chez le gouverneur de cette colonie?",
"Désolé, mais c'est impossible. Si je montre mon nez chez le gouverneur, ses soldats vont m'arrêter.",
"Je n'ai aucune raison de refuser.",
"Oh, mais ne t'inquiète pas! Tu es sous ma protection! Ça peut te paraître bête, mais je suis sûr que dès qu'ils sauront qui je suis, ils te laisseront tranquille. Ils auraient trop peur de contrarier mon père.",
"Ça pourrait marcher, mais je ne préfère pas prendre le risque.",
"Très bien, si tu le dis. Espérons que tu as raison.",
"Ah... Si seulement je pouvais te convaincre. Mais merci de ton aide. Bonne chance.",
"Bonne chance à toi aussi. J'espère que tu vas rentrer chez toi sans encombres.",
"Incroyable, il y a encore des gens nobles à notre époque!",
"Je ne sais pas s'ils sont nobles, mais il existe des gens bien. A propos, comment as-tu fait pour te retrouver dans une telle situation?",
"Je m'appelle ",
" et du sang noble coule dans mes veines...",
"Vraiment? Mais alors, que fais-tu ici? Et comment es-tu tombée aux mains de cette canaille?",
"Ah, c'est une longue histoire...",
"J'ai tout mon temps...",
"L'amour. L'amour en est la cause... Moi, fille de courtisan français, j'ai osé tomber amoureuse d'un roturier. Un capitaine...",
"Continue.",
"Mon père l'a découvert et m'a interdit de revoir mon bien-aimé qui est parti pour le Nouveau Monde. Oh, il m'a tellement manqué, tellement!",
"Et tu as décidé de le suivre?",
"Oui. Incognito, j'ai acheté un billet sur un navire qui venait ici, mais les pirates nous ont attaqués et tu connais la suite.",
"Triste histoire. Je peux peut-être t'aider à retrouver ton fiancé?",
"Eh bien, je te laisse rechercher ton bien-aimé. Au revoir.",
"Oh, il ne faut pas, tu as déjà tant fait pour moi...",
"Écoute, je veux t'aider. Comment espères-tu le retrouver, autrement?",
"Tu es si bon avec moi!",
"Dis-moi comment s'appelle ton fiancé et où je peux le trouver.",
"Il s'appelle ",
"Raymond Bouchez",
" et la dernière fois qu'il a été vu, c'était à la colonie française, je crois.",
"Alors, en route.",
"(À Raymond) - Mon amour, te revoilà enfin! Mais... qui est cette femme à tes côtés?!",
"...",
"(À Raymond) - Quoi?! Une vulgaire catin? C'est à ça que tu as consacré ton temps pendant que je te cherchais? Pendant que je souffrais?!",
"...",
"Ah! Pas d'effusion de sang. Partons, c'est tout. Je ne veux plus voir cette immonde créature!",
"Je suppose que tu as raison. Inutile de rejoindre les porcs dans la fange. Cet homme n'en vaut pas la peine.",
"Comment oses-tu me parler ainsi?! Je ne suis pas une roturière, du sang noble coule dans mes veines! Je suis ",
"!",
"Ouais, et moi je suis Neptune, dieu de la mer. Reste tranquille en attendant l'arrivée de mes hommes.",
"Oh, alors excuse-moi. Je devrais surveiller mon langage. Mais, que fais-tu ici?",

};
