string DLG_TEXT[61] = {
"Capitaine, tu es toujours ici? ",
"Mateus Santos",
" ne va pas s'éterniser dans cette taverne.",
"...",
"Que puis-je pour toi?",
"Tu t'appelles ",
"Vito Leone",
"Vito Leone",
"?",
"Bien joué, capitaine! Voilà tes 10 000 pièces d'or. Si tu dois encore... organiser des funérailles, fais-le nous savoir, nous nous en chargerons à prix d'ami.",
"Merci et adieu.",
"Oui, c'est moi. Et tu dois être le capitaine ",
". J'ai beaucoup entendu parler de tes prouesses lors de certaines... missions.",
"Voilà une semaine que tu es arrivé et tu sais déjà qui je suis et ce que je fais? Comment?",
"Dans mon boulot, manquer d'informations est plus dangereux qu'une balle ou une épée. Je vois que cela te surprend - ",
"Mateus Santos",
" ne t'a pas dit qui je suis, c'est ça?",
"Tu sais tout, pas vrai? Oui, ",
"Mateus Santos",
" m'a dit que tu étais un messager et que les nouvelles que tu apportais auguraient d'un grand danger.",
"Un messager? Quel farceur ce ",
"Mateus Santos",
". Capitaine, je ne suis pas messager. Je représente une organisation qu'un philistin pourrait appeler une guilde d'assassins. Et je ne suis pas là pour porter des nouvelles, mais pour punir un imposteur.",
"Vraiment? Et qui est cet imposteur?",
"Notre très estimé ",
"Mateus Santos",
", comme vous devez vous en douter. Voilà deux ans, il a surgi de nulle part, tué le chef de la branche locale de notre organisation et pris sa place.",
"...",
"En théorie, nous aurions pu fermer les yeux sur cette impudence s'il avait fait preuve d'un peu de respect. Mais non content d'avoir tué notre représentant, il a cessé de verser la part de bénéfices due à la guilde. Et ça, tu peux le comprendre, c'est impardonnable.",
"...",
"On a essayé de se débarrasser de ",
"Mateus Santos",
" avec l'aide de mercenaires locaux, mais il est plein de ressources et a toujours réussi à déjouer nos plans. C'est pourquoi la guilde a décidé d'envoyer l'un de ses membres pour régler la question.",
"Et ",
"Mateus Santos",
" m'a promis une grosse récompense pour la tête de son assassin potentiel : toi.",
"Bien sûr! Maintenant que la situation se corse, il comprend à qui il a affaire et il a peur. Mais ma mort ne changera rien : ",
"Mateus Santos",
" va bientôt mourir.",
"Cela ne va pas m'empêcher de te tuer pour toucher la récompense.",
"Oh, tu peux me tuer... mais tu ne recevras qu'une balle en récompense de tes efforts. Tu penses vraiment que ",
"Mateus Santos",
" te laissera en vie après m'avoir parlé? Je crains fort que ce soit ta dernière mission, capitaine.",
"Mmh... Si telle est la situation, que me conseilles-tu?",
"Tu me prends pour un imbécile? Tu veux vivre et tu es prêt à dire n'importe quoi pour sauver ta peau. Je vais te tuer et toucher la récompense!",
"Compte tenu de la situation, tu as deux solutions. La première : m'épargner et prendre le large. La deuxième : m'aider à me débarrasser de ",
"Mateus Santos",
". Cette dernière solution, en plus de te sauver la vie, te rapportera beaucoup d'argent.",
"Mmh... Je n'ai rien contre l'argent... ni la sécurité, à vrai dire. Mais comment envisages-tu de tuer ",
"Mateus Santos",
"? Il est bien gardé, c'est le moins qu'on puisse dire...",
"Pas question, occupe-toi seul de ",
"Mateus Santos",
"! Je ne veux plus entendre parler de cette histoire. Au revoir.",
"Tu me prends pour un imbécile? Tu dirais n'importe quoi pour sauver ta peau. Je vais te tuer et empocher ma récompense!",
"J'en fais mon affaire. Je vais l'attirer dans la taverne d'Isla Muelle pour de prétendues négociations. Il viendra, c'est sûr. Tu n'auras alors qu'à monter à l'étage de la taverne et l'achever. Ensuite, tu reviendras ici et je te donnerai 10 000 pièces d'or.",
"Marché conclu. Mais si tu m'as menti, je te retrouverai à l'autre bout de la Terre... et tu le paieras! Garde cela en mémoire.",
"Pas question, occupe-toi seul de ",
"Mateus Santos",
"! Je ne veux plus entendre parler de cette histoire. Au revoir.",
"Tu me prends pour un imbécile? Tu veux vivre et tu es prêt à dire n'importe quoi pour sauver ta peau. Je vais te tuer et toucher la récompense!",

};
