string DLG_TEXT[28] = {
"Eh bien, mais qui vois-je? ",
"!",
"Désolé... on se connaît?",
"Alors, as-tu mené ta mission à bien?",
"Oui. Il ne te causera plus le moindre ennui.",
"Parfait!",
"S'il te faut quoi que ce soit d'autre, je me ferai une joie de t'aider.",
"Ça y est, je me souviens de toi. Tu es le capitaine qui a réussi à s'échapper quand les Français ont pris Oxbay.",
"En effet. Comment le sais-tu?",
"Mon petit doigt me l'a dit.",
"Je vois. Dans ce cas, si tu veux bien m'excuser...",
"Attends! A en juger par ton ton de voix, ça ne va pas fort. Je peux t'aider?",
"Ça dépend. Pourquoi le ferais-tu?",
"J'aime à penser qu'en notre temps, tous les gens devraient être amis, se montrer polis et ne jamais avoir recours à la violence pour régler leurs problèmes, mais ce n'est pas le cas, hélas. J'ai besoin d'agir et il faudrait que tu m'aides.",
"Que faudrait-il que je fasse?",
"Un homme nuit à la bonne marche de mes affaires...",
"Et tu souhaites te débarrasser de lui? Dans ce cas, pourquoi ne pas t'en charger toi-même?",
"J'aimerais bien, mais il vit à Isla Muelle. Je suis connu, là-bas ; on me reconnaîtrait.",
"Admettons que je sois d'accord. Qu'est-ce que j'y gagne?",
"A vrai dire, je n'ai pas beaucoup d'argent à t'offrir. Toutes mes économies sont entre les mains d'une personne en qui j'ai toute confiance, mais...",
"Mais quoi?",
"Je possède un excellent bateau que je pourrais te donner.",
"Mmh... c'est tentant. D'accord, marché conclu!",
"Splendide! Dans ce cas, je te donne ce navire si tu te charges d'éliminer  ",
"Sidonio Ogarrio",
"Sidonio Ogarrio",
" à Isla Muelle.",
"Très bien, j'accepte.",

};