string DLG_TEXT[56] = {
"Serais-tu ",
"?",
"Oui.",
"Je suis ",
" et je t'attendais. Je dois te dire où t'amarrer.",
"Il n'y aura pas d'amarrage. Le transport repose au fond de l'océan.",
"Ah, le gouverneur m'a dit que quelqu'un m'attendrait, en effet. Est-ce de toi qu'il s'agit?",
"Je suppose, ",
". On m'a dit d'attendre ici un capitaine anglais appelé ",
" et de lui montrer où s'amarrer\nCeci fait, je dois le retrouver sur la plage et le conduire à une grotte.",
"Cela m'étonne... pourquoi les soldats ne peuvent-ils pas entrer dans la grotte en partant d'ici?",
"C'est afin de conserver l'élément de surprise. Les Français ont des espions à Greenford. Si nous nous dirigeons vers la grotte à partir d'ici, ils comprendront ce que nous mijotons\nNous devrons alors sans doute nous battre et, si les Français l'emportent, ils décideront peut-être de s'emparer également de Greenford.",
"Mmh... j'imagine que tu as raison. Donc, où et quand dois-je amener les soldats à terre?",
"Il y a une plage déserte appelée Gray Rock Bay, ",
". C'est le meilleur endroit pour cela.",
"Comment s'y rendre?",
"En sortant de la baie, prends au nord-est, puis contourne l'île par le nord. Tu verras un gros rocher gris séparé du reste de l'île\nLa baie se trouve juste derrière. Jette l'ancre à cet endroit, ",
".",
"Est-ce que tu nous attendras là-bas?",
"Oui, ",
". J'attendrai sur la plage toutes les nuits. Votre arrivée doit se faire de nuit pour éviter les bateaux français. Je ferai des signaux à l'aide d'une torche.",
"Très bien. Nous rejoindrons la baie une de ces nuits.",
"Excellent, ",
"! Je vous y attendrai. Et sois discret, surtout! Nul ne doit avoir connaissance de notre plan.",
"Bonne chance ",
".",
"Tu étais censé l'escorter! Pourquoi l'as-tu laissé couler?",
"L'ennemi était supérieur en nombre.",
"Oh, non! Tout est perdu! Qu'allons-nous faire, maintenant?",
"Allons-y, j'ai à faire!",
"Autre chose, ",
"? Avons-nous tout évoqué?",
"Oui. Au revoir ",
".",
"Oh non! C'est affreux, ",
"! Les Français ont dû remarquer ma torche! C'est affreux!",
"Quel est le problème? Qu'est-ce qui ne va pas?",
"Une patrouille française arrive!",
"Je suis toujours partant pour me battre!",
"Excellent! Quelle bagarre! Tu es sûr que nous nous sommes débarrassés de tous les soldats français?",
"Je n'en ai pas vu qui cherchaient à s'échapper.",
"Tant mieux, parce que si les Français apprennent ce qui s'est passé ici, ils passeront la jungle au peigne fin\nEt s'ils trouvent la grotte, nous n'aurons d'autre choix que de nous battre.",
"Je vois que tu n'aimes guère faire usage de ton arme.",
"Je ne me cherche pas d'excuses, ",
". Je suis un artisan, pas un soldat. Bien, ne nous laissons pas distraire de notre tâche.",
"Et maintenant?",
"Une fois les soldats à terre, je les conduirai à la grotte, ",
". Il n'est pas nécessaire que tu nous suives dans la jungle, je connais le chemin comme ma poche.",
"Parfait! Je meurs d'envie de reprendre la mer!",
"Bon voyage, ",
", et que les vents te soient favorables.",
"Au revoir.",
"C'est un plaisir de te voir, capitaine. Où est le transport de troupes?",
"Il a coulé en chemin. J'ai fait tout mon possible, mais...",
"Non! Tout est perdu! Il faut vite partir d'ici avant l'arrivée des Français!",
"Attends...",

};