string DLG_TEXT[28] = {
"*hic!* J'adore le vin d'ici.",
"Tu n'es qu'un porc!",
"J'ai entendu dire que tu cherchais ",
"Raoul Rheims",
".",
"Et j'imagine que tu sais où il se trouve?",
"Bien sûr! Mais j'ai la gorge... tellement sèche... que j'ai du mal à parler. Tu vois ce que je veux dire?",
"Oui. Peut-être que si je te la tranchais...",
"Tavernier, apporte-nous du rhum!",
"Je n'ai pas de quoi t'offrir à boire.",
"Eh, je demandais, c'est tout!",
"Dis-moi tout ce que tu sais et pas de blagues!",
"Ecoute, espèce de crétin : je pourrais te tuer les yeux fermés, si je voulais.\nDisparais!",
"... (Il faudra que je revienne par ici.)",
"La compagnie est tellement agréable...",
"Dis-moi tout.",
"Dans ce cas, nous ne pourrons pas parler.",
"...",
"Eh bien, je ne sais pas grand-chose à son sujet, mais je sais qu'il a pour protecteur le gouverneur de Redmond, ",
"Robert Christopher Silehard",
" lui-même.",
"Et en quoi cela est-il inhabituel?",
"Le gouverneur fait un allié puissant... et un redoutable adversaire. Il est possible que Rheims se le soit mis à dos et qu'il le paie aujourd'hui.",
"C'est une sacrée histoire, mais ça ne me dit toujours pas où il est.",
"Il a été attaqué en mer, il y a peu.\nAprès ça, j'ai entendu dire qu'il était allé rejoindre les contrebandiers de Conceicao, car il se sent en sécurité avec eux.\nMoi aussi, j'imagine que je me sentirais en sécurité si j'étais gardé par ",
"Camilo Machado",
" en personne.",
"Merci. Maintenant, je sais où le chercher.",

};