string DLG_TEXT[29] = {
"Va-t'en, s'il te plaît. J'ai à faire.",
"...",
"Mais il faut que je te parle.",
"Vraiment? Dans ce cas, je t'écoute.",
"Je voudrais savoir de quoi vous avez parlé, toi et l'assistant du prêtre.",
"Dis-moi de quoi vous avez parlé, toi et l'assistant du prêtre. Sinon...",
"Je regrette, mais j'ignore de quoi tu veux parler.",
"Pour être clair, je pense que vous avez falsifié plusieurs lettres, et j'aimerais savoir si c'est vrai ou non.",
"Tu as la preuve de ce que tu avances? Ton opinion ne vaut rien.\nLes rumeurs qui circulent sur mon passé ne te donnent pas le droit de m'accuser.",
"Du calme. Je me moque royalement de ton passé. Je ne te juge pas. Tout ce qui m'intéresse, ce sont ces lettres.",
"Écoute, tu as le choix : on discute entre gens bien élevée ou tu parles à mon épée. Dans un cas comme dans l'autre, tu as intérêt à tout me dire, sinon...",
"Je t'ai déjà dit que je ne savais pas de quoi tu parlais.",
"Peut-être faut-il t'aider un peu...",
"Dans ce cas, j'ai l'impression que je vais devoir changer de ton.",
"Tu veux m'offrir de l'argent?",
"Oui, si tu acceptes de me dire si c'est toi qui a écrit ces lettres. Dès que je le saurai, je m'en irai et tu n'auras plus le moindre ennui.",
"Ah, mais la vérité n'est jamais gratuite. Je te répondrai contre 2 000 pièces d'or.",
"Très bien, voici ton argent.",
"C'est exactement le genre de réponse que j'attendais de la part de l'auteur de ces lettres.",
"Je peux te dire la vérité pour rien. Non, je n'ai pas falsifié ces lettres, et je n'ai rien à voir avec cette histoire. Maintenant, laisse-moi tranquille.",
"D'accord.",
"Tu aurais dû deviner que j'étais impliqué dans cette affaire quand j'ai accepté ton argent.",
"Je tenais à m'en assurer.",
"Je reconnais que tu m'as eu. Oui, c'est bien moi qui ai écrit ces lettres. Tu n'as pas d'autres questions à me poser j'espère?",
"Non, tu peux reprendre tes occupations. Au revoir.",
"Tes menaces ne me font pas peur.",
"Alors, comme ça, tu ne veux rien dire? Dans ce cas, il est temps de te faire parler.",
"Défends-toi!",
"Voyons si tu sais te battre.",

};