string DLG_TEXT[99] = {
", ",
".",
", ",
".",
"Eh, l'ami! Tu pourrais m'accorder quelques instants?",
"Bonjour, bonjour. Je vois que tu es un vrai loup de mer, comme moi. Si on parlait un peu?",
"Désolé, mais je suis pressé. Nous parlerons plus tard.",
"Laisse-moi tranquille, tu me fatigues. Au revoir.",
"Qui es-tu? Discuter ne me dérange pas, mais j'aimerais au moins connaître ton nom...",
"Mon nom est ",
" et je suis capitaine du '",
"'.",
"Combien de fois faudra-t-il que je me répète? Je m'appelle ",
" et je suis capitaine du '",
"'.",
"Désolé, mais je suis pressé et je n'ai pas le temps de parler.",
"Je ne souhaite pas te révéler mon identité et je n'ai pas le temps de bavarder. Va au diable.",
"Ho, capitaine! C'est ton navire, là-bas? Pas mal, pas mal du tout, même. Rien à voir avec notre rafiot.",
"Ça te dérange si je te demande qui tu es?",
"Quel est ton nom, mon gars?",
"Oh, pardon, capitaine. Je suis ",
" du 'Juno'.",
"Parfait, ",
"! Maintenant que nous avons fait connaissance, j'aurai quelques questions à te poser.",
"Maintenant que je connais ton nom et que tu connais le mien, vas-tu enfin répondre à mes questions ou continuer à jouer les abrutis?",
"Désolé, il faut que je m'en aille.",
"Restons-en là.",
"Je t'écoute, capitaine.",
"Que se passe-t-il d'intéressant en ville?",
"Cessons de parler pour ne rien dire et venons-en au fait.",
"Ce qui se passe d'intéressant? Difficile à dire. Ça dépend de ce qu'on cherche, en fait. Un marchand se passionnera pour certaines choses, un marin pour d'autres. Par contre, je sais que ",
"Clair Larrouse",
"Clair Larrouse",
" est arrivé il y a peu. On dit qu'il rassemble un équipage en vue de sa prochaine expédition.",
"Mmh... ce nom m'est inconnu.",
"Je m'en moque. Parlons de choses sérieuses.",
"C'est tout ce que je voulais savoir.",
"Merci. C'est tout ce que je voulais savoir.",
"C'est tout? Ce genre de rumeur, on les entend partout en ville. Bonne journée.",
"Parlons de choses plus sérieuses...",
"Assez de ragots. Il est temps de passer aux choses sérieuses, ",
".",
"Tu débarques de la lune, ou quoi, capitaine? C'est un escrimeur et capitaine hors pair, et il a une veine de pendu.",
"Il est peut-être célèbre pour certains, mais pas pour moi. Ou puis-je le trouver?",
"Ha! Je connais beaucoup de prétendus bretteurs de talent qui ont en fait gagné leur réputation en assassinant leurs ennemis dans leur sommeil. Où puis-je le trouver?",
"Où veux-tu qu'il soit? A la taverne ou ailleurs en ville! Si j'étais toi, j'essaierais la taverne. Si Clair n'y est pas déjà, il s'y rendra sans doute bientôt.",
"Merci. Maintenant, j'aimerais parler affaires.",
"Assez bavardé. Venons-en aux choses sérieuses.",
"Merci. Il faut que j'y aille, maintenant.",
"Je vais aller lui parler. Au revoir.",
"De quoi veux-tu parler?",
"Quand es-tu arrivé à Isla Muelle?",
"Depuis combien de temps ton bateau est-il au port?",
"Comment s'est passé le voyage?",
"Ça t'a fait plaisir de voyager sous ma protection?",
"Comment vont les affaires?",
"Tu aimes être marchand?",
"Rappelle-moi le problème que te posent les bandits.",
"Tu m'as dit que les bandits te posaient des problèmes. Tu pourrais me rafraîchir la mémoire à ce sujet?",
"Certains des bandits qui tuaient tes animaux sont morts, mais ils étaient trop nombreux dans le campement.\nNe t'inquiète pas, je m'occuperai de ceux qui restent.",
"Personne ne vous ennuiera plus, tes animaux et toi.",
"Non, rien. Adieu.",
"Dieu te bénisse! Je ne te remercierai jamais assez.",
"Ne t'en fais pas. Si tu as besoin de quoi que ce soit, demande-le moi.",
"Il y a peu, des bandits sont arrivés sur l'île, et ils ne cessent de tuer mes animaux. Je me suis plaint aux autorités, mais elles n'ont rien fait.\nJe suis capable de me défendre, malgré mon âge, mais je crois que ces brigands sont cinq. C'est trop pour moi.",
"Je devrais pouvoir t'aider. Sais-tu où se trouve leur campement?",
"Seulement cinq? Où vois-tu un problème? Je vais leur donner une leçon sans difficulté. Sais-tu où se trouve leur campement?",
"Comment? Les autorités ne lèvent pas le petit doigt pour protéger leurs administrés? Quelle honte! J'espère que cette affaire sera vite réglée.",
"Cinq? C'est trop pour moi.",
"A vrai dire, ça ne va pas fort, capitaine.",
"Quel est le problème? Tu as investi de l'argent dans une affaire qui périclite?",
"Tout va bien de ce côté, capitaine. J'ai décidé de ne pas ouvrir une boutique, mais d'acheter un ranch et d'élever du bétail. J'ai grandi dans une ferme, alors les animaux, ça me connaît.",
"C'est très bien, mais où est le problème?",
"Élever du bétail? C'est ça, ton rêve? Eh bien! Et c'est quoi, ton problème?",
"Au début, tout allait bien, mais des bandits se sont installés sur l'île et ils ne cessent de tuer mes animaux.\nJe me suis plaint aux autorités, mais elles n'ont rien fait.\ nJe suis capable de me défendre, malgré mon âge, mais je crois que ces brigands sont cinq. C'est trop pour moi.",
"Je devrais pouvoir t'aider. Sais-tu où se trouve leur campement?",
"Seulement cinq? Où vois-tu un problème? Je vais leur donner une leçon sans difficulté. Sais-tu où se trouve leur campement?",
"Comment? Les autorités ne lèvent pas le petit doigt pour protéger leurs administrés? Quelle honte! J'espère que cette affaire sera vite réglée.",
"Tu voudrais que j'aille tuer ces gredins? Mais dans quelle époque vivons-nous?",
"Qui peut savoir? Quelque part dans la jungle, j'imagine. Tu veux vraiment m'aider? Dans ce cas, je tiens à te remercier de ta gentillesse. À vrai dire, je n'ai pas beaucoup d'argent,\nmais j'en perdrai davantage si ces gredins continuent de massacrer mon bétail. Reviens me voir quand tu les auras tués. Bonne chance!",
"Pas de problème. Il faut bien aider les gens dans le besoin, non?",
"D'accord, je vais t'aider. Un peu d'exercice me fera le plus grand bien, de toute façon. Et si tu as un peu d'or en trop, ce ne sera pas de refus...",
"C'est fantastique, ",
"! Il n'y a pas longtemps, on se sentait en sécurité, ici, mes amis et moi.",
"Ce n'est rien. Au fait, où est ton 'Juno'?",
"Il a levé l'ancre, mais j'avais mis un peu d'argent de côté pour lancer ma propre affaire à terre.",
"Je vois. Dans ce cas, bonne chance et à la prochaine.",
"Alors, comme ça, tu as décidé de devenir marchand? Voyez-vous ça! Bonne chance, donc.",
"Bonne chance à toi aussi, capitaine. Il est temps que j'y aille.",
"Adieu.",
"Hier, nous avons livré une cargaison de papier en provenance de la colonie française. Notre capitaine préfère le commerce à toutes les autres façons de gagner de l'argent, alors, nous parcourons l'archipel dans tous les sens.",
"Et les pirates? Ils vous gênent?",
"Alors, comment ça se passe? Vous n'avez pas peur des pirates?",
"Parfois, si. La dernière fois, nous leur avons échappé de justesse. C'est pour ça que le capitaine nous cherche une escorte. Parce qu'une fois chargé, notre bateau est lent et manoeuvre mal.",
"Tu dis que vous avez besoin d'une escorte? Combien paieriez-vous pour ça?",
"Une escorte, tu dis? Combien ça me rapportera si j'accepte de vous protéger?",
"Aucune idée. Tu devrais poser la question au capitaine. J'imagine qu'il doit se trouver à la boutique.",
"D'accord, je vais aller le voir. Merci de ton aide.",
"Très bien, je vais aller le voir.",

};