string DLG_TEXT[24] = {
"Bonjour capitaine.",
"Bonjour à vous, je suis ",
", capitaine du '",
"', un magnifique navire !",
"Je me présente, je m'appelle ",
". Je suis tellement perdu .....",
"Que se passe-t-il ?",
"Je ne pense pas que je puisse vous faire confiance...",
"Comme tu veux, mais ne m'importe plus !",
"Je pense que je peux vous faire confiance.",
"Dis moi. Qu'est-ce qui ne va pas ?",
"Je suis éperdument amoureux de ",
". Mais je ne peux pas lui demander sa main. Mes ressources sont trop faibles pour lui acheter son cadeau de fiançailles de ses rêves.",
"Vu ton rang, pourquoi n'a tu pas demander à tes parents ?",
"Mon père refuse de me prêter l'argent. Il n'est pas d'accord avec mon choix. Alors il m'a dit de trouver seul l'argent nécessaire. Mais je n'ai pas fini mes études et je n'ai donc pas encore de travail. Or, cette belle demoiselle a beaucoup d'autres prétendants.",
"Je vois, et tu compte sur le concours d'une tierce personne pour accéder à son cœur ?",
"C'est bien cela, pouvez-vous m'aider ? Je louerai vos mérites à tous ceux que je croiserais. Malheureusement, je n'aurait rien d'autre en échange.",
"Très bien, je veux bien t'aider.",
"Désolé, mais ce sera sans moi.",
"Merci capitaine ",
". Mais attention, il ne reste qu'une semaine avant que son prétendant le plus sérieux ne revienne d'Europe. Autre chose, ma tendre ",
" aimerait avoir ",
"Je reviendrais vers toi au plus vite.",
"Des nouvelles de ma chère et tendre ? Le temps presse capitaine.",

};