string DLG_TEXT[28] = {
"Hi ! Tu as l'air d'un pirate. J'ai besoin de toi !",
"Danielle ? Que fait-tu là ?",
"On n'arrête pas de m'appeler ainsi ! Fuck ! Je m'appelle Elizabeth Goodale !",
"Ah ! D'accord mais tu lui ressemble beaucoup. Que puis-je faire pour toi ?",
"La dernière tempête m'a laissé sans bateau. J'ai besoin de toi pour aller sur une autre île.",
"Où ça ?",
". Et j'ai un trésor qui m'attend là-bas.",
"Intéressant. Mais j'y gagne quoi ?",
"Désoler peut-être une autre fois !",
"Evidemment, on partagera le trésor à l'arrivée. Je te ferait une part en fonction de tes compétences de commandement.",
"Allons-y !",
"Tu trouveras, toute les informations nécessaires dans ton livre de quêtes. Arrivé sur le lieu, utilise le bouton 'Exécuter ordre rapide' pour creuser où tu veux. Avec de la chance, tu tomberas sur le trésor.",
"Bon ! Marin d'eau douce, on y va ?",
"Le trésor vaut à mon avis dans les ",
" pièces d'or. Voilà ta part du butin ",
" pièces d'or, comme je te l'ai dit, c'est en fonction de tes compétences de commandement. Le coffre est composé de ",
"Ca me va, merci à toi. J'espère que l'on pourra remettre ça une prochaine fois.",
"Je ne suis pas d'accord. Je vous tout le trésor.",
"Je sentais que quelque chose ne tournait pas rond chez toi. Si ça ne te convient pas, il te faudra te battre contre mon équipage qui est resté ici.",
"OK, j'ai changé d'avis, la part que tu me propose me convient.",
"EN GARDE !",
"Voilà. Bye !",
"Merci. A la prochaine fois !",
"Hi! What's up ?!",
"Hello my friend !",
"Salut Elizabeth ! As-tu quelque chasse au trésor à partager avec moi ?",
"Bad luck... But..... J'ai entendu parler d'un pirate asiatique qui traine à Quebradas Costillas. Je n'ai pas pu le rencontrer malheureusement mais il semblerait qu'il y a un fabuleux trésor à la clé !",
"Merci de l'info, à plus tard Elizabeth.",

};