string DLG_TEXT[28] = {
"Bonjour l'ami, je suis un chasseur de trésor et je cherche à faire équipage avec quelqu'un comme toi !",
"Chasseur de trésor ? J'ai toujours été attiré par l'appât du gain. Mais pourquoi as-tu besoin d'un équipage ?",
"On est plusieurs déjà dans mon équipage à récolter différentes rumeurs, à fouiner. Dès fois on tombe sur des indices ridicules mais parfois c'est une pépite qui nous tombe dessus. Et là, c'est carrément une carte au trésor que l'on a découvert.",
"Ah ! D'accord ! Et moi dans tout ça ?",
"Il nous manque un navire.",
"Pour aller où ?",
". La carte est formelle.",
"Intéressant. Mais j'y gagne quoi ?",
"Désoler peut-être une autre fois !",
"Evidemment, on partagera le trésor à l'arrivée entre tous les gars de l'équipage. Je te ferait une part en fonction de tes compétences de commandement.",
"Allons-y !",
"Tu trouveras, toute les informations nécessaires dans ton livre de quêtes. Arrivé sur le lieu, utilise le bouton 'Exécuter ordre rapide' pour creuser où tu veux. Avec de la chance, tu tomberas sur le trésor.",
"Ca fait des mois que l'on cherche après une carte au trésor ! On ne va pas attendre encore ? Si ?",
"Le trésor vaut à mon avis dans les ",
" pièces d'or. Voilà ta part du butin ",
" pièces d'or, comme je te l'ai dit, c'est en fonction de tes compétences de commandement. Le coffre est composé de ",
"Ca me va, merci à toi. J'espère que l'on pourra remettre ça une prochaine fois.",
"Je ne suis pas d'accord. Je vous tout le trésor.",
"Je sentais que quelque chose ne tournait pas rond chez toi. Si ça ne te convient pas, il te faudra te battre contre mon équipage et moi. Mais gare, nous sommes de bons escrimeurs",
"OK, j'ai changé d'avis, la part que tu me propose me convient.",
"EN GARDE !",
"Voilà. J'espère à une autre fois !",
"Merci. A la prochaine fois !",
"Salut à toi mon ami ! J'ai du nouveau !",
"Salut à toi mon ami !",
"Salutations à toi aussi ! As-tu quelque chasse au trésor à partager avec moi ?",
"Nooonnnn..... Désolé mais c'est calme en ce moment. Mais j'ai entendu parler d'un pirate asiatique qui traine à Quebradas Costillas. Je n'ai pas pu le rencontrer mais il semblerait qu'il y a un fabuleux trésor à la clé !",
"Merci de l'info, à plus tard.",

};